#include "help.h"

const HelpEntry help_db_io[] = {
  { "CLS", "Clear the screen", "CLS", HCAT_IO },
  { "COLOR", "Set text foreground/background", "COLOR 14,1 (yellow on blue)", HCAT_IO },
  { "CONSOLE", "Set or query active console device", "CONSOLE 2", HCAT_IO },
  { "EOF", "Standard I/O or string formatting", "EOF", HCAT_IO },
  { "GEMINI", "Network protocol handler", "GEMINI", HCAT_IO },
  { "GOPHER", "Network protocol handler", "GOPHER", HCAT_IO },
  { "HOME", "Move cursor to top-left", "HOME", HCAT_IO },
  { "INKEY", "Non-blocking key read value", "K = INKEY", HCAT_IO },
  { "INPUT$", "Read N chars from keyboard/file", "A$ = INPUT$(5) or A$ = INPUT$(10, #1)", HCAT_IO },
  { "INSTR", "Standard I/O or string formatting", "INSTR", HCAT_IO },
  { "LINE", "Read entire line (LINE INPUT)", "LINE INPUT A$ or LINE INPUT #1, A$", HCAT_IO },
  { "LOCATE", "Move cursor to row,column", "LOCATE 10,20", HCAT_IO },
  { "LPRINT", "Standard I/O or string formatting", "LPRINT", HCAT_IO },
  { "LSET", "Standard I/O or string formatting", "LSET", HCAT_IO },
  { "NBYTESWAITING", "Network socket operation", "NBYTESWAITING", HCAT_IO },
  { "NCONNECTED", "Network socket operation", "NCONNECTED", HCAT_IO },
  { "NEOF", "Network socket operation", "NEOF", HCAT_IO },
  { "NERROR", "Network socket operation", "NERROR", HCAT_IO },
  { "NHTTPSTATUS", "Network socket operation", "NHTTPSTATUS", HCAT_IO },
  { "NJSONQUERY", "Network socket operation", "NJSONQUERY", HCAT_IO },
  { "NSTATUS", "Network socket operation", "NSTATUS", HCAT_IO },
  { "OPEN", "Standard I/O or string formatting", "OPEN", HCAT_IO },
  { "PRINT", "Display output to console", "PRINT A$ or PRINT 2 + 2", HCAT_IO },
  { "RSET", "Standard I/O or string formatting", "RSET", HCAT_IO },
  { "SPC", "Standard I/O or string formatting", "SPC", HCAT_IO },
  { "TAB", "Standard I/O or string formatting", "TAB", HCAT_IO },
  { "WIDTH", "Set screen width", "WIDTH 80 or WIDTH 80,25", HCAT_IO },
  { "WRITE", "Write comma-delimited data", "WRITE #1, A, B$, C", HCAT_IO },
  { "INPUT", "Get console input into a variable", "INPUT \"Name? \"; N$", HCAT_IO },
  { "AT", "Position cursor (used with PRINT)", "PRINT AT(10,5); \"Hello\"", HCAT_IO },
  { NULL, NULL, NULL, 0 }
};
