#include "help.h"

const HelpEntry help_db_sysenv[] = {
  { "ATOMIC", "Begin a transactional block", "ATOMIC: A=A+1: B=B-1: COMMIT", HCAT_SYSENV },
  { "BYE", "Exit the interpreter", "BYE", HCAT_SYSENV },
  { "CLOCK", "Access system NTP clock", "CLOCK ON | CLOCK OFF", HCAT_SYSENV },
  { "COMMIT", "Commit active transaction changes", "COMMIT", HCAT_SYSENV },
  { "CURDIR$", "Current directory (alias for CWD$)", "PRINT CURDIR$", HCAT_SYSENV },
  { "DELAY", "Pause execution for milliseconds", "DELAY 500", HCAT_SYSENV },
  { "DIALECT", "System environment query/control", "DIALECT", HCAT_SYSENV },
  { "DIALECT$", "System environment query/control", "DIALECT$", HCAT_SYSENV },
  { "ENVIRON", "System environment query/control", "ENVIRON", HCAT_SYSENV },
  { "ERDEV", "Error device code of last device error", "PRINT ERDEV", HCAT_SYSENV },
  { "ERRORLEVEL", "Last shell exit code", "PRINT ERRORLEVEL", HCAT_SYSENV },
  { "EXIST", "System operation or file query", "EXIST", HCAT_SYSENV },
  { "EXTERR", "Extended error information", "PRINT EXTERR(0)", HCAT_SYSENV },
  { "HOSTNAME", "System environment query/control", "HOSTNAME", HCAT_SYSENV },
  { "JIFFIES", "System time or date query", "JIFFIES", HCAT_SYSENV },
  { "KEY(N)", "Enable/disable key event trapping", "KEY(1) ON | KEY(1) OFF | KEY(1) STOP", HCAT_SYSENV },
  { "KILL", "Reserved for future use", "KILL (use SCRATCH to delete files)", HCAT_SYSENV },
  { "MOTOR", "System operation or file query", "MOTOR", HCAT_SYSENV },
  { "ONKEY", "Trigger key interrupt handler", "ONKEY GOSUB 500", HCAT_SYSENV },
  { "PAUSE", "Pause program for N frames/seconds", "PAUSE 60", HCAT_SYSENV },
  { "PLAY(N)", "Enable/disable music buffer interrupt", "PLAY ON | PLAY OFF | PLAY STOP", HCAT_SYSENV },
  { "PWD", "Print current working directory path", "PWD", HCAT_SYSENV },
  { "ROLLBACK", "Rollback current transaction state", "ROLLBACK", HCAT_SYSENV },
  { "SECURITY", "System operation or file query", "SECURITY", HCAT_SYSENV },
  { "SLEEP", "Pause execution for N seconds", "SLEEP 2", HCAT_SYSENV },
  { "STICK", "Read joystick coordinate value", "PRINT STICK(0)", HCAT_SYSENV },
  { "STRIG", "Read joystick trigger status", "PRINT STRIG(0)", HCAT_SYSENV },
  { "SYSTEM", "System environment query/control", "SYSTEM", HCAT_SYSENV },
  { "TEST", "System operation or file query", "TEST", HCAT_SYSENV },
  { "TI", "System time or date query", "TI", HCAT_SYSENV },
  { "TI$", "System time or date query", "TI$", HCAT_SYSENV },
  { "TICKS", "System time or date query", "TICKS", HCAT_SYSENV },
  { "TODAY$", "System time or date query", "TODAY$", HCAT_SYSENV },
  { "TXN", "Query current transaction status", "PRINT TXN", HCAT_SYSENV },
  { "USERNAME", "System environment query/control", "USERNAME", HCAT_SYSENV },
  { "DATE", "Get or set the system date", "D$ = DATE$", HCAT_SYSENV },
  { "TIME", "Get or set the system time", "T$ = TIME$", HCAT_SYSENV },
  { "SYS", "Execute a system command", "SYS \"dir\"", HCAT_SYSENV },
  { "EXEC", "Execute a system command (Alias)", "EXEC \"ls\"", HCAT_SYSENV },
  { "SHELL", "Drop to system shell or exec command", "SHELL", HCAT_SYSENV },
  { "KEYWORD", "Modify keyword attributes at runtime", "KEYWORD PRINT UPPERCASE ON", HCAT_SYSENV },
  { NULL, NULL, NULL, 0 }
};
