#include "help.h"

const HelpEntry help_db_math[] = {
  { "ABS", "Absolute value", "PRINT ABS(-5) ' prints 5", HCAT_MATH },
  { "ACOS", "Arccosine (SBASIC, returns radians)", "PRINT ACOS(0) ' 1.5708 (PI/2)", HCAT_MATH },
  { "ASIN", "Arcsine (SBASIC, returns radians)", "PRINT ASIN(1) ' 1.5708 (PI/2)", HCAT_MATH },
  { "ATN", "Arctangent (returns radians)", "PI = 4*ATN(1)", HCAT_MATH },
  { "AVG", "Advanced mathematical function", "AVG", HCAT_MATH },
  { "CABS", "Advanced mathematical function", "CABS", HCAT_MATH },
  { "CARG", "Advanced mathematical function", "CARG", HCAT_MATH },
  { "CDBL", "Convert to double precision", "PRINT CDBL(X)", HCAT_MATH },
  { "CEXP", "Advanced mathematical function", "CEXP", HCAT_MATH },
  { "CINT", "Round to nearest integer", "PRINT CINT(3.6) ' prints 4", HCAT_MATH },
  { "CLOG", "Advanced mathematical function", "CLOG", HCAT_MATH },
  { "COMP", "Compare two values (SBASIC, returns -1/0/+1)", "PRINT COMP(3,5) ' -1", HCAT_MATH },
  { "COMPLEX", "Advanced mathematical function", "COMPLEX", HCAT_MATH },
  { "CONJ", "Advanced mathematical function", "CONJ", HCAT_MATH },
  { "COS", "Cosine (radians)", "PRINT COS(0) ' prints 1", HCAT_MATH },
  { "COSH", "Hyperbolic cosine (SBASIC)", "PRINT COSH(0) ' 1", HCAT_MATH },
  { "CPOW", "Advanced mathematical function", "CPOW", HCAT_MATH },
  { "CSNG", "Convert to single precision", "PRINT CSNG(X)", HCAT_MATH },
  { "CSQR", "Advanced mathematical function", "CSQR", HCAT_MATH },
  { "DET", "Determinant of a matrix", "PRINT DET(A)", HCAT_MATH },
  { "EXP", "Exponential (e^x)", "PRINT EXP(1) ' prints 2.71828", HCAT_MATH },
  { "FIX", "Truncate toward zero", "PRINT FIX(-3.7) ' prints -3", HCAT_MATH },
  { "HI", "High 8 bits (byte) of integer", "PRINT HI(256) ' 1", HCAT_MATH },
  { "IMAG", "Advanced mathematical function", "IMAG", HCAT_MATH },
  { "INT", "Truncate to integer (math) or trigger software interrupt", "PRINT INT(3.7) or INT &H10", HCAT_MATH },
  { "LGT", "Common logarithm base 10 (HP BASIC)", "PRINT LGT(100) ' 2", HCAT_MATH },
  { "LN", "Natural logarithm (base e)", "PRINT LN(2.71828)", HCAT_MATH },
  { "LO", "Low 8 bits (byte) of integer", "PRINT LO(257) ' 1", HCAT_MATH },
  { "LOG", "Natural logarithm (base e)", "PRINT LOG(2.71828)", HCAT_MATH },
  { "LOG10", "Common logarithm base 10 (SBASIC)", "PRINT LOG10(100) ' 2", HCAT_MATH },
  { "LOG2", "Binary logarithm base 2 (SBASIC)", "PRINT LOG2(8) ' 3", HCAT_MATH },
  { "MAX", "Advanced mathematical function", "MAX", HCAT_MATH },
  { "MED", "Advanced mathematical function", "MED", HCAT_MATH },
  { "MIN", "Advanced mathematical function", "MIN", HCAT_MATH },
  { "PDIF", "Positive difference (SBASIC, MAX(a-b,0))", "PRINT PDIF(5,3) ' 2", HCAT_MATH },
  { "PI", "Constant PI (SBASIC, 3.14159...)", "PRINT PI ' 3.14159265358979", HCAT_MATH },
  { "RANDOMIZE", "Seed the random number generator", "RANDOMIZE or RANDOMIZE 42", HCAT_MATH },
  { "REAL", "Advanced mathematical function", "REAL", HCAT_MATH },
  { "REMAINDER", "Modulo remainder of division", "PRINT REMAINDER(10, 3)", HCAT_MATH },
  { "RND", "Random number (0 to 1)", "PRINT RND(1) or PRINT INT(RND(1)*6)+1", HCAT_MATH },
  { "ROUND", "Advanced mathematical function", "ROUND", HCAT_MATH },
  { "SGN", "Sign of a number (-1, 0, or 1)", "PRINT SGN(-5) ' prints -1", HCAT_MATH },
  { "SIN", "Sine (radians)", "PRINT SIN(3.14159/2)", HCAT_MATH },
  { "SINH", "Hyperbolic sine (SBASIC)", "PRINT SINH(1) ' 1.1752", HCAT_MATH },
  { "SQR", "Square root", "PRINT SQR(144) ' prints 12", HCAT_MATH },
  { "TAN", "Tangent (radians)", "PRINT TAN(3.14159/4)", HCAT_MATH },
  { "TANH", "Hyperbolic tangent (SBASIC)", "PRINT TANH(1) ' 0.7616", HCAT_MATH },
  { "TIM", "Time components mode (HP BASIC, 0=min,1=hr,2=yday,3=yr)", "PRINT TIM(1)", HCAT_MATH },
  { "NUM", "Convert string to number", "N = NUM(\"123\")", HCAT_MATH },
  { NULL, NULL, NULL, 0 }
};
