#include "help.h"

const HelpEntry help_db_fileio[] = {
  { "ACCESS", "Query file channel permissions", "PRINT ACCESS(1)", HCAT_FILEIO },
  { "ASK", "Query file info (ECMA-116)", "ASK #1: FILESIZE F", HCAT_FILEIO },
  { "BIOCHECKSUM", "Low-level block I/O operation", "BIOCHECKSUM", HCAT_FILEIO },
  { "BIOCOMPARE", "Low-level block I/O operation", "BIOCOMPARE", HCAT_FILEIO },
  { "BIOCOPY", "Low-level block I/O operation", "BIOCOPY", HCAT_FILEIO },
  { "BIOFILL", "Low-level block I/O operation", "BIOFILL", HCAT_FILEIO },
  { "BIOSIZE", "Low-level block I/O operation", "BIOSIZE", HCAT_FILEIO },
  { "BIOSTATUS", "Low-level block I/O operation", "BIOSTATUS", HCAT_FILEIO },
  { "BIOWRITE", "Low-level block I/O operation", "BIOWRITE", HCAT_FILEIO },
  { "CHDIR", "File and directory management", "CHDIR", HCAT_FILEIO },
  { "CLOSE", "Close a file channel", "CLOSE #1", HCAT_FILEIO },
  { "CURDIR", "Query current directory path", "PRINT CURDIR", HCAT_FILEIO },
  { "CVD", "Unpack 8-byte string to double", "D = CVD(A$)", HCAT_FILEIO },
  { "CVI", "Unpack 2-byte string to integer", "N = CVI(A$)", HCAT_FILEIO },
  { "CVS", "Unpack 4-byte string to single", "F = CVS(A$)", HCAT_FILEIO },
  { "CWD", "File and directory management", "CWD", HCAT_FILEIO },
  { "DIR", "File and directory management", "DIR", HCAT_FILEIO },
  { "FIELD", "Define record buffer fields", "FIELD #1, 20 AS N$, 4 AS A$", HCAT_FILEIO },
  { "FILELEN", "File and directory management", "FILELEN", HCAT_FILEIO },
  { "FILES", "File and directory management", "FILES", HCAT_FILEIO },
  { "FILESIZE", "File and directory management", "FILESIZE", HCAT_FILEIO },
  { "GET", "Read a record from random file", "GET #1, recnum", HCAT_FILEIO },
  { "LOC", "Current file position", "PRINT LOC(1)", HCAT_FILEIO },
  { "LOCK", "Lock file records", "LOCK #1, record", HCAT_FILEIO },
  { "LOF", "Get length of open file", "PRINT LOF(1)", HCAT_FILEIO },
  { "MKD$", "Pack double to 8-byte string", "A$ = MKD$(D)", HCAT_FILEIO },
  { "MKDIR", "File and directory management", "MKDIR", HCAT_FILEIO },
  { "MKI$", "Pack integer to 2-byte string", "A$ = MKI$(N)", HCAT_FILEIO },
  { "MKS$", "Pack single to 4-byte string", "A$ = MKS$(F)", HCAT_FILEIO },
  { "MOUNTS", "Display all active VFS mounts", "MOUNTS", HCAT_FILEIO },
  { "NAME", "File and directory management", "NAME", HCAT_FILEIO },
  { "POINTER", "Query/set file position pointer", "POINTER #1, offset", HCAT_FILEIO },
  { "PUT", "Write a record to random file", "PUT #1, recnum", HCAT_FILEIO },
  { "RENAME", "File and directory management", "RENAME", HCAT_FILEIO },
  { "RESET", "Close all open files", "RESET", HCAT_FILEIO },
  { "REWRITE", "Re-open channel for writing", "REWRITE #1", HCAT_FILEIO },
  { "RMDIR", "File and directory management", "RMDIR", HCAT_FILEIO },
  { "SEEK", "Set or get file position", "SEEK #1, 100", HCAT_FILEIO },
  { "SET", "Set file pointer (ECMA-116)", "SET #1: POINTER 0", HCAT_FILEIO },
  { "SIOAVAIL", "Low-level block I/O operation", "SIOAVAIL", HCAT_FILEIO },
  { "SIOFLUSH", "Low-level block I/O operation", "SIOFLUSH", HCAT_FILEIO },
  { "SIOSEEK", "Low-level block I/O operation", "SIOSEEK", HCAT_FILEIO },
  { "SIOSTATUS", "Low-level block I/O operation", "SIOSTATUS", HCAT_FILEIO },
  { "SIOWRITE", "Low-level block I/O operation", "SIOWRITE", HCAT_FILEIO },
  { "UNLOCK", "Unlock file records", "UNLOCK #1, record", HCAT_FILEIO },
  { "VPATH$", "File and directory management", "VPATH$", HCAT_FILEIO },
  { NULL, NULL, NULL, 0 }
};
