#include "help.h"

const HelpEntry help_db_intro[] = {
  { "ALARM", "Built-in command or function: ALARM", "ALARM", HCAT_INTRO },
  { "ALIAS", "Advanced language feature", "ALIAS", HCAT_INTRO },
  { "ALIAS$", "Advanced language feature", "ALIAS$", HCAT_INTRO },
  { "CATALOG", "List all commands & functions", "CATALOG", HCAT_INTRO },
  { "COMPILE", "Advanced language feature", "COMPILE", HCAT_INTRO },
  { "COPY", "Built-in command or function: COPY", "COPY", HCAT_INTRO },
  { "DEFUSR", "Built-in command or function: DEFUSR", "DEFUSR", HCAT_INTRO },
  { "DEMAND", "Built-in command or function: DEMAND", "DEMAND", HCAT_INTRO },
  { "ENDSELECT", "Built-in command or function: ENDSELECT", "ENDSELECT", HCAT_INTRO },
  { "ERR$", "Built-in command or function: ERR$", "ERR$", HCAT_INTRO },
  { "EXISTS", "Built-in command or function: EXISTS", "EXISTS", HCAT_INTRO },
  { "HASH", "Built-in command or function: HASH", "HASH", HCAT_INTRO },
  { "HELP", "Show this help (or HELP keyword)", "HELP or HELP PRINT or HELP ABS", HCAT_INTRO },
  { "INFO", "Display system information", "INFO", HCAT_INTRO },
  { "IOCTL$", "Built-in command or function: IOCTL$", "IOCTL$", HCAT_INTRO },
  { "KEY", "Built-in command or function: KEY", "KEY", HCAT_INTRO },
  { "LIKE", "Built-in command or function: LIKE", "LIKE", HCAT_INTRO },
  { "LPOS", "Printer head column position", "PRINT LPOS(0)", HCAT_INTRO },
  { "MEMMAP$", "Current memory map name (read-only)", "PRINT MEMMAP$", HCAT_INTRO },
  { "MODULE", "Advanced language feature", "MODULE", HCAT_INTRO },
  { "MOVE", "Built-in command or function: MOVE", "MOVE", HCAT_INTRO },
  { "OVERRIDE", "Advanced language feature", "OVERRIDE", HCAT_INTRO },
  { "PUBLIC", "Advanced language feature", "PUBLIC", HCAT_INTRO },
  { "REFORMAT", "Built-in command or function: REFORMAT", "REFORMAT", HCAT_INTRO },
  { "SCOPE", "Advanced language feature", "SCOPE", HCAT_INTRO },
  { "SCRATCH", "Built-in command or function: SCRATCH", "SCRATCH", HCAT_INTRO },
  { "TXNSTATUS", "Built-in command or function: TXNSTATUS", "TXNSTATUS", HCAT_INTRO },
  { "UNLESS", "Built-in command or function: UNLESS", "UNLESS", HCAT_INTRO },
  { "USING", "Built-in command or function: USING", "USING", HCAT_INTRO },
  { "VARPTR$", "Built-in command or function: VARPTR$", "VARPTR$", HCAT_INTRO },
  { NULL, NULL, NULL, 0 }
};
