#include "help.h"

const HelpEntry help_db_string[] = {
  { "ASC", "ASCII value of first character", "ASC(A$)", HCAT_STRING },
  { "BIN", "Number base conversion", "BIN", HCAT_STRING },
  { "BIN$", "Convert to binary string (8-bit groups)", "PRINT BIN$(255) ' 11111111", HCAT_STRING },
  { "CHR", "Convert ASCII code to string character", "PRINT CHR(65)", HCAT_STRING },
  { "CHR$", "Character from ASCII code", "PRINT CHR$(65) ' A", HCAT_STRING },
  { "HEX", "Number base conversion", "HEX", HCAT_STRING },
  { "HEX$", "Convert to hexadecimal string", "PRINT HEX$(255) ' FF", HCAT_STRING },
  { "ICASE", "String manipulation function", "ICASE", HCAT_STRING },
  { "LCASE", "String manipulation function", "LCASE", HCAT_STRING },
  { "LEFT", "String manipulation function", "LEFT", HCAT_STRING },
  { "LEFT$", "Get left portion of string", "LEFT$(A$, 5)", HCAT_STRING },
  { "LEN", "Length of a string", "LEN(A$)", HCAT_STRING },
  { "LTRIM", "String manipulation function", "LTRIM", HCAT_STRING },
  { "MCASE", "String manipulation function", "MCASE", HCAT_STRING },
  { "MID", "String manipulation function", "MID", HCAT_STRING },
  { "MID$", "Substring function", "MID$(A$, start, len)", HCAT_STRING },
  { "OCT", "Number base conversion", "OCT", HCAT_STRING },
  { "OCT$", "Convert to octal string", "PRINT OCT$(255) ' 377", HCAT_STRING },
  { "REPLACE", "String manipulation function", "REPLACE", HCAT_STRING },
  { "REVERSE", "String manipulation function", "REVERSE", HCAT_STRING },
  { "RIGHT", "String manipulation function", "RIGHT", HCAT_STRING },
  { "RIGHT$", "Get right portion of string", "RIGHT$(A$, 5)", HCAT_STRING },
  { "RTRIM", "String manipulation function", "RTRIM", HCAT_STRING },
  { "SPACE", "String manipulation function", "SPACE", HCAT_STRING },
  { "SPACE$", "Generate N space characters", "PRINT SPACE$(10)", HCAT_STRING },
  { "STR", "String manipulation function", "STR", HCAT_STRING },
  { "STR$", "Convert number to string", "A$=STR$(42)", HCAT_STRING },
  { "STRING", "String manipulation function", "STRING", HCAT_STRING },
  { "TCASE", "String manipulation function", "TCASE", HCAT_STRING },
  { "TRIM", "String manipulation function", "TRIM", HCAT_STRING },
  { "UCASE", "String manipulation function", "UCASE", HCAT_STRING },
  { "VAL", "Convert string to number", "VAL(A$)", HCAT_STRING },
  { NULL, NULL, NULL, 0 }
};
