#include "help.h"

const HelpEntry help_db_flow[] = {
  { "BY", "Counting step in loop (SBASIC FOR loop alias)", "FOR I = 1 TO 10 BY 2", HCAT_FLOW },
  { "CASE", "Case clause within SELECT CASE", "CASE 1,2,3 or CASE IS > 10 or CASE ELSE", HCAT_FLOW },
  { "CAUSE", "Raise an exception (ECMA-116)", "CAUSE EXCEPTION 1000", HCAT_FLOW },
  { "CONTINUE", "Resume execution of loop", "CONTINUE FOR or CONTINUE DO", HCAT_FLOW },
  { "DECLARE", "Forward-declare a SUB or FUNCTION", "DECLARE SUB MySub(x, y$)", HCAT_FLOW },
  { "DEF", "Define a user function (one-line)", "DEF FNA(X)=X*X+1", HCAT_FLOW },
  { "DEFINE", "Begin user-defined block function", "DEFINE FUNCTION my_fn(x) ... ENDDEFINE", HCAT_FLOW },
  { "DO", "Begin a DO loop", "DO ... LOOP WHILE cond", HCAT_FLOW },
  { "ELSE", "Alternate branch in block IF or single-line IF", "IF X > 5 THEN PRINT X ELSE PRINT Y", HCAT_FLOW },
  { "ELSEIF", "Additional condition in block IF", "ELSEIF X>10 THEN ...", HCAT_FLOW },
  { "END", "Terminate program execution", "END", HCAT_FLOW },
  { "ENDDEFINE", "End user-defined function block", "ENDDEFINE", HCAT_FLOW },
  { "ENDFOR", "End counting loop (Structured BASIC)", "ENDFOR", HCAT_FLOW },
  { "ENDIF", "End a block IF structure", "END IF", HCAT_FLOW },
  { "ENDREPEAT", "End repeat loop block", "ENDREPEAT", HCAT_FLOW },
  { "ERROR", "Raise a user error", "ERROR 5", HCAT_FLOW },
  { "EXIT", "Exit a FOR or DO loop early", "EXIT FOR or EXIT DO", HCAT_FLOW },
  { "FN", "Call user-defined function", "PRINT FN my_fn(x)", HCAT_FLOW },
  { "FOR", "Begin a counting loop", "FOR I=1 TO 10 STEP 2 (or BY 2 in SBASIC)", HCAT_FLOW },
  { "FUNCTION", "Define a named function", "FUNCTION MyFn (x) ... END FUNCTION", HCAT_FLOW },
  { "GOSUB", "Call a subroutine at a line number", "GOSUB 500", HCAT_FLOW },
  { "GOTO", "Jump to a line number", "GOTO 100", HCAT_FLOW },
  { "IF", "Conditional decision structure", "IF X > 10 THEN PRINT X ELSE PRINT Y", HCAT_FLOW },
  { "IN", "Check containment in list or array", "IF X IN (1, 2, 3) THEN ...", HCAT_FLOW },
  { "IS", "Case selector comparison operator", "CASE IS > 10", HCAT_FLOW },
  { "LOOP", "End of a DO loop (with condition)", "LOOP WHILE A>0 or LOOP UNTIL A=0", HCAT_FLOW },
  { "NEXT", "End of a FOR loop", "NEXT I", HCAT_FLOW },
  { "ON", "Computed GOTO/GOSUB or error/event handler", "ON X GOTO 100,200 or ON ERROR GOTO 500", HCAT_FLOW },
  { "ON BREAK", "Set Ctrl+C / signal interrupt handler", "ON BREAK GOSUB 900", HCAT_FLOW },
  { "ON COM", "Set serial port interrupt handler", "ON COM(1) GOSUB 800", HCAT_FLOW },
  { "ON KEY", "Set key press interrupt handler", "ON KEY(1) GOSUB 700", HCAT_FLOW },
  { "ON PEN", "Set light pen interrupt handler", "ON PEN GOSUB 600", HCAT_FLOW },
  { "ON PLAY", "Set music buffer interrupt handler", "ON PLAY(3) GOSUB 500", HCAT_FLOW },
  { "ON STRIG", "Set joystick trigger interrupt handler", "ON STRIG(0) GOSUB 400", HCAT_FLOW },
  { "ON TIMER", "Set timer interrupt handler", "ON TIMER(5) GOSUB 300", HCAT_FLOW },
  { "PROCEDURE", "Begin procedure block definition", "PROCEDURE MyProc ... ENDPROC", HCAT_FLOW },
  { "REPEAT", "Begin repeat loop block", "REPEAT ... UNTIL cond", HCAT_FLOW },
  { "RESUME", "Return from an error handler", "RESUME or RESUME NEXT or RESUME 100", HCAT_FLOW },
  { "RETRY", "Retry failed transaction statement", "RETRY", HCAT_FLOW },
  { "RETURN", "Return from a GOSUB subroutine", "RETURN", HCAT_FLOW },
  { "SELECT", "Begin a SELECT CASE block", "SELECT CASE X", HCAT_FLOW },
  { "STEP", "Count loop step increments", "FOR I = 1 TO 10 STEP 2", HCAT_FLOW },
  { "STOP", "Pause program (use CONT to resume)", "STOP", HCAT_FLOW },
  { "SUB", "Define a named subroutine", "SUB MySub (x, y$) ... END SUB", HCAT_FLOW },
  { "THEN", "Conditional branch target indicator", "IF A > B THEN PRINT A", HCAT_FLOW },
  { "TO", "Counting upper limit indicator", "FOR I = 1 TO 10", HCAT_FLOW },
  { "TRAP", "Set error/event trap handler (hybrid)", "TRAP n | TRAP e,s,n | TRAP (status) | ON TRAP GOSUB n", HCAT_FLOW },
  { "UNTIL", "Exit condition for repeat loop", "LOOP UNTIL X > 5", HCAT_FLOW },
  { "USE", "Protected exception block handler", "WHEN EXCEPTION IN ... USE ... END WHEN", HCAT_FLOW },
  { "USR", "Invoke machine language function", "PRINT USR(x)", HCAT_FLOW },
  { "WEND", "End of a WHILE loop", "WEND", HCAT_FLOW },
  { "WHEN", "Begin protected exception block", "WHEN EXCEPTION IN ... USE ... END WHEN", HCAT_FLOW },
  { "WHILE", "Begin a conditional loop", "WHILE A>0 ... WEND", HCAT_FLOW },
  { "CALL", "Call a SUB procedure", "CALL MySub(1, 2)", HCAT_FLOW },
  { "TASK", "Multi-tasking thread spawn", "TASK 100", HCAT_FLOW },
  { NULL, NULL, NULL, 0 }
};
