#include "help.h"

const HelpEntry help_db_varmem[] = {
  { "AS", "Specify variable type or file channel alias", "AS", HCAT_VARMEM },
  { "BANK", "RAMBANK segmented virtual memory control", "BANK n SHARED | BANK n PRIVATE | BANK n CLEAR | BANK n STATUS | BANK LIST | BANK n", HCAT_VARMEM },
  { "CLEAR", "Clear stack and variables", "CLEAR", HCAT_VARMEM },
  { "CLR", "Clear all variables (Atari/C64)", "CLR", HCAT_VARMEM },
  { "COMMON", "Share vars with CHAINed program", "COMMON A, B$", HCAT_VARMEM },
  { "CONST", "Define a named constant", "CONST PI = 3.14159", HCAT_VARMEM },
  { "CSRLIN", "Current cursor row", "PRINT CSRLIN", HCAT_VARMEM },
  { "DEFDBL", "Declare double variable range", "DEFDBL A-Z", HCAT_VARMEM },
  { "DEFINT", "Declare integer variable range", "DEFINT A-Z", HCAT_VARMEM },
  { "DEFSNG", "Declare single variable range", "DEFSNG A-Z", HCAT_VARMEM },
  { "DEFSTR", "Declare string variable range", "DEFSTR A-Z", HCAT_VARMEM },
  { "DIM", "Declare an array with dimensions", "DIM A(10) or DIM M(3,3) or DIM A$(25)", HCAT_VARMEM },
  { "ERASE", "Erase an array from memory", "ERASE A", HCAT_VARMEM },
  { "FRE", "Free memory available", "PRINT FRE(0)", HCAT_VARMEM },
  { "LBOUND", "Array lower bound index", "PRINT LBOUND(A, 1)", HCAT_VARMEM },
  { "LET", "Assign value to variable (optional in most dialects)", "LET A = 5 or A = 5", HCAT_VARMEM },
  { "LOCAL", "Declare local variables in sub/fn", "LOCAL X, Y$", HCAT_VARMEM },
  { "MAT", "Matrix operations", "MAT PRINT A or MAT A=ZER", HCAT_VARMEM },
  { "MEMMAP", "Select memory map preset", "MEMMAP 48 or MEMMAP 64", HCAT_VARMEM },
  { "MKD", "Pack double to 8-byte string", "A$ = MKD(D)", HCAT_VARMEM },
  { "MKI", "Pack integer to 2-byte string", "A$ = MKI(I)", HCAT_VARMEM },
  { "MKS", "Pack single to 4-byte string", "A$ = MKS(S)", HCAT_VARMEM },
  { "OPTION", "Set interpreter options", "OPTION BASE 0|1 | STRICT ON|OFF | MIXED D1,D2,...", HCAT_VARMEM },
  { "PEEK", "Read byte from virtual memory", "PRINT PEEK(addr)", HCAT_VARMEM },
  { "PEEKB", "Read byte from a RAMBANK segment", "PRINT PEEKB(bank, offset)", HCAT_VARMEM },
  { "POKE", "Write byte to virtual memory", "POKE addr, value", HCAT_VARMEM },
  { "POKEB", "Write byte to a RAMBANK segment", "POKEB bank, offset, value", HCAT_VARMEM },
  { "POS", "Current cursor column", "PRINT POS(0)", HCAT_VARMEM },
  { "READ", "Read the next DATA value", "READ A or READ A$", HCAT_VARMEM },
  { "REDIM", "Resize a dynamic array", "REDIM A(20)", HCAT_VARMEM },
  { "REM", "Comment (ignored by interpreter)", "REM This is a comment (or ' shorthand)", HCAT_VARMEM },
  { "RESTORE", "Reset DATA pointer to beginning", "RESTORE or RESTORE 200", HCAT_VARMEM },
  { "SEG", "Get memory segment index of variable", "PRINT SEG(X)", HCAT_VARMEM },
  { "SHARED", "Share variables with main program", "SHARED A, B$", HCAT_VARMEM },
  { "STATIC", "Preserve local variables across calls", "STATIC count", HCAT_VARMEM },
  { "SWAP", "Exchange two variables", "SWAP A,B", HCAT_VARMEM },
  { "TYPE", "Define a user-defined type", "TYPE recname ... END TYPE", HCAT_VARMEM },
  { "UBOUND", "Array upper bound index", "PRINT UBOUND(A, 1)", HCAT_VARMEM },
  { "VARPTR", "Pointer index of a variable", "PRINT VARPTR(A)", HCAT_VARMEM },
  { "DATA", "Store numeric or string data", "DATA 10, 20, \"Hello\"", HCAT_VARMEM },
  { "PSTORE", "Store variable persistently", "PSTORE A", HCAT_VARMEM },
  { "PRETRIEVE", "Retrieve persistent variable", "PRETRIEVE A", HCAT_VARMEM },
  { NULL, NULL, NULL, 0 }
};
