10 REM ============================================================
20 REM  LIBALL.BAS - Load ALL 7 sample libraries
30 REM  Verifies every .LIB loads without errors.
40 REM ============================================================
50 REM
100 PRINT "=== Load All Libraries Test ==="
110 PRINT
120 PRINT "Loading TURTLE.LIB..."
130 LOAD LIBRARY "samples/TURTLE.LIB"
140 PRINT
150 PRINT "Loading TINYDB.LIB..."
160 LOAD LIBRARY "samples/TINYDB.LIB"
170 PRINT
180 PRINT "Loading REGEX.LIB..."
190 LOAD LIBRARY "samples/REGEX.LIB"
200 PRINT
210 PRINT "Loading ADVENT.LIB..."
220 LOAD LIBRARY "samples/ADVENT.LIB"
230 PRINT
240 PRINT "Loading GAMEKIT.LIB..."
250 LOAD LIBRARY "samples/GAMEKIT.LIB"
260 PRINT
270 PRINT "Loading IOTKIT.LIB..."
280 LOAD LIBRARY "samples/IOTKIT.LIB"
290 PRINT
300 PRINT "Loading EXTCMDS.LIB..."
310 LOAD LIBRARY "samples/EXTCMDS.LIB"
320 PRINT
330 PRINT "=== All 7 libraries loaded successfully ==="
340 PRINT
350 PRINT "Unloading all..."
360 UNLOAD LIBRARY "TURTLE"
370 UNLOAD LIBRARY "TINYDB"
380 UNLOAD LIBRARY "REGEX"
390 UNLOAD LIBRARY "ADVENT"
400 UNLOAD LIBRARY "GAMEKIT"
410 UNLOAD LIBRARY "IOTKIT"
420 UNLOAD LIBRARY "EXTCMDS"
430 PRINT
440 PRINT "=== All libraries unloaded ==="
450 END
