// FILENAME: scan_keyword.c
// LICENSE: Copyleft (c) 2026 BASIC++ Community — All Wrongs Reserved
// VERSION: 6.5.2.0
// NEEDED BY: libengine, BASIC++ runtime
// NEEDS: libcore (ctype.h, ctype.c, memops.h, memops.c, strops.h, strops.c)
// NEEDS: libengine (lexer.h, lexer.c, lexer_internal.h)
// NEEDS: libkernel (config.h)
// Implements lexical scanning and token stream processing for scan_keyword.
//
// ---- Includes ----

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "lexer/lexer.h"
#include "lexer/lexer_internal.h"
#include "types/config.h"
#include "runtime/ctype/ctype.h"
#include "runtime/string/memops.h"
#include "runtime/string/strops.h"

//
// ---- Static Keyword Map Table ----

static const KeywordMap k_keywords[] = {
    {"PRINT", KW_PRINT},
    {"LET", KW_LET},
    {"INPUT", KW_INPUT},
    {"IF", KW_IF},
    {"THEN", KW_THEN},
    {"ELSE", KW_ELSE},
    {"GOTO", KW_GOTO},
    {"GOSUB", KW_GOSUB},
    {"RETURN", KW_RETURN},
    {"END", KW_END},
    {"REM", KW_REM},
    {"LIST", KW_LIST},
    {"RUN", KW_RUN},
    {"NEW", KW_NEW},
    {"FOR", KW_FOR},
    {"NEXT", KW_NEXT},
    {"TO", KW_TO},
    {"STEP", KW_STEP},
    {"BY", KW_BY},
    {"WHILE", KW_WHILE},
    {"WEND", KW_WEND},
    {"DO", KW_DO},
    {"LOOP", KW_LOOP},
    {"UNTIL", KW_UNTIL},
    {"DIM", KW_DIM},
    {"ERASE", KW_ERASE},
    {"OPTION", KW_OPTION},
    {"DATA", KW_DATA},
    {"READ", KW_READ},
    {"RESTORE", KW_RESTORE},
    {"DEF", KW_DEF},
    {"DEFINT", KW_DEFINT},
    {"DEFSNG", KW_DEFSNG},
    {"DEFDBL", KW_DEFDBL},
    {"DEFSTR", KW_DEFSTR},
    {"DEFLNG", KW_DEFLNG},
    {"USR", KW_USR},
    {"ON", KW_ON},
    {"ERROR", KW_ERROR},
    {"RESUME", KW_RESUME},
    {"LOAD", KW_LOAD},
    {"SAVE", KW_SAVE},
    {"MERGE", KW_MERGE},
    {"COMMON", KW_COMMON},
    {"CHAIN", KW_CHAIN},
    {"SELFTEST", KW_SELFTEST},
    {"OPEN", KW_OPEN},
    {"CLOSE", KW_CLOSE},
    {"AS", KW_AS},
    {"FILES", KW_FILES},
    {"KILL", KW_KILL},
    {"SCRATCH", KW_SCRATCH},
    {"CHDIR", KW_CHDIR},
    {"MKDIR", KW_MKDIR},
    {"RMDIR", KW_RMDIR},
    {"DIR", KW_DIR},
    {"SETATTR", KW_SETATTR},
    {"LOCK", KW_LOCK},
    {"UNLOCK", KW_UNLOCK},
    {"ENVIRON", KW_ENVIRON},
    {"NAME", KW_NAME},
    {"GET", KW_GET},
    {"PUT", KW_PUT},
    {"BGET", KW_BGET},
    {"BPUT", KW_BPUT},
    {"SEEK", KW_SEEK},
    {"FIELD", KW_FIELD},
    {"SELECT", KW_SELECT},
    {"CASE", KW_CASE},
    {"CONST", KW_CONST},
    {"DECLARE", KW_DECLARE},
    {"SUB", KW_SUB},
    {"FUNCTION", KW_FUNCTION},
    {"CALL", KW_CALL},
    {"AUTO", KW_AUTO},
    {"BCOLOR", KW_BCOLOR},
    {"FCOLOR", KW_FCOLOR},
    {"CLEAR", KW_CLEAR},
    {"CURSOR", KW_CURSOR},
    {"LOCATE", KW_LOCATE},
    {"SHARED", KW_SHARED},
    {"SCREEN", KW_SCREEN},
    {"COLOR", KW_COLOR},
    {"LINE", KW_LINE},
    {"CIRCLE", KW_CIRCLE},
    {"PSET", KW_PSET},
    {"PRESET", KW_PRESET},
    {"CLS", KW_CLS},
    {"HOME", KW_HOME},
    {"LSET", KW_LSET},
    {"DEFSEG", KW_DEFSEG},
    {"RSET", KW_RSET},
    {"SWAP", KW_SWAP},
    {"LOCAL", KW_LOCAL},
    {"STATIC", KW_STATIC},
    {"REDIM", KW_REDIM},
    {"PRESERVE", KW_PRESERVE},
    {"PAINT", KW_PAINT},
    {"BEEP", KW_BEEP},
    {"SOUND", KW_SOUND},
    {"PLAY", KW_PLAY},
    {"BLOAD", KW_BLOAD},
    {"BSAVE", KW_BSAVE},
    {"BRUN", KW_BRUN},
    {"USING", KW_USING},
#if SUPPORT_EDITOR
    {"EDIT", KW_EDIT},
#endif
    {"LEVEL", KW_LEVEL},
    {"RESTRICT", KW_RESTRICT},
    {"RESET", KW_RESET},
    {"INFO", KW_INFO},
    {"UNLOAD", KW_UNLOAD},
    {"WAIT", KW_WAIT},
#if SUPPORT_MAT
    {"MAT", KW_MAT},
#endif
    {"MUX", KW_MUX},
    {"DEMUX", KW_DEMUX},
    {"UNPACK", KW_UNPACK},
    {"BITMUX", KW_BITMUX},
    {"ARRAY", KW_ARRAY},
    {"ENUM", KW_ENUM},
    {"WITH", KW_WITH},
    {"NOISE", KW_NOISE},
    {"_SNDPLAY", KW_SNDPLAY},
    {"_SNDLOOP", KW_SNDLOOP},
    {"_SNDSTOP", KW_SNDSTOP},
    {"_SNDPAUSE", KW_SNDPAUSE},
    {"_SNDVOL", KW_SNDVOL},
    {"_MOUSEINPUT", KW_MOUSEINPUT},
    {"_MOUSEHIDE", KW_MOUSEHIDE},
    {"_MOUSESHOW", KW_MOUSESHOW},
    {"MOUSE", KW_MOUSE},
    {"_MOUSE", KW_MOUSE},
    {"HMOUSE", KW_HMOUSE},
    {"_HMOUSE", KW_HMOUSE},
    {"VMOUSE", KW_VMOUSE},
    {"_VMOUSE", KW_VMOUSE},
    {"TRIG", KW_TRIG},
    {"_TRIG", KW_TRIG},
    {"DISPLAY", KW_DISPLAY},
    {"DISP", KW_DISP},
    {"DOEVENTS", KW_DOEVENTS},
    {"MSGBOX", KW_MSGBOX},
    {"LPRINT", KW_LPRINT},
    {"LLIST", KW_LLIST},
    {"RANDOMIZE", KW_RANDOMIZE},
    {"_RANDOMIZE", KW_RANDOMIZE},
    {"PWD", KW_PWD},
    {"HOSTNAME", KW_HOSTNAME},
    {"_HOSTNAME", KW_HOSTNAME},
    {"USERNAME", KW_USERNAME},
    {"_USERNAME", KW_USERNAME},
    {"PATH", KW_PATH},
    {"_PATH", KW_PATH},
    {"_TITLE", KW_TITLE},
    {"_SCREENMOVE", KW_SCREENMOVE},
    {"_FULLSCREEN", KW_FULLSCREEN},
    {"_RESIZE", KW_RESIZE},
    {"_ICON", KW_ICON},
    {"NWRITE", KW_NWRITE},
    {"_FREEIMAGE", KW_FREEIMAGE},
    {"_PUTIMAGE", KW_PUTIMAGE},
    {"_STATESAVE", KW_STATESAVE},
    {"_STATELOAD", KW_STATELOAD},
    {"MAP", KW_MAP},
    {"FILTER", KW_FILTER},
    {"REDUCE", KW_REDUCE},
    {"RENUM", KW_RENUM},
    {"REFORMAT", KW_REFORMAT},
    {"DELETE", KW_DELETE},
    {"HELP", KW_HELP},
    {"CATALOG", KW_CATALOG},
    {"CATEGORY", KW_CATEGORY},
    {"CATEGORIES", KW_CATEGORIES},
    {"DEVICES", KW_DEVICES},
    {"UNSAVE", KW_UNSAVE},
    {"POKE", KW_POKE},
    {"UNLESS", KW_UNLESS},
    {"DEMAND", KW_DEMAND},
    {"TRY", KW_TRY},
    {"CATCH", KW_CATCH},
    {"THROW", KW_THROW},
    {"ALIAS", KW_ALIAS},
    {"SCOPE", KW_SCOPE},
    {"KEYWORD", KW_KEYWORD},
    {"OVERRIDE", KW_OVERRIDE},
    {"METADATA", KW_METADATA},
    {"DEFINE", KW_DEFINE},
#if SUPPORT_OOP
    {"TYPE", KW_TYPE},
    {"CLASS", KW_CLASS},
#endif
    {"BORDER", KW_BORDER},
    {"INK", KW_INK},
    {"PAPER", KW_PAPER},
    {"PAUSE", KW_PAUSE},
    {"SYS", KW_SYS},
    {"GR", KW_GR},
    {"HGR", KW_HGR},
    {"HGR2", KW_HGR2},
    {"HCOLOR", KW_HCOLOR},
    {"PLOT", KW_PLOT},
    {"HLIN", KW_HLIN},
    {"VLIN", KW_VLIN},
    {"HPLOT", KW_HPLOT},
    {"ONERR", KW_ONERR},
    {"GRAPHICS", KW_GRAPHICS},
    {"MODE", KW_MODE},
    {"DRAWTO", KW_DRAWTO},
    {"SYSTEM", KW_SYSTEM},
    {"SHELL", KW_SHELL},
    {"BYE", KW_BYE},
    {"STOP", KW_STOP},
    {"EXIT", KW_EXIT},
    {"PROCEDURE", KW_PROCEDURE},
    {"ENDFUNC", KW_ENDFUNC},
    {"ENDPROC", KW_ENDPROC},
    {"TIMER", KW_TIMER},
    {"ALARM", KW_ALARM},
    {"ALARM$", KW_ALARM_STR},
    {"KEY", KW_KEY},
    {"OFF", KW_OFF},
    {"SET", KW_SET},
    {"SNOOZE", KW_SNOOZE},
    {"UNSET", KW_UNSET},
    {"INITGRAPH", KW_INITGRAPH},
    {"CLOSEGRAPH", KW_CLOSEGRAPH},
    {"PUTPIXEL", KW_PUTPIXEL},
    {"GETPIXEL", KW_GETPIXEL},
    {"BAR", KW_BAR},
    {"ELLIPSE", KW_ELLIPSE},
    {"RECTANGLE", KW_RECTANGLE},
    {"OUTTEXTXY", KW_OUTTEXTXY},
    {"PALETTE", KW_PALETTE},
    {"ASSERT", KW_ASSERT},
    {"TRON", KW_TRON},
    {"TROFF", KW_TROFF},
    {"BREAK", KW_BREAK},
    {"VARS", KW_VARS},
    {"CHECK", KW_CHECK},
    {"VERIFY", KW_VERIFY},
    {"TEST", KW_TEST},
    {"ENDTEST", KW_ENDTEST},
    {"TRACE", KW_TRACE},
    {"DEBUG", KW_DEBUG},
    {"CONT", KW_CONT},
    {"BACKTRACE", KW_BACKTRACE},
    {"DUMP", KW_DUMP},
    {"VER", KW_VER},
    {"VER$", KW_VER_STR},
    {"VARPTR", KW_VARPTR},
    {"VARPTR$", KW_VARPTR_STR},
    {"VERSION", KW_VERSION},
    {"REMOVE", KW_REMOVE},
    {"REMOVE$", KW_REMOVE_STR},
    {"AND", KW_AND},
    {"OR", KW_OR},
    {"NOT", KW_NOT},
    {"XOR", KW_XOR},
    {"EQ", KW_EQ},
    {"NE", KW_NE},
    {"LT", KW_LT},
    {"GT", KW_GT},
    {"LE", KW_LE},
    {"GE", KW_GE},
    {"IMP", KW_IMP},
    {"EQV", KW_EQV},
    {"MOD", KW_MOD},
    {"SHL", KW_SHL},
    {"SHR", KW_SHR},
    {"READBIT", KW_READBIT},
    {"SETBIT", KW_SETBIT},
    {"RESETBIT", KW_RESETBIT},
    {"TOGGLEBIT", KW_TOGGLEBIT},
    {"MIN", KW_MIN},
    {"MAX", KW_MAX},
    {"HYPOT", KW_HYPOT},
    {"REMAINDER", KW_REMAINDER},
    {"ATAN2", KW_ATAN2},
    {"PUBLIC", KW_PUBLIC},
    {"SHARE", KW_SHARE},
    {"WHEN", KW_WHEN},
    {"USE", KW_USE},
    {"HANDLER", KW_HANDLER},
    {"CAUSE", KW_CAUSE},
    {"RETRY", KW_RETRY},
    {"CONTINUE", KW_CONTINUE},
    {"ASK", KW_ASK},
    {"RECSIZE", KW_RECSIZE},
    {"RECTYPE", KW_RECTYPE},
    {"ORGANIZATION", KW_ORGANIZATION},
    {"VIEWPORT", KW_VIEWPORT},
    {"WINDOW", KW_WINDOW},
    {"PICTURE", KW_PICTURE},
    {"DRAW", KW_DRAW},
    {"EXTERNAL", KW_EXTERNAL},
    {"DET", KW_DET},
    {"DOT", KW_DOT},
    {"CROSS", KW_CROSS},
    {"ZER", KW_ZER},
    {"ONE", KW_ONE},
    {"IDN", KW_IDN},
    {"TRN", KW_TRN},
    {"INV", KW_INV},
    {"COMPLEX", KW_COMPLEX},
    {"DEFCPX", KW_DEFCPX},
    {"CHANGE", KW_CHANGE},
    {"FORM", KW_FORM},
    {"IMAGE", KW_IMAGE},
    {"TEXT", KW_TEXT},
    {"MODIFY", KW_MODIFY},
    {"APPEND", KW_APPEND},
    {"LINPUT", KW_LINPUT},
    {"ZONE", KW_ZONE},
    {"MARGIN", KW_MARGIN},
    {"FNEND", KW_FNEND},
    {"GLOBAL", KW_GLOBAL},
    {"EXPORT", KW_EXPORT},
    {"BYVAL", KW_BYVAL},
    {"BYREF", KW_BYREF},
    {"EXTYPE", KW_EXTYPE},
    {"EXTEXT$", KW_EXTEXT_STR},
    {"OPTIONAL", KW_OPTIONAL},
    {"PRIVATE", KW_PRIVATE},
    {"IMPORT", KW_IMPORT},
    {"MODULE", KW_MODULE},
    {"EXTEND", KW_EXTEND},
    {"NOEXTEND", KW_NOEXTEND},
    {"SCALE", KW_SCALE},
    {"SLEEP", KW_SLEEP},
    {"ECHO", KW_ECHO},
    {"NOECHO", KW_NOECHO},
    {"RECORD", KW_RECORD},
    {"SCRATCH", KW_SCRATCH},
    {"ENTER", KW_ENTER},
    {"ASSIGN", KW_ASSIGN},
    {"ADVANCE", KW_ADVANCE},
    {"OLD", KW_OLD},
    {"DIR", KW_DIR},
    {"SUSPEND", KW_SUSPEND},
    {"TASK", KW_TASK},
    {"EVENT", KW_EVENT},
    {"EXTENDS", KW_EXTENDS},
    {"PROPERTY", KW_PROPERTY},
    {"METHOD", KW_METHOD},
    {"CONSTRUCTOR", KW_CONSTRUCTOR},
    {"DESTRUCTOR", KW_DESTRUCTOR},
    {"PROTECTED", KW_PROTECTED},
    {"ABSTRACT", KW_ABSTRACT},
    {"INTERFACE", KW_INTERFACE},
    {"IMPLEMENTS", KW_IMPLEMENTS},
    {"OPERATOR", KW_OPERATOR},
    {"NOTHING", KW_NOTHING},
    {"LOGIN", KW_LOGIN},
    {"LOGOUT", KW_LOGOUT},
    {"WHO", KW_WHO},
    {"TTY", KW_TTY},
    {"PRIORITY", KW_PRIORITY},
    {"HELLO", KW_HELLO},
    {"GOODBYE", KW_GOODBYE},
    {"WHENEVER", KW_WHENEVER},
    {"VDIM", KW_VDIM},
    {"REWIND", KW_REWIND},
    {"BACKSPACE", KW_BACKSPACE},
    {"NOMARGIN", KW_NOMARGIN},
    {"NOPAGE", KW_NOPAGE},
    {"PAGE", KW_PAGE},
    {"DCOUNT", KW_DCOUNT},
    {"CREATEINDEX", KW_CREATEINDEX},
    {"DELETEINDEX", KW_DELETEINDEX},
    {"SETINDEX", KW_SETINDEX},
    {"INSERT", KW_INSERT},
    {"UPDATE", KW_UPDATE},
    {"RETRIEVE", KW_RETRIEVE},
    {"SEEKEQ", KW_SEEKEQ},
    {"SEEKGE", KW_SEEKGE},
    {"SEEKGT", KW_SEEKGT},
    {"BUTTON", KW_BUTTON},
    {"MENU", KW_MENU},
    {"TEXTBOX", KW_TEXTBOX},
    {"LISTBOX", KW_LISTBOX},
    {"CHECKBOX", KW_CHECKBOX},
    {"OPTIONBUTTON", KW_OPTIONBUTTON},
    {"LABEL", KW_LABEL},
    {"FRAME", KW_FRAME},
    {"COMBOBOX", KW_COMBOBOX},
    {"HSCROLLBAR", KW_HSCROLLBAR},
    {"VSCROLLBAR", KW_VSCROLLBAR},
    {"DRIVELISTBOX", KW_DRIVELISTBOX},
    {"DIRLISTBOX", KW_DIRLISTBOX},
    {"FILELISTBOX", KW_FILELISTBOX},
    {"TIMERCONTROL", KW_TIMERCONTROL},
    {"INTERRUPT", KW_INTERRUPT},
    {"INTERRUPTX", KW_INTERRUPTX},
    {"EXCHANGE", KW_EXCHANGE},
    {"PERFORM", KW_PERFORM},
    {"INVOKE", KW_INVOKE},
    {"PREFIX", KW_PREFIX},
    {"PROCEDURE", KW_PROCEDURE},
    {"REPEAT", KW_REPEAT},
    {"ENDLOOP", KW_ENDLOOP},
    {"EXITIF", KW_EXITIF},
    {"DESTROY", KW_DESTROY},
    {"CREATE", KW_CREATE},
    {"PARAM", KW_PARAM},
    {"ENDTYPE", KW_ENDTYPE},
    {"BYTE", KW_BYTE},
    {"BOOLEAN", KW_BOOLEAN},
    {"REAL", KW_REAL},
    {"FIND", KW_FIND},
    {"MAPEND", KW_MAPEND},
    {"SUBEND", KW_SUBEND},
    {"SUBEXIT", KW_SUBEXIT},
    {"INCR", KW_INCR},
    {"DECR", KW_DECR},
    {"CLR", KW_CLR},
    {"VOID", KW_VOID},
    {"ARRAYFILL", KW_ARRAYFILL},
    {"CEIL", KW_CEIL},
    {"PINMODE", KW_PINMODE},
    {"DWRITE", KW_DWRITE},
    {"DAC", KW_DAC},
    {"PWM", KW_PWM},
    {"SERVO", KW_SERVO},
    {"I2C", KW_I2C},
    {"SPI", KW_SPI},
    {"NEOPIXEL", KW_NEOPIXEL},
    {"DHT", KW_DHT},
    {"DELAY", KW_DELAY},
    {"EVERY", KW_EVERY},
    {"DEEPSLEEP", KW_DEEPSLEEP},
    {"LIGHTSLEEP", KW_LIGHTSLEEP},
    {"REBOOT", KW_REBOOT},
    {"FREQ", KW_FREQ},
    {"WIFI", KW_WIFI},
    {"MQTT", KW_MQTT},
    {"WEBREPL", KW_WEBREPL},
    {"PYTHON", KW_PYTHON},
    {"PEER", KW_PEER},
    {"BT", KW_BT},
    {"BLE", KW_BLE},
    {"NFC", KW_NFC},
    {"GEMINI", KW_GEMINI},
    {"GOPHER", KW_GOPHER},
    {"TNFS", KW_TNFS},
    {"FUJI", KW_FUJI},
    {"REMOTE", KW_REMOTE},
    {"NIL", KW_NIL},
    {"NET", KW_NET},
    {"SOCK", KW_SOCK},
    {"PORT", KW_PORT},
    {"SNIFF", KW_SNIFF},
    {"PACKET", KW_PACKET},
    {"CRYPTO", KW_CRYPTO},
    {NULL, KW_NONE}
};

//
// ---- Custom Keyword Registry ----

static CustomKeywordMap g_custom_keywords[MAX_CUSTOM_KEYWORDS];
static int              g_custom_keyword_count = 0;

// resets all custom keyword registrations back to factory dialect baseline
void keyword_clear_custom(void) {
    g_custom_keyword_count = 0;
}

// registers a new dynamic keyword identifier into the custom keyword pool
BppKeywordId keyword_register_custom(const char *name) {
    if (!name || g_custom_keyword_count >= MAX_CUSTOM_KEYWORDS) {
        return KW_NONE;
    }
    for (int i = 0; i < g_custom_keyword_count; ++i) {
        if (runtime_strcasecmp(g_custom_keywords[i].name, name) == 0) {
            return g_custom_keywords[i].id;
        }
    }
    size_t len = runtime_strlen(name);
    if (len > 63) len = 63;
    runtime_memset(&g_custom_keywords[g_custom_keyword_count], 0, sizeof(CustomKeywordMap));
    runtime_memcpy(g_custom_keywords[g_custom_keyword_count].name, name, len);
    g_custom_keywords[g_custom_keyword_count].name[len] = '\0';
    
    BppKeywordId new_id = (BppKeywordId)(1000 + g_custom_keyword_count);
    g_custom_keywords[g_custom_keyword_count].id = new_id;
    g_custom_keyword_count++;
    return new_id;
}

// retrieves the string name of any static or dynamic keyword ID
const char *lex_keyword_name(BppKeywordId kw) {
    for (int i = 0; k_keywords[i].name != NULL; ++i) {
        if (k_keywords[i].id == kw) {
            return k_keywords[i].name;
        }
    }
    for (int i = 0; i < g_custom_keyword_count; ++i) {
        if (g_custom_keywords[i].id == kw) {
            return g_custom_keywords[i].name;
        }
    }
    return "UNKNOWN";
}

// looks up keyword ID by string name across static and dynamic registries
BppKeywordId lex_find_keyword_by_name(const char *name) {
    if (!name) return KW_NONE;
    for (int i = 0; k_keywords[i].name != NULL; ++i) {
        if (runtime_strcasecmp(k_keywords[i].name, name) == 0) {
            return k_keywords[i].id;
        }
    }
    for (int i = 0; i < g_custom_keyword_count; ++i) {
        if (runtime_strcasecmp(g_custom_keywords[i].name, name) == 0) {
            return g_custom_keywords[i].id;
        }
    }
    return KW_NONE;
}

