/* Generated by BASIC++ Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* === Runtime Variables === */
static double bpp_vars[26];           /* A-Z */
static char bpp_strvars[26][256];     /* A$-Z$ */
static double bpp_at_array[4096];     /* @() legacy array */
static int bpp_print_width = 14;

/* === GOSUB Stack === */
#define BPP_MAX_STACK 256
static int bpp_gosub_stack[BPP_MAX_STACK];
static int bpp_gosub_sp = 0;

/* === DIM Arrays === */
#define BPP_MAX_DIM 64
#define BPP_MAX_ELEM 8192
static double bpp_dim_pool[BPP_MAX_ELEM];
static int bpp_dim_used = 0;
typedef struct { char name[32]; int d1,d2,off; } BppDim;
static BppDim bpp_dims[BPP_MAX_DIM];
static int bpp_dim_count = 0;

static void bpp_dim_alloc(const char *nm, int d1, int d2) {
    int sz = (d1+1) * (d2>0 ? d2+1 : 1);
    BppDim *d = &bpp_dims[bpp_dim_count++];
    strncpy(d->name, nm, 31); d->name[31]='\0';
    d->d1=d1; d->d2=d2; d->off=bpp_dim_used;
    memset(&bpp_dim_pool[bpp_dim_used], 0, sizeof(double)*(size_t)sz);
    bpp_dim_used += sz;
}

static double *bpp_dim_ref(const char *nm, int i1, int i2) {
    int k;
    for (k=0; k<bpp_dim_count; k++) {
        if (strcmp(bpp_dims[k].name, nm)==0) {
            int idx = (bpp_dims[k].d2>0)
                ? i1*(bpp_dims[k].d2+1)+i2 : i1;
            return &bpp_dim_pool[bpp_dims[k].off + idx];
        }
    }
    fprintf(stderr, "Array not found: %s\n", nm);
    exit(1);
    return NULL;
}

/* === String DIM arrays === */
#define BPP_MAX_STRDIM 26
#define BPP_MAX_STRDIM_SIZE 256
static struct { char nm[16]; int d1; int d2;
    char data[BPP_MAX_STRDIM_SIZE][256]; } bpp_strdims[BPP_MAX_STRDIM];
static int bpp_strdim_count = 0;

static char *bpp_strdim_ref(const char *nm, int i1, int i2) {
    int k;
    (void)i2;
    for (k = 0; k < bpp_strdim_count; k++) {
        if (strcmp(bpp_strdims[k].nm, nm) == 0) {
            if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
            return bpp_strdims[k].data[i1];
        }
    }
    /* Auto-create */
    if (bpp_strdim_count < BPP_MAX_STRDIM) {
        int j;
        strncpy(bpp_strdims[bpp_strdim_count].nm, nm, 15);
        bpp_strdims[bpp_strdim_count].nm[15] = '\0';
        for (j = 0; j < BPP_MAX_STRDIM_SIZE; j++)
            bpp_strdims[bpp_strdim_count].data[j][0] = '\0';
        bpp_strdim_count++;
        if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
        return bpp_strdims[bpp_strdim_count-1].data[i1];
    }
    fprintf(stderr, "String array not found: %s\n", nm);
    exit(1);
    return NULL;
}

/* === DATA/READ support === */
#define BPP_MAX_DATA 4096
static double bpp_data_pool[BPP_MAX_DATA];
static int bpp_data_count = 0;
static int bpp_data_ptr = 0;

static double bpp_read_num(void) {
    if (bpp_data_ptr >= bpp_data_count) {
        fprintf(stderr, "OUT OF DATA\n"); exit(1);
    }
    return bpp_data_pool[bpp_data_ptr++];
}

/* === String helpers === */
static char bpp_strtmp[8][256];
static int bpp_strtmp_idx = 0;

static char *bpp_tmp(void) {
    char *p = bpp_strtmp[bpp_strtmp_idx];
    bpp_strtmp_idx = (bpp_strtmp_idx+1) & 7;
    return p;
}

static const char *bpp_concat(const char *a, const char *b) {
    char *t = bpp_tmp();
    t[0]='\0';
    strncat(t, a, 254);
    strncat(t, b, 254-(int)strlen(t));
    return t;
}

static const char *bpp_left(const char *s, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if (n>len) n=len; if(n<0) n=0;
    memcpy(t, s, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_right(const char *s, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if (n>len) n=len; if(n<0) n=0;
    memcpy(t, s+len-n, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_mid(const char *s, int st, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if(st<0) st=0; if(st>len) st=len;
    if(n<0) n=0; if(st+n>len) n=len-st;
    memcpy(t, s+st, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_chr(int n) {
    char *t = bpp_tmp();
    t[0]=(char)n; t[1]='\0';
    return t;
}

static const char *bpp_str(double n) {
    char *t = bpp_tmp();
    sprintf(t, "%g", n);
    return t;
}

/* === TAB helper === */
static const char *bpp_tab(int col) {
    static char buf[256];
    int i;
    if (col < 0) col = 0;
    if (col > 255) col = 255;
    for (i = 0; i < col; i++) buf[i] = ' ';
    buf[col] = '\0';
    return buf;
}

/* === DEF FN support === */
#define BPP_MAX_FN 26
typedef double (*BppFnPtr)(double);
static double bpp_fn_param;

int main(void) {

  L10: /* Line 10 */
      L20: /* Line 20 */
      L21: /* Line 21 */
      L22: /* Line 22 */
    bpp_vars[6] = 0;
    if (((strcmp(bpp_strvars[11], "P") > 0))) { bpp_vars[6] = 1;
 }
  L23: /* Line 23 */
      L29: /* Line 29 */
    printf("%s", "STATEMENT");
  L30: /* Line 30 */
    printf("? ");
    fflush(stdout);
    { char _buf[256]; int _len;
      fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
      while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
      strncpy(bpp_strvars[0], _buf, 255); }
  L35: /* Line 35 */
      L40: /* Line 40 */
    bpp_vars[0] = (double)(unsigned char)(bpp_left(bpp_strvars[0], (int)(1)))[0];
  L50: /* Line 50 */
    /* REM  */
  L60: /* Line 60 */
    /* REM  */
  L70: /* Line 70 */
    bpp_vars[19] = 1;
  bpp_for_0:;
  L80: /* Line 80 */
    strncpy(bpp_strvars[15], bpp_mid(bpp_strvars[0], (int)(bpp_vars[19]), (int)(1)), 255); bpp_strvars[15][255]='\0';
  L90: /* Line 90 */
    bpp_vars[14] = 1;
  bpp_for_1:;
  L95: /* Line 95 */
    sprintf(bpp_strvars[18], "%g", bpp_read_num());
    *bpp_dim_ref("S", (int)(1), 0) = bpp_read_num();
    *bpp_dim_ref("S", (int)(2), 0) = bpp_read_num();
    *bpp_dim_ref("S", (int)(3), 0) = bpp_read_num();
    *bpp_dim_ref("S", (int)(4), 0) = bpp_read_num();
    *bpp_dim_ref("S", (int)(5), 0) = bpp_read_num();
    *bpp_dim_ref("S", (int)(6), 0) = bpp_read_num();
    *bpp_dim_ref("S", (int)(7), 0) = bpp_read_num();
  L96: /* Line 96 */
    if (((strcmp(bpp_strvars[15], " ") == 0))) { goto L812;
 }
  L100: /* Line 100 */
    if (((strcmp(bpp_strvars[15], bpp_strvars[18]) == 0))) { goto L200;
 }
  L120: /* Line 120 */
    bpp_vars[14] += 1;
    if (bpp_vars[14] <= 50) goto bpp_for_1;
  L200: /* Line 200 */
    bpp_data_ptr = 0;
  L201: /* Line 201 */
    strncpy(bpp_strvars[23], bpp_strvars[12], 255); bpp_strvars[23][255]='\0';
  L202: /* Line 202 */
    if (((strcmp(bpp_strvars[12], "ALL") == 0))) { strncpy(bpp_strvars[23], bpp_strvars[18], 255); bpp_strvars[23][255]='\0';
 }
  L205: /* Line 205 */
    bpp_vars[20] = 1;
  bpp_for_2:;
  L210: /* Line 210 */
    bpp_vars[10] = 8;
  bpp_for_3:;
  L230: /* Line 230 */
    if (((pow(2, bpp_vars[10])) < *bpp_dim_ref("S", (int)(bpp_vars[20]), 0))) { goto L270;
 }
  L240: /* Line 240 */
    *bpp_dim_ref("J", (int)((9 - bpp_vars[10])), 0) = 0;
  L250: /* Line 250 */
    goto L280;
  L270: /* Line 270 */
    *bpp_dim_ref("J", (int)((9 - bpp_vars[10])), 0) = 1;
    *bpp_dim_ref("S", (int)(bpp_vars[20]), 0) = (*bpp_dim_ref("S", (int)(bpp_vars[20]), 0) - (pow(2, bpp_vars[10])));
  L272: /* Line 272 */
    if ((*bpp_dim_ref("S", (int)(bpp_vars[20]), 0) == 1)) { goto L815;
 }
  L280: /* Line 280 */
    bpp_vars[10] += (-(1));
    if (((-(1)) > 0 && bpp_vars[10] <= 0) || ((-(1)) < 0 && bpp_vars[10] >= 0)) goto bpp_for_3;
  L445: /* Line 445 */
    bpp_vars[19] = 1;
  bpp_for_4:;
  L447: /* Line 447 */
    printf("%s", bpp_tab((int)(((((63 - (4.5 * bpp_vars[24])) * bpp_vars[6]) / (double)strlen(bpp_strvars[23])) + 1))));
  L450: /* Line 450 */
    bpp_vars[1] = 1;
  bpp_for_5:;
  L460: /* Line 460 */
    if ((*bpp_dim_ref("J", (int)(bpp_vars[1]), 0) == 0)) { goto L500;
 }
  L465: /* Line 465 */
    bpp_vars[8] = 1;
  bpp_for_6:;
    printf("%s", bpp_strvars[23]);
    bpp_vars[8] += 1;
    if (bpp_vars[8] <= bpp_vars[24]) goto bpp_for_6;
  L470: /* Line 470 */
    goto L600;
  L500: /* Line 500 */
    bpp_vars[8] = 1;
  bpp_for_7:;
  L510: /* Line 510 */
    bpp_vars[8] = 1;
  bpp_for_8:;
  L520: /* Line 520 */
    printf("%s", " ");
    bpp_vars[8] += 1;
    if (bpp_vars[8] <= (double)strlen(bpp_strvars[23])) goto bpp_for_8;
  L530: /* Line 530 */
    bpp_vars[8] += 1;
    if (bpp_vars[8] <= (double)strlen(bpp_strvars[23])) goto bpp_for_8;
  L600: /* Line 600 */
    bpp_vars[1] += 1;
    if (bpp_vars[1] <= *bpp_dim_ref("F", (int)(bpp_vars[20]), 0)) goto bpp_for_5;
  L620: /* Line 620 */
        printf("\n");
  L630: /* Line 630 */
    bpp_vars[19] += 1;
    if (bpp_vars[19] <= bpp_vars[23]) goto bpp_for_4;
  L700: /* Line 700 */
    bpp_vars[20] += 1;
    if (bpp_vars[20] <= 7) goto bpp_for_2;
  L750: /* Line 750 */
    bpp_vars[7] = 1;
  bpp_for_9:;
        printf("\n");
    bpp_vars[7] += 1;
    if (bpp_vars[7] <= (2 * bpp_vars[23])) goto bpp_for_9;
  L800: /* Line 800 */
    bpp_vars[19] += 1;
    if (bpp_vars[19] <= bpp_vars[23]) goto bpp_for_4;
  L806: /* Line 806 */
    bpp_vars[7] = 1;
  bpp_for_10:;
        printf("\n");
    bpp_vars[7] += 1;
    if (bpp_vars[7] <= 75) goto bpp_for_10;
  L810: /* Line 810 */
    goto bpp_end;
  L812: /* Line 812 */
    bpp_vars[7] = 1;
  bpp_for_11:;
        printf("\n");
    bpp_vars[7] += 1;
    if (bpp_vars[7] <= (7 * bpp_vars[23])) goto bpp_for_11;
  L813: /* Line 813 */
    goto L800;
  L815: /* Line 815 */
    *bpp_dim_ref("F", (int)(bpp_vars[20]), 0) = (9 - bpp_vars[10]);
    goto L445;
  L899: /* Line 899 */
    /* DATA - see initialization */
  L900: /* Line 900 */
    /* DATA - see initialization */
  L901: /* Line 901 */
    /* DATA - see initialization */
  L902: /* Line 902 */
    /* DATA - see initialization */
  L903: /* Line 903 */
    /* DATA - see initialization */
  L904: /* Line 904 */
    /* DATA - see initialization */
  L905: /* Line 905 */
    /* DATA - see initialization */
  L906: /* Line 906 */
    /* DATA - see initialization */
  L907: /* Line 907 */
    /* DATA - see initialization */
  L908: /* Line 908 */
    /* DATA - see initialization */
  L909: /* Line 909 */
    /* DATA - see initialization */
  L910: /* Line 910 */
    /* DATA - see initialization */
  L911: /* Line 911 */
    /* DATA - see initialization */
  L912: /* Line 912 */
    /* DATA - see initialization */
  L913: /* Line 913 */
    /* DATA - see initialization */
  L914: /* Line 914 */
    /* DATA - see initialization */
  L915: /* Line 915 */
    /* DATA - see initialization */
  L916: /* Line 916 */
    /* DATA - see initialization */
  L917: /* Line 917 */
    /* DATA - see initialization */
  L918: /* Line 918 */
    /* DATA - see initialization */
  L919: /* Line 919 */
    /* DATA - see initialization */
  L920: /* Line 920 */
    /* DATA - see initialization */
  L921: /* Line 921 */
    /* DATA - see initialization */
  L922: /* Line 922 */
    /* DATA - see initialization */
  L923: /* Line 923 */
    /* DATA - see initialization */
  L924: /* Line 924 */
    /* DATA - see initialization */
  L925: /* Line 925 */
    /* DATA - see initialization */
  L926: /* Line 926 */
    /* DATA - see initialization */
  L927: /* Line 927 */
    /* DATA - see initialization */
  L928: /* Line 928 */
    /* DATA - see initialization */
  L929: /* Line 929 */
    /* DATA - see initialization */
  L930: /* Line 930 */
    /* DATA - see initialization */
  L931: /* Line 931 */
    /* DATA - see initialization */
  L932: /* Line 932 */
    /* DATA - see initialization */
  L933: /* Line 933 */
    /* DATA - see initialization */
  L934: /* Line 934 */
    /* DATA - see initialization */
  L935: /* Line 935 */
    /* DATA - see initialization */
  L936: /* Line 936 */
    /* DATA - see initialization */
  L937: /* Line 937 */
    /* DATA - see initialization */
  L938: /* Line 938 */
    /* DATA - see initialization */
  L939: /* Line 939 */
    /* DATA - see initialization */
  L940: /* Line 940 */
    /* DATA - see initialization */
  L1000: /* Line 1000 */
    printf("STOPPED\n"); goto bpp_end;
  L1002: /* Line 1002 */
    goto bpp_end;
  bpp_end:
    return 0;
}
