/* Generated by BASIC++ Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* === Runtime Variables === */
static double bpp_vars[26];           /* A-Z */
static char bpp_strvars[26][256];     /* A$-Z$ */
static double bpp_at_array[4096];     /* @() legacy array */
static int bpp_print_width = 14;

/* === GOSUB Stack === */
#define BPP_MAX_STACK 256
static int bpp_gosub_stack[BPP_MAX_STACK];
static int bpp_gosub_sp = 0;

/* === DIM Arrays === */
#define BPP_MAX_DIM 64
#define BPP_MAX_ELEM 8192
static double bpp_dim_pool[BPP_MAX_ELEM];
static int bpp_dim_used = 0;
typedef struct { char name[32]; int d1,d2,off; } BppDim;
static BppDim bpp_dims[BPP_MAX_DIM];
static int bpp_dim_count = 0;

static void bpp_dim_alloc(const char *nm, int d1, int d2) {
    int sz = (d1+1) * (d2>0 ? d2+1 : 1);
    BppDim *d = &bpp_dims[bpp_dim_count++];
    strncpy(d->name, nm, 31); d->name[31]='\0';
    d->d1=d1; d->d2=d2; d->off=bpp_dim_used;
    memset(&bpp_dim_pool[bpp_dim_used], 0, sizeof(double)*(size_t)sz);
    bpp_dim_used += sz;
}

static double *bpp_dim_ref(const char *nm, int i1, int i2) {
    int k;
    for (k=0; k<bpp_dim_count; k++) {
        if (strcmp(bpp_dims[k].name, nm)==0) {
            int idx = (bpp_dims[k].d2>0)
                ? i1*(bpp_dims[k].d2+1)+i2 : i1;
            return &bpp_dim_pool[bpp_dims[k].off + idx];
        }
    }
    fprintf(stderr, "Array not found: %s\n", nm);
    exit(1);
    return NULL;
}

/* === String DIM arrays === */
#define BPP_MAX_STRDIM 26
#define BPP_MAX_STRDIM_SIZE 256
static struct { char nm[16]; int d1; int d2;
    char data[BPP_MAX_STRDIM_SIZE][256]; } bpp_strdims[BPP_MAX_STRDIM];
static int bpp_strdim_count = 0;

static char *bpp_strdim_ref(const char *nm, int i1, int i2) {
    int k;
    (void)i2;
    for (k = 0; k < bpp_strdim_count; k++) {
        if (strcmp(bpp_strdims[k].nm, nm) == 0) {
            if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
            return bpp_strdims[k].data[i1];
        }
    }
    /* Auto-create */
    if (bpp_strdim_count < BPP_MAX_STRDIM) {
        int j;
        strncpy(bpp_strdims[bpp_strdim_count].nm, nm, 15);
        bpp_strdims[bpp_strdim_count].nm[15] = '\0';
        for (j = 0; j < BPP_MAX_STRDIM_SIZE; j++)
            bpp_strdims[bpp_strdim_count].data[j][0] = '\0';
        bpp_strdim_count++;
        if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
        return bpp_strdims[bpp_strdim_count-1].data[i1];
    }
    fprintf(stderr, "String array not found: %s\n", nm);
    exit(1);
    return NULL;
}

/* === DATA/READ support === */
#define BPP_MAX_DATA 4096
static double bpp_data_pool[BPP_MAX_DATA];
static int bpp_data_count = 0;
static int bpp_data_ptr = 0;

static double bpp_read_num(void) {
    if (bpp_data_ptr >= bpp_data_count) {
        fprintf(stderr, "OUT OF DATA\n"); exit(1);
    }
    return bpp_data_pool[bpp_data_ptr++];
}

/* === String helpers === */
static char bpp_strtmp[8][256];
static int bpp_strtmp_idx = 0;

static char *bpp_tmp(void) {
    char *p = bpp_strtmp[bpp_strtmp_idx];
    bpp_strtmp_idx = (bpp_strtmp_idx+1) & 7;
    return p;
}

static const char *bpp_concat(const char *a, const char *b) {
    char *t = bpp_tmp();
    t[0]='\0';
    strncat(t, a, 254);
    strncat(t, b, 254-(int)strlen(t));
    return t;
}

static const char *bpp_left(const char *s, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if (n>len) n=len; if(n<0) n=0;
    memcpy(t, s, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_right(const char *s, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if (n>len) n=len; if(n<0) n=0;
    memcpy(t, s+len-n, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_mid(const char *s, int st, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if(st<0) st=0; if(st>len) st=len;
    if(n<0) n=0; if(st+n>len) n=len-st;
    memcpy(t, s+st, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_chr(int n) {
    char *t = bpp_tmp();
    t[0]=(char)n; t[1]='\0';
    return t;
}

static const char *bpp_str(double n) {
    char *t = bpp_tmp();
    sprintf(t, "%g", n);
    return t;
}

/* === TAB helper === */
static const char *bpp_tab(int col) {
    static char buf[256];
    int i;
    if (col < 0) col = 0;
    if (col > 255) col = 255;
    for (i = 0; i < col; i++) buf[i] = ' ';
    buf[col] = '\0';
    return buf;
}

/* === DEF FN support === */
#define BPP_MAX_FN 26
typedef double (*BppFnPtr)(double);
static double bpp_fn_param;

int main(void) {

  L8: /* Line 8 */
    printf("%s", "YOU ARE A PILOT IN A WORLD WAR II BOMBER.");
    printf("\n");
  L10: /* Line 10 */
      L20: /* Line 20 */
    if (((((bpp_vars[0] > 0)) && ((bpp_vars[0] < 5))))) { goto L25;
 }
  L22: /* Line 22 */
    printf("%s", "TRY AGAIN...");
    printf("\n");
    goto L10;
  L25: /* Line 25 */
    { int _sel = (int)(bpp_vars[0]);
        if (_sel == 1) goto L30;
        if (_sel == 2) goto L110;
        if (_sel == 3) goto L200;
        if (_sel == 4) goto L220;
    }
  L30: /* Line 30 */
      L40: /* Line 40 */
    if (((((bpp_vars[1] > 0)) && ((bpp_vars[1] < 4))))) { goto L45;
 }
  L42: /* Line 42 */
    printf("%s", "TRY AGAIN...");
    printf("\n");
    goto L30;
  L45: /* Line 45 */
        printf("\n");
    { int _sel = (int)(bpp_vars[1]);
        if (_sel == 1) goto L50;
        if (_sel == 2) goto L80;
        if (_sel == 3) goto L90;
    }
  L50: /* Line 50 */
    printf("%s", "SHOULD BE EASY -- YOU'RE FLYING A NAZI-MADE PLANE.");
    printf("\n");
  L60: /* Line 60 */
    goto L280;
  L80: /* Line 80 */
    printf("%s", "BE CAREFUL!!!");
    printf("\n");
    goto L280;
  L90: /* Line 90 */
    printf("%s", "YOU'RE GOING FOR THE OIL, EH?");
    printf("\n");
    goto L280;
  L110: /* Line 110 */
      L120: /* Line 120 */
    if (((((bpp_vars[6] > 0)) && ((bpp_vars[6] < 5))))) { goto L125;
 }
  L122: /* Line 122 */
    printf("%s", "TRY AGAIN...");
    printf("\n");
    goto L110;
  L125: /* Line 125 */
        printf("\n");
    { int _sel = (int)(bpp_vars[6]);
        if (_sel == 1) goto L130;
        if (_sel == 2) goto L150;
        if (_sel == 3) goto L170;
        if (_sel == 4) goto L190;
    }
  L130: /* Line 130 */
    printf("%s", "YOU'VE GOT 2 TONS OF BOMBS FLYING FOR PLOESTI.");
    printf("\n");
    goto L280;
  L150: /* Line 150 */
    printf("%s", "YOU'RE DUMPING THE A-BOMB ON HIROSHIMA.");
    printf("\n");
    goto L280;
  L170: /* Line 170 */
    printf("%s", "YOU'RE CHASING THE BISMARK IN THE NORTH SEA.");
    printf("\n");
    goto L280;
  L190: /* Line 190 */
    printf("%s", "YOU'RE BUSTING A GERMAN HEAVY WATER PLANT IN THE RUHR.");
    printf("\n");
  L195: /* Line 195 */
    goto L280;
  L200: /* Line 200 */
    printf("%s", "YOU'RE FLYING A KAMIKAZE MISSION OVER THE USS LEXINGTON.");
    printf("\n");
  L205: /* Line 205 */
      L207: /* Line 207 */
    if (((strcmp(bpp_strvars[5], "N") == 0))) { bpp_vars[18] = 0;
 }
    goto L358;
  L210: /* Line 210 */
        printf("\n");
    if ((((double)(rand() % (int)(1))) > 0.65000000000000002)) { goto L325;
 }
  L215: /* Line 215 */
    goto L380;
  L220: /* Line 220 */
    printf("%s", "A NAZI, EH?  OH WELL.  ARE YOU GOING FOR RUSSIA(1),");
    printf("\n");
  L230: /* Line 230 */
      L232: /* Line 232 */
    printf("%s", "TRY AGAIN...");
    printf("\n");
    goto L220;
  L235: /* Line 235 */
        printf("\n");
    { int _sel = (int)(bpp_vars[12]);
        if (_sel == 1) goto L250;
        if (_sel == 2) goto L260;
        if (_sel == 3) goto L270;
    }
  L250: /* Line 250 */
    printf("%s", "YOU'RE NEARING STALINGRAD.");
    printf("\n");
    goto L280;
  L260: /* Line 260 */
    printf("%s", "NEARING LONDON.  BE CAREFUL, THEY'VE GOT RADAR.");
    printf("\n");
    goto L280;
  L270: /* Line 270 */
    printf("%s", "NEARING VERSAILLES.  DUCK SOUP.  THEY'RE NEARLY DEFENSELESS.");
    printf("\n");
  L280: /* Line 280 */
        printf("\n");
  L285: /* Line 285 */
      L290: /* Line 290 */
    if ((bpp_vars[3] < 160)) { goto L300;
 }
  L292: /* Line 292 */
    printf("%s", "MISSIONS, NOT MILES...");
    printf("\n");
  L295: /* Line 295 */
    printf("%s", "150 MISSIONS IS HIGH EVEN FOR OLD-TIMERS.");
    printf("\n");
  L297: /* Line 297 */
    printf("%s", "NOW THEN, ");
    goto L285;
  L300: /* Line 300 */
        printf("\n");
    if ((bpp_vars[3] < 100)) { goto L310;
 }
  L305: /* Line 305 */
    printf("%s", "THAT'S PUSHING THE ODDS!");
    printf("\n");
    goto L320;
  L310: /* Line 310 */
    if ((bpp_vars[3] < 25)) { printf("%s", "FRESH OUT OF TRAINING, EH?");
printf("\n");
 }
  L320: /* Line 320 */
        printf("\n");
    if ((bpp_vars[3] < (160 * ((double)(rand() % (int)(1)))))) { goto L330;
 }
  L325: /* Line 325 */
    printf("%s", "DIRECT HIT!!!! ");
    printf("\n");
  L327: /* Line 327 */
    printf("%s", "MISSION SUCCESSFUL.");
    printf("\n");
    goto L390;
  L330: /* Line 330 */
    printf("%s", "MISSED TARGET BY");
    printf("\n");
  L335: /* Line 335 */
    printf("%s", "NOW YOU'RE REALLY IN FOR IT !!");
    printf("\n");
        printf("\n");
  L340: /* Line 340 */
      L345: /* Line 345 */
    if (((((bpp_vars[17] > 0)) && ((bpp_vars[17] < 4))))) { goto L350;
 }
  L347: /* Line 347 */
    printf("%s", "TRY AGAIN...");
    printf("\n");
    goto L340;
  L350: /* Line 350 */
        printf("\n");
    bpp_vars[19] = 0;
    if ((bpp_vars[17] == 2)) { goto L360;
 }
  L355: /* Line 355 */
      L357: /* Line 357 */
    if ((bpp_vars[18] < 10)) { printf("%s", "YOU LIE, BUT YOU'LL PAY...");
printf("\n");
 }
    goto L380;
  L358: /* Line 358 */
        printf("\n");
  L360: /* Line 360 */
        printf("\n");
    if ((bpp_vars[17] > 1)) { bpp_vars[19] = 35;
 }
  L365: /* Line 365 */
    if (((bpp_vars[18] + bpp_vars[19]) > (100 * ((double)(rand() % (int)(1)))))) { goto L380;
 }
  L370: /* Line 370 */
    printf("%s", "YOU MADE IT THROUGH TREMENDOUS FLAK!!");
    printf("\n");
    goto L390;
  L380: /* Line 380 */
    printf("%s", "* * * * BOOM * * * *");
    printf("\n");
  L384: /* Line 384 */
    printf("%s", "YOU HAVE BEEN SHOT DOWN.....");
    printf("\n");
  L386: /* Line 386 */
    printf("%s", "DEARLY BELOVED, WE ARE GATHERED HERE TODAY TO PAY OUR");
    printf("\n");
  L387: /* Line 387 */
    printf("%s", "LAST TRIBUTE...");
    printf("\n");
  L390: /* Line 390 */
        printf("\n");
        printf("\n");
        printf("\n");
      L395: /* Line 395 */
    if (((strcmp(bpp_strvars[20], "Y") == 0))) { goto L8;
 }
  L400: /* Line 400 */
    printf("%s", "CHICKEN !!!");
    printf("\n");
        printf("\n");
    goto bpp_end;
  bpp_end:
    return 0;
}
