/* Generated by BASIC++ Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* === Runtime Variables === */
static double bpp_vars[26];           /* A-Z */
static char bpp_strvars[26][256];     /* A$-Z$ */
static double bpp_at_array[4096];     /* @() legacy array */
static int bpp_print_width = 14;

/* === GOSUB Stack === */
#define BPP_MAX_STACK 256
static int bpp_gosub_stack[BPP_MAX_STACK];
static int bpp_gosub_sp = 0;

/* === DIM Arrays === */
#define BPP_MAX_DIM 64
#define BPP_MAX_ELEM 8192
static double bpp_dim_pool[BPP_MAX_ELEM];
static int bpp_dim_used = 0;
typedef struct { char name[32]; int d1,d2,off; } BppDim;
static BppDim bpp_dims[BPP_MAX_DIM];
static int bpp_dim_count = 0;

static void bpp_dim_alloc(const char *nm, int d1, int d2) {
    int sz = (d1+1) * (d2>0 ? d2+1 : 1);
    BppDim *d = &bpp_dims[bpp_dim_count++];
    strncpy(d->name, nm, 31); d->name[31]='\0';
    d->d1=d1; d->d2=d2; d->off=bpp_dim_used;
    memset(&bpp_dim_pool[bpp_dim_used], 0, sizeof(double)*(size_t)sz);
    bpp_dim_used += sz;
}

static double *bpp_dim_ref(const char *nm, int i1, int i2) {
    int k;
    for (k=0; k<bpp_dim_count; k++) {
        if (strcmp(bpp_dims[k].name, nm)==0) {
            int idx = (bpp_dims[k].d2>0)
                ? i1*(bpp_dims[k].d2+1)+i2 : i1;
            return &bpp_dim_pool[bpp_dims[k].off + idx];
        }
    }
    fprintf(stderr, "Array not found: %s\n", nm);
    exit(1);
    return NULL;
}

/* === String DIM arrays === */
#define BPP_MAX_STRDIM 26
#define BPP_MAX_STRDIM_SIZE 256
static struct { char nm[16]; int d1; int d2;
    char data[BPP_MAX_STRDIM_SIZE][256]; } bpp_strdims[BPP_MAX_STRDIM];
static int bpp_strdim_count = 0;

static char *bpp_strdim_ref(const char *nm, int i1, int i2) {
    int k;
    (void)i2;
    for (k = 0; k < bpp_strdim_count; k++) {
        if (strcmp(bpp_strdims[k].nm, nm) == 0) {
            if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
            return bpp_strdims[k].data[i1];
        }
    }
    /* Auto-create */
    if (bpp_strdim_count < BPP_MAX_STRDIM) {
        int j;
        strncpy(bpp_strdims[bpp_strdim_count].nm, nm, 15);
        bpp_strdims[bpp_strdim_count].nm[15] = '\0';
        for (j = 0; j < BPP_MAX_STRDIM_SIZE; j++)
            bpp_strdims[bpp_strdim_count].data[j][0] = '\0';
        bpp_strdim_count++;
        if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
        return bpp_strdims[bpp_strdim_count-1].data[i1];
    }
    fprintf(stderr, "String array not found: %s\n", nm);
    exit(1);
    return NULL;
}

/* === DATA/READ support === */
#define BPP_MAX_DATA 4096
static double bpp_data_pool[BPP_MAX_DATA];
static int bpp_data_count = 0;
static int bpp_data_ptr = 0;

static double bpp_read_num(void) {
    if (bpp_data_ptr >= bpp_data_count) {
        fprintf(stderr, "OUT OF DATA\n"); exit(1);
    }
    return bpp_data_pool[bpp_data_ptr++];
}

/* === String helpers === */
static char bpp_strtmp[8][256];
static int bpp_strtmp_idx = 0;

static char *bpp_tmp(void) {
    char *p = bpp_strtmp[bpp_strtmp_idx];
    bpp_strtmp_idx = (bpp_strtmp_idx+1) & 7;
    return p;
}

static const char *bpp_concat(const char *a, const char *b) {
    char *t = bpp_tmp();
    t[0]='\0';
    strncat(t, a, 254);
    strncat(t, b, 254-(int)strlen(t));
    return t;
}

static const char *bpp_left(const char *s, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if (n>len) n=len; if(n<0) n=0;
    memcpy(t, s, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_right(const char *s, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if (n>len) n=len; if(n<0) n=0;
    memcpy(t, s+len-n, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_mid(const char *s, int st, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if(st<0) st=0; if(st>len) st=len;
    if(n<0) n=0; if(st+n>len) n=len-st;
    memcpy(t, s+st, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_chr(int n) {
    char *t = bpp_tmp();
    t[0]=(char)n; t[1]='\0';
    return t;
}

static const char *bpp_str(double n) {
    char *t = bpp_tmp();
    sprintf(t, "%g", n);
    return t;
}

/* === TAB helper === */
static const char *bpp_tab(int col) {
    static char buf[256];
    int i;
    if (col < 0) col = 0;
    if (col > 255) col = 255;
    for (i = 0; i < col; i++) buf[i] = ' ';
    buf[col] = '\0';
    return buf;
}

/* === DEF FN support === */
#define BPP_MAX_FN 26
typedef double (*BppFnPtr)(double);
static double bpp_fn_param;

int main(void) {

  L2: /* Line 2 */
    printf("%s", bpp_tab((int)(33)));
    printf("%s", "CHANGE");
    printf("\n");
  L4: /* Line 4 */
    printf("%s", bpp_tab((int)(15)));
    printf("%s", "CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY");
    printf("\n");
  L5: /* Line 5 */
        printf("\n");
        printf("\n");
        printf("\n");
  L6: /* Line 6 */
    printf("%s", "I, YOUR FRIENDLY MICROCOMPUTER, WILL DETERMINE");
    printf("\n");
  L8: /* Line 8 */
    printf("%s", "THE CORRECT CHANGE FOR ITEMS COSTING UP TO $100.");
    printf("\n");
  L9: /* Line 9 */
        printf("\n");
        printf("\n");
  L10: /* Line 10 */
    printf("%s", "COST OF ITEM");
    printf("? ");
    fflush(stdout);
    { char _buf[256]; double _v;
      fgets(_buf, 256, stdin); _v = atof(_buf);
      bpp_vars[0] = _v; }
    printf("%s", "AMOUNT OF PAYMENT");
    printf("? ");
    fflush(stdout);
    { char _buf[256]; double _v;
      fgets(_buf, 256, stdin); _v = atof(_buf);
      bpp_vars[15] = _v; }
  L20: /* Line 20 */
    bpp_vars[2] = (bpp_vars[15] - bpp_vars[0]);
    bpp_vars[12] = bpp_vars[2];
    if ((bpp_vars[2] != 0)) { goto L90;
 }
  L25: /* Line 25 */
    printf("%s", "CORRECT AMOUNT, THANK YOU.");
    printf("\n");
  L30: /* Line 30 */
    goto L400;
  L90: /* Line 90 */
    if ((bpp_vars[2] > 0)) { goto L120;
 }
  L95: /* Line 95 */
    printf("%s", "SORRY, YOU HAVE SHORT-CHANGED ME $");
    { double _v = (bpp_vars[0] - bpp_vars[15]); if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("\n");
  L100: /* Line 100 */
    goto L10;
  L120: /* Line 120 */
    printf("%s", "YOUR CHANGE, $");
    { double _v = bpp_vars[2]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("\n");
  L130: /* Line 130 */
    bpp_vars[3] = floor((bpp_vars[2] / 10));
  L140: /* Line 140 */
    if ((bpp_vars[3] == 0)) { goto L155;
 }
  L150: /* Line 150 */
    { double _v = bpp_vars[3]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("%s", "TEN DOLLAR BILL(S)");
    printf("\n");
  L155: /* Line 155 */
    bpp_vars[2] = (bpp_vars[12] - (bpp_vars[3] * 10));
  L160: /* Line 160 */
    bpp_vars[4] = floor((bpp_vars[2] / 5));
  L170: /* Line 170 */
    if ((bpp_vars[4] == 0)) { goto L185;
 }
  L180: /* Line 180 */
    { double _v = bpp_vars[4]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("%s", "FIVE DOLLARS BILL(S)");
    printf("\n");
  L185: /* Line 185 */
    bpp_vars[2] = (bpp_vars[12] - ((bpp_vars[3] * 10) + (bpp_vars[4] * 5)));
  L190: /* Line 190 */
    bpp_vars[5] = floor(bpp_vars[2]);
  L200: /* Line 200 */
    if ((bpp_vars[5] == 0)) { goto L215;
 }
  L210: /* Line 210 */
    { double _v = bpp_vars[5]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("%s", "ONE DOLLAR BILL(S)");
    printf("\n");
  L215: /* Line 215 */
    bpp_vars[2] = (bpp_vars[12] - (((bpp_vars[3] * 10) + (bpp_vars[4] * 5)) + bpp_vars[5]));
  L220: /* Line 220 */
    bpp_vars[2] = (bpp_vars[2] * 100);
  L225: /* Line 225 */
    bpp_vars[13] = bpp_vars[2];
  L230: /* Line 230 */
    bpp_vars[6] = floor((bpp_vars[2] / 50));
  L240: /* Line 240 */
    if ((bpp_vars[6] == 0)) { goto L255;
 }
  L250: /* Line 250 */
    { double _v = bpp_vars[6]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("%s", "ONE HALF DOLLAR(S)");
    printf("\n");
  L255: /* Line 255 */
    bpp_vars[2] = (bpp_vars[13] - (bpp_vars[6] * 50));
  L260: /* Line 260 */
    bpp_vars[7] = floor((bpp_vars[2] / 25));
  L270: /* Line 270 */
    if ((bpp_vars[7] == 0)) { goto L285;
 }
  L280: /* Line 280 */
    { double _v = bpp_vars[7]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("%s", "QUARTER(S)");
    printf("\n");
  L285: /* Line 285 */
    bpp_vars[2] = (bpp_vars[13] - ((bpp_vars[6] * 50) + (bpp_vars[7] * 25)));
  L290: /* Line 290 */
    bpp_vars[8] = floor((bpp_vars[2] / 10));
  L300: /* Line 300 */
    if ((bpp_vars[8] == 0)) { goto L315;
 }
  L310: /* Line 310 */
    { double _v = bpp_vars[8]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("%s", "DIME(S)");
    printf("\n");
  L315: /* Line 315 */
    bpp_vars[2] = (bpp_vars[13] - (((bpp_vars[6] * 50) + (bpp_vars[7] * 25)) + (bpp_vars[8] * 10)));
  L320: /* Line 320 */
    bpp_vars[9] = floor((bpp_vars[2] / 5));
  L330: /* Line 330 */
    if ((bpp_vars[9] == 0)) { goto L345;
 }
  L340: /* Line 340 */
    { double _v = bpp_vars[9]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("%s", "NICKEL(S)");
    printf("\n");
  L345: /* Line 345 */
    bpp_vars[2] = (bpp_vars[13] - ((((bpp_vars[6] * 50) + (bpp_vars[7] * 25)) + (bpp_vars[8] * 10)) + (bpp_vars[9] * 5)));
  L350: /* Line 350 */
    bpp_vars[10] = floor((bpp_vars[2] + 0.5));
  L360: /* Line 360 */
    if ((bpp_vars[10] == 0)) { goto L380;
 }
  L370: /* Line 370 */
    { double _v = bpp_vars[10]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("%s", "PENNY(S)");
    printf("\n");
  L380: /* Line 380 */
    printf("%s", "THANK YOU, COME AGAIN.");
    printf("\n");
  L390: /* Line 390 */
        printf("\n");
        printf("\n");
  L400: /* Line 400 */
    goto L10;
  L410: /* Line 410 */
    goto bpp_end;
  bpp_end:
    return 0;
}
