/* Generated by BASIC++ Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* === Runtime Variables === */
static double bpp_vars[26];           /* A-Z */
static char bpp_strvars[26][256];     /* A$-Z$ */
static double bpp_at_array[4096];     /* @() legacy array */
static int bpp_print_width = 14;

/* === GOSUB Stack === */
#define BPP_MAX_STACK 256
static int bpp_gosub_stack[BPP_MAX_STACK];
static int bpp_gosub_sp = 0;

/* === DIM Arrays === */
#define BPP_MAX_DIM 64
#define BPP_MAX_ELEM 8192
static double bpp_dim_pool[BPP_MAX_ELEM];
static int bpp_dim_used = 0;
typedef struct { char name[32]; int d1,d2,off; } BppDim;
static BppDim bpp_dims[BPP_MAX_DIM];
static int bpp_dim_count = 0;

static void bpp_dim_alloc(const char *nm, int d1, int d2) {
    int sz = (d1+1) * (d2>0 ? d2+1 : 1);
    BppDim *d = &bpp_dims[bpp_dim_count++];
    strncpy(d->name, nm, 31); d->name[31]='\0';
    d->d1=d1; d->d2=d2; d->off=bpp_dim_used;
    memset(&bpp_dim_pool[bpp_dim_used], 0, sizeof(double)*(size_t)sz);
    bpp_dim_used += sz;
}

static double *bpp_dim_ref(const char *nm, int i1, int i2) {
    int k;
    for (k=0; k<bpp_dim_count; k++) {
        if (strcmp(bpp_dims[k].name, nm)==0) {
            int idx = (bpp_dims[k].d2>0)
                ? i1*(bpp_dims[k].d2+1)+i2 : i1;
            return &bpp_dim_pool[bpp_dims[k].off + idx];
        }
    }
    fprintf(stderr, "Array not found: %s\n", nm);
    exit(1);
    return NULL;
}

/* === String DIM arrays === */
#define BPP_MAX_STRDIM 26
#define BPP_MAX_STRDIM_SIZE 256
static struct { char nm[16]; int d1; int d2;
    char data[BPP_MAX_STRDIM_SIZE][256]; } bpp_strdims[BPP_MAX_STRDIM];
static int bpp_strdim_count = 0;

static char *bpp_strdim_ref(const char *nm, int i1, int i2) {
    int k;
    (void)i2;
    for (k = 0; k < bpp_strdim_count; k++) {
        if (strcmp(bpp_strdims[k].nm, nm) == 0) {
            if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
            return bpp_strdims[k].data[i1];
        }
    }
    /* Auto-create */
    if (bpp_strdim_count < BPP_MAX_STRDIM) {
        int j;
        strncpy(bpp_strdims[bpp_strdim_count].nm, nm, 15);
        bpp_strdims[bpp_strdim_count].nm[15] = '\0';
        for (j = 0; j < BPP_MAX_STRDIM_SIZE; j++)
            bpp_strdims[bpp_strdim_count].data[j][0] = '\0';
        bpp_strdim_count++;
        if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
        return bpp_strdims[bpp_strdim_count-1].data[i1];
    }
    fprintf(stderr, "String array not found: %s\n", nm);
    exit(1);
    return NULL;
}

/* === DATA/READ support === */
#define BPP_MAX_DATA 4096
static double bpp_data_pool[BPP_MAX_DATA];
static int bpp_data_count = 0;
static int bpp_data_ptr = 0;

static double bpp_read_num(void) {
    if (bpp_data_ptr >= bpp_data_count) {
        fprintf(stderr, "OUT OF DATA\n"); exit(1);
    }
    return bpp_data_pool[bpp_data_ptr++];
}

/* === String helpers === */
static char bpp_strtmp[8][256];
static int bpp_strtmp_idx = 0;

static char *bpp_tmp(void) {
    char *p = bpp_strtmp[bpp_strtmp_idx];
    bpp_strtmp_idx = (bpp_strtmp_idx+1) & 7;
    return p;
}

static const char *bpp_concat(const char *a, const char *b) {
    char *t = bpp_tmp();
    t[0]='\0';
    strncat(t, a, 254);
    strncat(t, b, 254-(int)strlen(t));
    return t;
}

static const char *bpp_left(const char *s, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if (n>len) n=len; if(n<0) n=0;
    memcpy(t, s, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_right(const char *s, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if (n>len) n=len; if(n<0) n=0;
    memcpy(t, s+len-n, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_mid(const char *s, int st, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if(st<0) st=0; if(st>len) st=len;
    if(n<0) n=0; if(st+n>len) n=len-st;
    memcpy(t, s+st, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_chr(int n) {
    char *t = bpp_tmp();
    t[0]=(char)n; t[1]='\0';
    return t;
}

static const char *bpp_str(double n) {
    char *t = bpp_tmp();
    sprintf(t, "%g", n);
    return t;
}

/* === TAB helper === */
static const char *bpp_tab(int col) {
    static char buf[256];
    int i;
    if (col < 0) col = 0;
    if (col > 255) col = 255;
    for (i = 0; i < col; i++) buf[i] = ' ';
    buf[col] = '\0';
    return buf;
}

/* === DEF FN support === */
#define BPP_MAX_FN 26
typedef double (*BppFnPtr)(double);
static double bpp_fn_param;

int main(void) {
    bpp_data_pool[0] = 1;
    bpp_data_pool[1] = 49;
    bpp_data_pool[2] = 52;
    bpp_data_pool[3] = 4;
    bpp_data_pool[4] = 13;
    bpp_data_pool[5] = 61;
    bpp_data_pool[6] = 64;
    bpp_data_pool[7] = 16;
    bpp_data_pool[8] = 22;
    bpp_data_pool[9] = 39;
    bpp_data_pool[10] = 23;
    bpp_data_pool[11] = 38;
    bpp_data_pool[12] = 26;
    bpp_data_pool[13] = 42;
    bpp_data_pool[14] = 27;
    bpp_data_pool[15] = 43;
    bpp_data_pool[16] = 1;
    bpp_data_pool[17] = 2;
    bpp_data_pool[18] = 3;
    bpp_data_pool[19] = 4;
    bpp_data_pool[20] = 5;
    bpp_data_pool[21] = 6;
    bpp_data_pool[22] = 7;
    bpp_data_pool[23] = 8;
    bpp_data_pool[24] = 9;
    bpp_data_pool[25] = 10;
    bpp_data_pool[26] = 11;
    bpp_data_pool[27] = 12;
    bpp_data_pool[28] = 13;
    bpp_data_pool[29] = 14;
    bpp_data_pool[30] = 15;
    bpp_data_pool[31] = 16;
    bpp_data_pool[32] = 17;
    bpp_data_pool[33] = 18;
    bpp_data_pool[34] = 19;
    bpp_data_pool[35] = 20;
    bpp_data_pool[36] = 21;
    bpp_data_pool[37] = 22;
    bpp_data_pool[38] = 23;
    bpp_data_pool[39] = 24;
    bpp_data_pool[40] = 25;
    bpp_data_pool[41] = 26;
    bpp_data_pool[42] = 27;
    bpp_data_pool[43] = 28;
    bpp_data_pool[44] = 29;
    bpp_data_pool[45] = 30;
    bpp_data_pool[46] = 31;
    bpp_data_pool[47] = 32;
    bpp_data_pool[48] = 33;
    bpp_data_pool[49] = 34;
    bpp_data_pool[50] = 35;
    bpp_data_pool[51] = 36;
    bpp_data_pool[52] = 37;
    bpp_data_pool[53] = 38;
    bpp_data_pool[54] = 39;
    bpp_data_pool[55] = 40;
    bpp_data_pool[56] = 41;
    bpp_data_pool[57] = 42;
    bpp_data_pool[58] = 43;
    bpp_data_pool[59] = 44;
    bpp_data_pool[60] = 45;
    bpp_data_pool[61] = 46;
    bpp_data_pool[62] = 47;
    bpp_data_pool[63] = 48;
    bpp_data_pool[64] = 49;
    bpp_data_pool[65] = 50;
    bpp_data_pool[66] = 51;
    bpp_data_pool[67] = 52;
    bpp_data_pool[68] = 53;
    bpp_data_pool[69] = 54;
    bpp_data_pool[70] = 55;
    bpp_data_pool[71] = 56;
    bpp_data_pool[72] = 57;
    bpp_data_pool[73] = 58;
    bpp_data_pool[74] = 59;
    bpp_data_pool[75] = 60;
    bpp_data_pool[76] = 61;
    bpp_data_pool[77] = 62;
    bpp_data_pool[78] = 63;
    bpp_data_pool[79] = 64;
    bpp_data_pool[80] = 1;
    bpp_data_pool[81] = 17;
    bpp_data_pool[82] = 33;
    bpp_data_pool[83] = 49;
    bpp_data_pool[84] = 5;
    bpp_data_pool[85] = 21;
    bpp_data_pool[86] = 37;
    bpp_data_pool[87] = 53;
    bpp_data_pool[88] = 9;
    bpp_data_pool[89] = 25;
    bpp_data_pool[90] = 41;
    bpp_data_pool[91] = 57;
    bpp_data_pool[92] = 13;
    bpp_data_pool[93] = 29;
    bpp_data_pool[94] = 45;
    bpp_data_pool[95] = 61;
    bpp_data_pool[96] = 2;
    bpp_data_pool[97] = 18;
    bpp_data_pool[98] = 34;
    bpp_data_pool[99] = 50;
    bpp_data_pool[100] = 6;
    bpp_data_pool[101] = 22;
    bpp_data_pool[102] = 38;
    bpp_data_pool[103] = 54;
    bpp_data_pool[104] = 10;
    bpp_data_pool[105] = 26;
    bpp_data_pool[106] = 42;
    bpp_data_pool[107] = 58;
    bpp_data_pool[108] = 14;
    bpp_data_pool[109] = 30;
    bpp_data_pool[110] = 46;
    bpp_data_pool[111] = 62;
    bpp_data_pool[112] = 3;
    bpp_data_pool[113] = 19;
    bpp_data_pool[114] = 35;
    bpp_data_pool[115] = 51;
    bpp_data_pool[116] = 7;
    bpp_data_pool[117] = 23;
    bpp_data_pool[118] = 39;
    bpp_data_pool[119] = 55;
    bpp_data_pool[120] = 11;
    bpp_data_pool[121] = 27;
    bpp_data_pool[122] = 43;
    bpp_data_pool[123] = 59;
    bpp_data_pool[124] = 15;
    bpp_data_pool[125] = 31;
    bpp_data_pool[126] = 47;
    bpp_data_pool[127] = 63;
    bpp_data_pool[128] = 4;
    bpp_data_pool[129] = 20;
    bpp_data_pool[130] = 36;
    bpp_data_pool[131] = 52;
    bpp_data_pool[132] = 8;
    bpp_data_pool[133] = 24;
    bpp_data_pool[134] = 40;
    bpp_data_pool[135] = 56;
    bpp_data_pool[136] = 12;
    bpp_data_pool[137] = 28;
    bpp_data_pool[138] = 44;
    bpp_data_pool[139] = 60;
    bpp_data_pool[140] = 16;
    bpp_data_pool[141] = 32;
    bpp_data_pool[142] = 48;
    bpp_data_pool[143] = 64;
    bpp_data_pool[144] = 1;
    bpp_data_pool[145] = 5;
    bpp_data_pool[146] = 9;
    bpp_data_pool[147] = 13;
    bpp_data_pool[148] = 17;
    bpp_data_pool[149] = 21;
    bpp_data_pool[150] = 25;
    bpp_data_pool[151] = 29;
    bpp_data_pool[152] = 33;
    bpp_data_pool[153] = 37;
    bpp_data_pool[154] = 41;
    bpp_data_pool[155] = 45;
    bpp_data_pool[156] = 49;
    bpp_data_pool[157] = 53;
    bpp_data_pool[158] = 57;
    bpp_data_pool[159] = 61;
    bpp_data_pool[160] = 2;
    bpp_data_pool[161] = 6;
    bpp_data_pool[162] = 10;
    bpp_data_pool[163] = 14;
    bpp_data_pool[164] = 18;
    bpp_data_pool[165] = 22;
    bpp_data_pool[166] = 26;
    bpp_data_pool[167] = 30;
    bpp_data_pool[168] = 34;
    bpp_data_pool[169] = 38;
    bpp_data_pool[170] = 42;
    bpp_data_pool[171] = 46;
    bpp_data_pool[172] = 50;
    bpp_data_pool[173] = 54;
    bpp_data_pool[174] = 58;
    bpp_data_pool[175] = 62;
    bpp_data_pool[176] = 3;
    bpp_data_pool[177] = 7;
    bpp_data_pool[178] = 11;
    bpp_data_pool[179] = 15;
    bpp_data_pool[180] = 19;
    bpp_data_pool[181] = 23;
    bpp_data_pool[182] = 27;
    bpp_data_pool[183] = 31;
    bpp_data_pool[184] = 35;
    bpp_data_pool[185] = 39;
    bpp_data_pool[186] = 43;
    bpp_data_pool[187] = 47;
    bpp_data_pool[188] = 51;
    bpp_data_pool[189] = 55;
    bpp_data_pool[190] = 59;
    bpp_data_pool[191] = 63;
    bpp_data_pool[192] = 4;
    bpp_data_pool[193] = 8;
    bpp_data_pool[194] = 12;
    bpp_data_pool[195] = 16;
    bpp_data_pool[196] = 20;
    bpp_data_pool[197] = 24;
    bpp_data_pool[198] = 28;
    bpp_data_pool[199] = 32;
    bpp_data_pool[200] = 36;
    bpp_data_pool[201] = 40;
    bpp_data_pool[202] = 44;
    bpp_data_pool[203] = 48;
    bpp_data_pool[204] = 52;
    bpp_data_pool[205] = 56;
    bpp_data_pool[206] = 60;
    bpp_data_pool[207] = 64;
    bpp_data_pool[208] = 1;
    bpp_data_pool[209] = 6;
    bpp_data_pool[210] = 11;
    bpp_data_pool[211] = 16;
    bpp_data_pool[212] = 17;
    bpp_data_pool[213] = 22;
    bpp_data_pool[214] = 27;
    bpp_data_pool[215] = 32;
    bpp_data_pool[216] = 33;
    bpp_data_pool[217] = 38;
    bpp_data_pool[218] = 43;
    bpp_data_pool[219] = 48;
    bpp_data_pool[220] = 49;
    bpp_data_pool[221] = 54;
    bpp_data_pool[222] = 59;
    bpp_data_pool[223] = 64;
    bpp_data_pool[224] = 13;
    bpp_data_pool[225] = 10;
    bpp_data_pool[226] = 7;
    bpp_data_pool[227] = 4;
    bpp_data_pool[228] = 29;
    bpp_data_pool[229] = 26;
    bpp_data_pool[230] = 23;
    bpp_data_pool[231] = 20;
    bpp_data_pool[232] = 45;
    bpp_data_pool[233] = 42;
    bpp_data_pool[234] = 39;
    bpp_data_pool[235] = 36;
    bpp_data_pool[236] = 61;
    bpp_data_pool[237] = 58;
    bpp_data_pool[238] = 55;
    bpp_data_pool[239] = 52;
    bpp_data_pool[240] = 1;
    bpp_data_pool[241] = 21;
    bpp_data_pool[242] = 41;
    bpp_data_pool[243] = 61;
    bpp_data_pool[244] = 2;
    bpp_data_pool[245] = 22;
    bpp_data_pool[246] = 42;
    bpp_data_pool[247] = 62;
    bpp_data_pool[248] = 3;
    bpp_data_pool[249] = 23;
    bpp_data_pool[250] = 43;
    bpp_data_pool[251] = 63;
    bpp_data_pool[252] = 4;
    bpp_data_pool[253] = 24;
    bpp_data_pool[254] = 44;
    bpp_data_pool[255] = 64;
    bpp_data_pool[256] = 49;
    bpp_data_pool[257] = 37;
    bpp_data_pool[258] = 25;
    bpp_data_pool[259] = 13;
    bpp_data_pool[260] = 50;
    bpp_data_pool[261] = 38;
    bpp_data_pool[262] = 26;
    bpp_data_pool[263] = 14;
    bpp_data_pool[264] = 51;
    bpp_data_pool[265] = 39;
    bpp_data_pool[266] = 27;
    bpp_data_pool[267] = 15;
    bpp_data_pool[268] = 52;
    bpp_data_pool[269] = 40;
    bpp_data_pool[270] = 28;
    bpp_data_pool[271] = 16;
    bpp_data_pool[272] = 1;
    bpp_data_pool[273] = 18;
    bpp_data_pool[274] = 35;
    bpp_data_pool[275] = 52;
    bpp_data_pool[276] = 5;
    bpp_data_pool[277] = 22;
    bpp_data_pool[278] = 39;
    bpp_data_pool[279] = 56;
    bpp_data_pool[280] = 9;
    bpp_data_pool[281] = 26;
    bpp_data_pool[282] = 43;
    bpp_data_pool[283] = 60;
    bpp_data_pool[284] = 13;
    bpp_data_pool[285] = 30;
    bpp_data_pool[286] = 47;
    bpp_data_pool[287] = 64;
    bpp_data_pool[288] = 49;
    bpp_data_pool[289] = 34;
    bpp_data_pool[290] = 19;
    bpp_data_pool[291] = 4;
    bpp_data_pool[292] = 53;
    bpp_data_pool[293] = 38;
    bpp_data_pool[294] = 23;
    bpp_data_pool[295] = 8;
    bpp_data_pool[296] = 57;
    bpp_data_pool[297] = 42;
    bpp_data_pool[298] = 27;
    bpp_data_pool[299] = 12;
    bpp_data_pool[300] = 61;
    bpp_data_pool[301] = 46;
    bpp_data_pool[302] = 31;
    bpp_data_pool[303] = 16;
    bpp_data_pool[304] = 1;
    bpp_data_pool[305] = 22;
    bpp_data_pool[306] = 43;
    bpp_data_pool[307] = 64;
    bpp_data_pool[308] = 16;
    bpp_data_pool[309] = 27;
    bpp_data_pool[310] = 38;
    bpp_data_pool[311] = 49;
    bpp_data_pool[312] = 4;
    bpp_data_pool[313] = 23;
    bpp_data_pool[314] = 42;
    bpp_data_pool[315] = 61;
    bpp_data_pool[316] = 13;
    bpp_data_pool[317] = 26;
    bpp_data_pool[318] = 39;
    bpp_data_pool[319] = 52;
    bpp_data_count = 320;

  L50: /* Line 50 */
    printf("%s", bpp_chr((int)(26)));
    printf("\n");
    /* REM  WIDTH 80 */
  L100: /* Line 100 */
    printf("%s", bpp_tab((int)(33)));
    printf("%s", "QUBIC");
    printf("\n");
        printf("\n");
  L110: /* Line 110 */
    printf("%s", bpp_tab((int)(15)));
    printf("%s", "CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY");
    printf("\n");
  L120: /* Line 120 */
        printf("\n");
        printf("\n");
        printf("\n");
  L210: /* Line 210 */
    printf("%s", "DO YOU WANT INSTRUCTIONS");
  L220: /* Line 220 */
    printf("? ");
    fflush(stdout);
    { char _buf[256]; int _len;
      fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
      while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
      strncpy(bpp_strvars[2], _buf, 255); }
  L230: /* Line 230 */
    if (((strcmp(bpp_left(bpp_strvars[2], (int)(1)), "N") == 0))) { goto L315;
 }
  L240: /* Line 240 */
    if (((strcmp(bpp_left(bpp_strvars[2], (int)(1)), "Y") == 0))) { goto L265;
 }
  L250: /* Line 250 */
    printf("%s", "INCORRECT ANSWER.  PLEASE TYPE 'YES' OR 'NO'");
  L260: /* Line 260 */
    goto L220;
  L265: /* Line 265 */
        printf("\n");
  L270: /* Line 270 */
    printf("%s", "THE GAME IS TIC-TAC-TOE IN A 4 X 4 X 4 CUBE.");
    printf("\n");
  L280: /* Line 280 */
    printf("%s", "EACH MOVE IS INDICATED BY A 3 DIGIT NUMBER, WITH EACH");
    printf("\n");
  L290: /* Line 290 */
    printf("%s", "DIGIT BETWEEN 1 AND 4 INCLUSIVE.  THE DIGITS INDICATE THE");
    printf("\n");
  L300: /* Line 300 */
    printf("%s", "LEVEL, ROW, AND COLUMN, RESPECTIVELY, OF THE OCCUPIED");
    printf("\n");
  L305: /* Line 305 */
    printf("%s", "PLACE.  ");
    printf("\n");
  L306: /* Line 306 */
        printf("\n");
  L307: /* Line 307 */
    printf("%s", "TO PRINT THE PLAYING BOARD, TYPE 0 (ZERO) AS YOUR MOVE.");
    printf("\n");
  L308: /* Line 308 */
    printf("%s", "THE PROGRAM WILL PRINT THE BOARD WITH YOUR MOVES INDI-");
    printf("\n");
  L309: /* Line 309 */
    printf("%s", "CATED WITH A (Y), THE MACHINE'S MOVES WITH AN (M), AND");
    printf("\n");
  L310: /* Line 310 */
    printf("%s", "UNUSED SQUARES WITH A ( ).  OUTPUT IS ON PAPER.");
    printf("\n");
  L311: /* Line 311 */
        printf("\n");
  L312: /* Line 312 */
    printf("%s", "TO STOP THE PROGRAM RUN, TYPE 1 AS YOUR MOVE.");
    printf("\n");
  L313: /* Line 313 */
        printf("\n");
        printf("\n");
  L315: /* Line 315 */
    bpp_dim_alloc("X", (int)(64), 0);
    bpp_dim_alloc("L", (int)(76), 0);
    bpp_dim_alloc("M", (int)(76), (int)(4));
    bpp_dim_alloc("Y", (int)(16), 0);
  L320: /* Line 320 */
    bpp_vars[8] = 1;
  bpp_for_0:;
  L330: /* Line 330 */
    *bpp_dim_ref("Y", (int)(bpp_vars[8]), 0) = bpp_read_num();
  L340: /* Line 340 */
    bpp_vars[8] += 1;
    if (bpp_vars[8] <= 16) goto bpp_for_0;
  L350: /* Line 350 */
    bpp_vars[8] = 1;
  bpp_for_1:;
  L360: /* Line 360 */
    bpp_vars[9] = 1;
  bpp_for_2:;
  L370: /* Line 370 */
    *bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9])) = bpp_read_num();
  L380: /* Line 380 */
    bpp_vars[9] += 1;
    if (bpp_vars[9] <= 4) goto bpp_for_2;
  L390: /* Line 390 */
    bpp_vars[8] += 1;
    if (bpp_vars[8] <= 76) goto bpp_for_1;
  L400: /* Line 400 */
    bpp_vars[8] = 1;
  bpp_for_3:;
  L410: /* Line 410 */
    *bpp_dim_ref("X", (int)(bpp_vars[8]), 0) = 0;
  L420: /* Line 420 */
    bpp_vars[8] += 1;
    if (bpp_vars[8] <= 64) goto bpp_for_3;
  L430: /* Line 430 */
    bpp_vars[25] = 1;
  L440: /* Line 440 */
    printf("%s", "DO YOU WANT TO MOVE FIRST");
  L450: /* Line 450 */
    printf("? ");
    fflush(stdout);
    { char _buf[256]; int _len;
      fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
      while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
      strncpy(bpp_strvars[18], _buf, 255); }
  L460: /* Line 460 */
    if (((strcmp(bpp_left(bpp_strvars[18], (int)(1)), "N") == 0))) { goto L630;
 }
  L470: /* Line 470 */
    if (((strcmp(bpp_left(bpp_strvars[18], (int)(1)), "Y") == 0))) { goto L500;
 }
  L480: /* Line 480 */
    printf("%s", "INCORRECT ANSWER.  PLEASE TYPE 'YES' OR 'NO'.");
  L490: /* Line 490 */
    goto L450;
  L500: /* Line 500 */
    printf("%s", " ");
    printf("\n");
  L510: /* Line 510 */
    printf("%s", "YOUR MOVE");
  L520: /* Line 520 */
      L521: /* Line 521 */
    if ((bpp_vars[9] == 1)) { goto L2770;
 }
  L522: /* Line 522 */
    if ((bpp_vars[9] != 0)) { goto L525;
 }
  L523: /* Line 523 */
    bpp_gosub_stack[bpp_gosub_sp++] = 0; goto L2550;
  bpp_ret_0:;
  L524: /* Line 524 */
    goto L500;
  L525: /* Line 525 */
    if ((bpp_vars[9] < 111)) { goto L2750;
 }
  L526: /* Line 526 */
    if ((bpp_vars[9] > 444)) { goto L2750;
 }
  L530: /* Line 530 */
    bpp_gosub_stack[bpp_gosub_sp++] = 1; goto L2500;
  bpp_ret_1:;
  L540: /* Line 540 */
    bpp_vars[10] = floor((bpp_vars[9] / 100));
  L550: /* Line 550 */
    bpp_vars[9] = (bpp_vars[9] - (bpp_vars[10] * 100));
  L560: /* Line 560 */
    bpp_vars[10] = floor((bpp_vars[9] / 10));
  L570: /* Line 570 */
    bpp_vars[10] = ((bpp_vars[9] - (bpp_vars[10] * 100)) - (bpp_vars[10] * 10));
  L580: /* Line 580 */
    bpp_vars[12] = ((((16 * bpp_vars[10]) + (4 * bpp_vars[10])) + bpp_vars[10]) - 20);
  L590: /* Line 590 */
    if ((*bpp_dim_ref("X", (int)(bpp_vars[12]), 0) == 0)) { goto L620;
 }
  L600: /* Line 600 */
    printf("%s", "THAT SQUARE IS USED, TRY AGAIN.");
    printf("\n");
  L610: /* Line 610 */
    goto L500;
  L620: /* Line 620 */
    *bpp_dim_ref("X", (int)(bpp_vars[12]), 0) = 1;
  L630: /* Line 630 */
    bpp_gosub_stack[bpp_gosub_sp++] = 2; goto L1640;
  bpp_ret_2:;
  L640: /* Line 640 */
    bpp_vars[9] = 1;
  L650: /* Line 650 */
    bpp_vars[8] = 1;
  L660: /* Line 660 */
    if ((bpp_vars[9] == 1)) { goto L720;
 }
  L670: /* Line 670 */
    if ((bpp_vars[9] == 2)) { goto L790;
 }
  L680: /* Line 680 */
    if ((bpp_vars[9] == 3)) { goto L930;
 }
  L690: /* Line 690 */
    bpp_vars[8] = (bpp_vars[8] + 1);
    if ((bpp_vars[8] <= 76)) { goto L660;
 }
  L700: /* Line 700 */
    bpp_vars[9] = (bpp_vars[9] + 1);
    if ((bpp_vars[9] <= 3)) { goto L650;
 }
  L710: /* Line 710 */
    goto L1300;
  L720: /* Line 720 */
    if ((*bpp_dim_ref("L", (int)(bpp_vars[8]), 0) != 4)) { goto L690;
 }
  L730: /* Line 730 */
    printf("%s", "YOU WIN AS FOLLOWS");
  L740: /* Line 740 */
    bpp_vars[9] = 1;
  bpp_for_4:;
  L750: /* Line 750 */
    bpp_vars[12] = *bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]));
  L760: /* Line 760 */
    bpp_gosub_stack[bpp_gosub_sp++] = 3; goto L1570;
  bpp_ret_3:;
  L770: /* Line 770 */
    bpp_vars[9] += 1;
    if (bpp_vars[9] <= 4) goto bpp_for_4;
  L780: /* Line 780 */
    goto L1490;
  L790: /* Line 790 */
    if ((*bpp_dim_ref("L", (int)(bpp_vars[8]), 0) != 15)) { goto L690;
 }
  L800: /* Line 800 */
    bpp_vars[9] = 1;
  bpp_for_5:;
  L810: /* Line 810 */
    bpp_vars[12] = *bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]));
  L820: /* Line 820 */
    if ((*bpp_dim_ref("X", (int)(bpp_vars[12]), 0) != 0)) { goto L860;
 }
  L830: /* Line 830 */
    *bpp_dim_ref("X", (int)(bpp_vars[12]), 0) = 5;
  L840: /* Line 840 */
    printf("%s", "MACHINE MOVES TO");
  L850: /* Line 850 */
    bpp_gosub_stack[bpp_gosub_sp++] = 4; goto L1570;
  bpp_ret_4:;
  L860: /* Line 860 */
    bpp_vars[9] += 1;
    if (bpp_vars[9] <= 4) goto bpp_for_5;
  L870: /* Line 870 */
    printf("%s", ", AND WINS AS FOLLOWS");
    printf("\n");
  L880: /* Line 880 */
    bpp_vars[9] = 1;
  bpp_for_6:;
  L890: /* Line 890 */
    bpp_vars[12] = *bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]));
  L900: /* Line 900 */
    bpp_gosub_stack[bpp_gosub_sp++] = 5; goto L1570;
  bpp_ret_5:;
  L910: /* Line 910 */
    bpp_vars[9] += 1;
    if (bpp_vars[9] <= 4) goto bpp_for_6;
  L920: /* Line 920 */
    goto L1490;
  L930: /* Line 930 */
    if ((*bpp_dim_ref("L", (int)(bpp_vars[8]), 0) != 3)) { goto L690;
 }
  L940: /* Line 940 */
    printf("%s", "NICE TRY. MACHINE MOVES TO");
  L950: /* Line 950 */
    bpp_vars[9] = 1;
  bpp_for_7:;
  L960: /* Line 960 */
    bpp_vars[12] = *bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]));
  L970: /* Line 970 */
    if ((*bpp_dim_ref("X", (int)(bpp_vars[12]), 0) != 0)) { goto L1010;
 }
  L980: /* Line 980 */
    *bpp_dim_ref("X", (int)(bpp_vars[12]), 0) = 5;
  L990: /* Line 990 */
    bpp_gosub_stack[bpp_gosub_sp++] = 6; goto L1570;
  bpp_ret_6:;
  L1000: /* Line 1000 */
    goto L500;
  L1010: /* Line 1010 */
    bpp_vars[9] += 1;
    if (bpp_vars[9] <= 4) goto bpp_for_7;
  L1020: /* Line 1020 */
    goto L1300;
  L1030: /* Line 1030 */
    bpp_vars[8] = 1;
  L1040: /* Line 1040 */
    *bpp_dim_ref("L", (int)(bpp_vars[8]), 0) = (((*bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(1))), 0) + *bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(2))), 0)) + *bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(3))), 0)) + *bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(4))), 0));
  L1050: /* Line 1050 */
    bpp_vars[11] = *bpp_dim_ref("L", (int)(bpp_vars[8]), 0);
  L1060: /* Line 1060 */
    if ((bpp_vars[11] < 2)) { goto L1130;
 }
  L1070: /* Line 1070 */
    if ((bpp_vars[11] >= 3)) { goto L1130;
 }
  L1080: /* Line 1080 */
    if ((bpp_vars[11] > 2)) { goto L2230;
 }
  L1090: /* Line 1090 */
    bpp_vars[9] = 1;
  bpp_for_8:;
  L1100: /* Line 1100 */
    if ((*bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]))), 0) != 0)) { goto L1120;
 }
  L1110: /* Line 1110 */
    *bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]))), 0) = (1 / 8);
  L1120: /* Line 1120 */
    bpp_vars[9] += 1;
    if (bpp_vars[9] <= 4) goto bpp_for_8;
  L1130: /* Line 1130 */
    bpp_vars[8] = (bpp_vars[8] + 1);
    if ((bpp_vars[8] <= 76)) { goto L1040;
 }
  L1140: /* Line 1140 */
    bpp_gosub_stack[bpp_gosub_sp++] = 7; goto L1640;
  bpp_ret_7:;
  L1150: /* Line 1150 */
    bpp_vars[8] = 1;
  L1160: /* Line 1160 */
    if ((*bpp_dim_ref("L", (int)(bpp_vars[8]), 0) == (1 / 2))) { goto L2360;
 }
  L1170: /* Line 1170 */
    if ((*bpp_dim_ref("L", (int)(bpp_vars[8]), 0) == (1 + (3 / 8)))) { goto L2360;
 }
  L1180: /* Line 1180 */
    bpp_vars[8] = (bpp_vars[8] + 1);
    if ((bpp_vars[8] <= 76)) { goto L1160;
 }
  L1190: /* Line 1190 */
    goto L1830;
  L1200: /* Line 1200 */
    bpp_vars[25] = 1;
  L1210: /* Line 1210 */
    if ((*bpp_dim_ref("X", (int)(*bpp_dim_ref("Y", (int)(bpp_vars[25]), 0)), 0) == 0)) { goto L1250;
 }
  L1220: /* Line 1220 */
    bpp_vars[25] = (bpp_vars[25] + 1);
  L1230: /* Line 1230 */
    if ((bpp_vars[25] != 17)) { goto L1210;
 }
  L1240: /* Line 1240 */
    goto L1720;
  L1250: /* Line 1250 */
    bpp_vars[12] = *bpp_dim_ref("Y", (int)(bpp_vars[25]), 0);
  L1260: /* Line 1260 */
    *bpp_dim_ref("X", (int)(bpp_vars[12]), 0) = 5;
  L1270: /* Line 1270 */
    printf("%s", "MACHINE MOVES TO");
  L1280: /* Line 1280 */
    bpp_gosub_stack[bpp_gosub_sp++] = 8; goto L1570;
  bpp_ret_8:;
  L1290: /* Line 1290 */
    goto L500;
  L1300: /* Line 1300 */
    bpp_vars[23] = bpp_vars[23];
  L1310: /* Line 1310 */
    bpp_vars[8] = 1;
  L1320: /* Line 1320 */
    *bpp_dim_ref("L", (int)(bpp_vars[8]), 0) = (((*bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(1))), 0) + *bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(2))), 0)) + *bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(3))), 0)) + *bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(4))), 0));
  L1330: /* Line 1330 */
    bpp_vars[11] = *bpp_dim_ref("L", (int)(bpp_vars[8]), 0);
  L1340: /* Line 1340 */
    if ((bpp_vars[11] < 10)) { goto L1410;
 }
  L1350: /* Line 1350 */
    if ((bpp_vars[11] >= 11)) { goto L1410;
 }
  L1360: /* Line 1360 */
    if ((bpp_vars[11] > 10)) { goto L2230;
 }
  L1370: /* Line 1370 */
    bpp_vars[9] = 1;
  bpp_for_9:;
  L1380: /* Line 1380 */
    if ((*bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]))), 0) != 0)) { goto L1400;
 }
  L1390: /* Line 1390 */
    *bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]))), 0) = (1 / 8);
  L1400: /* Line 1400 */
    bpp_vars[9] += 1;
    if (bpp_vars[9] <= 4) goto bpp_for_9;
  L1410: /* Line 1410 */
    bpp_vars[8] = (bpp_vars[8] + 1);
    if ((bpp_vars[8] <= 76)) { goto L1320;
 }
  L1420: /* Line 1420 */
    bpp_gosub_stack[bpp_gosub_sp++] = 9; goto L1640;
  bpp_ret_9:;
  L1430: /* Line 1430 */
    bpp_vars[8] = 1;
  L1440: /* Line 1440 */
    if ((*bpp_dim_ref("L", (int)(bpp_vars[8]), 0) == 0.5)) { goto L2360;
 }
  L1450: /* Line 1450 */
    if ((*bpp_dim_ref("L", (int)(bpp_vars[8]), 0) == (5 + (3 / 8)))) { goto L2360;
 }
  L1460: /* Line 1460 */
    bpp_vars[8] = (bpp_vars[8] + 1);
    if ((bpp_vars[8] <= 76)) { goto L1440;
 }
  L1470: /* Line 1470 */
    bpp_gosub_stack[bpp_gosub_sp++] = 10; goto L2500;
  bpp_ret_10:;
  L1480: /* Line 1480 */
    goto L1030;
  L1490: /* Line 1490 */
    printf("%s", " ");
    printf("\n");
  L1500: /* Line 1500 */
    printf("%s", "DO YOU WANT TO TRY ANOTHER GAME");
  L1510: /* Line 1510 */
    printf("? ");
    fflush(stdout);
    { char _buf[256]; int _len;
      fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
      while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
      strncpy(bpp_strvars[23], _buf, 255); }
  L1520: /* Line 1520 */
    if (((strcmp(bpp_left(bpp_strvars[23], (int)(1)), "Y") == 0))) { goto L400;
 }
  L1530: /* Line 1530 */
    if (((strcmp(bpp_left(bpp_strvars[23], (int)(1)), "N") == 0))) { goto L1560;
 }
  L1540: /* Line 1540 */
    printf("%s", "INCORRECT ANSWER. PLEASE TYPE 'YES' OR 'NO'");
  L1550: /* Line 1550 */
    goto L1510;
  L1560: /* Line 1560 */
    goto bpp_end;
  L1570: /* Line 1570 */
    bpp_vars[10] = (floor(((bpp_vars[12] - 1) / 16)) + 1);
  L1580: /* Line 1580 */
    bpp_vars[9] = (bpp_vars[12] - (16 * (bpp_vars[10] - 1)));
  L1590: /* Line 1590 */
    bpp_vars[10] = (floor(((bpp_vars[9] - 1) / 4)) + 1);
  L1600: /* Line 1600 */
    bpp_vars[10] = ((bpp_vars[12] - ((bpp_vars[10] - 1) * 16)) - ((bpp_vars[10] - 1) * 4));
  L1610: /* Line 1610 */
    bpp_vars[12] = (((bpp_vars[10] * 100) + (bpp_vars[10] * 10)) + bpp_vars[10]);
  L1620: /* Line 1620 */
    { double _v = bpp_vars[12]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
  L1630: /* Line 1630 */
    { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
      switch(_ra) {
        case 0: goto bpp_ret_0;
        case 1: goto bpp_ret_1;
        case 2: goto bpp_ret_2;
        case 3: goto bpp_ret_3;
        case 4: goto bpp_ret_4;
        case 5: goto bpp_ret_5;
        case 6: goto bpp_ret_6;
        case 7: goto bpp_ret_7;
        case 8: goto bpp_ret_8;
        case 9: goto bpp_ret_9;
        case 10: goto bpp_ret_10;
        case 11: goto bpp_ret_11;
        case 12: goto bpp_ret_12;
        case 13: goto bpp_ret_13;
        case 14: goto bpp_ret_14;
        default: goto bpp_end;
      } }
  L1640: /* Line 1640 */
    bpp_vars[18] = 1;
  bpp_for_10:;
  L1650: /* Line 1650 */
    bpp_vars[9] = *bpp_dim_ref("M", (int)(bpp_vars[18]), (int)(1));
  L1660: /* Line 1660 */
    bpp_vars[9] = *bpp_dim_ref("M", (int)(bpp_vars[18]), (int)(2));
  L1670: /* Line 1670 */
    bpp_vars[9] = *bpp_dim_ref("M", (int)(bpp_vars[18]), (int)(3));
  L1680: /* Line 1680 */
    bpp_vars[9] = *bpp_dim_ref("M", (int)(bpp_vars[18]), (int)(4));
  L1690: /* Line 1690 */
    *bpp_dim_ref("L", (int)(bpp_vars[18]), 0) = (((*bpp_dim_ref("X", (int)(bpp_vars[9]), 0) + *bpp_dim_ref("X", (int)(bpp_vars[9]), 0)) + *bpp_dim_ref("X", (int)(bpp_vars[9]), 0)) + *bpp_dim_ref("X", (int)(bpp_vars[9]), 0));
  L1700: /* Line 1700 */
    bpp_vars[18] += 1;
    if (bpp_vars[18] <= 76) goto bpp_for_10;
  L1710: /* Line 1710 */
    { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
      switch(_ra) {
        case 0: goto bpp_ret_0;
        case 1: goto bpp_ret_1;
        case 2: goto bpp_ret_2;
        case 3: goto bpp_ret_3;
        case 4: goto bpp_ret_4;
        case 5: goto bpp_ret_5;
        case 6: goto bpp_ret_6;
        case 7: goto bpp_ret_7;
        case 8: goto bpp_ret_8;
        case 9: goto bpp_ret_9;
        case 10: goto bpp_ret_10;
        case 11: goto bpp_ret_11;
        case 12: goto bpp_ret_12;
        case 13: goto bpp_ret_13;
        case 14: goto bpp_ret_14;
        default: goto bpp_end;
      } }
  L1720: /* Line 1720 */
    bpp_vars[8] = 1;
  bpp_for_11:;
  L1730: /* Line 1730 */
    if ((*bpp_dim_ref("X", (int)(bpp_vars[8]), 0) != 0)) { goto L1800;
 }
  L1740: /* Line 1740 */
    *bpp_dim_ref("X", (int)(bpp_vars[8]), 0) = 5;
  L1750: /* Line 1750 */
    bpp_vars[12] = bpp_vars[8];
  L1760: /* Line 1760 */
    printf("%s", "MACHINE LIKES");
  L1770: /* Line 1770 */
    bpp_gosub_stack[bpp_gosub_sp++] = 11; goto L1570;
  bpp_ret_11:;
  L1780: /* Line 1780 */
    printf("%s", " ");
    printf("\n");
  L1790: /* Line 1790 */
    goto L500;
  L1800: /* Line 1800 */
    bpp_vars[8] += 1;
    if (bpp_vars[8] <= 64) goto bpp_for_11;
  L1810: /* Line 1810 */
    printf("%s", "THE GAME IS A DRAW.");
    printf("\n");
  L1820: /* Line 1820 */
    goto L1490;
  L1830: /* Line 1830 */
    bpp_vars[10] = 1;
  bpp_for_12:;
  L1840: /* Line 1840 */
    bpp_vars[15] = 0;
  L1850: /* Line 1850 */
    bpp_vars[8] = ((4 * bpp_vars[10]) - 3);
  bpp_for_13:;
  L1860: /* Line 1860 */
    bpp_vars[9] = 1;
  bpp_for_14:;
  L1870: /* Line 1870 */
    bpp_vars[15] = (bpp_vars[15] + *bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]))), 0));
  L1880: /* Line 1880 */
    bpp_vars[9] += 1;
    if (bpp_vars[9] <= 4) goto bpp_for_14;
  L1890: /* Line 1890 */
    bpp_vars[8] += 1;
    if (bpp_vars[8] <= (4 * bpp_vars[10])) goto bpp_for_13;
  L1900: /* Line 1900 */
    if ((bpp_vars[15] < 4)) { goto L1940;
 }
  L1910: /* Line 1910 */
    if ((bpp_vars[15] < 5)) { goto L1970;
 }
  L1920: /* Line 1920 */
    if ((bpp_vars[15] < 9)) { goto L1940;
 }
  L1930: /* Line 1930 */
    if ((bpp_vars[15] < 10)) { goto L1970;
 }
  L1940: /* Line 1940 */
    bpp_vars[10] += 1;
    if (bpp_vars[10] <= 18) goto bpp_for_12;
  L1950: /* Line 1950 */
    bpp_gosub_stack[bpp_gosub_sp++] = 12; goto L2500;
  bpp_ret_12:;
  L1960: /* Line 1960 */
    goto L1200;
  L1970: /* Line 1970 */
    bpp_vars[18] = (1 / 8);
  L1980: /* Line 1980 */
    bpp_vars[8] = ((4 * bpp_vars[10]) - 3);
  bpp_for_15:;
  L1990: /* Line 1990 */
    goto L2370;
  L2000: /* Line 2000 */
    bpp_vars[8] += 1;
    if (bpp_vars[8] <= (4 * bpp_vars[10])) goto bpp_for_15;
  L2010: /* Line 2010 */
    bpp_vars[18] = 0;
  L2020: /* Line 2020 */
    goto L1980;
  L2030: /* Line 2030 */
    /* DATA - see initialization */
  L2040: /* Line 2040 */
    /* DATA - see initialization */
  L2050: /* Line 2050 */
    /* DATA - see initialization */
  L2060: /* Line 2060 */
    /* DATA - see initialization */
  L2070: /* Line 2070 */
    /* DATA - see initialization */
  L2080: /* Line 2080 */
    /* DATA - see initialization */
  L2090: /* Line 2090 */
    /* DATA - see initialization */
  L2100: /* Line 2100 */
    /* DATA - see initialization */
  L2110: /* Line 2110 */
    /* DATA - see initialization */
  L2120: /* Line 2120 */
    /* DATA - see initialization */
  L2130: /* Line 2130 */
    /* DATA - see initialization */
  L2140: /* Line 2140 */
    /* DATA - see initialization */
  L2150: /* Line 2150 */
    /* DATA - see initialization */
  L2160: /* Line 2160 */
    /* DATA - see initialization */
  L2170: /* Line 2170 */
    /* DATA - see initialization */
  L2180: /* Line 2180 */
    /* DATA - see initialization */
  L2190: /* Line 2190 */
    /* DATA - see initialization */
  L2200: /* Line 2200 */
    /* DATA - see initialization */
  L2210: /* Line 2210 */
    /* DATA - see initialization */
  L2220: /* Line 2220 */
    /* DATA - see initialization */
  L2230: /* Line 2230 */
    bpp_vars[9] = 1;
  bpp_for_16:;
  L2240: /* Line 2240 */
    if ((*bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]))), 0) != (1 / 8))) { goto L2330;
 }
  L2250: /* Line 2250 */
    *bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]))), 0) = 5;
  L2260: /* Line 2260 */
    if ((*bpp_dim_ref("L", (int)(bpp_vars[8]), 0) < 5)) { goto L2290;
 }
  L2270: /* Line 2270 */
    printf("%s", "LET'S SEE YOU GET OUT OF THIS:  MACHINE MOVES TO");
  L2280: /* Line 2280 */
    goto L2300;
  L2290: /* Line 2290 */
    printf("%s", "YOU FOX.  JUST IN THE NICK OF TIME, MACHINE MOVES TO");
  L2300: /* Line 2300 */
    bpp_vars[12] = *bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]));
  L2310: /* Line 2310 */
    bpp_gosub_stack[bpp_gosub_sp++] = 13; goto L1570;
  bpp_ret_13:;
  L2320: /* Line 2320 */
    goto L500;
  L2330: /* Line 2330 */
    bpp_vars[9] += 1;
    if (bpp_vars[9] <= 4) goto bpp_for_16;
  L2340: /* Line 2340 */
    printf("%s", "MACHINE CONCEDES THIS GAME.");
    printf("\n");
  L2350: /* Line 2350 */
    goto L1490;
  L2360: /* Line 2360 */
    bpp_vars[18] = (1 / 8);
  L2370: /* Line 2370 */
    if (((bpp_vars[8] - (floor((bpp_vars[8] / 4)) * 4)) > 1)) { goto L2400;
 }
  L2380: /* Line 2380 */
    bpp_vars[0] = 1;
  L2390: /* Line 2390 */
    goto L2410;
  L2400: /* Line 2400 */
    bpp_vars[0] = 2;
  L2410: /* Line 2410 */
    bpp_vars[9] = bpp_vars[0];
  bpp_for_17:;
  L2420: /* Line 2420 */
    if ((*bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]))), 0) == bpp_vars[18])) { goto L2450;
 }
  L2430: /* Line 2430 */
    bpp_vars[9] += (5 - (2 * bpp_vars[0]));
    if (((5 - (2 * bpp_vars[0])) > 0 && bpp_vars[9] <= (5 - bpp_vars[0])) || ((5 - (2 * bpp_vars[0])) < 0 && bpp_vars[9] >= (5 - bpp_vars[0]))) goto bpp_for_17;
  L2440: /* Line 2440 */
    goto L2000;
  L2450: /* Line 2450 */
    *bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]))), 0) = 5;
  L2460: /* Line 2460 */
    bpp_vars[12] = *bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]));
  L2470: /* Line 2470 */
    printf("%s", "MACHINE TAKES");
  L2480: /* Line 2480 */
    bpp_gosub_stack[bpp_gosub_sp++] = 14; goto L1570;
  bpp_ret_14:;
  L2490: /* Line 2490 */
    goto L500;
  L2500: /* Line 2500 */
    bpp_vars[8] = 1;
  bpp_for_18:;
  L2510: /* Line 2510 */
    if ((*bpp_dim_ref("X", (int)(bpp_vars[8]), 0) != (1 / 8))) { goto L2530;
 }
  L2520: /* Line 2520 */
    *bpp_dim_ref("X", (int)(bpp_vars[8]), 0) = 0;
  L2530: /* Line 2530 */
    bpp_vars[8] += 1;
    if (bpp_vars[8] <= 64) goto bpp_for_18;
  L2540: /* Line 2540 */
    { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
      switch(_ra) {
        case 0: goto bpp_ret_0;
        case 1: goto bpp_ret_1;
        case 2: goto bpp_ret_2;
        case 3: goto bpp_ret_3;
        case 4: goto bpp_ret_4;
        case 5: goto bpp_ret_5;
        case 6: goto bpp_ret_6;
        case 7: goto bpp_ret_7;
        case 8: goto bpp_ret_8;
        case 9: goto bpp_ret_9;
        case 10: goto bpp_ret_10;
        case 11: goto bpp_ret_11;
        case 12: goto bpp_ret_12;
        case 13: goto bpp_ret_13;
        case 14: goto bpp_ret_14;
        default: goto bpp_end;
      } }
  L2550: /* Line 2550 */
    bpp_vars[23] = 1;
  bpp_for_19:;
        printf("\n");
    /* NEXT  : no matching FOR */
    bpp_vars[8] = 1;
  bpp_for_20:;
  L2560: /* Line 2560 */
    bpp_vars[9] = 1;
  bpp_for_21:;
  L2562: /* Line 2562 */
    bpp_vars[8] = 1;
  bpp_for_22:;
  L2564: /* Line 2564 */
    printf("%s", "   ");
  L2566: /* Line 2566 */
    bpp_vars[8] += 1;
    if (bpp_vars[8] <= bpp_vars[9]) goto bpp_for_22;
  L2570: /* Line 2570 */
    bpp_vars[10] = 1;
  bpp_for_23:;
  L2600: /* Line 2600 */
    bpp_vars[16] = ((((16 * bpp_vars[8]) + (4 * bpp_vars[9])) + bpp_vars[10]) - 20);
  L2610: /* Line 2610 */
    if ((*bpp_dim_ref("X", (int)(bpp_vars[16]), 0) != bpp_vars[14])) { goto L2630;
 }
  L2620: /* Line 2620 */
    printf("%s", "( )      ");
  L2630: /* Line 2630 */
    if ((*bpp_dim_ref("X", (int)(bpp_vars[16]), 0) != 5)) { goto L2650;
 }
  L2640: /* Line 2640 */
    printf("%s", "(M)      ");
  L2650: /* Line 2650 */
    if ((*bpp_dim_ref("X", (int)(bpp_vars[16]), 0) != 1)) { goto L2660;
 }
  L2655: /* Line 2655 */
    printf("%s", "(Y)      ");
  L2660: /* Line 2660 */
    if ((*bpp_dim_ref("X", (int)(bpp_vars[16]), 0) != (1 / 8))) { goto L2670;
 }
  L2665: /* Line 2665 */
    printf("%s", "( )      ");
  L2670: /* Line 2670 */
    bpp_vars[10] += 1;
    if (bpp_vars[10] <= 4) goto bpp_for_23;
  L2680: /* Line 2680 */
        printf("\n");
  L2690: /* Line 2690 */
        printf("\n");
  L2700: /* Line 2700 */
    bpp_vars[9] += 1;
    if (bpp_vars[9] <= 4) goto bpp_for_21;
  L2710: /* Line 2710 */
        printf("\n");
  L2720: /* Line 2720 */
        printf("\n");
  L2730: /* Line 2730 */
    bpp_vars[8] += 1;
    if (bpp_vars[8] <= bpp_vars[9]) goto bpp_for_22;
  L2735: /* Line 2735 */
    /* REM  PRINT CHR$(12) */
  L2740: /* Line 2740 */
    { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
      switch(_ra) {
        case 0: goto bpp_ret_0;
        case 1: goto bpp_ret_1;
        case 2: goto bpp_ret_2;
        case 3: goto bpp_ret_3;
        case 4: goto bpp_ret_4;
        case 5: goto bpp_ret_5;
        case 6: goto bpp_ret_6;
        case 7: goto bpp_ret_7;
        case 8: goto bpp_ret_8;
        case 9: goto bpp_ret_9;
        case 10: goto bpp_ret_10;
        case 11: goto bpp_ret_11;
        case 12: goto bpp_ret_12;
        case 13: goto bpp_ret_13;
        case 14: goto bpp_ret_14;
        default: goto bpp_end;
      } }
  L2750: /* Line 2750 */
    printf("%s", "INCORRECT MOVE, RETYPE IT--");
  L2760: /* Line 2760 */
    goto L520;
  L2770: /* Line 2770 */
    goto bpp_end;
  bpp_end:
    return 0;
}
