/* Generated by BASIC++ Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* === Runtime Variables === */
static double bpp_vars[26];           /* A-Z */
static char bpp_strvars[26][256];     /* A$-Z$ */
static double bpp_at_array[4096];     /* @() legacy array */
static int bpp_print_width = 14;

/* === GOSUB Stack === */
#define BPP_MAX_STACK 256
static int bpp_gosub_stack[BPP_MAX_STACK];
static int bpp_gosub_sp = 0;

/* === DIM Arrays === */
#define BPP_MAX_DIM 64
#define BPP_MAX_ELEM 8192
static double bpp_dim_pool[BPP_MAX_ELEM];
static int bpp_dim_used = 0;
typedef struct { char name[32]; int d1,d2,off; } BppDim;
static BppDim bpp_dims[BPP_MAX_DIM];
static int bpp_dim_count = 0;

static void bpp_dim_alloc(const char *nm, int d1, int d2) {
    int sz = (d1+1) * (d2>0 ? d2+1 : 1);
    BppDim *d = &bpp_dims[bpp_dim_count++];
    strncpy(d->name, nm, 31); d->name[31]='\0';
    d->d1=d1; d->d2=d2; d->off=bpp_dim_used;
    memset(&bpp_dim_pool[bpp_dim_used], 0, sizeof(double)*(size_t)sz);
    bpp_dim_used += sz;
}

static double *bpp_dim_ref(const char *nm, int i1, int i2) {
    int k;
    for (k=0; k<bpp_dim_count; k++) {
        if (strcmp(bpp_dims[k].name, nm)==0) {
            int idx = (bpp_dims[k].d2>0)
                ? i1*(bpp_dims[k].d2+1)+i2 : i1;
            return &bpp_dim_pool[bpp_dims[k].off + idx];
        }
    }
    fprintf(stderr, "Array not found: %s\n", nm);
    exit(1);
    return NULL;
}

/* === String DIM arrays === */
#define BPP_MAX_STRDIM 26
#define BPP_MAX_STRDIM_SIZE 256
static struct { char nm[16]; int d1; int d2;
    char data[BPP_MAX_STRDIM_SIZE][256]; } bpp_strdims[BPP_MAX_STRDIM];
static int bpp_strdim_count = 0;

static char *bpp_strdim_ref(const char *nm, int i1, int i2) {
    int k;
    (void)i2;
    for (k = 0; k < bpp_strdim_count; k++) {
        if (strcmp(bpp_strdims[k].nm, nm) == 0) {
            if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
            return bpp_strdims[k].data[i1];
        }
    }
    /* Auto-create */
    if (bpp_strdim_count < BPP_MAX_STRDIM) {
        int j;
        strncpy(bpp_strdims[bpp_strdim_count].nm, nm, 15);
        bpp_strdims[bpp_strdim_count].nm[15] = '\0';
        for (j = 0; j < BPP_MAX_STRDIM_SIZE; j++)
            bpp_strdims[bpp_strdim_count].data[j][0] = '\0';
        bpp_strdim_count++;
        if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
        return bpp_strdims[bpp_strdim_count-1].data[i1];
    }
    fprintf(stderr, "String array not found: %s\n", nm);
    exit(1);
    return NULL;
}

/* === DATA/READ support === */
#define BPP_MAX_DATA 4096
static double bpp_data_pool[BPP_MAX_DATA];
static int bpp_data_count = 0;
static int bpp_data_ptr = 0;

static double bpp_read_num(void) {
    if (bpp_data_ptr >= bpp_data_count) {
        fprintf(stderr, "OUT OF DATA\n"); exit(1);
    }
    return bpp_data_pool[bpp_data_ptr++];
}

/* === String helpers === */
static char bpp_strtmp[8][256];
static int bpp_strtmp_idx = 0;

static char *bpp_tmp(void) {
    char *p = bpp_strtmp[bpp_strtmp_idx];
    bpp_strtmp_idx = (bpp_strtmp_idx+1) & 7;
    return p;
}

static const char *bpp_concat(const char *a, const char *b) {
    char *t = bpp_tmp();
    t[0]='\0';
    strncat(t, a, 254);
    strncat(t, b, 254-(int)strlen(t));
    return t;
}

static const char *bpp_left(const char *s, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if (n>len) n=len; if(n<0) n=0;
    memcpy(t, s, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_right(const char *s, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if (n>len) n=len; if(n<0) n=0;
    memcpy(t, s+len-n, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_mid(const char *s, int st, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if(st<0) st=0; if(st>len) st=len;
    if(n<0) n=0; if(st+n>len) n=len-st;
    memcpy(t, s+st, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_chr(int n) {
    char *t = bpp_tmp();
    t[0]=(char)n; t[1]='\0';
    return t;
}

static const char *bpp_str(double n) {
    char *t = bpp_tmp();
    sprintf(t, "%g", n);
    return t;
}

/* === TAB helper === */
static const char *bpp_tab(int col) {
    static char buf[256];
    int i;
    if (col < 0) col = 0;
    if (col > 255) col = 255;
    for (i = 0; i < col; i++) buf[i] = ' ';
    buf[col] = '\0';
    return buf;
}

/* === DEF FN support === */
#define BPP_MAX_FN 26
typedef double (*BppFnPtr)(double);
static double bpp_fn_param;

int main(void) {

  L10: /* Line 10 */
    printf("%s", bpp_tab((int)(34)));
    printf("%s", "STARS");
    printf("\n");
  L20: /* Line 20 */
    printf("%s", bpp_tab((int)(15)));
    printf("%s", "CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY");
    printf("\n");
  L30: /* Line 30 */
        printf("\n");
        printf("\n");
        printf("\n");
  L100: /* Line 100 */
    /* REM  *** STARS - PEOPLE'S COMPUTER CENTER, MENLO PARK, CA */
  L140: /* Line 140 */
    /* REM  *** A IS LIMIT ON NUMBER, M IS NUMBER OF GUESSES */
  L150: /* Line 150 */
    bpp_vars[0] = 100;
    bpp_vars[12] = 7;
  L170: /* Line 170 */
      L190: /* Line 190 */
    if (((strcmp(bpp_left(bpp_strvars[0], (int)(1)), "N") == 0))) { goto L280;
 }
  L200: /* Line 200 */
    /* REM  *** INSTRUCTIONS ON HOW TO PLAY */
  L210: /* Line 210 */
    printf("%s", "I AM THINKING OF A WHOLE NUMBER FROM 1 TO");
    { double _v = bpp_vars[0]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("\n");
  L220: /* Line 220 */
    printf("%s", "TRY TO GUESS MY NUMBER.  AFTER YOU GUESS, I");
    printf("\n");
  L230: /* Line 230 */
    printf("%s", "WILL TYPE ONE OR MORE STARS (*).  THE MORE");
    printf("\n");
  L240: /* Line 240 */
    printf("%s", "STARS I TYPE, THE CLOSER YOU ARE TO MY NUMBER.");
    printf("\n");
  L250: /* Line 250 */
    printf("%s", "ONE STAR (*) MEANS FAR AWAY, SEVEN STARS (*******)");
    printf("\n");
  L260: /* Line 260 */
    printf("%s", "MEANS REALLY CLOSE!  YOU GET");
    { double _v = bpp_vars[12]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("%s", "GUESSES.");
    printf("\n");
  L270: /* Line 270 */
    /* REM  *** COMPUTER THINKS OF A NUMBER */
  L280: /* Line 280 */
        printf("\n");
  L290: /* Line 290 */
        printf("\n");
  L300: /* Line 300 */
    bpp_vars[23] = floor(((bpp_vars[0] * ((double)(rand() % (int)(1)))) + 1));
  L310: /* Line 310 */
    printf("%s", "OK, I AM THINKING OF A NUMBER, START GUESSING.");
    printf("\n");
  L320: /* Line 320 */
    /* REM  *** GUESSING BEGINS, HUMAN GETS M GUESSES */
  L330: /* Line 330 */
    bpp_vars[10] = 1;
  bpp_for_0:;
  L340: /* Line 340 */
        printf("\n");
  L350: /* Line 350 */
    printf("%s", "YOUR GUESS");
  L360: /* Line 360 */
    printf("? ");
    fflush(stdout);
    { char _buf[256]; double _v;
      fgets(_buf, 256, stdin); _v = atof(_buf);
      bpp_vars[6] = _v; }
  L370: /* Line 370 */
    if ((bpp_vars[6] == bpp_vars[23])) { goto L600;
 }
  L380: /* Line 380 */
    bpp_vars[3] = fabs((bpp_vars[6] - bpp_vars[23]));
  L390: /* Line 390 */
    if ((bpp_vars[3] >= 64)) { goto L510;
 }
  L400: /* Line 400 */
    if ((bpp_vars[3] >= 32)) { goto L500;
 }
  L410: /* Line 410 */
    if ((bpp_vars[3] >= 16)) { goto L490;
 }
  L420: /* Line 420 */
    if ((bpp_vars[3] >= 8)) { goto L480;
 }
  L430: /* Line 430 */
    if ((bpp_vars[3] >= 4)) { goto L470;
 }
  L440: /* Line 440 */
    if ((bpp_vars[3] >= 2)) { goto L460;
 }
  L450: /* Line 450 */
    printf("%s", "*");
  L460: /* Line 460 */
    printf("%s", "*");
  L470: /* Line 470 */
    printf("%s", "*");
  L480: /* Line 480 */
    printf("%s", "*");
  L490: /* Line 490 */
    printf("%s", "*");
  L500: /* Line 500 */
    printf("%s", "*");
  L510: /* Line 510 */
    printf("%s", "*");
  L520: /* Line 520 */
        printf("\n");
  L530: /* Line 530 */
    bpp_vars[10] += 1;
    if (bpp_vars[10] <= bpp_vars[12]) goto bpp_for_0;
  L540: /* Line 540 */
    /* REM  *** DID NOT GUESS IN M GUESSES */
  L550: /* Line 550 */
        printf("\n");
  L560: /* Line 560 */
    printf("%s", "SORRY, THAT'S");
    { double _v = bpp_vars[12]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("%s", "GUESSES. THE NUMBER WAS");
    { double _v = bpp_vars[23]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("\n");
  L580: /* Line 580 */
    goto L650;
  L590: /* Line 590 */
    /* REM  *** WE HAVE A WINNER */
  L600: /* Line 600 */
        printf("\n");
    bpp_vars[13] = 1;
  bpp_for_1:;
  L610: /* Line 610 */
    printf("%s", "*");
  L620: /* Line 620 */
    bpp_vars[13] += 1;
    if (bpp_vars[13] <= 79) goto bpp_for_1;
  L630: /* Line 630 */
        printf("\n");
        printf("\n");
  L640: /* Line 640 */
    printf("%s", "YOU GOT IT IN");
    { double _v = bpp_vars[10]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("%s", "GUESSES!!!  LET'S PLAY AGAIN...");
    printf("\n");
  L650: /* Line 650 */
    goto L280;
  L660: /* Line 660 */
    goto bpp_end;
  bpp_end:
    return 0;
}
