/* Copyleft (c) 2026, BASIC++ Community. All wrongs reserved.
 *
 * This file is part of BASIC++ - a modular, portable BASIC language framework.
 * See LICENSE for terms. See docs/ for programmer guides.
 */
/*
 * What it does: Auto-generated static dialect configuration for custom lightweight builds.
 * Why it exists: Provides compile-time dialect maps to minimize memory footprint in blite and bscript.
 * Why it works this way: Hardcodes dialect parameters into a static struct initializer to bypass runtime parsing.
 * What can be changed: Do not edit this file directly; regenerate it using `bppc --dialect`.
 * What cannot be changed: Structure initialization and mapping tables.
 * What to expect: Standardized initialization function `init_custom_static_dialect`.
 * What to do if something breaks: Regenerate using the transpiler or check source dialect config.
 * Assumptions: Target d must be a valid BppDialect pointer.
 * Portability concerns: ANSI C17 compatible.
 * Future expansions: Re-run bppc compilation tool.
 * External extension hooks: Standard BppDialect struct mappings.
 */
#ifndef CUSTOM_DIALECT_STATIC_H
#define CUSTOM_DIALECT_STATIC_H

#include <stdbool.h>
#include <string.h>
#include "core/dialect.h"

static inline void init_custom_static_dialect(BppDialect *d) {
    snprintf(d->name, sizeof(d->name), "StaticJSON");
    d->comment_char = '#';
    d->stmt_separator = ';';
    d->default_array_base = 1;
    d->case_sensitive = true;
    d->math_precedence = PRECEDENCE_STANDARD;
    d->keyword_count = 2;
    snprintf(d->keywords[0].name, sizeof(d->keywords[0].name), "DISPLAY");
    snprintf(d->keywords[0].mapped_to, sizeof(d->keywords[0].mapped_to), "PRINT");
    snprintf(d->keywords[1].name, sizeof(d->keywords[1].name), "QUIT");
    snprintf(d->keywords[1].mapped_to, sizeof(d->keywords[1].mapped_to), "END");
}

#endif
