/* Auto-generated help database */
static const BuiltinHelpEntry g_builtin_help[] = {
    {"PRINT", "Input / Output", "PRINT", "Display output to console"},
    {"LET", "Variables & Memory", "LET", "Assign value to variable (optional in most dialects)"},
    {"INPUT", "Input / Output", "INPUT", "Get console input into a variable"},
    {"IF", "Control Flow", "IF", "Conditional decision structure"},
    {"THEN", "Control Flow", "THEN", "Conditional branch target indicator"},
    {"ELSE", "Control Flow", "ELSE", "Alternate branch in block IF or single-line IF"},
    {"GOTO", "Control Flow", "GOTO", "Jump to a line number"},
    {"GOSUB", "Control Flow", "GOSUB", "Call a subroutine at a line number"},
    {"RETURN", "Control Flow", "RETURN", "Return from a GOSUB subroutine"},
    {"END", "Control Flow", "END", "Terminate program execution"},
    {"REM", "Variables & Memory", "REM", "Comment (ignored by interpreter)"},
    {"LIST", "Program Mgmt & Editing", "LIST", "List stored program lines"},
    {"RUN", "Program Mgmt & Editing", "RUN", "Execute the stored program"},
    {"NEW", "Program Mgmt & Editing", "NEW", "Clear program and variables"},
    {"FOR", "Control Flow", "FOR", "Begin a counting loop"},
    {"NEXT", "Control Flow", "NEXT", "End of a FOR loop"},
    {"TO", "Control Flow", "TO", "Counting upper limit indicator"},
    {"STEP", "Control Flow", "STEP", "Count loop step increments"},
    {"BY", "Control Flow", "BY", "Counting step in loop (SBASIC FOR loop alias)"},
    {"WHILE", "Control Flow", "WHILE", "Begin a conditional loop"},
    {"WEND", "Control Flow", "WEND", "End of a WHILE loop"},
    {"DO", "Control Flow", "DO", "Begin a DO loop"},
    {"LOOP", "Control Flow", "LOOP", "End of a DO loop (with condition)"},
    {"UNTIL", "Control Flow", "UNTIL", "Exit condition for repeat loop"},
    {"DIM", "Variables & Memory", "DIM", "Declare an array with dimensions"},
    {"ERASE", "Variables & Memory", "ERASE", "Erase an array from memory"},
    {"OPTION", "Variables & Memory", "OPTION", "Set interpreter options"},
    {"DATA", "Variables & Memory", "DATA", "Store numeric or string data"},
    {"READ", "Variables & Memory", "READ", "Read the next DATA value"},
    {"RESTORE", "Variables & Memory", "RESTORE", "Reset DATA pointer to beginning"},
    {"DEFINT", "Variables & Memory", "DEFINT", "Declare integer variable range"},
    {"DEFSNG", "Variables & Memory", "DEFSNG", "Declare single variable range"},
    {"DEFDBL", "Variables & Memory", "DEFDBL", "Declare double variable range"},
    {"DEFSTR", "Variables & Memory", "DEFSTR", "Declare string variable range"},
    {"ON", "Control Flow", "ON", "Computed GOTO/GOSUB or error/event handler"},
    {"ERROR", "Control Flow", "ERROR", "Raise a user error"},
    {"RESUME", "Control Flow", "RESUME", "Return from an error handler"},
    {"LOAD", "Program Mgmt & Editing", "LOAD", "Load program from disk"},
    {"SAVE", "Program Mgmt & Editing", "SAVE", "Save program to disk"},
    {"MERGE", "Program Mgmt & Editing", "MERGE", "Merge program lines from disk"},
    {"COMMON", "Variables & Memory", "COMMON [SHARED] var1, var2, ...", "Declare common variables to persist across CHAIN"},
    {"CHAIN", "Program Mgmt & Editing", "CHAIN filename$", "Load and execute a new program, preserving COMMON variables"},
    {"SELFTEST", "Debug & Testing", "SELFTEST", "Run built-in interpreter tests"},
    {"ASSERT", "Debug & Testing", "ASSERT", "Assert condition is true"},
    {"BREAK", "Debug & Testing", "BREAK", "Trigger interactive breakpoint"},
    {"TRON", "Debug & Testing", "TRON", "Turn statement tracing ON"},
    {"TROFF", "Debug & Testing", "TROFF", "Turn statement tracing OFF"},
    {"VARS", "Debug & Testing", "VARS", "Display all active variables"},
    {"OPEN", "Input / Output", "OPEN", "Standard I/O or string formatting"},
    {"CLOSE", "File I/O", "CLOSE", "Close a file channel"},
    {"AS", "Variables & Memory", "AS", "Specify variable type or file channel alias"},
    {"FILES", "File I/O", "FILES", "File and directory management"},
    {"KILL", "System & Environ", "KILL", "Reserved for future use"},
    {"CHDIR", "File I/O", "CHDIR", "File and directory management"},
    {"MKDIR", "File I/O", "MKDIR", "File and directory management"},
    {"RMDIR", "File I/O", "RMDIR", "File and directory management"},
    {"DIR", "Uncategorized", "DIR", "No description available."},
    {"SETATTR", "Uncategorized", "SETATTR", "No description available."},
    {"LOCK", "Uncategorized", "LOCK", "No description available."},
    {"UNLOCK", "Uncategorized", "UNLOCK", "No description available."},
    {"ENVIRON", "Uncategorized", "ENVIRON", "No description available."},
    {"NAME", "File I/O", "NAME", "File and directory management"},
    {"GET", "File I/O", "GET", "Read a record from random file"},
    {"PUT", "File I/O", "PUT", "Write a record to random file"},
    {"BGET", "Uncategorized", "BGET", "No description available."},
    {"BPUT", "Uncategorized", "BPUT", "No description available."},
    {"SEEK", "File I/O", "SEEK", "Set or get file position"},
    {"FIELD", "Uncategorized", "FIELD", "No description available."},
    {"SELECT", "Control Flow", "SELECT", "Begin a SELECT CASE block"},
    {"CASE", "Control Flow", "CASE", "Case clause within SELECT CASE"},
    {"DECLARE", "Control Flow", "DECLARE", "Forward-declare a SUB or FUNCTION"},
    {"SUB", "Control Flow", "SUB", "Define a named subroutine"},
    {"FUNCTION", "Control Flow", "FUNCTION", "Define a named function"},
    {"CALL", "Control Flow", "CALL", "Call a SUB procedure"},
    {"AUTO", "Uncategorized", "AUTO", "No description available."},
    {"BCOLOR", "Uncategorized", "BCOLOR", "No description available."},
    {"FCOLOR", "Uncategorized", "FCOLOR", "No description available."},
    {"CLEAR", "Uncategorized", "CLEAR", "No description available."},
    {"CURSOR", "Uncategorized", "CURSOR", "No description available."},
    {"LOCATE", "Uncategorized", "LOCATE", "No description available."},
    {"SHARED", "Uncategorized", "SHARED", "No description available."},
    {"SCREEN", "Graphics", "SCREEN", "Set screen mode"},
    {"COLOR", "Input / Output", "COLOR", "Set text foreground/background"},
    {"LINE", "Input / Output", "LINE", "Read entire line (LINE INPUT)"},
    {"CIRCLE", "Graphics", "CIRCLE", "Draw a circle"},
    {"PSET", "Graphics", "PSET", "Set a pixel at (x,y)"},
    {"PRESET", "Graphics", "PRESET", "Reset a pixel at (x,y)"},
    {"CLS", "Input / Output", "CLS", "Clear the screen"},
    {"LSET", "Uncategorized", "LSET", "No description available."},
    {"DEFSEG", "Uncategorized", "DEFSEG", "No description available."},
    {"RSET", "Uncategorized", "RSET", "No description available."},
    {"SWAP", "Uncategorized", "SWAP", "No description available."},
    {"LOCAL", "Uncategorized", "LOCAL", "No description available."},
    {"STATIC", "Uncategorized", "STATIC", "No description available."},
    {"REDIM", "Uncategorized", "REDIM", "No description available."},
    {"PRESERVE", "Uncategorized", "PRESERVE", "No description available."},
    {"PAINT", "Graphics", "PAINT", "Flood fill an area"},
    {"BEEP", "Sound", "BEEP", "Emit an audible beep"},
    {"SOUND", "Sound", "SOUND", "Play a tone at frequency"},
    {"PLAY", "Graphics", "PLAY", "Graphics or sound macro"},
    {"BLOAD", "Program Mgmt & Editing", "BLOAD", "Load binary memory image"},
    {"BSAVE", "Program Mgmt & Editing", "BSAVE", "Save binary memory image"},
    {"BRUN", "Program Mgmt & Editing", "BRUN", "Load and execute binary program"},
    {"USING", "Introspection", "USING", "Built-in command or function: USING"},
#if BPP_SUPPORT_EDITOR
    {"EDIT", "Program Mgmt & Editing", "EDIT", "Edit a program line"},
#endif
    {"SECURITY", "System & Environ", "SECURITY", "System operation or file query"},
    {"MODULE", "Introspection", "MODULE", "Advanced language feature"},
    {"LEVEL", "Uncategorized", "LEVEL", "No description available."},
    {"RESTRICT", "Uncategorized", "RESTRICT", "No description available."},
    {"RESET", "File I/O", "RESET", "Close all open files"},
    {"INFO", "Introspection", "INFO", "Display system information"},
    {"UNLOAD", "Program Mgmt & Editing", "UNLOAD", "Unload module or program"},
    {"TASK", "Control Flow", "TASK", "Multi-tasking thread spawn"},
    {"WAIT", "Devices & Network", "WAIT", "Wait for hardware port state"},
#if BPP_SUPPORT_MAT
    {"MAT", "Variables & Memory", "MAT", "Matrix operations"},
#endif
    {"ARRAY", "Uncategorized", "ARRAY", "No description available."},
    {"MAP", "Uncategorized", "MAP", "No description available."},
    {"FILTER", "Uncategorized", "FILTER", "No description available."},
    {"REDUCE", "Uncategorized", "REDUCE", "No description available."},
#if BPP_SUPPORT_EDITOR
    {"RENUM", "Program Mgmt & Editing", "RENUM", "Renumber program lines"},
#endif
#if BPP_SUPPORT_EDITOR
    {"DELETE", "Program Mgmt & Editing", "DELETE", "Delete program lines"},
#endif
    {"HELP", "Introspection", "HELP", "Show this help (or HELP keyword)"},
    {"CATALOG", "Introspection", "CATALOG", "List all commands & functions"},
    {"DEVICES", "Uncategorized", "DEVICES", "No description available."},
    {"IOCTL", "Devices & Network", "IOCTL", "Send control string to device"},
#if BPP_SUPPORT_NET
    {"MOUNT", "Devices & Network", "MOUNT", "Mount a VFS path"},
#endif
#if BPP_SUPPORT_NET
    {"UMOUNT", "Devices & Network", "UMOUNT", "Unmount a VFS path"},
#endif
    {"UNSAVE", "Program Mgmt & Editing", "UNSAVE", "Delete saved program (alias for KILL)"},
    {"CHVT", "Uncategorized", "CHVT", "No description available."},
#if BPP_SUPPORT_NET
    {"NET", "Uncategorized", "NET", "No description available."},
#endif
    {"OUT", "Devices & Network", "OUT", "Write to a hardware port"},
    {"POKE", "Variables & Memory", "POKE", "Write byte to virtual memory"},
#if BPP_SUPPORT_BIOS
    {"BIOS", "Devices & Network", "BIOS", "Access mock BIOS interrupt or switch memory map model (string)"},
#endif
#if BPP_SUPPORT_GEMINI
    {"GEMINI", "Input / Output", "GEMINI", "Network protocol handler"},
#endif
    {"UNLESS", "Introspection", "UNLESS", "Built-in command or function: UNLESS"},
    {"DEMAND", "Introspection", "DEMAND", "Built-in command or function: DEMAND"},
    {"TRY", "Uncategorized", "TRY", "No description available."},
    {"CATCH", "Uncategorized", "CATCH", "No description available."},
    {"THROW", "Uncategorized", "THROW", "No description available."},
    {"ALIAS", "Introspection", "ALIAS", "Advanced language feature"},
    {"METADATA", "Uncategorized", "METADATA", "No description available."},
    {"DIALECT", "System & Environ", "DIALECT", "System environment query/control"},
    {"DEFINE", "Uncategorized", "DEFINE", "No description available."},
#if BPP_SUPPORT_OOP
    {"TYPE", "Variables & Memory", "TYPE", "Define a user-defined type"},
#endif
#if BPP_SUPPORT_OOP
    {"CLASS", "Variables & Memory", "CLASS", "Define OOP Class block"},
#endif
    {"BORDER", "Uncategorized", "BORDER", "No description available."},
    {"INK", "Uncategorized", "INK", "No description available."},
    {"PAPER", "Uncategorized", "PAPER", "No description available."},
    {"PAUSE", "Uncategorized", "PAUSE", "No description available."},
    {"SYS", "Uncategorized", "SYS", "No description available."},
    {"GR", "Uncategorized", "GR", "No description available."},
    {"HGR", "Uncategorized", "HGR", "No description available."},
    {"HGR2", "Uncategorized", "HGR2", "No description available."},
    {"HCOLOR", "Uncategorized", "HCOLOR", "No description available."},
    {"PLOT", "Uncategorized", "PLOT", "No description available."},
    {"HLIN", "Uncategorized", "HLIN", "No description available."},
    {"VLIN", "Uncategorized", "VLIN", "No description available."},
    {"HPLOT", "Uncategorized", "HPLOT", "No description available."},
    {"ONERR", "Uncategorized", "ONERR", "No description available."},
    {"GRAPHICS", "Uncategorized", "GRAPHICS", "No description available."},
    {"DRAWTO", "Uncategorized", "DRAWTO", "No description available."},
    {"SYSTEM", "Uncategorized", "SYSTEM", "No description available."},
    {"SHELL", "Uncategorized", "SHELL", "No description available."},
    {"BYE", "Uncategorized", "BYE", "No description available."},
    {"STOP", "Uncategorized", "STOP", "No description available."},
    {"EXIT", "Uncategorized", "EXIT", "No description available."},
    {"PROCEDURE", "Control Flow", "PROCEDURE", "Define a named procedure (alias for SUB)"},
    {"ENDFUNC", "Control Flow", "ENDFUNC", "End a FUNCTION block"},
    {"ENDPROC", "Control Flow", "ENDPROC", "End a PROCEDURE block"},
    {"TXN", "File I/O", "TXN", "Transaction control (BEGIN, COMMIT, ROLLBACK, STATUS)"},
    {"ATOMIC", "File I/O", "ATOMIC", "Start implicit atomic transaction"},
    {"COMMIT", "File I/O", "COMMIT", "Commit active transaction"},
    {"ROLLBACK", "File I/O", "ROLLBACK", "Rollback active transaction"},
    {"AND", "Uncategorized", "AND", "No description available."},
    {"OR", "Uncategorized", "OR", "No description available."},
    {"NOT", "Uncategorized", "NOT", "No description available."},
    {"XOR", "Uncategorized", "XOR", "No description available."},
    {"INKEY$", "Uncategorized", "INKEY$", "No description available."},
    {"PEN", "Uncategorized", "PEN", "No description available."},
    {"TIME$", "Uncategorized", "TIME$", "No description available."},
    {"DATE$", "Uncategorized", "DATE$", "No description available."},
    {"SQR", "Arithmetic / Math", "SQR", "Square root"},
    {"ABS", "Arithmetic / Math", "ABS", "Absolute value"},
    {"SIN", "Arithmetic / Math", "SIN", "Sine (radians)"},
    {"COS", "Arithmetic / Math", "COS", "Cosine (radians)"},
    {"TAN", "Arithmetic / Math", "TAN", "Tangent (radians)"},
    {"ATN", "Arithmetic / Math", "ATN", "Arctangent (returns radians)"},
    {"LOG", "Arithmetic / Math", "LOG", "Natural logarithm (base e)"},
    {"EXP", "Arithmetic / Math", "EXP", "Exponential (e^x)"},
    {"INT", "Arithmetic / Math", "INT", "Truncate to integer (math) or trigger software interrupt"},
    {"FIX", "Arithmetic / Math", "FIX", "Truncate toward zero"},
    {"DET", "Uncategorized", "DET", "No description available."},
    {"DOT", "Uncategorized", "DOT", "No description available."},
    {"CROSS", "Uncategorized", "CROSS", "No description available."},
    {"RND", "Arithmetic / Math", "RND", "Random number (0 to 1)"},
    {"RANDOMIZE", "Arithmetic / Math", "RANDOMIZE [seed] / RANDOMIZE(func_arg$)", "Seed the random number generator or generate random string/date/time values"},
    {"LEN", "String Functions", "LEN", "Length of a string"},
    {"ASC", "String Functions", "ASC", "ASCII value of first character"},
    {"CHR$", "String Functions", "CHR$", "Character from ASCII code"},
    {"CINT", "Arithmetic / Math", "CINT(x)", "Convert value to a 16-bit signed integer"},
    {"CSNG", "Arithmetic / Math", "CSNG(x)", "Convert value to single-precision float"},
    {"CDBL", "Arithmetic / Math", "CDBL(x)", "Convert value to double-precision float"},
    {"VARPTR", "Variables & Memory", "VARPTR(var)", "Get memory offset of a variable"},
    {"VARPTR$", "Variables & Memory", "VARPTR$(var)", "Get packed variable descriptor string"},
    {"VARSEG", "Variables & Memory", "VARSEG(var)", "Get memory segment of a variable"},
    {"SADD", "Variables & Memory", "SADD(var$)", "Get memory offset of a string variable's data"},
    {"VAL", "String Functions", "VAL", "Convert string to number"},
    {"STR$", "String Functions", "STR$", "Convert number to string"},
    {"LEFT$", "String Functions", "LEFT$", "Get left portion of string"},
    {"RIGHT$", "String Functions", "RIGHT$", "Get right portion of string"},
    {"MID$", "String Functions", "MID$", "Substring function"},
    {"INSTR", "Input / Output", "INSTR", "Standard I/O or string formatting"},
    {"UCASE$", "String Functions", "UCASE$", "Convert string to uppercase"},
    {"LCASE$", "String Functions", "LCASE$", "Convert string to lowercase"},
    {"LTRIM$", "String Functions", "LTRIM$", "Trim leading spaces"},
    {"RTRIM$", "String Functions", "RTRIM$", "Trim trailing spaces"},
    {"TRIM$", "String Functions", "TRIM$", "Trim leading and trailing spaces"},
    {"SPACE$", "String Functions", "SPACE$", "Create space string"},
    {"STRING$", "String Functions", "STRING$", "Create repeated character string"},
    {"REPLACE$", "String Functions", "REPLACE$", "Replace substrings"},
    {"REMOVE$", "String Functions", "REMOVE$(s$, find$) or REMOVE$ var_or_arr$, find$", "Remove substrings"},
    {"REMOVE", "Variables & Memory", "REMOVE(x, val) or REMOVE var_or_arr, val", "Remove numeric values (zero out)"},
    {"UBOUND", "Variables & Memory", "UBOUND", "Array upper bound index"},
    {"LBOUND", "Variables & Memory", "LBOUND", "Array lower bound index"},
    {"EOF", "Input / Output", "EOF", "Standard I/O or string formatting"},
    {"LOF", "File I/O", "LOF", "Get length of open file"},
    {"LOC", "File I/O", "LOC", "Current file position"},
    {"HELP", "Introspection", "HELP", "Show this help (or HELP keyword)"},
    {"FREEFILE", "Uncategorized", "FREEFILE", "No description available."},
    {"INPUT", "Input / Output", "INPUT", "Get console input into a variable"},
    {"IOCTL", "Devices & Network", "IOCTL", "Send control string to device"},
    {"TXNSTATUS", "Uncategorized", "TXNSTATUS", "No description available."},
    {"SIOREAD$", "Uncategorized", "SIOREAD$", "No description available."},
    {"SIOREADLN$", "Uncategorized", "SIOREADLN$", "No description available."},
    {"SIOWRITE", "Uncategorized", "SIOWRITE", "No description available."},
    {"SIOSEEK", "Uncategorized", "SIOSEEK", "No description available."},
    {"SIOFLUSH", "Uncategorized", "SIOFLUSH", "No description available."},
    {"SIOSTATUS", "Uncategorized", "SIOSTATUS", "No description available."},
    {"SIOAVAIL", "Uncategorized", "SIOAVAIL", "No description available."},
    {"BIOREAD$", "Uncategorized", "BIOREAD$", "No description available."},
    {"BIOWRITE", "Uncategorized", "BIOWRITE", "No description available."},
    {"BIOCOPY", "Uncategorized", "BIOCOPY", "No description available."},
    {"BIOFILL", "Uncategorized", "BIOFILL", "No description available."},
    {"BIOSTATUS", "Uncategorized", "BIOSTATUS", "No description available."},
    {"BIOSIZE", "Uncategorized", "BIOSIZE", "No description available."},
    {"BIOCHECKSUM", "Uncategorized", "BIOCHECKSUM", "No description available."},
    {"BIOCOMPARE", "Uncategorized", "BIOCOMPARE", "No description available."},
    {"FILEATTR", "Uncategorized", "FILEATTR", "No description available."},
    {"MKI$", "Uncategorized", "MKI$", "No description available."},
    {"MKS$", "Uncategorized", "MKS$", "No description available."},
    {"MKD$", "Uncategorized", "MKD$", "No description available."},
    {"CVI", "Uncategorized", "CVI", "No description available."},
    {"CVS", "Uncategorized", "CVS", "No description available."},
    {"CVD", "Uncategorized", "CVD", "No description available."},
    {"DEVICECOUNT", "Uncategorized", "DEVICECOUNT", "No description available."},
    {"DEVICE$", "Uncategorized", "DEVICE$", "No description available."},
    {"DEVICECLASS$", "Uncategorized", "DEVICECLASS$", "No description available."},
    {"DEVICEINFO$", "Uncategorized", "DEVICEINFO$", "No description available."},
    {"POLL", "Uncategorized", "POLL", "No description available."},
#if BPP_SUPPORT_NET
    {"NSTATUS", "Input / Output", "NSTATUS", "Network socket operation"},
#endif
#if BPP_SUPPORT_NET
    {"NCONNECTED", "Input / Output", "NCONNECTED", "Network socket operation"},
#endif
#if BPP_SUPPORT_NET
    {"NHTTPSTATUS", "Input / Output", "NHTTPSTATUS", "Network socket operation"},
#endif
#if BPP_SUPPORT_NET
    {"HTTP_GET$", "Devices & Network", "HTTP_GET$", "Perform HTTP GET request"},
#endif
#if BPP_SUPPORT_BIOS
    {"MEMMAP$", "Introspection", "MEMMAP$", "Get name of currently active BIOS memory map model"},
#endif
    {"PEEK", "Variables & Memory", "PEEK", "Read byte from virtual memory"},
    {"MAP_NEW", "Uncategorized", "MAP_NEW", "No description available."},
    {"MAP_SET", "Uncategorized", "MAP_SET", "No description available."},
    {"MAP_GET", "Uncategorized", "MAP_GET", "No description available."},
    {"MAP_GET$", "Uncategorized", "MAP_GET$", "No description available."},
    {"MAP_REMOVE", "Uncategorized", "MAP_REMOVE", "No description available."},
    {"MAP_COUNT", "Uncategorized", "MAP_COUNT", "No description available."},
    {"MAP_KEY$", "Uncategorized", "MAP_KEY$", "No description available."},
    {"MAP_HAS", "Uncategorized", "MAP_HAS", "No description available."},
#if BPP_SUPPORT_JSON
    {"JSON_PARSE", "Uncategorized", "JSON_PARSE", "No description available."},
#endif
#if BPP_SUPPORT_JSON
    {"JSON_STRINGIFY$", "Uncategorized", "JSON_STRINGIFY$", "No description available."},
#endif
#if BPP_SUPPORT_XML
    {"XML_PARSE", "Uncategorized", "XML_PARSE", "No description available."},
#endif
#if BPP_SUPPORT_XML
    {"XML_STRINGIFY$", "Uncategorized", "XML_STRINGIFY$", "No description available."},
#endif
    {"YAML_PARSE", "Uncategorized", "YAML_PARSE", "No description available."},
    {"YAML_STRINGIFY$", "Uncategorized", "YAML_STRINGIFY$", "No description available."},
#if BPP_SUPPORT_INI
    {"INI_PARSE", "Uncategorized", "INI_PARSE", "No description available."},
#endif
#if BPP_SUPPORT_INI
    {"INI_STRINGIFY$", "Uncategorized", "INI_STRINGIFY$", "No description available."},
#endif
    {"DIALECT_LOAD", "Uncategorized", "DIALECT_LOAD", "No description available."},
    {"DIALECT_REGISTER", "Uncategorized", "DIALECT_REGISTER", "No description available."},
    {"DIALECT_VALIDATE", "Uncategorized", "DIALECT_VALIDATE", "No description available."},
    {"DIALECT_DOC$", "Uncategorized", "DIALECT_DOC$", "No description available."},
    {"ENVIRON$", "Uncategorized", "ENVIRON$", "No description available."},
    {"DIR$", "Uncategorized", "DIR$", "No description available."},
    {"GETATTR", "Uncategorized", "GETATTR", "No description available."},
    {"INP", "Devices & Network", "INP", "Read from a hardware port"},
    {"INITGRAPH", "BGI Graphics", "INITGRAPH mode_id", "Initialize BGI graphics mode by heritage mode ID"},
    {"CLOSEGRAPH", "BGI Graphics", "CLOSEGRAPH", "Shutdown BGI graphics and release VRAM"},
    {"PUTPIXEL", "BGI Graphics", "PUTPIXEL x, y, color", "Write a single pixel at (x, y)"},
    {"BAR", "BGI Graphics", "BAR x1, y1, x2, y2", "Draw a filled rectangle using fill color"},
    {"ELLIPSE", "BGI Graphics", "ELLIPSE cx, cy, sa, ea, rx, ry", "Draw an elliptical arc"},
    {"RECTANGLE", "BGI Graphics", "RECTANGLE x1, y1, x2, y2", "Draw an unfilled rectangle outline"},
    {"OUTTEXTXY", "BGI Graphics", "OUTTEXTXY x, y, text$", "Render text at (x, y) in graphics mode"},
    {"PALETTE", "BGI Graphics", "PALETTE index, R, G, B", "Set a palette entry (0-255) to an RGB color"},
    {"_CLIPBOARD$", "System & Environ", "_CLIPBOARD$", "Get or set the system clipboard text content"},
    {"_LOADIMAGE", "Graphics", "handle = _LOADIMAGE(filename$)", "Load image from a file, returning an image handle"},
    {"_PUTIMAGE", "Graphics", "_PUTIMAGE [x, y], handle", "Draw a loaded image handle at (x, y)"},
    {"_FREEIMAGE", "Graphics", "_FREEIMAGE handle", "Release memory allocated for an image handle"},
    {"_CREATEIMAGE", "Graphics", "handle = _CREATEIMAGE(width, height, mode)", "Create a blank memory buffer image"},
    {"_COPYIMAGE", "Graphics", "handle = _COPYIMAGE(source_handle)", "Duplicate an image handle"},
    {"_WIDTH", "Graphics", "w = _WIDTH(handle)", "Get width of an image handle or screen"},
    {"_HEIGHT", "Graphics", "h = _HEIGHT(handle)", "Get height of an image handle or screen"},
    {"_DEFLATE$", "String Functions", "comp$ = _DEFLATE$(data$)", "Compress a string using LZ77 deflation"},
    {"_INFLATE$", "String Functions", "decomp$ = _INFLATE$(comp$)", "Decompress an LZ77-compressed string"},
    {"_STATESAVE", "System & Environ", "_STATESAVE filename$", "Serialize and save the current VM execution state to a binary file"},
    {"_STATELOAD", "System & Environ", "_STATELOAD filename$", "Restore the VM execution state from a saved binary file"},
    {"sound.tone", "Sound", "sound.tone freq, dur", "Emit a tone at specified frequency and duration"},
    {"music.play", "Sound", "music.play mml$", "Queue and play MML format music string"},
    {"mouse.x", "Devices & Network", "x = mouse.x", "Query current mouse X coordinate"},
    {"mouse.y", "Devices & Network", "y = mouse.y", "Query current mouse Y coordinate"},
    {"mouse.button", "Devices & Network", "b = mouse.button(btn)", "Query if a mouse button is pressed"},
    {"mouse.wheel", "Devices & Network", "w = mouse.wheel", "Query mouse wheel delta"},
    {"mouse.hide", "Devices & Network", "mouse.hide", "Hide system mouse cursor"},
    {"mouse.show", "Devices & Network", "mouse.show", "Show system mouse cursor"},
    {"window.title", "Graphics", "window.title text$", "Set main application window title"},
    {"window.move", "Graphics", "window.move x, y", "Reposition main window on desktop"},
    {"window.fullscreen", "Graphics", "window.fullscreen", "Toggle window fullscreen mode"},
    {"window.resizable", "Graphics", "window.resizable flag", "Set if main window is user resizable"},
    {"EXISTS", "File I/O", "EXISTS(filename$)", "Check if a file exists, returns -1 if true and 0 if false"},
    {"FILESIZE", "File I/O", "FILESIZE(filename$)", "Get the size of a file in bytes"},
    {"FILEMOD$", "File I/O", "FILEMOD$(filename$)", "Get the modification timestamp of a file (YYYY-MM-DD HH:MM:SS)"},
    {"PWD", "File I/O", "PWD", "Print the current working directory path to console"},
    {"BASEDIR$", "File I/O", "BASEDIR$", "Get the parent directory path of the current working directory"},
    {"BASENAME$", "File I/O", "BASENAME$", "Get the current working directory name (basename)"},
    {"BASEPATH$", "File I/O", "BASEPATH$", "Get the full current working directory path"},
    {"HOSTNAME", "System & Environ", "HOSTNAME", "Print system network hostname to console"},
    {"HOSTNAME$", "System & Environ", "HOSTNAME$", "Get system network hostname"},
    {"USERNAME", "System & Environ", "USERNAME", "Print current user name to console"},
    {"USERNAME$", "System & Environ", "USERNAME$", "Get current user name"},
    {"PATH$", "File I/O", "PATH$ / PATH$(category$)", "Get or set virtual filesystem search paths"},
    {"ERR$", "System & Environ", "ERR$([code])", "Get the string representation of an error code, or the last error message if code is omitted"},
    {"HEX$", "String Functions", "HEX$(n)", "Convert number to hexadecimal string"},
    {"OCT$", "String Functions", "OCT$(n)", "Convert number to octal string"},
    {"BIN$", "String Functions", "BIN$(n)", "Convert number to binary string"},
    {"EDIT$", "String Functions", "EDIT$(s$, mask)", "Perform mask-based string modifications (VAX compatible)"},
    {"NUM$", "String Functions", "NUM$(n)", "Convert number to string with leading space if positive"},
    {"TI", "System & Environ", "TI", "Get numeric local time as HHMMSS"},
    {"TI$", "System & Environ", "TI$", "Get string local time as HH:MM:SS (24-hour format)"},
    {"TIME", "System & Environ", "TIME", "Get numeric local time as HHMMSS"},
    {"TIME$", "System & Environ", "TIME$", "Get string local time as HH:MM:SS A/P (12-hour format)"},
    {"DATE", "System & Environ", "DATE", "Get numeric local date as YYYYMMDD"},
    {"DATE$", "System & Environ", "DATE$", "Get string local date as DD-MM-YYYY"},
    {"DAY", "System & Environ", "DAY", "Get numeric local day of the month (1-31)"},
    {"DAY$", "System & Environ", "DAY$", "Get local day of the week abbreviated in uppercase (SUN-SAT)"},
    {"MONTH", "System & Environ", "MONTH", "Get numeric local month of the year (1-12)"},
    {"MONTH$", "System & Environ", "MONTH$", "Get local month of the year abbreviated in uppercase (JAN-DEC)"},
    {"YEAR", "System & Environ", "YEAR", "Get numeric local year"},
    {"HOURS", "System & Environ", "HOURS", "Get numeric UTC hour (0-23)"},
    {"MINUTES", "System & Environ", "MINUTES", "Get numeric UTC minute (0-59)"},
    {"SECONDS", "System & Environ", "SECONDS", "Get numeric UTC second (0-59)"},
    {"CLOCK$", "System & Environ", "CLOCK$", "Get current UTC date and time in ISO 8601 format"},
    {"TZ", "System & Environ", "TZ", "Get numeric timezone offset (formatted as +/-HHMM)"},
    {"TZ$", "System & Environ", "TZ$", "Get local timezone abbreviation"},
    {"TIMEZONE$", "System & Environ", "TIMEZONE$", "Get full timezone name string"},
    {"UTC", "System & Environ", "UTC", "Get numeric timezone offset from UTC in seconds"},
    {"JIFFIES", "System & Environ", "JIFFIES([mode$])", "Get uptime ticks based on frequency multiplier (NTSC/PAL/SECAM)"},
    {"TRUE", "System & Environ", "TRUE", "Boolean constant (1.0)"},
    {"FALSE", "System & Environ", "FALSE", "Boolean constant (-1.0)"},
    {"ALARM", "System & Environ", "[SET] ALARM[(n)] [ON|OFF|STOP|PAUSE|SNOOZE [m]|UNSET]", "Query countdown or control its state"},
    {"ALARM$", "System & Environ", "[SET] ALARM$[(time)] [ON|OFF|STOP|PAUSE|SNOOZE [m]|UNSET]", "Query daily alarm or control its state"},
    {"SET", "System & Environ", "SET ALARM(...) <modifier>", "Configure and activate/snooze/unset alarms"},
    {"MOUSE", "Input / Output", "MOUSE ON|OFF | MOUSE x, y, char, attr", "Show/hide mouse or set position and custom cursor style"},
    {"HMOUSE", "Input / Output", "HMOUSE x | x = HMOUSE", "Set or query mouse cursor horizontal column coordinate"},
    {"VMOUSE", "Input / Output", "VMOUSE y | y = VMOUSE", "Set or query mouse cursor vertical row coordinate"},
    {"TRIG", "Input / Output", "TRIG ON|OFF|STOP | state = TRIG(n)", "Query mouse button click states and trigger button trapping events"},
    {"GUID$", "System & Environ", "GUID$", "Generate a random 36-character standard UUIDv4 string"},
    {"CSRLIN", "Input / Output", "row = CSRLIN", "Get the current cursor row line number (1-indexed)"},
    {"POS", "Input / Output", "col = POS(n)", "Get the current cursor column position (1-indexed)"},
    {"LPOS", "Input / Output", "col = LPOS(n)", "Get the current printer column position (1-indexed)"},
    {"RESET", "File I/O", "RESET", "Close all open file and device channels and flush buffers"},
    {"USR", "System & Environ", "DEF USR[n] = addr | res = USR[n](arg)", "Machine code/C routine dispatch table (USR0 to USR9)"},
    {"ERDEV", "System & Environ", "code = ERDEV", "Get 16-bit hardware/INT 24h error code from last device operation"},
    {"ERDEV$", "System & Environ", "name$ = ERDEV$", "Get 8-character ASCII device driver name from last error"},
    {"EXTERR", "System & Environ", "val = EXTERR(n)", "Query extended operating system error (0=code, 1=class, 2=action, 3=locus)"},
    {"HASH$", "System & Environ", "digest$ = HASH$(algo$, data$)", "Generate MD5, SHA1, SHA256, SHA512, or CRC32 hash string"},
    {"SALT$", "System & Environ", "salted$ = SALT$(data$, salt$)", "Compute salted SHA256 password hash string"},
    {"AUDITCRACK", "Security & Audit", "match = AUDITCRACK(hash$, wordlist$ [, algo$])", "Perform dictionary attack hash auditing"},
    {"SANDBOXAUDIT", "Security & Audit", "is_sandboxed = SANDBOXAUDIT()", "Detect if execution is running inside a VM or sandbox"},
    {"VMCHECK", "Security & Audit", "is_vm = VMCHECK()", "Inspect hypervisor timing artifacts for VM detection"},
};
