// FILENAME: help_data.h
// LICENSE: Copyleft (c) 2026 BASIC++ Community — All Wrongs Reserved
// VERSION: 6.5.2.0
// NEEDED BY: libengine (category.c, help.c)
// NEEDS: platform, memory
// Provides runtime implementation for the HELP_DATA statement in BASIC++.
//
// ---- Includes ----

static const BuiltinHelpEntry g_builtin_help[] = {
    {"PRINT", "Input / Output", "PRINT", "Display output to console"},
    {"LET", "Variables & Memory", "LET", "Assign value to variable (optional in most dialects)"},
    {"INPUT", "Input / Output", "INPUT", "Get console input into a variable"},
    {"IF", "Control Flow", "IF", "Conditional decision structure"},
    {"THEN", "Control Flow", "THEN", "Conditional branch target indicator"},
    {"ELSE", "Control Flow", "ELSE", "Alternate branch in block IF or single-line IF"},
    {"GOTO", "Control Flow", "GOTO", "Jump to a line number"},
    {"GOSUB", "Control Flow", "GOSUB", "Call a subroutine at a line number"},
    {"RETURN", "Control Flow", "RETURN", "Return from a GOSUB subroutine"},
    {"END", "Control Flow", "END", "Terminate program execution"},
    {"REM", "Variables & Memory", "REM", "Comment (ignored by interpreter)"},
    {"LIST", "Program Mgmt & Editing", "LIST", "List stored program lines"},
    {"RUN", "Program Mgmt & Editing", "RUN", "Execute the stored program"},
    {"NEW", "Program Mgmt & Editing", "NEW", "Clear program and variables"},
    {"REFORMAT", "Program Mgmt & Editing", "REFORMAT [spaces_per_indent] [target] [CHECK|STRICT|SPLIT|UPPER|LOWER|PRESERVE|SPACES]", "Reformats BASIC source code with configurable indentation and static structural analysis"},
    {"FOR", "Control Flow", "FOR", "Begin a counting loop"},
    {"NEXT", "Control Flow", "NEXT", "End of a FOR loop"},
    {"TO", "Control Flow", "TO", "Counting upper limit indicator"},
    {"STEP", "Control Flow", "STEP", "Count loop step increments"},
    {"BY", "Control Flow", "BY", "Counting step in loop (SBASIC FOR loop alias)"},
    {"WHILE", "Control Flow", "WHILE", "Begin a conditional loop"},
    {"WEND", "Control Flow", "WEND", "End of a WHILE loop"},
    {"DO", "Control Flow", "DO", "Begin a DO loop"},
    {"LOOP", "Control Flow", "LOOP", "End of a DO loop (with condition)"},
    {"UNTIL", "Control Flow", "UNTIL", "Exit condition for repeat loop"},
    {"DIM", "Variables & Memory", "DIM", "Declare an array with dimensions"},
    {"ERASE", "Variables & Memory", "ERASE", "Erase an array from memory"},
    {"OPTION", "Variables & Memory", "OPTION", "Set interpreter options"},
    {"DATA", "Variables & Memory", "DATA", "Store numeric or string data"},
    {"READ", "Variables & Memory", "READ", "Read the next DATA value"},
    {"RESTORE", "Variables & Memory", "RESTORE", "Reset DATA pointer to beginning"},
    {"DEFINT", "Variables & Memory", "DEFINT", "Declare integer variable range"},
    {"DEFSNG", "Variables & Memory", "DEFSNG", "Declare single variable range"},
    {"DEFDBL", "Variables & Memory", "DEFDBL", "Declare double variable range"},
    {"DEFSTR", "Variables & Memory", "DEFSTR", "Declare string variable range"},
    {"ON", "Control Flow", "ON", "Computed GOTO/GOSUB or error/event handler"},
    {"ERROR", "Control Flow", "ERROR", "Raise a user error"},
    {"RESUME", "Control Flow", "RESUME", "Return from an error handler"},
    {"LOAD", "Program Mgmt & Editing", "LOAD", "Load program from disk"},
    {"SAVE", "Program Mgmt & Editing", "SAVE", "Save program to disk"},
    {"MERGE", "Program Mgmt & Editing", "MERGE", "Merge program lines from disk"},
    {"COMMON", "Variables & Memory", "COMMON [SHARED] var1, var2, ...", "Declare common variables to persist across CHAIN"},
    {"CHAIN", "Program Mgmt & Editing", "CHAIN filename$", "Load and execute a new program, preserving COMMON variables"},
    {"SELFTEST", "Debug & Testing", "SELFTEST", "Run built-in interpreter tests"},
    {"ASSERT", "Debug & Testing", "ASSERT condition [, message$]", "Assert condition is true"},
    {"BREAK", "Debug & Testing", "BREAK [line] [IF cond]", "Trigger interactive breakpoint"},
    {"TRON", "Debug & Testing", "TRON", "Turn statement tracing ON"},
    {"TROFF", "Debug & Testing", "TROFF", "Turn statement tracing OFF"},
    {"TRACE", "Debug & Testing", "TRACE [ON|OFF|STEP|STACK|CALLS]", "Single-step program execution and trace call stack"},
    {"DEBUG", "Debug & Testing", "DEBUG [ON|OFF|DUMP|STACK|MEMORY|VARS]", "Master interactive debugger control and state dump"},
    {"CONT", "Debug & Testing", "CONT", "Resume program execution after BREAK or STOP"},
    {"CHECK", "Debug & Testing", "CHECK [SUMMARY|DETAILED|JSON]", "Execute static analysis on active program in memory"},
    {"VERIFY", "Debug & Testing", "VERIFY [\"filename.bas\"] [SUMMARY|DETAILED|JSON]", "Execute static analysis on file in isolated memory context"},
    {"TEST", "Debug & Testing", "TEST \"Suite Name\"", "Begin a declarative unit test suite block"},
    {"ENDTEST", "Debug & Testing", "ENDTEST", "End unit test suite block and output metrics"},
    {"BACKTRACE", "Debug & Testing", "BACKTRACE", "Display active procedure and call stack backtrace"},
    {"INFO", "System & Environ", "INFO", "Display system dashboard metrics, RAM usage, and version tag"},
    {"DUMP", "Debug & Testing", "DUMP [VARS|FILES|STACK|MEMORY]", "Dump system and debugger state snapshot"},
    {"VERSION", "System & Environ", "VERSION \"1.2.0\"", "Tag program version number in source code"},
    {"VER", "System & Environ", "VER", "Print host engine version and program version tag"},
    {"VARPTR", "Variables & Memory", "VARPTR(var)", "Return integer memory address pointer for a variable"},
    {"VARPTR$", "Variables & Memory", "VARPTR$(var)", "Return string descriptor header for a variable address"},
    {"VARS", "Debug & Testing", "VARS", "Display all active variables"},
    {"OPEN", "Input / Output", "OPEN", "Standard I/O or string formatting"},
    {"CLOSE", "File I/O", "CLOSE", "Close a file channel"},
    {"AS", "Variables & Memory", "AS", "Specify variable type or file channel alias"},
    {"FILES", "File I/O", "FILES", "File and directory management"},
    {"KILL", "System & Environ", "KILL", "Reserved for future use"},
    {"CHDIR", "File I/O", "CHDIR", "File and directory management"},
    {"MKDIR", "File I/O", "MKDIR", "File and directory management"},
    {"RMDIR", "File I/O", "RMDIR", "File and directory management"},
    {"DIR", "Uncategorized", "DIR", "No description available."},
    {"SETATTR", "Uncategorized", "SETATTR", "No description available."},
    {"LOCK", "Uncategorized", "LOCK", "No description available."},
    {"UNLOCK", "Uncategorized", "UNLOCK", "No description available."},
    {"ENVIRON", "Uncategorized", "ENVIRON", "No description available."},
    {"NAME", "File I/O", "NAME", "File and directory management"},
    {"GET", "File I/O", "GET", "Read a record from random file"},
    {"PUT", "File I/O", "PUT", "Write a record to random file"},
    {"BGET", "Uncategorized", "BGET", "No description available."},
    {"BPUT", "Uncategorized", "BPUT", "No description available."},
    {"SEEK", "File I/O", "SEEK", "Set or get file position"},
    {"FIELD", "Uncategorized", "FIELD", "No description available."},
    {"SELECT", "Control Flow", "SELECT", "Begin a SELECT CASE block"},
    {"CASE", "Control Flow", "CASE", "Case clause within SELECT CASE"},
    {"DECLARE", "Control Flow", "DECLARE", "Forward-declare a SUB or FUNCTION"},
    {"SUB", "Control Flow", "SUB", "Define a named subroutine"},
    {"FUNCTION", "Control Flow", "FUNCTION", "Define a named function"},
    {"CALL", "Control Flow", "CALL", "Call a SUB procedure"},
    {"AUTO", "Uncategorized", "AUTO", "No description available."},
    {"BCOLOR", "Uncategorized", "BCOLOR", "No description available."},
    {"FCOLOR", "Uncategorized", "FCOLOR", "No description available."},
    {"CLEAR", "Uncategorized", "CLEAR", "No description available."},
    {"CURSOR", "Uncategorized", "CURSOR", "No description available."},
    {"LOCATE", "Uncategorized", "LOCATE", "No description available."},
    {"SHARED", "Uncategorized", "SHARED", "No description available."},
    {"SCREEN", "Graphics", "SCREEN", "Set screen mode"},
    {"COLOR", "Input / Output", "COLOR", "Set text foreground/background"},
    {"LINE", "Input / Output", "LINE", "Read entire line (LINE INPUT)"},
    {"CIRCLE", "Graphics", "CIRCLE", "Draw a circle"},
    {"PSET", "Graphics", "PSET", "Set a pixel at (x,y)"},
    {"PRESET", "Graphics", "PRESET", "Reset a pixel at (x,y)"},
    {"CLS", "Input / Output", "CLS", "Clear the screen"},
    {"LSET", "Uncategorized", "LSET", "No description available."},
    {"DEFSEG", "Uncategorized", "DEFSEG", "No description available."},
    {"RSET", "Uncategorized", "RSET", "No description available."},
    {"SWAP", "Uncategorized", "SWAP", "No description available."},
    {"LOCAL", "Uncategorized", "LOCAL", "No description available."},
    {"STATIC", "Uncategorized", "STATIC", "No description available."},
    {"REDIM", "Uncategorized", "REDIM", "No description available."},
    {"PRESERVE", "Uncategorized", "PRESERVE", "No description available."},
    {"PAINT", "Graphics", "PAINT", "Flood fill an area"},
    {"BEEP", "Sound", "BEEP [count [, delay]]", "Emit speaker beep tones for count repetitions with optional delay in seconds"},
    {"SOUND", "Sound", "SOUND", "Play a tone at frequency"},
    {"PLAY", "Graphics", "PLAY", "Graphics or sound macro"},
    {"BLOAD", "Program Mgmt & Editing", "BLOAD", "Load binary memory image"},
    {"BSAVE", "Program Mgmt & Editing", "BSAVE", "Save binary memory image"},
    {"BRUN", "Program Mgmt & Editing", "BRUN", "Load and execute binary program"},
    {"USING", "Introspection", "USING", "Built-in command or function: USING"},
#if SUPPORT_EDITOR
    {"EDIT", "Program Mgmt & Editing", "EDIT", "Edit a program line"},
#endif
    {"SECURITY", "System & Environ", "SECURITY", "System operation or file query"},
    {"MODULE", "Introspection", "MODULE", "Advanced language feature"},
    {"LEVEL", "Uncategorized", "LEVEL", "No description available."},
    {"RESTRICT", "Uncategorized", "RESTRICT", "No description available."},
    {"RESET", "File I/O", "RESET", "Close all open files"},
    {"INFO", "Introspection", "INFO", "Display system information"},
    {"UNLOAD", "Program Mgmt & Editing", "UNLOAD", "Unload module or program"},
    {"TASK", "Control Flow", "TASK", "Multi-tasking thread spawn"},
    {"WAIT", "Devices & Network", "WAIT", "Wait for hardware port state"},
#if SUPPORT_MAT
    {"MAT", "Variables & Memory", "MAT", "Matrix operations"},
#endif
    {"ARRAY", "Uncategorized", "ARRAY", "No description available."},
    {"MAP", "Uncategorized", "MAP", "No description available."},
    {"FILTER", "Uncategorized", "FILTER", "No description available."},
    {"REDUCE", "Uncategorized", "REDUCE", "No description available."},
#if SUPPORT_EDITOR
    {"RENUM", "Program Mgmt & Editing", "RENUM", "Renumber program lines"},
#endif
#if SUPPORT_EDITOR
    {"DELETE", "Program Mgmt & Editing", "DELETE", "Delete program lines"},
#endif
    {"HELP", "Introspection", "HELP", "Show this help (or HELP keyword)"},
    {"CATALOG", "Introspection", "CATALOG", "List all commands & functions"},
    {"DEVICES", "Uncategorized", "DEVICES", "No description available."},
    {"IOCTL", "Devices & Network", "IOCTL", "Send control string to device"},
#if SUPPORT_NET
    {"MOUNT", "Devices & Network", "MOUNT", "Mount a VFS path"},
#endif
#if SUPPORT_NET
    {"UMOUNT", "Devices & Network", "UMOUNT", "Unmount a VFS path"},
#endif
    {"UNSAVE", "Program Mgmt & Editing", "UNSAVE", "Delete saved program (alias for KILL)"},
    {"CHVT", "Uncategorized", "CHVT", "No description available."},
#if SUPPORT_NET
    {"NET", "Uncategorized", "NET", "No description available."},
#endif
    {"OUT", "Devices & Network", "OUT", "Write to a hardware port"},
    {"POKE", "Variables & Memory", "POKE", "Write byte to virtual memory"},
#if SUPPORT_BIOS
    {"BIOS", "Devices & Network", "BIOS", "Access mock BIOS interrupt or switch memory map model (string)"},
#endif
#if SUPPORT_GEMINI
    {"GEMINI", "Input / Output", "GEMINI", "Network protocol handler"},
#endif
    {"UNLESS", "Introspection", "UNLESS", "Built-in command or function: UNLESS"},
    {"DEMAND", "Introspection", "DEMAND", "Built-in command or function: DEMAND"},
    {"TRY", "Uncategorized", "TRY", "No description available."},
    {"CATCH", "Uncategorized", "CATCH", "No description available."},
    {"THROW", "Uncategorized", "THROW", "No description available."},
    {"ALIAS", "Introspection", "ALIAS", "Advanced language feature"},
    {"METADATA", "Uncategorized", "METADATA", "No description available."},
    {"DIALECT", "System & Environ", "DIALECT", "System environment query/control"},
    {"DEFINE", "Uncategorized", "DEFINE", "No description available."},
#if SUPPORT_OOP
    {"TYPE", "Variables & Memory", "TYPE", "Define a user-defined type"},
#endif
#if SUPPORT_OOP
    {"CLASS", "Variables & Memory", "CLASS", "Define OOP Class block"},
#endif
    {"BORDER", "Uncategorized", "BORDER", "No description available."},
    {"INK", "Uncategorized", "INK", "No description available."},
    {"PAPER", "Uncategorized", "PAPER", "No description available."},
    {"PAUSE", "Uncategorized", "PAUSE", "No description available."},
    {"SYS", "Uncategorized", "SYS", "No description available."},
    {"GR", "Uncategorized", "GR", "No description available."},
    {"HGR", "Uncategorized", "HGR", "No description available."},
    {"HGR2", "Uncategorized", "HGR2", "No description available."},
    {"HCOLOR", "Uncategorized", "HCOLOR", "No description available."},
    {"PLOT", "Uncategorized", "PLOT", "No description available."},
    {"HLIN", "Uncategorized", "HLIN", "No description available."},
    {"VLIN", "Uncategorized", "VLIN", "No description available."},
    {"HPLOT", "Uncategorized", "HPLOT", "No description available."},
    {"ONERR", "Uncategorized", "ONERR", "No description available."},
    {"GRAPHICS", "Uncategorized", "GRAPHICS", "No description available."},
    {"DRAWTO", "Uncategorized", "DRAWTO", "No description available."},
    {"SYSTEM", "Uncategorized", "SYSTEM", "No description available."},
    {"SHELL", "Uncategorized", "SHELL", "No description available."},
    {"BYE", "Uncategorized", "BYE", "No description available."},
    {"STOP", "Uncategorized", "STOP", "No description available."},
    {"EXIT", "Uncategorized", "EXIT", "No description available."},
    {"PROCEDURE", "Control Flow", "PROCEDURE", "Define a named procedure (alias for SUB)"},
    {"ENDFUNC", "Control Flow", "ENDFUNC", "End a FUNCTION block"},
    {"ENDPROC", "Control Flow", "ENDPROC", "End a PROCEDURE block"},
    {"TXN", "File I/O", "TXN", "Transaction control (BEGIN, COMMIT, ROLLBACK, STATUS)"},
    {"ATOMIC", "File I/O", "ATOMIC", "Start implicit atomic transaction"},
    {"COMMIT", "File I/O", "COMMIT", "Commit active transaction"},
    {"ROLLBACK", "File I/O", "ROLLBACK", "Rollback active transaction"},
    {"AND", "Operators & Logic", "a AND b / AND(a, b [, ...])", "Bitwise or logical AND conjunction (dual infix & prefix)"},
    {"OR", "Operators & Logic", "a OR b / OR(a, b [, ...])", "Bitwise or logical OR disjunction (dual infix & prefix)"},
    {"NOT", "Operators & Logic", "NOT a / NOT(a)", "Bitwise complement or logical NOT negation (dual unary & prefix)"},
    {"XOR", "Operators & Logic", "a XOR b / XOR(a, b)", "Bitwise or logical exclusive OR (dual infix & prefix)"},
    {"IMP", "Operators & Logic", "a IMP b / IMP(a, b)", "Bitwise or logical implication (~a | b) (dual infix & prefix)"},
    {"EQV", "Operators & Logic", "a EQV b / EQV(a, b)", "Bitwise or logical equivalence (~(a ^ b)) (dual infix & prefix)"},
    {"MOD", "Operators & Logic", "a MOD b / MOD(a, b)", "Integer modulo remainder (dual infix & prefix)"},
    {"REMAINDER", "Operators & Logic", "a REMAINDER b / REMAINDER(a, b)", "Floating-point remainder a - b * floor(a / b) (dual infix & prefix)"},
    {"SHL", "Operators & Logic", "a SHL b / SHL(a, b)", "Bitwise shift left (dual infix & prefix)"},
    {"SHR", "Operators & Logic", "a SHR b / SHR(a, b)", "Bitwise shift right (dual infix & prefix)"},
    {"READBIT", "Bitwise Functions", "a READBIT b / READBIT(a, b)", "Read bit b of integer a (dual infix & prefix)"},
    {"SETBIT", "Bitwise Functions", "a SETBIT b / SETBIT(a, b)", "Set bit b of integer a (dual infix & prefix)"},
    {"RESETBIT", "Bitwise Functions", "a RESETBIT b / RESETBIT(a, b)", "Reset bit b of integer a to 0 (dual infix & prefix)"},
    {"TOGGLEBIT", "Bitwise Functions", "a TOGGLEBIT b / TOGGLEBIT(a, b)", "Invert bit b of integer a (dual infix & prefix)"},
    {"BITCOUNT", "Bitwise Functions", "BITCOUNT(a)", "Count number of set bits in integer a"},
    {"MIN", "Arithmetic / Math", "a MIN b / MIN(a, b [, ...])", "Minimum value (dual infix & prefix)"},
    {"MAX", "Arithmetic / Math", "a MAX b / MAX(a, b [, ...])", "Maximum value (dual infix & prefix)"},
    {"HYPOT", "Arithmetic / Math", "a HYPOT b / HYPOT(a, b [, ...])", "Euclidean norm sqrt(a^2 + b^2) (dual infix & prefix)"},
    {"ATAN2", "Arithmetic / Math", "y ATAN2 x / ATAN2(y, x)", "Two-argument arctangent in radians (dual infix & prefix)"},
    {"EQ", "Operators & Logic", "EQ", "Mnemonic equality operator (alias for =)"},
    {"NE", "Operators & Logic", "NE", "Mnemonic inequality operator (alias for <>)"},
    {"LT", "Operators & Logic", "LT", "Mnemonic less-than operator (alias for <)"},
    {"GT", "Operators & Logic", "GT", "Mnemonic greater-than operator (alias for >)"},
    {"LE", "Operators & Logic", "LE", "Mnemonic less-than-or-equal operator (alias for <=)"},
    {"GE", "Operators & Logic", "GE", "Mnemonic greater-than-or-equal operator (alias for >=)"},
    {"INKEY$", "Uncategorized", "INKEY$", "No description available."},
    {"PEN", "Uncategorized", "PEN", "No description available."},
    {"TIME$", "Uncategorized", "TIME$", "No description available."},
    {"DATE$", "Uncategorized", "DATE$", "No description available."},
    {"SQR", "Arithmetic / Math", "SQR", "Square root"},
    {"ABS", "Arithmetic / Math", "ABS", "Absolute value"},
    {"SIN", "Arithmetic / Math", "SIN", "Sine (radians)"},
    {"COS", "Arithmetic / Math", "COS", "Cosine (radians)"},
    {"TAN", "Arithmetic / Math", "TAN", "Tangent (radians)"},
    {"ATN", "Arithmetic / Math", "ATN", "Arctangent (returns radians)"},
    {"LOG", "Arithmetic / Math", "LOG", "Natural logarithm (base e)"},
    {"EXP", "Arithmetic / Math", "EXP", "Exponential (e^x)"},
    {"INT", "Arithmetic / Math", "INT", "Truncate to integer (math) or trigger software interrupt"},
    {"FIX", "Arithmetic / Math", "FIX", "Truncate toward zero"},
    {"DET", "Uncategorized", "DET", "No description available."},
    {"DOT", "Uncategorized", "DOT", "No description available."},
    {"CROSS", "Uncategorized", "CROSS", "No description available."},
    {"RND", "Arithmetic / Math", "RND", "Random number (0 to 1)"},
    {"RANDOMIZE", "Arithmetic / Math", "RANDOMIZE [seed] / RANDOMIZE(func_arg$)", "Seed the random number generator or generate random string/date/time values"},
    {"LEN", "String Functions", "LEN", "Length of a string"},
    {"ASC", "String Functions", "ASC", "ASCII value of first character"},
    {"CHR$", "String Functions", "CHR$", "Character from ASCII code"},
    {"CINT", "Arithmetic / Math", "CINT(x)", "Convert value to a 16-bit signed integer"},
    {"CSNG", "Arithmetic / Math", "CSNG(x)", "Convert value to single-precision float"},
    {"CDBL", "Arithmetic / Math", "CDBL(x)", "Convert value to double-precision float"},
    {"VARPTR", "Variables & Memory", "VARPTR(var)", "Get memory offset of a variable"},
    {"VARPTR$", "Variables & Memory", "VARPTR$(var)", "Get packed variable descriptor string"},
    {"VARSEG", "Variables & Memory", "VARSEG(var)", "Get memory segment of a variable"},
    {"SADD", "Variables & Memory", "SADD(var$)", "Get memory offset of a string variable's data"},
    {"VAL", "String Functions", "VAL", "Convert string to number"},
    {"STR$", "String Functions", "STR$", "Convert number to string"},
    {"LEFT$", "String Functions", "LEFT$", "Get left portion of string"},
    {"RIGHT$", "String Functions", "RIGHT$", "Get right portion of string"},
    {"MID$", "String Functions", "MID$", "Substring function"},
    {"INSTR", "Input / Output", "INSTR", "Standard I/O or string formatting"},
    {"UCASE$", "String Functions", "UCASE$", "Convert string to uppercase"},
    {"LCASE$", "String Functions", "LCASE$", "Convert string to lowercase"},
    {"LTRIM$", "String Functions", "LTRIM$", "Trim leading spaces"},
    {"RTRIM$", "String Functions", "RTRIM$", "Trim trailing spaces"},
    {"TRIM$", "String Functions", "TRIM$", "Trim leading and trailing spaces"},
    {"SPACE$", "String Functions", "SPACE$", "Create space string"},
    {"STRING$", "String Functions", "STRING$", "Create repeated character string"},
    {"SHUFFLE$", "String Functions", "SHUFFLE$(str$ [, seed])", "Return string with characters randomly scrambled via Fisher-Yates shuffle"},
    {"REPLACE$", "String Functions", "REPLACE$", "Replace substrings"},

    {"REMOVE$", "String Functions", "REMOVE$(s$, find$) or REMOVE$ var_or_arr$, find$", "Remove substrings"},
    {"REMOVE", "Variables & Memory", "REMOVE(x, val) or REMOVE var_or_arr, val", "Remove numeric values (zero out)"},
    {"UBOUND", "Variables & Memory", "UBOUND", "Array upper bound index"},
    {"LBOUND", "Variables & Memory", "LBOUND", "Array lower bound index"},
    {"EOF", "Input / Output", "EOF", "Standard I/O or string formatting"},
    {"LOF", "File I/O", "LOF", "Get length of open file"},
    {"LOC", "File I/O", "LOC", "Current file position"},
    {"HELP", "Introspection", "HELP [keyword | category]", "Show interactive help or list keywords in a category"},
    {"HELP$", "Introspection", "HELP$(keyword$)", "Return documentation text for keyword or category"},
    {"CATEGORY", "Introspection", "CATEGORY [keyword | category]", "Display all categories, show keyword category, or list category keywords"},
    {"CATEGORIES", "Introspection", "CATEGORIES [keyword | category]", "Alias for CATEGORY"},
    {"CATEGORY$", "Introspection", "CATEGORY$(keyword$)", "Return category name of specified keyword"},
    {"CATEGORIES$", "Introspection", "CATEGORIES$(keyword$)", "Alias for CATEGORY$"},
    {"CATALOG", "Introspection", "CATALOG", "Show master inventory of environment keywords and modules"},

    {"FREEFILE", "Uncategorized", "FREEFILE", "No description available."},
    {"INPUT", "Input / Output", "INPUT", "Get console input into a variable"},
    {"IOCTL", "Devices & Network", "IOCTL", "Send control string to device"},
    {"TXNSTATUS", "Uncategorized", "TXNSTATUS", "No description available."},
    {"SIOREAD$", "Uncategorized", "SIOREAD$", "No description available."},
    {"SIOREADLN$", "Uncategorized", "SIOREADLN$", "No description available."},
    {"SIOWRITE", "Uncategorized", "SIOWRITE", "No description available."},
    {"SIOSEEK", "Uncategorized", "SIOSEEK", "No description available."},
    {"SIOFLUSH", "Uncategorized", "SIOFLUSH", "No description available."},
    {"SIOSTATUS", "Uncategorized", "SIOSTATUS", "No description available."},
    {"SIOAVAIL", "Uncategorized", "SIOAVAIL", "No description available."},
    {"BIOREAD$", "Uncategorized", "BIOREAD$", "No description available."},
    {"BIOWRITE", "Uncategorized", "BIOWRITE", "No description available."},
    {"BIOCOPY", "Uncategorized", "BIOCOPY", "No description available."},
    {"BIOFILL", "Uncategorized", "BIOFILL", "No description available."},
    {"BIOSTATUS", "Uncategorized", "BIOSTATUS", "No description available."},
    {"BIOSIZE", "Uncategorized", "BIOSIZE", "No description available."},
    {"BIOCHECKSUM", "Uncategorized", "BIOCHECKSUM", "No description available."},
    {"BIOCOMPARE", "Uncategorized", "BIOCOMPARE", "No description available."},
    {"FILEATTR", "Uncategorized", "FILEATTR", "No description available."},
    {"MKI$", "Uncategorized", "MKI$", "No description available."},
    {"MKS$", "Uncategorized", "MKS$", "No description available."},
    {"MKD$", "Uncategorized", "MKD$", "No description available."},
    {"CVI", "Uncategorized", "CVI", "No description available."},
    {"CVS", "Uncategorized", "CVS", "No description available."},
    {"CVD", "Uncategorized", "CVD", "No description available."},
    {"DEVICECOUNT", "Uncategorized", "DEVICECOUNT", "No description available."},
    {"DEVICE$", "Uncategorized", "DEVICE$", "No description available."},
    {"DEVICECLASS$", "Uncategorized", "DEVICECLASS$", "No description available."},
    {"DEVICEINFO$", "Uncategorized", "DEVICEINFO$", "No description available."},
    {"POLL", "Uncategorized", "POLL", "No description available."},
#if SUPPORT_NET
    {"NSTATUS", "Input / Output", "NSTATUS", "Network socket operation"},
#endif
#if SUPPORT_NET
    {"NCONNECTED", "Input / Output", "NCONNECTED", "Network socket operation"},
#endif
#if SUPPORT_NET
    {"NHTTPSTATUS", "Input / Output", "NHTTPSTATUS", "Network socket operation"},
#endif
#if SUPPORT_NET
    {"HTTP_GET$", "Devices & Network", "HTTP_GET$", "Perform HTTP GET request"},
#endif
#if SUPPORT_BIOS
    {"MEMMAP$", "Introspection", "MEMMAP$", "Get name of currently active BIOS memory map model"},
#endif
    {"PEEK", "Variables & Memory", "PEEK", "Read byte from virtual memory"},
    {"MAP_NEW", "Uncategorized", "MAP_NEW", "No description available."},
    {"MAP_SET", "Uncategorized", "MAP_SET", "No description available."},
    {"MAP_GET", "Uncategorized", "MAP_GET", "No description available."},
    {"MAP_GET$", "Uncategorized", "MAP_GET$", "No description available."},
    {"MAP_REMOVE", "Uncategorized", "MAP_REMOVE", "No description available."},
    {"MAP_COUNT", "Uncategorized", "MAP_COUNT", "No description available."},
    {"MAP_KEY$", "Uncategorized", "MAP_KEY$", "No description available."},
    {"MAP_HAS", "Uncategorized", "MAP_HAS", "No description available."},
#if SUPPORT_JSON
    {"JSON_PARSE", "Uncategorized", "JSON_PARSE", "No description available."},
#endif
#if SUPPORT_JSON
    {"JSON_STRINGIFY$", "Uncategorized", "JSON_STRINGIFY$", "No description available."},
#endif
#if SUPPORT_XML
    {"XML_PARSE", "Uncategorized", "XML_PARSE", "No description available."},
#endif
#if SUPPORT_XML
    {"XML_STRINGIFY$", "Uncategorized", "XML_STRINGIFY$", "No description available."},
#endif
    {"YAML_PARSE", "Uncategorized", "YAML_PARSE", "No description available."},
    {"YAML_STRINGIFY$", "Uncategorized", "YAML_STRINGIFY$", "No description available."},
#if SUPPORT_INI
    {"INI_PARSE", "Uncategorized", "INI_PARSE", "No description available."},
#endif
#if SUPPORT_INI
    {"INI_STRINGIFY$", "Uncategorized", "INI_STRINGIFY$", "No description available."},
#endif
    {"DIALECT_LOAD", "Uncategorized", "DIALECT_LOAD", "No description available."},
    {"DIALECT_REGISTER", "Uncategorized", "DIALECT_REGISTER", "No description available."},
    {"DIALECT_VALIDATE", "Uncategorized", "DIALECT_VALIDATE", "No description available."},
    {"DIALECT_DOC$", "Uncategorized", "DIALECT_DOC$", "No description available."},
    {"ENVIRON$", "Uncategorized", "ENVIRON$", "No description available."},
    {"DIR$", "Uncategorized", "DIR$", "No description available."},
    {"GETATTR", "Uncategorized", "GETATTR", "No description available."},
    {"INP", "Devices & Network", "INP", "Read from a hardware port"},
    {"INITGRAPH", "BGI Graphics", "INITGRAPH mode_id", "Initialize BGI graphics mode by heritage mode ID"},
    {"CLOSEGRAPH", "BGI Graphics", "CLOSEGRAPH", "Shutdown BGI graphics and release VRAM"},
    {"PUTPIXEL", "BGI Graphics", "PUTPIXEL x, y, color", "Write a single pixel at (x, y)"},
    {"BAR", "BGI Graphics", "BAR x1, y1, x2, y2", "Draw a filled rectangle using fill color"},
    {"ELLIPSE", "BGI Graphics", "ELLIPSE cx, cy, sa, ea, rx, ry", "Draw an elliptical arc"},
    {"RECTANGLE", "BGI Graphics", "RECTANGLE x1, y1, x2, y2", "Draw an unfilled rectangle outline"},
    {"OUTTEXTXY", "BGI Graphics", "OUTTEXTXY x, y, text$", "Render text at (x, y) in graphics mode"},
    {"PALETTE", "BGI Graphics", "PALETTE index, R, G, B", "Set a palette entry (0-255) to an RGB color"},
    {"_CLIPBOARD$", "System & Environ", "_CLIPBOARD$", "Get or set the system clipboard text content"},
    {"_LOADIMAGE", "Graphics", "handle = _LOADIMAGE(filename$)", "Load image from a file, returning an image handle"},
    {"_PUTIMAGE", "Graphics", "_PUTIMAGE [x, y], handle", "Draw a loaded image handle at (x, y)"},
    {"_FREEIMAGE", "Graphics", "_FREEIMAGE handle", "Release memory allocated for an image handle"},
    {"_CREATEIMAGE", "Graphics", "handle = _CREATEIMAGE(width, height, mode)", "Create a blank memory buffer image"},
    {"_COPYIMAGE", "Graphics", "handle = _COPYIMAGE(source_handle)", "Duplicate an image handle"},
    {"_WIDTH", "Graphics", "w = _WIDTH(handle)", "Get width of an image handle or screen"},
    {"_HEIGHT", "Graphics", "h = _HEIGHT(handle)", "Get height of an image handle or screen"},
    {"_DEFLATE$", "String Functions", "comp$ = _DEFLATE$(data$)", "Compress a string using LZ77 deflation"},
    {"_INFLATE$", "String Functions", "decomp$ = _INFLATE$(comp$)", "Decompress an LZ77-compressed string"},
    {"_STATESAVE", "System & Environ", "_STATESAVE filename$", "Serialize and save the current VM execution state to a binary file"},
    {"_STATELOAD", "System & Environ", "_STATELOAD filename$", "Restore the VM execution state from a saved binary file"},
    {"BEEP", "Sound", "BEEP [count [, delay]]", "Emits standard 800 Hz speaker beep tones for count repetitions with optional delay in seconds (default 1 beep, 1.0s delay)"},
    {"SOUND", "Sound", "SOUND freq, duration", "Generates a pure audio tone of specified frequency in Hz for duration in clock ticks"},
    {"PLAY", "Sound", "PLAY mml$", "Plays musical melodies and sound effects using Music Macro Language (MML) strings"},
    {"VOICE", "Sound", "VOICE [channel,] note, duration [, wave]", "Emit multi-voice synthesizer tone on specified channel"},
    {"NOISE", "Sound", "NOISE [channel,] type, duration", "Generate white or periodic noise effects"},
    {"_SNDPLAY", "Sound", "handle = _SNDPLAY(filename$)", "Load and play an audio sound file asynchronously"},
    {"_SNDLOOP", "Sound", "_SNDLOOP handle", "Loop playback of a loaded audio sound file"},
    {"_SNDSTOP", "Sound", "_SNDSTOP handle", "Stop playback of a loaded audio sound file"},
    {"_SNDPAUSE", "Sound", "_SNDPAUSE handle", "Pause playback of a loaded audio sound file"},
    {"_SNDVOL", "Sound", "_SNDVOL handle, volume", "Set playback volume level (0-100) for a sound handle"},
    {"sound.tone", "Sound", "sound.tone freq, dur", "Emit a tone at specified frequency and duration"},
    {"music.play", "Sound", "music.play mml$", "Queue and play MML format music string"},
    {"mouse.x", "Devices & Network", "x = mouse.x", "Query current mouse X coordinate"},
    {"mouse.y", "Devices & Network", "y = mouse.y", "Query current mouse Y coordinate"},
    {"mouse.button", "Devices & Network", "b = mouse.button(btn)", "Query if a mouse button is pressed"},
    {"mouse.wheel", "Devices & Network", "w = mouse.wheel", "Query mouse wheel delta"},
    {"mouse.hide", "Devices & Network", "mouse.hide", "Hide system mouse cursor"},
    {"mouse.show", "Devices & Network", "mouse.show", "Show system mouse cursor"},
    {"window.title", "Graphics", "window.title text$", "Set main application window title"},
    {"window.move", "Graphics", "window.move x, y", "Reposition main window on desktop"},
    {"window.fullscreen", "Graphics", "window.fullscreen", "Toggle window fullscreen mode"},
    {"window.resizable", "Graphics", "window.resizable flag", "Set if main window is user resizable"},
    {"EXISTS", "File I/O", "EXISTS(filename$)", "Check if a file exists, returns -1 if true and 0 if false"},
    {"FILESIZE", "File I/O", "FILESIZE(filename$)", "Get the size of a file in bytes"},
    {"FILEMOD$", "File I/O", "FILEMOD$(filename$)", "Get the modification timestamp of a file (YYYY-MM-DD HH:MM:SS)"},
    {"PWD", "File I/O", "PWD", "Print the current working directory path to console"},
    {"BASEDIR$", "File I/O", "BASEDIR$", "Get the parent directory path of the current working directory"},
    {"BASENAME$", "File I/O", "BASENAME$", "Get the current working directory name (basename)"},
    {"BASEPATH$", "File I/O", "BASEPATH$", "Get the full current working directory path"},
    {"HOSTNAME", "System & Environ", "HOSTNAME", "Print system network hostname to console"},
    {"HOSTNAME$", "System & Environ", "HOSTNAME$", "Get system network hostname"},
    {"USERNAME", "System & Environ", "USERNAME", "Print current user name to console"},
    {"USERNAME$", "System & Environ", "USERNAME$", "Get current user name"},
    {"PATH$", "File I/O", "PATH$ / PATH$(category$)", "Get or set virtual filesystem search paths"},
    {"ERR$", "System & Environ", "ERR$([code])", "Get the string representation of an error code, or the last error message if code is omitted"},
    {"HEX$", "String Functions", "HEX$(n)", "Convert number to hexadecimal string"},
    {"OCT$", "String Functions", "OCT$(n)", "Convert number to octal string"},
    {"BIN$", "String Functions", "BIN$(n)", "Convert number to binary string"},
    {"EDIT$", "String Functions", "EDIT$(s$, mask)", "Perform mask-based string modifications (VAX compatible)"},
    {"NUM$", "String Functions", "NUM$(n)", "Convert number to string with leading space if positive"},
    {"TI", "System & Environ", "TI", "Get numeric local time as HHMMSS"},
    {"TI$", "System & Environ", "TI$", "Get string local time as HH:MM:SS (24-hour format)"},
    {"TIME", "System & Environ", "TIME", "Get numeric local time as HHMMSS"},
    {"TIME$", "System & Environ", "TIME$", "Get string local time as HH:MM:SS A/P (12-hour format)"},
    {"DATE", "System & Environ", "DATE", "Get numeric local date as YYYYMMDD"},
    {"DATE$", "System & Environ", "DATE$", "Get string local date as DD-MM-YYYY"},
    {"DAY", "System & Environ", "DAY", "Get numeric local day of the month (1-31)"},
    {"DAY$", "System & Environ", "DAY$", "Get local day of the week abbreviated in uppercase (SUN-SAT)"},
    {"MONTH", "System & Environ", "MONTH", "Get numeric local month of the year (1-12)"},
    {"MONTH$", "System & Environ", "MONTH$", "Get local month of the year abbreviated in uppercase (JAN-DEC)"},
    {"YEAR", "System & Environ", "YEAR", "Get numeric local year"},
    {"HOURS", "System & Environ", "HOURS", "Get numeric UTC hour (0-23)"},
    {"MINUTES", "System & Environ", "MINUTES", "Get numeric UTC minute (0-59)"},
    {"SECONDS", "System & Environ", "SECONDS", "Get numeric UTC second (0-59)"},
    {"CLOCK$", "System & Environ", "CLOCK$", "Get current date and time string in YYYY-MM-DD HH:MM:SS format"},
    {"CLOCK", "System & Environ", "CLOCK", "Get current numeric local date and time in YYYYMMDDhhmmss format"},
    {"PI", "Math & Trigonometry", "PI", "Mathematical constant Pi (3.141592653589793)"},
    {"TZ", "System & Environ", "TZ", "Get numeric timezone offset (formatted as +/-HHMM)"},
    {"TZ$", "System & Environ", "TZ$", "Get local timezone abbreviation"},
    {"TIMEZONE$", "System & Environ", "TIMEZONE$", "Get full timezone name string"},
    {"UTC", "System & Environ", "UTC", "Get numeric timezone offset from UTC in seconds"},
    {"JIFFIES", "System & Environ", "JIFFIES([mode$])", "Get uptime ticks based on frequency multiplier (NTSC/PAL/SECAM)"},
    {"TRUE", "System & Environ", "TRUE", "Boolean constant (1.0)"},
    {"FALSE", "System & Environ", "FALSE", "Boolean constant (-1.0)"},
    {"ALARM", "System & Environ", "[SET] ALARM[(n)] [ON|OFF|STOP|PAUSE|SNOOZE [m]|UNSET]", "Query countdown or control its state"},
    {"ALARM$", "System & Environ", "[SET] ALARM$[(time)] [ON|OFF|STOP|PAUSE|SNOOZE [m]|UNSET]", "Query daily alarm or control its state"},
    {"SET", "System & Environ", "SET ALARM(...) <modifier>", "Configure and activate/snooze/unset alarms"},
    {"MOUSE", "Input / Output", "MOUSE ON|OFF | MOUSE x, y, char, attr", "Show/hide mouse or set position and custom cursor style"},
    {"HMOUSE", "Input / Output", "HMOUSE x | x = HMOUSE", "Set or query mouse cursor horizontal column coordinate"},
    {"VMOUSE", "Input / Output", "VMOUSE y | y = VMOUSE", "Set or query mouse cursor vertical row coordinate"},
    {"TRIG", "Input / Output", "TRIG ON|OFF|STOP | state = TRIG(n)", "Query mouse button click states and trigger button trapping events"},
    {"GUID$", "System & Environ", "GUID$", "Generate a random 36-character standard UUIDv4 string"},
    {"CSRLIN", "Input / Output", "row = CSRLIN", "Get the current cursor row line number (1-indexed)"},
    {"POS", "Input / Output", "col = POS(n)", "Get the current cursor column position (1-indexed)"},
    {"LPOS", "Input / Output", "col = LPOS(n)", "Get the current printer column position (1-indexed)"},
    {"RESET", "File I/O", "RESET", "Close all open file and device channels and flush buffers"},
    {"USR", "System & Environ", "DEF USR[n] = addr | res = USR[n](arg)", "Machine code/C routine dispatch table (USR0 to USR9)"},
    {"ERDEV", "System & Environ", "code = ERDEV", "Get 16-bit hardware/INT 24h error code from last device operation"},
    {"ERDEV$", "System & Environ", "name$ = ERDEV$", "Get 8-character ASCII device driver name from last error"},
    {"EXTERR", "System & Environ", "val = EXTERR(n)", "Query extended operating system error (0=code, 1=class, 2=action, 3=locus)"},
    {"HASH$", "System & Environ", "digest$ = HASH$(algo$, data$)", "Generate MD5, SHA1, SHA256, SHA512, or CRC32 hash string"},
    {"SALT$", "System & Environ", "salted$ = SALT$(data$, salt$)", "Compute salted SHA256 password hash string"},
    {"AUDITCRACK", "Security & Audit", "match = AUDITCRACK(hash$, wordlist$ [, algo$])", "Perform dictionary attack hash auditing"},
    {"SANDBOXAUDIT", "Security & Audit", "is_sandboxed = SANDBOXAUDIT()", "Detect if execution is running inside a VM or sandbox"},
    {"VMCHECK", "Security & Audit", "is_vm = VMCHECK()", "Inspect hypervisor timing artifacts for VM detection"},
    // Phase 1 & 2: Super BASIC Complex, Statements & I/O
    {"DEFCPX", "Variables & Memory", "DEFCPX letter[-letter]", "Declare default complex variable type range"},
    {"COMPLEX", "Variables & Memory", "COMPLEX var1, var2, ...", "Explicitly declare complex variables and arrays"},
    {"CMPLX", "Math & Trigonometry", "z = CMPLX(real, imag)", "Construct a complex number value"},
    {"REAL", "Math & Trigonometry", "r = REAL(z)", "Return real component of a complex number"},
    {"IMAG", "Math & Trigonometry", "i = IMAG(z)", "Return imaginary component of a complex number"},
    {"CONJ", "Math & Trigonometry", "z2 = CONJ(z)", "Return complex conjugate of a complex number"},
    {"ARG", "Math & Trigonometry", "theta = ARG(z)", "Return phase angle (argument) of a complex number in radians"},
    {"CMPLX$", "String Functions", "s$ = CMPLX$(z)", "Format complex number as a string (e.g. 3+4I)"},
    {"CSQR", "Math & Trigonometry", "z2 = CSQR(z)", "Complex square root"},
    {"CLOG", "Math & Trigonometry", "z2 = CLOG(z)", "Complex natural logarithm"},
    {"CEXP", "Math & Trigonometry", "z2 = CEXP(z)", "Complex exponential function"},
    {"CSIN", "Math & Trigonometry", "z2 = CSIN(z)", "Complex sine function"},
    {"CCOS", "Math & Trigonometry", "z2 = CCOS(z)", "Complex cosine function"},
    {"CTAN", "Math & Trigonometry", "z2 = CTAN(z)", "Complex tangent function"},
    {"CASN", "Math & Trigonometry", "z2 = CASN(z)", "Complex inverse sine function"},
    {"CACS", "Math & Trigonometry", "z2 = CACS(z)", "Complex inverse cosine function"},
    {"CATN", "Math & Trigonometry", "z2 = CATN(z)", "Complex inverse tangent function"},
    {"MKL$", "String Functions", "s$ = MKL$(n&)", "Serialize 32-bit long integer to 4-byte IEEE little-endian string"},
    {"CVL", "Math & Trigonometry", "n& = CVL(s$)", "Deserialize 4-byte string to 32-bit long integer"},
    {"MKC$", "String Functions", "s$ = MKC$(z)", "Serialize complex number to 16-byte IEEE little-endian string pair"},
    {"CVC", "Math & Trigonometry", "z = CVC(s$)", "Deserialize 16-byte string to complex number pair"},
    {"CHANGE", "Variables & Memory", "CHANGE s$ TO arr | CHANGE arr TO s$", "Convert string to/from numeric ASCII array with length at arr(0)"},
    {"MARGIN", "Input / Output", "MARGIN [#ch,] width", "Set print line margin width for console or file channel"},
    {"ZONE", "Input / Output", "ZONE [#ch,] width", "Set comma print tab zone column width for console or file channel"},
    {"APPEND", "File I/O", "APPEND [#]channel, \"filespec\"", "Open a file channel in append mode (SDS 940 / DEC PDP-10 Super BASIC)"},
    {"MODIFY", "File I/O", "MODIFY [#]channel, \"filespec\"", "Open a file channel in read/write random access modify mode"},
    {"TEXT", "File I/O", "TEXT [#]channel, \"filespec\"", "Open a file channel in sequential text output mode"},
    {"LINPUT", "Input / Output", "LINPUT [#ch,] [\"prompt\";] var$", "Read entire line into a string without delimiters"},
    {"IMAGE", "Input / Output", "IMAGE : format_mask_list", "Declare structured line format mask for PRINT USING"},
    {"FORM", "Input / Output", "FORM format_specifier_list", "Declare structured data format specification"},
    {"FNEND", "Control Flow", "FNEND", "Mark the end of a multi-line DEF FN function block"},
    // Phase 3: SDS 940 / DEC PDP-10 Advanced Math, Trig & Matrix Functions
    {"SINH", "Math & Trigonometry", "y = SINH(x) | y = HSN(x)", "Hyperbolic sine function"},
    {"HSN", "Math & Trigonometry", "y = HSN(x) | y = SINH(x)", "Hyperbolic sine function (Super BASIC alias)"},
    {"COSH", "Math & Trigonometry", "y = COSH(x) | y = HCS(x)", "Hyperbolic cosine function"},
    {"HCS", "Math & Trigonometry", "y = HCS(x) | y = COSH(x)", "Hyperbolic cosine function (Super BASIC alias)"},
    {"TANH", "Math & Trigonometry", "y = TANH(x) | y = HTN(x)", "Hyperbolic tangent function"},
    {"HTN", "Math & Trigonometry", "y = HTN(x) | y = TANH(x)", "Hyperbolic tangent function (Super BASIC alias)"},
    {"LOG10", "Math & Trigonometry", "y = LOG10(x) | y = LGT(x)", "Base-10 common logarithm (x > 0)"},
    {"LGT", "Math & Trigonometry", "y = LGT(x) | y = LOG10(x)", "Base-10 common logarithm (Super BASIC alias)"},
    {"LOG2", "Math & Trigonometry", "y = LOG2(x)", "Base-2 binary logarithm (x > 0)"},
    {"COT", "Math & Trigonometry", "y = COT(x)", "Trigonometric cotangent of angle in radians (1 / tan(x))"},
    {"SEC", "Math & Trigonometry", "y = SEC(x)", "Trigonometric secant of angle in radians (1 / cos(x))"},
    {"CSC", "Math & Trigonometry", "y = CSC(x)", "Trigonometric cosecant of angle in radians (1 / sin(x))"},
    {"ASN", "Math & Trigonometry", "y = ASN(x) | y = ASIN(x)", "Inverse arcsine in radians for -1.0 <= x <= 1.0"},
    {"ACS", "Math & Trigonometry", "y = ACS(x) | y = ACOS(x)", "Inverse arccosine in radians for -1.0 <= x <= 1.0"},
    {"EXN", "Math & Trigonometry", "y = EXN(x) | y = EXP(x)", "Exponential function e^x (Super BASIC alias)"},
    {"RAD", "Math & Trigonometry", "r = RAD(deg)", "Convert angle in degrees to radians"},
    {"DEG", "Math & Trigonometry", "deg = DEG(rad)", "Convert angle in radians to degrees"},
    {"COMP", "Math & Trigonometry", "res = COMP(a, b)", "Compare two numbers: -1 if a < b, 0 if a == b, 1 if a > b"},
    {"PDIF", "Math & Trigonometry", "res = PDIF(a, b)", "Positive difference: a - b if a > b, else 0"},
    // Phase 6: Universal Timesharing, DEC PDP-10 & Tymshare Super BASIC
    {"EXTEND", "Control Flow", "EXTEND", "Enable extended multi-character identifiers and spaces in variable names"},
    {"SCALE", "Control Flow", "SCALE factor", "Set fixed-point rounding scale factor (DEC PDP-10 / BASIC-PLUS)"},
    {"ECHO", "Input / Output", "ECHO [ON|OFF]", "Enable terminal character echo"},
    {"ENTER", "Input / Output", "ENTER timeout_secs, var", "Timed terminal input with second timeout limit"},
    {"RECORD", "File I/O", "RECORD #ch, rec_num", "Direct access seek to record number on random file channel"},
    {"ASSIGN", "File I/O", "ASSIGN \"file\" TO #ch", "Assign file or device channel alias"},
    {"ADVANCE", "File I/O", "ADVANCE #ch, n", "Advance file read pointer forward by n bytes"},
    {"UNSAVE", "File I/O", "UNSAVE \"file\"", "Delete file from filesystem storage (Tymshare / Super BASIC)"},
    {"SCRATCH", "File I/O", "SCRATCH \"file\"", "Delete file or clear channel buffers"},
    {"PWD", "File I/O", "PWD", "Print current working directory path"},
    {"PATH", "File I/O", "PATH [\"dir\"]", "Display or set filesystem search path"},
    {"SLEEP", "Control Flow", "SLEEP [seconds]", "Suspend program execution for specified number of seconds"},
    {"PAUSE", "Control Flow", "PAUSE [prompt$]", "Pause program execution and wait for user keypress"},
    {"WAIT", "Control Flow", "WAIT port, and [, xor] | WAIT #ch, secs | WAIT secs", "Wait for I/O port, channel timeout, or second delay"},
    {"CVT$%", "String Functions", "s$ = CVT$%(n%)", "Convert 16-bit integer to 2-byte PDP-10 ASCII string"},
    {"CVT%$", "Math & Trigonometry", "n% = CVT%$(s$)", "Convert 2-byte ASCII string to 16-bit integer"},
    {"CVT$F", "String Functions", "s$ = CVT$F(f!)", "Convert single-precision float to 4-byte string representation"},
    {"CVTF$", "Math & Trigonometry", "f! = CVTF$(s$)", "Convert 4-byte string representation to single-precision float"},
    {"SWAP%", "Math & Trigonometry", "n% = SWAP%(n%)", "Byte-swap 16-bit integer value (PDP-10)"},
    {"RAD$", "String Functions", "s$ = RAD$(n&)", "Convert 32-bit integer to 6-character Radix-50 ASCII string"},
    {"NUM$", "String Functions", "s$ = NUM$(n)", "Convert number to string without leading space"},
    {"NUM1$", "String Functions", "s$ = NUM1$(n)", "Convert number to compact unformatted numeric string"},
    {"VAL%", "Math & Trigonometry", "n% = VAL%(s$)", "Parse integer value from numeric string (DEC PDP-10)"},
    {"XLATE$", "String Functions", "s$ = XLATE$(src$, table$)", "Translate string characters using translation table"},
    {"MAG", "Math & Trigonometry", "m = MAG(x, y) | m = MAG(z)", "Vector or complex number magnitude"},
    {"SYS", "System & Environ", "res = SYS(code)", "Execute system service or monitor call"},
    {"SUSPEND", "Control Flow", "SUSPEND [TIMER|KEY|COM|TASK id|EVENT name$|expr] [, timeout]", "Suspend execution until an event occurs or timeout expires"},
    {"KEY", "Event Trapping & Console", "KEY ON | KEY OFF | KEY LIST | KEY n, string$ | KEY(n) {ON|OFF|STOP}", "Enables, disables, or customizes function key softkey display and key event trapping"}
};
