/* Generated by BASIC++ Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* === Runtime Variables === */
static double bpp_vars[26];           /* A-Z */
static char bpp_strvars[26][256];     /* A$-Z$ */
static double bpp_at_array[4096];     /* @() legacy array */
static int bpp_print_width = 14;

/* === GOSUB Stack === */
#define BPP_MAX_STACK 256
static int bpp_gosub_stack[BPP_MAX_STACK];
static int bpp_gosub_sp = 0;

/* === DIM Arrays === */
#define BPP_MAX_DIM 64
#define BPP_MAX_ELEM 8192
static double bpp_dim_pool[BPP_MAX_ELEM];
static int bpp_dim_used = 0;
typedef struct { char name[32]; int d1,d2,off; } BppDim;
static BppDim bpp_dims[BPP_MAX_DIM];
static int bpp_dim_count = 0;

static void bpp_dim_alloc(const char *nm, int d1, int d2) {
    int sz = (d1+1) * (d2>0 ? d2+1 : 1);
    BppDim *d = &bpp_dims[bpp_dim_count++];
    strncpy(d->name, nm, 31); d->name[31]='\0';
    d->d1=d1; d->d2=d2; d->off=bpp_dim_used;
    memset(&bpp_dim_pool[bpp_dim_used], 0, sizeof(double)*(size_t)sz);
    bpp_dim_used += sz;
}

static double *bpp_dim_ref(const char *nm, int i1, int i2) {
    int k;
    for (k=0; k<bpp_dim_count; k++) {
        if (strcmp(bpp_dims[k].name, nm)==0) {
            int idx = (bpp_dims[k].d2>0)
                ? i1*(bpp_dims[k].d2+1)+i2 : i1;
            return &bpp_dim_pool[bpp_dims[k].off + idx];
        }
    }
    fprintf(stderr, "Array not found: %s\n", nm);
    exit(1);
    return NULL;
}

/* === String DIM arrays === */
#define BPP_MAX_STRDIM 26
#define BPP_MAX_STRDIM_SIZE 256
static struct { char nm[16]; int d1; int d2;
    char data[BPP_MAX_STRDIM_SIZE][256]; } bpp_strdims[BPP_MAX_STRDIM];
static int bpp_strdim_count = 0;

static char *bpp_strdim_ref(const char *nm, int i1, int i2) {
    int k;
    (void)i2;
    for (k = 0; k < bpp_strdim_count; k++) {
        if (strcmp(bpp_strdims[k].nm, nm) == 0) {
            if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
            return bpp_strdims[k].data[i1];
        }
    }
    /* Auto-create */
    if (bpp_strdim_count < BPP_MAX_STRDIM) {
        int j;
        strncpy(bpp_strdims[bpp_strdim_count].nm, nm, 15);
        bpp_strdims[bpp_strdim_count].nm[15] = '\0';
        for (j = 0; j < BPP_MAX_STRDIM_SIZE; j++)
            bpp_strdims[bpp_strdim_count].data[j][0] = '\0';
        bpp_strdim_count++;
        if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
        return bpp_strdims[bpp_strdim_count-1].data[i1];
    }
    fprintf(stderr, "String array not found: %s\n", nm);
    exit(1);
    return NULL;
}

/* === DATA/READ support === */
#define BPP_MAX_DATA 4096
static double bpp_data_pool[BPP_MAX_DATA];
static int bpp_data_count = 0;
static int bpp_data_ptr = 0;

static double bpp_read_num(void) {
    if (bpp_data_ptr >= bpp_data_count) {
        fprintf(stderr, "OUT OF DATA\n"); exit(1);
    }
    return bpp_data_pool[bpp_data_ptr++];
}

/* === String helpers === */
static char bpp_strtmp[8][256];
static int bpp_strtmp_idx = 0;

static char *bpp_tmp(void) {
    char *p = bpp_strtmp[bpp_strtmp_idx];
    bpp_strtmp_idx = (bpp_strtmp_idx+1) & 7;
    return p;
}

static const char *bpp_concat(const char *a, const char *b) {
    char *t = bpp_tmp();
    t[0]='\0';
    strncat(t, a, 254);
    strncat(t, b, 254-(int)strlen(t));
    return t;
}

static const char *bpp_left(const char *s, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if (n>len) n=len; if(n<0) n=0;
    memcpy(t, s, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_right(const char *s, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if (n>len) n=len; if(n<0) n=0;
    memcpy(t, s+len-n, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_mid(const char *s, int st, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if(st<0) st=0; if(st>len) st=len;
    if(n<0) n=0; if(st+n>len) n=len-st;
    memcpy(t, s+st, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_chr(int n) {
    char *t = bpp_tmp();
    t[0]=(char)n; t[1]='\0';
    return t;
}

static const char *bpp_str(double n) {
    char *t = bpp_tmp();
    sprintf(t, "%g", n);
    return t;
}

/* === TAB helper === */
static const char *bpp_tab(int col) {
    static char buf[256];
    int i;
    if (col < 0) col = 0;
    if (col > 255) col = 255;
    for (i = 0; i < col; i++) buf[i] = ' ';
    buf[col] = '\0';
    return buf;
}

/* === DEF FN support === */
#define BPP_MAX_FN 26
typedef double (*BppFnPtr)(double);
static double bpp_fn_param;

int main(void) {

  L10: /* Line 10 */
    printf("%s", bpp_tab((int)(34)));
    printf("%s", "BUG");
    printf("\n");
  L20: /* Line 20 */
    printf("%s", bpp_tab((int)(15)));
    printf("%s", "CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY");
    printf("\n");
  L30: /* Line 30 */
        printf("\n");
        printf("\n");
        printf("\n");
  L40: /* Line 40 */
    /* REM  */
  L50: /* Line 50 */
    bpp_vars[0] = 0;
    bpp_vars[1] = 0;
    bpp_vars[7] = 0;
    bpp_vars[11] = 0;
    bpp_vars[13] = 0;
    bpp_vars[15] = 0;
    bpp_vars[16] = 0;
    bpp_vars[17] = 0;
    bpp_vars[18] = 0;
    bpp_vars[19] = 0;
    bpp_vars[20] = 0;
    bpp_vars[21] = 0;
    bpp_vars[24] = 0;
  L60: /* Line 60 */
    printf("%s", "THE GAME BUG");
    printf("\n");
  L70: /* Line 70 */
    printf("%s", "I HOPE YOU ENJOY THIS GAME.");
    printf("\n");
  L80: /* Line 80 */
        printf("\n");
  L90: /* Line 90 */
    printf("%s", "DO YOU WANT INSTRUCTIONS");
  L100: /* Line 100 */
    printf("? ");
    fflush(stdout);
    { char _buf[256]; int _len;
      fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
      while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
      strncpy(bpp_strvars[25], _buf, 255); }
  L110: /* Line 110 */
    if (((strcmp(bpp_strvars[25], "NO") == 0))) { goto L300;
 }
  L120: /* Line 120 */
    printf("%s", "THE OBJECT OF BUG IS TO FINISH YOUR BUG BEFORE I FINISH");
    printf("\n");
  L130: /* Line 130 */
    printf("%s", "MINE. EACH NUMBER STANDS FOR A PART OF THE BUG BODY.");
    printf("\n");
  L140: /* Line 140 */
    printf("%s", "I WILL ROLL THE DIE FOR YOU, TELL YOU WHAT I ROLLED FOR YOU");
    printf("\n");
  L150: /* Line 150 */
    printf("%s", "WHAT THE NUMBER STANDS FOR, AND IF YOU CAN GET THE PART.");
    printf("\n");
  L160: /* Line 160 */
    printf("%s", "IF YOU CAN GET THE PART I WILL GIVE IT TO YOU.");
    printf("\n");
  L170: /* Line 170 */
    printf("%s", "THE SAME WILL HAPPEN ON MY TURN.");
    printf("\n");
  L180: /* Line 180 */
    printf("%s", "IF THERE IS A CHANGE IN EITHER BUG I WILL GIVE YOU THE");
    printf("\n");
  L190: /* Line 190 */
    printf("%s", "OPTION OF SEEING THE PICTURES OF THE BUGS.");
    printf("\n");
  L200: /* Line 200 */
    printf("%s", "THE NUMBERS STAND FOR PARTS AS FOLLOWS:");
    printf("\n");
  L210: /* Line 210 */
    printf("%s", "NUMBER");
    printf("%s", "PART");
    printf("%s", "NUMBER OF PART NEEDED");
    printf("\n");
  L220: /* Line 220 */
    printf("%s", "1");
    printf("%s", "BODY");
    printf("%s", "1");
    printf("\n");
  L230: /* Line 230 */
    printf("%s", "2");
    printf("%s", "NECK");
    printf("%s", "1");
    printf("\n");
  L240: /* Line 240 */
    printf("%s", "3");
    printf("%s", "HEAD");
    printf("%s", "1");
    printf("\n");
  L250: /* Line 250 */
    printf("%s", "4");
    printf("%s", "FEELERS");
    printf("%s", "2");
    printf("\n");
  L260: /* Line 260 */
    printf("%s", "5");
    printf("%s", "TAIL");
    printf("%s", "1");
    printf("\n");
  L270: /* Line 270 */
    printf("%s", "6");
    printf("%s", "LEGS");
    printf("%s", "6");
    printf("\n");
  L280: /* Line 280 */
        printf("\n");
  L290: /* Line 290 */
        printf("\n");
  L300: /* Line 300 */
    if ((bpp_vars[24] > 0)) { goto L2480;
 }
  L310: /* Line 310 */
    bpp_vars[25] = floor(((6 * ((double)(rand() % (int)(1)))) + 1));
  L320: /* Line 320 */
    bpp_vars[2] = 1;
  L330: /* Line 330 */
    printf("%s", "YOU ROLLED A");
    { double _v = bpp_vars[25]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("\n");
  L340: /* Line 340 */
    { int _sel = (int)(bpp_vars[25]);
        if (_sel == 1) goto L350;
        if (_sel == 2) goto L430;
        if (_sel == 3) goto L540;
        if (_sel == 4) goto L650;
        if (_sel == 5) goto L760;
        if (_sel == 6) goto L870;
    }
  L350: /* Line 350 */
    printf("%s", "1=BODY");
    printf("\n");
  L360: /* Line 360 */
    if ((bpp_vars[1] == 1)) { goto L410;
 }
  L370: /* Line 370 */
    printf("%s", "YOU NOW HAVE A BODY.");
    printf("\n");
  L380: /* Line 380 */
    bpp_vars[1] = 1;
  L390: /* Line 390 */
    bpp_vars[2] = 0;
  L400: /* Line 400 */
    goto L970;
  L410: /* Line 410 */
    printf("%s", "YOU DO NOT NEED A BODY.");
    printf("\n");
  L420: /* Line 420 */
    goto L970;
  L430: /* Line 430 */
    printf("%s", "2=NECK");
    printf("\n");
  L440: /* Line 440 */
    if ((bpp_vars[13] == 1)) { goto L500;
 }
  L450: /* Line 450 */
    if ((bpp_vars[1] == 0)) { goto L520;
 }
  L460: /* Line 460 */
    printf("%s", "YOU NOW HAVE A NECK.");
    printf("\n");
  L470: /* Line 470 */
    bpp_vars[13] = 1;
  L480: /* Line 480 */
    bpp_vars[2] = 0;
  L490: /* Line 490 */
    goto L970;
  L500: /* Line 500 */
    printf("%s", "YOU DO NOT NEED A NECK.");
    printf("\n");
  L510: /* Line 510 */
    goto L970;
  L520: /* Line 520 */
    printf("%s", "YOU DO NOT HAVE A BODY.");
    printf("\n");
  L530: /* Line 530 */
    goto L970;
  L540: /* Line 540 */
    printf("%s", "3=HEAD");
    printf("\n");
  L550: /* Line 550 */
    if ((bpp_vars[13] == 0)) { goto L610;
 }
  L560: /* Line 560 */
    if ((bpp_vars[7] == 1)) { goto L630;
 }
  L570: /* Line 570 */
    printf("%s", "YOU NEEDED A HEAD.");
    printf("\n");
  L580: /* Line 580 */
    bpp_vars[7] = 1;
  L590: /* Line 590 */
    bpp_vars[2] = 0;
  L600: /* Line 600 */
    goto L970;
  L610: /* Line 610 */
    printf("%s", "YOU DO NOT HAVE A NECK.");
    printf("\n");
  L620: /* Line 620 */
    goto L970;
  L630: /* Line 630 */
    printf("%s", "YOU HAVE A HEAD.");
    printf("\n");
  L640: /* Line 640 */
    goto L970;
  L650: /* Line 650 */
    printf("%s", "4=FEELERS");
    printf("\n");
  L660: /* Line 660 */
    if ((bpp_vars[7] == 0)) { goto L740;
 }
  L670: /* Line 670 */
    if ((bpp_vars[0] == 2)) { goto L720;
 }
  L680: /* Line 680 */
    printf("%s", "I NOW GIVE YOU A FEELER.");
    printf("\n");
  L690: /* Line 690 */
    bpp_vars[0] = (bpp_vars[0] + 1);
  L700: /* Line 700 */
    bpp_vars[2] = 0;
  L710: /* Line 710 */
    goto L970;
  L720: /* Line 720 */
    printf("%s", "YOU HAVE TWO FEELERS ALREADY.");
    printf("\n");
  L730: /* Line 730 */
    goto L970;
  L740: /* Line 740 */
    printf("%s", "YOU DO NOT HAVE A HEAD.");
    printf("\n");
  L750: /* Line 750 */
    goto L970;
  L760: /* Line 760 */
    printf("%s", "5=TAIL");
    printf("\n");
  L770: /* Line 770 */
    if ((bpp_vars[1] == 0)) { goto L830;
 }
  L780: /* Line 780 */
    if ((bpp_vars[19] == 1)) { goto L850;
 }
  L790: /* Line 790 */
    printf("%s", "I NOW GIVE YOU A TAIL.");
    printf("\n");
  L800: /* Line 800 */
    bpp_vars[19] = (bpp_vars[19] + 1);
  L810: /* Line 810 */
    bpp_vars[2] = 0;
  L820: /* Line 820 */
    goto L970;
  L830: /* Line 830 */
    printf("%s", "YOU DO NOT HAVE A BODY.");
    printf("\n");
  L840: /* Line 840 */
    goto L970;
  L850: /* Line 850 */
    printf("%s", "YOU ALREADY HAVE A TAIL.");
    printf("\n");
  L860: /* Line 860 */
    goto L970;
  L870: /* Line 870 */
    printf("%s", "6=LEG");
    printf("\n");
  L880: /* Line 880 */
    if ((bpp_vars[11] == 6)) { goto L940;
 }
  L890: /* Line 890 */
    if ((bpp_vars[1] == 0)) { goto L960;
 }
  L900: /* Line 900 */
    bpp_vars[11] = (bpp_vars[11] + 1);
  L910: /* Line 910 */
    bpp_vars[2] = 0;
  L920: /* Line 920 */
    printf("%s", "YOU NOW HAVE");
    { double _v = bpp_vars[11]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("%s", "LEGS.");
    printf("\n");
  L930: /* Line 930 */
    goto L970;
  L940: /* Line 940 */
    printf("%s", "YOU HAVE 6 FEET ALREADY.");
    printf("\n");
  L950: /* Line 950 */
    goto L970;
  L960: /* Line 960 */
    printf("%s", "YOU DO NOT HAVE A BODY.");
    printf("\n");
  L970: /* Line 970 */
    bpp_vars[23] = floor(((6 * ((double)(rand() % (int)(1)))) + 1));
  L971: /* Line 971 */
        printf("\n");
  L975: /* Line 975 */
    bpp_vars[3] = 1;
  bpp_for_0:;
    bpp_vars[3] += 1;
    if (bpp_vars[3] <= 2000) goto bpp_for_0;
  L980: /* Line 980 */
    printf("%s", "I ROLLED A");
    { double _v = bpp_vars[23]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("\n");
  L990: /* Line 990 */
    { int _sel = (int)(bpp_vars[23]);
        if (_sel == 1) goto L1000;
        if (_sel == 2) goto L1080;
        if (_sel == 3) goto L1190;
        if (_sel == 4) goto L1300;
        if (_sel == 5) goto L1410;
        if (_sel == 6) goto L1520;
    }
  L1000: /* Line 1000 */
    printf("%s", "1=BODY");
    printf("\n");
  L1010: /* Line 1010 */
    if ((bpp_vars[15] == 1)) { goto L1060;
 }
  L1020: /* Line 1020 */
    printf("%s", "I NOW HAVE A BODY.");
    printf("\n");
  L1030: /* Line 1030 */
    bpp_vars[2] = 0;
  L1040: /* Line 1040 */
    bpp_vars[15] = 1;
  L1050: /* Line 1050 */
    goto L1630;
  L1060: /* Line 1060 */
    printf("%s", "I DO NOT NEED A BODY.");
    printf("\n");
  L1070: /* Line 1070 */
    goto L1630;
  L1080: /* Line 1080 */
    printf("%s", "2=NECK");
    printf("\n");
  L1090: /* Line 1090 */
    if ((bpp_vars[16] == 1)) { goto L1150;
 }
  L1100: /* Line 1100 */
    if ((bpp_vars[15] == 0)) { goto L1170;
 }
  L1110: /* Line 1110 */
    printf("%s", "I NOW HAVE A NECK.");
    printf("\n");
  L1120: /* Line 1120 */
    bpp_vars[16] = 1;
  L1130: /* Line 1130 */
    bpp_vars[2] = 0;
  L1140: /* Line 1140 */
    goto L1630;
  L1150: /* Line 1150 */
    printf("%s", "I DO NOT NEED A NECK.");
    printf("\n");
  L1160: /* Line 1160 */
    goto L1630;
  L1170: /* Line 1170 */
    printf("%s", "I DO NOT HAVE A BODY.");
    printf("\n");
  L1180: /* Line 1180 */
    goto L1630;
  L1190: /* Line 1190 */
    printf("%s", "3=HEAD");
    printf("\n");
  L1200: /* Line 1200 */
    if ((bpp_vars[16] == 0)) { goto L1260;
 }
  L1210: /* Line 1210 */
    if ((bpp_vars[17] == 1)) { goto L1280;
 }
  L1220: /* Line 1220 */
    printf("%s", "I NEEDED A HEAD.");
    printf("\n");
  L1230: /* Line 1230 */
    bpp_vars[17] = 1;
  L1240: /* Line 1240 */
    bpp_vars[2] = 0;
  L1250: /* Line 1250 */
    goto L1630;
  L1260: /* Line 1260 */
    printf("%s", "I DO NOT HAVE A NECK.");
    printf("\n");
  L1270: /* Line 1270 */
    goto L1630;
  L1280: /* Line 1280 */
    printf("%s", "I DO NOT NEED A HEAD.");
    printf("\n");
  L1290: /* Line 1290 */
    goto L1630;
  L1300: /* Line 1300 */
    printf("%s", "4=FEELERS");
    printf("\n");
  L1310: /* Line 1310 */
    if ((bpp_vars[17] == 0)) { goto L1390;
 }
  L1320: /* Line 1320 */
    if ((bpp_vars[18] == 2)) { goto L1370;
 }
  L1330: /* Line 1330 */
    printf("%s", "I GET A FEELER.");
    printf("\n");
  L1340: /* Line 1340 */
    bpp_vars[18] = (bpp_vars[18] + 1);
  L1350: /* Line 1350 */
    bpp_vars[2] = 0;
  L1360: /* Line 1360 */
    goto L1630;
  L1370: /* Line 1370 */
    printf("%s", "I HAVE 2 FEELERS ALREADY.");
    printf("\n");
  L1380: /* Line 1380 */
    goto L1630;
  L1390: /* Line 1390 */
    printf("%s", "I DO NOT HAVE A HEAD.");
    printf("\n");
  L1400: /* Line 1400 */
    goto L1630;
  L1410: /* Line 1410 */
    printf("%s", "5=TAIL");
    printf("\n");
  L1420: /* Line 1420 */
    if ((bpp_vars[15] == 0)) { goto L1480;
 }
  L1430: /* Line 1430 */
    if ((bpp_vars[20] == 1)) { goto L1500;
 }
  L1440: /* Line 1440 */
    printf("%s", "I NOW HAVE A TAIL.");
    printf("\n");
  L1450: /* Line 1450 */
    bpp_vars[20] = 1;
  L1460: /* Line 1460 */
    bpp_vars[2] = 0;
  L1470: /* Line 1470 */
    goto L1630;
  L1480: /* Line 1480 */
    printf("%s", "I DO NOT HAVE A BODY.");
    printf("\n");
  L1490: /* Line 1490 */
    goto L1630;
  L1500: /* Line 1500 */
    printf("%s", "I DO NOT NEED A TAIL.");
    printf("\n");
  L1510: /* Line 1510 */
    goto L1630;
  L1520: /* Line 1520 */
    printf("%s", "6=LEGS");
    printf("\n");
  L1530: /* Line 1530 */
    if ((bpp_vars[21] == 6)) { goto L1590;
 }
  L1540: /* Line 1540 */
    if ((bpp_vars[15] == 0)) { goto L1610;
 }
  L1550: /* Line 1550 */
    bpp_vars[21] = (bpp_vars[21] + 1);
  L1560: /* Line 1560 */
    bpp_vars[2] = 0;
  L1570: /* Line 1570 */
    printf("%s", "I NOW HAVE");
    { double _v = bpp_vars[21]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("%s", "LEGS.");
    printf("\n");
  L1580: /* Line 1580 */
    goto L1630;
  L1590: /* Line 1590 */
    printf("%*s", bpp_print_width, "");
    printf("%s", "I HAVE 6 FEET.");
    printf("\n");
  L1600: /* Line 1600 */
    goto L1630;
  L1610: /* Line 1610 */
    printf("%s", "I DO NOT HAVE A BODY.");
    printf("\n");
  L1620: /* Line 1620 */
    goto L1630;
  L1630: /* Line 1630 */
    if ((((((((bpp_vars[0] == 2)) && ((bpp_vars[19] == 1))))) && ((bpp_vars[11] == 6))))) { goto L1650;
 }
  L1640: /* Line 1640 */
    goto L1670;
  L1650: /* Line 1650 */
    printf("%s", "YOUR BUG IS FINISHED.");
    printf("\n");
  L1660: /* Line 1660 */
    bpp_vars[24] = (bpp_vars[24] + 1);
  L1670: /* Line 1670 */
    if ((((((((bpp_vars[18] == 2)) && ((bpp_vars[15] == 1))))) && ((bpp_vars[21] == 6))))) { goto L1690;
 }
  L1680: /* Line 1680 */
    goto L1710;
  L1690: /* Line 1690 */
    printf("%s", "MY BUG IS FINISHED.");
    printf("\n");
  L1700: /* Line 1700 */
    bpp_vars[24] = (bpp_vars[24] + 2);
  L1710: /* Line 1710 */
    if ((bpp_vars[2] == 1)) { goto L300;
 }
  L1720: /* Line 1720 */
    printf("%s", "DO YOU WANT THE PICTURES");
  L1730: /* Line 1730 */
    printf("? ");
    fflush(stdout);
    { char _buf[256]; int _len;
      fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
      while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
      strncpy(bpp_strvars[25], _buf, 255); }
  L1740: /* Line 1740 */
    if (((strcmp(bpp_strvars[25], "NO") == 0))) { goto L300;
 }
  L1750: /* Line 1750 */
    printf("%s", "*****YOUR BUG*****");
    printf("\n");
  L1760: /* Line 1760 */
        printf("\n");
  L1770: /* Line 1770 */
        printf("\n");
  L1780: /* Line 1780 */
    if ((bpp_vars[0] == 0)) { goto L1860;
 }
  L1790: /* Line 1790 */
    bpp_vars[25] = 1;
  bpp_for_1:;
  L1800: /* Line 1800 */
    bpp_vars[23] = 1;
  bpp_for_2:;
  L1810: /* Line 1810 */
    printf("%s", bpp_tab((int)(10)));
  L1820: /* Line 1820 */
    printf("%s", "A ");
  L1830: /* Line 1830 */
    bpp_vars[23] += 1;
    if (bpp_vars[23] <= bpp_vars[0]) goto bpp_for_2;
  L1840: /* Line 1840 */
        printf("\n");
  L1850: /* Line 1850 */
    bpp_vars[25] += 1;
    if (bpp_vars[25] <= 4) goto bpp_for_1;
  L1860: /* Line 1860 */
    if ((bpp_vars[7] == 0)) { goto L1880;
 }
  L1870: /* Line 1870 */
    bpp_gosub_stack[bpp_gosub_sp++] = 0; goto L2470;
  bpp_ret_0:;
  L1880: /* Line 1880 */
    if ((bpp_vars[13] == 0)) { goto L1920;
 }
  L1890: /* Line 1890 */
    bpp_vars[25] = 1;
  bpp_for_3:;
  L1900: /* Line 1900 */
    printf("%s", "          N N");
    printf("\n");
  L1910: /* Line 1910 */
    bpp_vars[25] += 1;
    if (bpp_vars[25] <= 2) goto bpp_for_3;
  L1920: /* Line 1920 */
    if ((bpp_vars[1] == 0)) { goto L2000;
 }
  L1930: /* Line 1930 */
    printf("%s", "     BBBBBBBBBBBB");
    printf("\n");
  L1940: /* Line 1940 */
    bpp_vars[25] = 1;
  bpp_for_4:;
  L1950: /* Line 1950 */
    printf("%s", "     B          B");
    printf("\n");
  L1960: /* Line 1960 */
    bpp_vars[25] += 1;
    if (bpp_vars[25] <= 2) goto bpp_for_4;
  L1970: /* Line 1970 */
    if ((bpp_vars[19] != 1)) { goto L1990;
 }
  L1980: /* Line 1980 */
    printf("%s", "TTTTTB          B");
    printf("\n");
  L1990: /* Line 1990 */
    printf("%s", "     BBBBBBBBBBBB");
    printf("\n");
  L2000: /* Line 2000 */
    if ((bpp_vars[11] == 0)) { goto L2080;
 }
  L2010: /* Line 2010 */
    bpp_vars[25] = 1;
  bpp_for_5:;
  L2020: /* Line 2020 */
    printf("%s", bpp_tab((int)(5)));
  L2030: /* Line 2030 */
    bpp_vars[23] = 1;
  bpp_for_6:;
  L2040: /* Line 2040 */
    printf("%s", " L");
  L2050: /* Line 2050 */
    bpp_vars[23] += 1;
    if (bpp_vars[23] <= bpp_vars[11]) goto bpp_for_6;
  L2060: /* Line 2060 */
        printf("\n");
  L2070: /* Line 2070 */
    bpp_vars[25] += 1;
    if (bpp_vars[25] <= 2) goto bpp_for_5;
  L2080: /* Line 2080 */
    bpp_vars[25] = 1;
  bpp_for_7:;
  L2090: /* Line 2090 */
        printf("\n");
  L2100: /* Line 2100 */
    bpp_vars[25] += 1;
    if (bpp_vars[25] <= 4) goto bpp_for_7;
  L2110: /* Line 2110 */
    printf("%s", "*****MY BUG*****");
    printf("\n");
  L2120: /* Line 2120 */
        printf("\n");
  L2130: /* Line 2130 */
        printf("\n");
  L2140: /* Line 2140 */
        printf("\n");
  L2150: /* Line 2150 */
    if ((bpp_vars[18] == 0)) { goto L2230;
 }
  L2160: /* Line 2160 */
    bpp_vars[25] = 1;
  bpp_for_8:;
  L2170: /* Line 2170 */
    printf("%s", bpp_tab((int)(10)));
  L2180: /* Line 2180 */
    bpp_vars[23] = 1;
  bpp_for_9:;
  L2190: /* Line 2190 */
    printf("%s", "F ");
  L2200: /* Line 2200 */
    bpp_vars[23] += 1;
    if (bpp_vars[23] <= bpp_vars[18]) goto bpp_for_9;
  L2210: /* Line 2210 */
        printf("\n");
  L2220: /* Line 2220 */
    bpp_vars[25] += 1;
    if (bpp_vars[25] <= 4) goto bpp_for_8;
  L2230: /* Line 2230 */
    if ((bpp_vars[17] != 1)) { goto L2250;
 }
  L2240: /* Line 2240 */
    bpp_gosub_stack[bpp_gosub_sp++] = 1; goto L2470;
  bpp_ret_1:;
  L2250: /* Line 2250 */
    if ((bpp_vars[16] == 0)) { goto L2280;
 }
  L2260: /* Line 2260 */
    printf("%s", "          N N");
    printf("\n");
  L2270: /* Line 2270 */
    printf("%s", "          N N");
    printf("\n");
  L2280: /* Line 2280 */
    if ((bpp_vars[15] == 0)) { goto L2360;
 }
  L2290: /* Line 2290 */
    printf("%s", "     BBBBBBBBBBBB");
    printf("\n");
  L2300: /* Line 2300 */
    bpp_vars[25] = 1;
  bpp_for_10:;
  L2310: /* Line 2310 */
    printf("%s", "     B          B");
    printf("\n");
  L2320: /* Line 2320 */
    bpp_vars[25] += 1;
    if (bpp_vars[25] <= 2) goto bpp_for_10;
  L2330: /* Line 2330 */
    if ((bpp_vars[20] != 1)) { goto L2350;
 }
  L2340: /* Line 2340 */
    printf("%s", "TTTTTB          B");
    printf("\n");
  L2350: /* Line 2350 */
    printf("%s", "     BBBBBBBBBBBB");
    printf("\n");
  L2360: /* Line 2360 */
    if ((bpp_vars[21] == 0)) { goto L2450;
 }
  L2370: /* Line 2370 */
    bpp_vars[25] = 1;
  bpp_for_11:;
  L2380: /* Line 2380 */
    printf("%s", bpp_tab((int)(5)));
  L2390: /* Line 2390 */
    bpp_vars[23] = 1;
  bpp_for_12:;
  L2400: /* Line 2400 */
    printf("%s", " L");
  L2410: /* Line 2410 */
    bpp_vars[23] += 1;
    if (bpp_vars[23] <= bpp_vars[21]) goto bpp_for_12;
  L2420: /* Line 2420 */
        printf("\n");
  L2430: /* Line 2430 */
    bpp_vars[25] += 1;
    if (bpp_vars[25] <= 2) goto bpp_for_11;
  L2450: /* Line 2450 */
    if ((bpp_vars[24] != 0)) { goto L2540;
 }
  L2460: /* Line 2460 */
    goto L300;
  L2470: /* Line 2470 */
    printf("%s", "        HHHHHHH");
    printf("\n");
  L2480: /* Line 2480 */
    printf("%s", "        H     H");
    printf("\n");
  L2490: /* Line 2490 */
    printf("%s", "        H O O H");
    printf("\n");
  L2500: /* Line 2500 */
    printf("%s", "        H     H");
    printf("\n");
  L2510: /* Line 2510 */
    printf("%s", "        H  V  H");
    printf("\n");
  L2520: /* Line 2520 */
    printf("%s", "        HHHHHHH");
    printf("\n");
  L2530: /* Line 2530 */
    { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
      switch(_ra) {
        case 0: goto bpp_ret_0;
        case 1: goto bpp_ret_1;
        default: goto bpp_end;
      } }
  L2540: /* Line 2540 */
    printf("%s", "I HOPE YOU ENJOYED THE GAME, PLAY IT AGAIN SOON!!");
    printf("\n");
  L2550: /* Line 2550 */
    goto bpp_end;
  bpp_end:
    return 0;
}
