#ifdef _MSC_VER
#ifndef _CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
#endif
#pragma warning(disable: 4996)
#pragma warning(disable: 4101)
#pragma warning(disable: 4244)
#pragma warning(disable: 4102)
#pragma warning(disable: 4311)
#pragma warning(disable: 4312)
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wstringop-truncation"
#pragma GCC diagnostic ignored "-Wrestrict"
#pragma GCC diagnostic ignored "-Wdouble-promotion"
#pragma GCC diagnostic ignored "-Wpointer-to-int-cast"
#pragma GCC diagnostic ignored "-Wint-to-pointer-cast"
#endif

/* Generated by BASIC++ Compiler for target: windows */
#define BPP_TARGET_WINDOWS
#define BPP_SUPPORT_MULTITASKING 1
#define BPP_SUPPORT_GRAPHICS 1
#define BPP_SUPPORT_FILESYSTEM 1

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* Windows specific platform headers */
#include <windows.h>

/* === Runtime Variables === */
static double bpp_vars[1024]; /* A-Z and named */
static char bpp_strvars[1024][256]; /* A$-Z$ and named */
static double bpp_at_array[4096]; /* @() legacy array */
static int bpp_print_width = 14;

/* === GOSUB Stack === */
#define BPP_MAX_STACK 256
static int bpp_gosub_stack[BPP_MAX_STACK];
static int bpp_gosub_sp = 0;

/* === DIM Arrays === */
#define BPP_MAX_DIM 64
#define BPP_MAX_ELEM 4194304
static double bpp_dim_pool[BPP_MAX_ELEM];
static int bpp_dim_used = 0;
typedef struct { char name[32]; int d1,d2,off; } BppDim;
static BppDim bpp_dims[BPP_MAX_DIM];
static int bpp_dim_count = 0;

static void bpp_dim_alloc(const char *nm, int d1, int d2) {
 int sz = (d1+1) * (d2>0 ? d2+1 : 1);
 BppDim *d = &bpp_dims[bpp_dim_count++];
 strncpy(d->name, nm, 31); d->name[31]='\0';
 d->d1=d1; d->d2=d2; d->off=bpp_dim_used;
 memset(&bpp_dim_pool[bpp_dim_used], 0, sizeof(double)*(size_t)sz);
 bpp_dim_used += sz;
}

static double *bpp_dim_ref(const char *nm, int i1, int i2) {
 int k;
 for (k=0; k<bpp_dim_count; k++) {
 if (strcmp(bpp_dims[k].name, nm)==0) {
 int idx = (bpp_dims[k].d2>0)
 ? i1*(bpp_dims[k].d2+1)+i2 : i1;
 return &bpp_dim_pool[bpp_dims[k].off + idx];
 }
 }
 fprintf(stderr, "Array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === String DIM arrays === */
#define BPP_MAX_STRDIM 26
#define BPP_MAX_STRDIM_SIZE 256
static struct { char nm[16]; int d1; int d2;
 char data[BPP_MAX_STRDIM_SIZE][256]; } bpp_strdims[BPP_MAX_STRDIM];
static int bpp_strdim_count = 0;

static char *bpp_strdim_ref(const char *nm, int i1, int i2) {
 int k;
 (void)i2;
 for (k = 0; k < bpp_strdim_count; k++) {
 if (strcmp(bpp_strdims[k].nm, nm) == 0) {
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[k].data[i1];
 }
 }
 /* Auto-create */
 if (bpp_strdim_count < BPP_MAX_STRDIM) {
 int j;
 strncpy(bpp_strdims[bpp_strdim_count].nm, nm, 15);
 bpp_strdims[bpp_strdim_count].nm[15] = '\0';
 for (j = 0; j < BPP_MAX_STRDIM_SIZE; j++)
 bpp_strdims[bpp_strdim_count].data[j][0] = '\0';
 bpp_strdim_count++;
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[bpp_strdim_count-1].data[i1];
 }
 fprintf(stderr, "String array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === DATA/READ support === */
#define BPP_MAX_DATA 4096
static const char *bpp_data_pool[BPP_MAX_DATA];
static int bpp_data_count = 0;
static int bpp_data_ptr = 0;

static double bpp_read_num(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return atof(bpp_data_pool[bpp_data_ptr++]);
}

static const char *bpp_read_str(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return bpp_data_pool[bpp_data_ptr++];
}

/* === String helpers === */
static char bpp_strtmp[8][256];
static int bpp_strtmp_idx = 0;

static char *bpp_tmp(void) {
 char *p = bpp_strtmp[bpp_strtmp_idx];
 bpp_strtmp_idx = (bpp_strtmp_idx+1) & 7;
 return p;
}

static const char *bpp_concat(const char *a, const char *b) {
 char *t = bpp_tmp();
 t[0]='\0';
 strncat(t, a, 254);
 strncat(t, b, 254-(int)strlen(t));
 return t;
}

static const char *bpp_left(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_right(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s+len-n, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_mid(const char *s, int st, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (st<0) st=0;
 if (st>len) st=len;
 if (n<0) n=0;
 if (st+n>len) n=len-st;
 memcpy(t, s+st, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_chr(int n) {
 char *t = bpp_tmp();
 t[0]=(char)n; t[1]='\0';
 return t;
}

static const char *bpp_str(double n) {
 char *t = bpp_tmp();
 sprintf(t, "%g", n);
 return t;
}

/* === TAB helper === */
static const char *bpp_tab(int col) {
 static char buf[256];
 int i;
 if (col < 0) col = 0;
 if (col > 255) col = 255;
 for (i = 0; i < col; i++) buf[i] = ' ';
 buf[col] = '\0';
 return buf;
}

/* === DEF FN support === */
#define BPP_MAX_FN 26
typedef double (*BppFnPtr)(double);
static double bpp_fn_param;

int main(void) {
  bpp_data_pool[0] = "17";
  bpp_data_pool[1] = "8";
  bpp_data_pool[2] = "4";
  bpp_data_pool[3] = "14";
  bpp_data_pool[4] = "19";
  bpp_data_pool[5] = "3";
  bpp_data_pool[6] = "10";
  bpp_data_pool[7] = "1";
  bpp_data_pool[8] = "7";
  bpp_data_pool[9] = "11";
  bpp_data_pool[10] = "15";
  bpp_data_pool[11] = "9";
  bpp_data_pool[12] = "5";
  bpp_data_pool[13] = "20";
  bpp_data_pool[14] = "13";
  bpp_data_pool[15] = "18";
  bpp_data_pool[16] = "16";
  bpp_data_pool[17] = "2";
  bpp_data_pool[18] = "12";
  bpp_data_pool[19] = "6";
  bpp_data_pool[20] = "20";
  bpp_data_pool[21] = "2";
  bpp_data_pool[22] = "17";
  bpp_data_pool[23] = "5";
  bpp_data_pool[24] = "8";
  bpp_data_pool[25] = "18";
  bpp_data_pool[26] = "12";
  bpp_data_pool[27] = "11";
  bpp_data_pool[28] = "1";
  bpp_data_pool[29] = "4";
  bpp_data_pool[30] = "19";
  bpp_data_pool[31] = "14";
  bpp_data_pool[32] = "10";
  bpp_data_pool[33] = "7";
  bpp_data_pool[34] = "9";
  bpp_data_pool[35] = "15";
  bpp_data_pool[36] = "6";
  bpp_data_pool[37] = "13";
  bpp_data_pool[38] = "16";
  bpp_data_pool[39] = "3";
  bpp_data_pool[40] = "PITCHOUT";
  bpp_data_pool[41] = "TRIPLE REVERSE";
  bpp_data_pool[42] = "DRAW";
  bpp_data_pool[43] = "QB SNEAK";
  bpp_data_pool[44] = "END AROUND";
  bpp_data_pool[45] = "DOUBLE REVERSE";
  bpp_data_pool[46] = "LEFT SWEEP";
  bpp_data_pool[47] = "RIGHT SWEEP";
  bpp_data_pool[48] = "OFF TACKLE";
  bpp_data_pool[49] = "WISHBONE OPTION";
  bpp_data_pool[50] = "FLARE PASS";
  bpp_data_pool[51] = "SCREEN PASS";
  bpp_data_pool[52] = "ROLL OUT OPTION";
  bpp_data_pool[53] = "RIGHT CURL";
  bpp_data_pool[54] = "LEFT CURL";
  bpp_data_pool[55] = "WISHBONE OPTION";
  bpp_data_pool[56] = "SIDELINE PASS";
  bpp_data_pool[57] = "HALF-BACK OPTION";
  bpp_data_pool[58] = "RAZZLE-DAZZLE";
  bpp_data_pool[59] = "BOMB!!!!";
  bpp_data_count = 60;

 /* Line 1 */
 printf("%s", bpp_tab((int)(32)));
 printf("%s", "FOOTBALL");
 printf("\n");
 /* Line 2 */
 printf("%s", bpp_tab((int)(15)));
 printf("%s", "CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY");
 printf("\n");
 /* Line 3 */
  printf("\n");
  printf("\n");
  printf("\n");
 /* Line 100 */
 /* REM  */
 /* Line 120 */
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("A", (int)(20), 0);
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("B", (int)(20), 0);
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("C", (int)(40), 0);
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("H", (int)(2), 0);
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("T", (int)(2), 0);
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("W", (int)(2), 0);
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("X", (int)(2), 0);
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("Y", (int)(2), 0);
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("Z", (int)(2), 0);
 /* Line 130 */
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("M$", (int)(2), 0);
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("D", (int)(2), 0);
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("P$", (int)(20), 0);
 /* Line 140 */
 printf("%s", "PRESENTING N.F.U. FOOTBALL (NO FORTRAN USED)");
 printf("\n");
 /* Line 145 */
  printf("\n");
  printf("\n");
 L150: /* Line 150 */
 printf("%s", "DO YOU WANT INSTRUCTIONS");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[0], _buf, 255); }
 /* Line 160 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[0], "NO") == 0))) { /* BASIC: GOTO */
goto L290;
 }
 /* Line 165 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[0], "YES") != 0))) { /* BASIC: GOTO */
goto L150;
 }
 /* Line 170 */
 printf("%s", "THIS IS A FOOTBALL GAME FOR TWO TEAMS IN WHICH PLAYERS MUST");
 printf("\n");
 /* Line 180 */
 printf("%s", "PREPARE A TAPE WITH A DATA STATEMENT (1770 FOR TEAM 1,");
 printf("\n");
 /* Line 190 */
 printf("%s", "1780 FOR TEAM 2) IN WHICH EACH TEAM SCRAMBLES NOS. 1-20");
 printf("\n");
 /* Line 195 */
 printf("%s", "THESE NUMBERS ARE THEN ASSIGNED TO TWENTY GIVEN PLAYS.");
 printf("\n");
 /* Line 200 */
 printf("%s", "A LIST OF NOS. AND THEIR PLAYS IS PROVIDED WITH");
 printf("\n");
 /* Line 210 */
 printf("%s", "BOTH TEAMS HAVING THE SAME PLAYS. THE MORE SIMILAR THE");
 printf("\n");
 /* Line 220 */
 printf("%s", "PLAYS THE LESS YARDAGE GAINED.  SCORES ARE GIVEN");
 printf("\n");
 /* Line 223 */
 printf("%s", "WHENEVER SCORES ARE MADE. SCORES MAY ALSO BE OBTAINED");
 printf("\n");
 /* Line 225 */
 printf("%s", "BY INPUTTING 99,99 FOR PLAY NOS. TO PUNT OR ATTEMPT A");
 printf("\n");
 /* Line 227 */
 printf("%s", "FIELD GOAL, INPUT 77,77 FOR PLAY NUMBERS. QUESTIONS WILL BE");
 printf("\n");
 /* Line 230 */
 printf("%s", "ASKED THEN. ON 4TH DOWN, YOU WILL ALSO BE ASKED WHETHER");
 printf("\n");
 /* Line 240 */
 printf("%s", "YOU WANT TO PUNT OR ATTEMPT A FIELD GOAL. IF THE ANSWER TO");
 printf("\n");
 /* Line 250 */
 printf("%s", "BOTH QUESTIONS IS NO IT WILL BE ASSUMED YOU WANT TO");
 printf("\n");
 /* Line 260 */
 printf("%s", "TRY AND GAIN YARDAGE. ANSWER ALL QUESTIONS YES OR NO.");
 printf("\n");
 /* Line 270 */
 printf("%s", "THE GAME IS PLAYED UNTIL PLAYERS TERMINATE (CONTROL-C).");
 printf("\n");
 /* Line 280 */
 printf("%s", "PLEASE PREPARE A TAPE AND RUN.");
 printf("\n");
 printf("STOPPED\n"); goto bpp_end;
 L290: /* Line 290 */
  printf("\n");
 printf("%s", "PLEASE INPUT SCORE LIMIT ON GAME");
 printf("? ");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[4] = _v; }
 /* Line 300 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_0:;
 /* BASIC: READ statement */
 bpp_vars[13] = bpp_read_num();
 /* BASIC: IF statement */
 if ((bpp_vars[8] > 20)) { /* BASIC: GOTO */
goto L350;
 }
 /* Line 330 */
 *bpp_dim_ref("A", (int)(bpp_vars[13]), 0) = bpp_vars[8];
 /* BASIC: GOTO */
 goto L360;
 L350: /* Line 350 */
 *bpp_dim_ref("B", (int)(bpp_vars[13]), 0) = (bpp_vars[8] - 20);
 L360: /* Line 360 */
 *bpp_dim_ref("C", (int)(bpp_vars[8]), 0) = bpp_vars[13];
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= 40) goto bpp_for_0;
 /* Line 370 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_1:;
 /* BASIC: READ statement */
 strncpy(bpp_strvars[15], bpp_read_str(), 255);
 /* Line 380 */
 bpp_vars[11] = 0;
 bpp_vars[19] = 1;
 L410: /* Line 410 */
 printf("%s", "TEAM");
 { double _v = bpp_vars[19]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "PLAY CHART");
 printf("\n");
 /* Line 420 */
 printf("%s", "NO.      PLAY");
 printf("\n");
 /* Line 430 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_2:;
 /* Line 440 */
 /* REM  */
 /* Line 450 */
 { double _v = *bpp_dim_ref("C", (int)((bpp_vars[8] + bpp_vars[11])), 0); if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", bpp_tab((int)(6)));
 printf("%s", bpp_strdim_ref("P", (int)(bpp_vars[8]), 0));
 printf("\n");
 /* Line 460 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= 20) goto bpp_for_2;
 /* Line 630 */
 bpp_vars[11] = (bpp_vars[11] + 20);
 bpp_vars[19] = 2;
 /* Line 640 */
  printf("\n");
 /* Line 650 */
 printf("%s", "TEAR OFF HERE----------------------------------------------");
 printf("\n");
 /* Line 660 */
 /* BASIC: FOR loop initialization */
 bpp_vars[23] = 1;
 bpp_for_3:;
  printf("\n");
 /* BASIC: NEXT loop step */
 bpp_vars[23] += 1;
 if (bpp_vars[23] <= 11) goto bpp_for_3;
 /* Line 670 */
 /* BASIC: FOR loop initialization */
 bpp_vars[25] = 1;
 bpp_for_4:;
 /* BASIC: NEXT loop step */
 bpp_vars[25] += 1;
 if (bpp_vars[25] <= 3000) goto bpp_for_4;
 /* Line 680 */
 /* BASIC: IF statement */
 if ((bpp_vars[11] == 20)) { /* BASIC: GOTO */
goto L410;
 }
 /* Line 690 */
 *bpp_dim_ref("D", (int)(1), 0) = 0;
 *bpp_dim_ref("D", (int)(2), 0) = 3;
 strncpy(bpp_strdim_ref("M", (int)(1), 0), "--->", 255);
 strncpy(bpp_strdim_ref("M", (int)(2), 0), "<---", 255);
 /* Line 700 */
 *bpp_dim_ref("H", (int)(1), 0) = 0;
 *bpp_dim_ref("H", (int)(2), 0) = 0;
 *bpp_dim_ref("T", (int)(1), 0) = 2;
 *bpp_dim_ref("T", (int)(2), 0) = 1;
 /* Line 710 */
 *bpp_dim_ref("W", (int)(1), 0) = (-(1));
 *bpp_dim_ref("W", (int)(2), 0) = 1;
 *bpp_dim_ref("X", (int)(1), 0) = 100;
 *bpp_dim_ref("X", (int)(2), 0) = 0;
 /* Line 720 */
 *bpp_dim_ref("Y", (int)(1), 0) = 1;
 *bpp_dim_ref("Y", (int)(2), 0) = (-(1));
 *bpp_dim_ref("Z", (int)(1), 0) = 0;
 *bpp_dim_ref("Z", (int)(2), 0) = 100;
 /* Line 725 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 0; goto L1910;
 bpp_ret_0:;
 /* Line 730 */
 printf("%s", "TEAM 1 DEFENDS 0 YD GOAL -- TEAM 2 DEFENDS 100 YD GOAL.");
 printf("\n");
 /* Line 740 */
 bpp_vars[19] = floor(((2 * ((double)(rand() % (int)(1)))) + 1));
 /* Line 760 */
  printf("\n");
 printf("%s", "THE COIN IS FLIPPED");
 printf("\n");
 L765: /* Line 765 */
 bpp_vars[15] = (*bpp_dim_ref("X", (int)(bpp_vars[19]), 0) - (*bpp_dim_ref("Y", (int)(bpp_vars[19]), 0) * 40));
 /* Line 770 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 1; goto L1860;
 bpp_ret_1:;
  printf("\n");
 printf("%s", "TEAM");
 { double _v = bpp_vars[19]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "RECEIVES KICK-OFF");
 printf("\n");
 /* Line 780 */
 bpp_vars[10] = floor(((26 * ((double)(rand() % (int)(1)))) + 40));
 L790: /* Line 790 */
 bpp_vars[15] = (bpp_vars[15] - (*bpp_dim_ref("Y", (int)(bpp_vars[19]), 0) * bpp_vars[10]));
 L794: /* Line 794 */
 /* BASIC: IF statement */
 if (((*bpp_dim_ref("W", (int)(bpp_vars[19]), 0) * bpp_vars[15]) < (*bpp_dim_ref("Z", (int)(bpp_vars[19]), 0) + 10))) { /* BASIC: GOTO */
goto L810;
 }
 /* Line 795 */
  printf("\n");
 printf("%s", "BALL WENT OUT OF ENDZONE --AUTOMATIC TOUCHBACK--");
 printf("\n");
 /* Line 796 */
 /* BASIC: GOTO */
 goto L870;
 L810: /* Line 810 */
 printf("%s", "BALL WENT");
 { double _v = bpp_vars[10]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "YARDS.  NOW ON");
 { double _v = bpp_vars[15]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("\n");
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 2; goto L1900;
 bpp_ret_2:;
 L830: /* Line 830 */
 printf("%s", "TEAM");
 { double _v = bpp_vars[19]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "DO YOU WANT TO RUNBACK");
 printf("? ");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[0], _buf, 255); }
 /* Line 840 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[0], "YES") == 0))) { /* BASIC: GOTO */
goto L1430;
 }
 /* Line 845 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[0], "NO") != 0))) { /* BASIC: GOTO */
goto L830;
 }
 /* Line 850 */
 /* BASIC: IF statement */
 if (((*bpp_dim_ref("W", (int)(bpp_vars[19]), 0) * bpp_vars[15]) < *bpp_dim_ref("Z", (int)(bpp_vars[19]), 0))) { /* BASIC: GOTO */
goto L880;
 }
 L870: /* Line 870 */
 bpp_vars[15] = (*bpp_dim_ref("Z", (int)(bpp_vars[19]), 0) - (*bpp_dim_ref("W", (int)(bpp_vars[19]), 0) * 20));
 L880: /* Line 880 */
 bpp_vars[3] = 1;
 bpp_vars[18] = bpp_vars[15];
 L885: /* Line 885 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_5:;
 printf("%s", "=");
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= 72) goto bpp_for_5;
 /* Line 890 */
  printf("\n");
 printf("%s", "TEAM");
 { double _v = bpp_vars[19]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "DOWN");
 { double _v = bpp_vars[3]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "ON");
 { double _v = bpp_vars[15]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("\n");
 /* Line 893 */
 /* BASIC: IF statement */
 if ((bpp_vars[3] != 1)) { /* BASIC: GOTO */
goto L900;
 }
 /* Line 895 */
 /* BASIC: IF statement */
 if (((*bpp_dim_ref("Y", (int)(bpp_vars[19]), 0) * (bpp_vars[15] + (*bpp_dim_ref("Y", (int)(bpp_vars[19]), 0) * 10))) >= *bpp_dim_ref("X", (int)(bpp_vars[19]), 0))) { /* BASIC: GOTO */
goto L898;
 }
 /* Line 897 */
 bpp_vars[2] = 4;
 /* BASIC: GOTO */
 goto L900;
 L898: /* Line 898 */
 bpp_vars[2] = 8;
 L900: /* Line 900 */
 /* BASIC: IF statement */
 if ((bpp_vars[2] == 8)) { /* BASIC: GOTO */
goto L904;
 }
 /* Line 901 */
 printf("%s", bpp_tab((int)(27)));
 { double _v = (10 - ((*bpp_dim_ref("Y", (int)(bpp_vars[19]), 0) * bpp_vars[15]) - (*bpp_dim_ref("Y", (int)(bpp_vars[19]), 0) * bpp_vars[18]))); if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "YARDS TO 1ST DOWN");
 printf("\n");
 /* Line 902 */
 /* BASIC: GOTO */
 goto L910;
 L904: /* Line 904 */
 printf("%s", bpp_tab((int)(27)));
 { double _v = (*bpp_dim_ref("X", (int)(bpp_vars[19]), 0) - (*bpp_dim_ref("Y", (int)(bpp_vars[19]), 0) * bpp_vars[15])); if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "YARDS");
 printf("\n");
 L910: /* Line 910 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 3; goto L1900;
 bpp_ret_3:;
 /* BASIC: IF statement */
 if ((bpp_vars[3] == 4)) { /* BASIC: GOTO */
goto L1180;
 }
 L920: /* Line 920 */
 /* REM  */
 /* Line 930 */
 bpp_vars[20] = floor(((3 * ((double)(rand() % (int)(0)))) - 1));
 /* BASIC: GOTO */
 goto L940;
 L936: /* Line 936 */
 printf("%s", "ILLEGAL PLAY NUMBER, CHECK AND");
 printf("\n");
 L940: /* Line 940 */
 printf("%s", "INPUT OFFENSIVE PLAY, DEFENSIVE PLAY");
 /* Line 950 */
 /* BASIC: IF statement */
 if ((bpp_vars[19] == 2)) { /* BASIC: GOTO */
goto L970;
 }
 /* Line 960 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[26] = _v; }
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[27] = _v; }
 /* BASIC: GOTO */
 goto L975;
 L970: /* Line 970 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[27] = _v; }
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[26] = _v; }
 L975: /* Line 975 */
 /* BASIC: IF statement */
 if ((bpp_vars[26] == 77)) { /* BASIC: GOTO */
goto L1180;
 }
 /* Line 980 */
 /* BASIC: IF statement */
 if ((bpp_vars[26] > 20)) { /* BASIC: GOTO */
goto L1800;
 }
 /* Line 985 */
 /* BASIC: IF statement */
 if ((bpp_vars[26] < 1)) { /* BASIC: GOTO */
goto L1800;
 }
 /* Line 990 */
 /* BASIC: IF statement */
 if ((bpp_vars[27] > 20)) { /* BASIC: GOTO */
goto L1800;
 }
 /* Line 992 */
 /* BASIC: IF statement */
 if ((bpp_vars[27] < 1)) { /* BASIC: GOTO */
goto L1800;
 }
 /* Line 995 */
 bpp_vars[26] = floor(bpp_vars[26]);
 bpp_vars[27] = floor(bpp_vars[27]);
 /* Line 1000 */
 bpp_vars[24] = floor(((fabs((*bpp_dim_ref("A", (int)(bpp_vars[26]), 0) - *bpp_dim_ref("B", (int)(bpp_vars[27]), 0))) / 19) * ((((*bpp_dim_ref("X", (int)(bpp_vars[19]), 0) - (*bpp_dim_ref("Y", (int)(bpp_vars[19]), 0) * bpp_vars[15])) + 25) * ((double)(rand() % (int)(1)))) - 15)));
 /* Line 1005 */
  printf("\n");
 /* BASIC: IF statement */
 if ((bpp_vars[19] == 2)) { /* BASIC: GOTO */
goto L1015;
 }
 /* Line 1010 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("A", (int)(bpp_vars[26]), 0) < 11)) { /* BASIC: GOTO */
goto L1048;
 }
 /* Line 1012 */
 /* BASIC: GOTO */
 goto L1020;
 L1015: /* Line 1015 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("B", (int)(bpp_vars[27]), 0) < 11)) { /* BASIC: GOTO */
goto L1048;
 }
 L1020: /* Line 1020 */
 /* BASIC: IF statement */
 if ((bpp_vars[20] != 0)) { /* BASIC: GOTO */
goto L1035;
 }
 /* Line 1025 */
 printf("%s", "PASS INCOMPLETE TEAM");
 { double _v = bpp_vars[19]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("\n");
 /* Line 1030 */
 bpp_vars[24] = 0;
 /* BASIC: GOTO */
 goto L1050;
 L1035: /* Line 1035 */
 bpp_vars[6] = ((double)(rand() % (int)(1)));
 /* BASIC: IF statement */
 if ((bpp_vars[6] > 0.025000000000000001)) { /* BASIC: GOTO */
goto L1040;
 }
 /* Line 1037 */
 /* BASIC: IF statement */
 if ((bpp_vars[24] > 2)) { /* BASIC: GOTO */
goto L1045;
 }
 L1040: /* Line 1040 */
 printf("%s", "QUARTERBACK SCRAMBLED");
 printf("\n");
 /* BASIC: GOTO */
 goto L1050;
 L1045: /* Line 1045 */
 printf("%s", "PASS COMPLETED");
 printf("\n");
 /* BASIC: GOTO */
 goto L1050;
 L1048: /* Line 1048 */
 printf("%s", "THE BALL WAS RUN");
 printf("\n");
 L1050: /* Line 1050 */
 bpp_vars[15] = (bpp_vars[15] - (*bpp_dim_ref("W", (int)(bpp_vars[19]), 0) * bpp_vars[24]));
 /* Line 1060 */
  printf("\n");
 printf("%s", "NET YARDS GAINED ON DOWN");
 { double _v = bpp_vars[3]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "ARE ");
 { double _v = bpp_vars[24]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("\n");
 /* Line 1070 */
 bpp_vars[6] = ((double)(rand() % (int)(1)));
 /* BASIC: IF statement */
 if ((bpp_vars[6] > 0.025000000000000001)) { /* BASIC: GOTO */
goto L1110;
 }
 L1080: /* Line 1080 */
  printf("\n");
 printf("%s", "** LOSS OF POSSESSION FROM TEAM");
 { double _v = bpp_vars[19]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "TO TEAM");
 { double _v = *bpp_dim_ref("T", (int)(bpp_vars[19]), 0); if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("\n");
 /* Line 1100 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 4; goto L1850;
 bpp_ret_4:;
  printf("\n");
 bpp_vars[19] = *bpp_dim_ref("T", (int)(bpp_vars[19]), 0);
 /* BASIC: GOTO */
 goto L830;
 L1110: /* Line 1110 */
 /* BASIC: IF statement */
 if (((*bpp_dim_ref("Y", (int)(bpp_vars[19]), 0) * bpp_vars[15]) >= *bpp_dim_ref("X", (int)(bpp_vars[19]), 0))) { /* BASIC: GOTO */
goto L1320;
 }
 /* Line 1120 */
 /* BASIC: IF statement */
 if (((*bpp_dim_ref("W", (int)(bpp_vars[19]), 0) * bpp_vars[15]) >= *bpp_dim_ref("Z", (int)(bpp_vars[19]), 0))) { /* BASIC: GOTO */
goto L1230;
 }
 /* Line 1130 */
 /* BASIC: IF statement */
 if ((((*bpp_dim_ref("Y", (int)(bpp_vars[19]), 0) * bpp_vars[15]) - (*bpp_dim_ref("Y", (int)(bpp_vars[19]), 0) * bpp_vars[18])) >= 10)) { /* BASIC: GOTO */
goto L880;
 }
 /* Line 1140 */
 bpp_vars[3] = (bpp_vars[3] + 1);
 /* BASIC: IF statement */
 if ((bpp_vars[3] != 5)) { /* BASIC: GOTO */
goto L885;
 }
 /* Line 1160 */
  printf("\n");
 printf("%s", "CONVERSION UNSUCCESSFUL TEAM");
 { double _v = bpp_vars[19]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("\n");
 bpp_vars[19] = *bpp_dim_ref("T", (int)(bpp_vars[19]), 0);
 /* Line 1170 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 5; goto L1850;
 bpp_ret_5:;
 /* BASIC: GOTO */
 goto L880;
 L1180: /* Line 1180 */
 printf("%s", "DOES TEAM");
 { double _v = bpp_vars[19]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "WANT TO PUNT");
 printf("? ");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[0], _buf, 255); }
 /* Line 1185 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[0], "NO") == 0))) { /* BASIC: GOTO */
goto L1200;
 }
 /* Line 1187 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[0], "YES") != 0))) { /* BASIC: GOTO */
goto L1180;
 }
 L1190: /* Line 1190 */
  printf("\n");
 printf("%s", "TEAM");
 { double _v = bpp_vars[19]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "WILL PUNT");
 printf("\n");
 bpp_vars[6] = ((double)(rand() % (int)(1)));
 /* BASIC: IF statement */
 if ((bpp_vars[6] < 0.025000000000000001)) { /* BASIC: GOTO */
goto L1080;
 }
 /* Line 1195 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 6; goto L1850;
 bpp_ret_6:;
 bpp_vars[10] = floor(((25 * ((double)(rand() % (int)(1)))) + 35));
 bpp_vars[19] = *bpp_dim_ref("T", (int)(bpp_vars[19]), 0);
 /* BASIC: GOTO */
 goto L790;
 L1200: /* Line 1200 */
 printf("%s", "DOES TEAM");
 { double _v = bpp_vars[19]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "WANT TO ATTEMPT A FIELD GOAL");
 printf("? ");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[0], _buf, 255); }
 /* Line 1210 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[0], "YES") == 0))) { /* BASIC: GOTO */
goto L1640;
 }
 /* Line 1215 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[0], "NO") != 0))) { /* BASIC: GOTO */
goto L1200;
 }
 /* Line 1217 */
 /* BASIC: GOTO */
 goto L920;
 L1230: /* Line 1230 */
  printf("\n");
 printf("%s", "SAFETY AGAINST TEAM");
 { double _v = bpp_vars[19]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "**********************OH-OH");
 printf("\n");
 /* Line 1240 */
 *bpp_dim_ref("H", (int)(*bpp_dim_ref("T", (int)(bpp_vars[19]), 0)), 0) = (*bpp_dim_ref("H", (int)(*bpp_dim_ref("T", (int)(bpp_vars[19]), 0)), 0) + 2);
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 7; goto L1810;
 bpp_ret_7:;
 /* Line 1280 */
 printf("%s", "TEAM");
 { double _v = bpp_vars[19]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "DO YOU WANT TO PUNT INSTEAD OF A KICKOFF");
 printf("? ");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[0], _buf, 255); }
 /* Line 1290 */
 bpp_vars[15] = (*bpp_dim_ref("Z", (int)(bpp_vars[19]), 0) - (*bpp_dim_ref("W", (int)(bpp_vars[19]), 0) * 20));
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[0], "YES") == 0))) { /* BASIC: GOTO */
goto L1190;
 }
 L1320: /* Line 1320 */
  printf("\n");
 printf("%s", "TOUCHDOWN BY TEAM");
 { double _v = bpp_vars[19]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "*********************YEA TEAM");
 printf("\n");
 /* Line 1340 */
 bpp_vars[16] = 7;
 bpp_vars[6] = ((double)(rand() % (int)(1)));
 /* BASIC: IF statement */
 if ((bpp_vars[6] > 0.10000000000000001)) { /* BASIC: GOTO */
goto L1380;
 }
 /* Line 1360 */
 bpp_vars[16] = 6;
 printf("%s", "EXTRA POINT NO GOOD");
 printf("\n");
 /* BASIC: GOTO */
 goto L1390;
 L1380: /* Line 1380 */
 printf("%s", "EXTRA POINT GOOD");
 printf("\n");
 L1390: /* Line 1390 */
 *bpp_dim_ref("H", (int)(bpp_vars[19]), 0) = (*bpp_dim_ref("H", (int)(bpp_vars[19]), 0) + bpp_vars[16]);
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 8; goto L1810;
 bpp_ret_8:;
 /* Line 1420 */
 bpp_vars[19] = *bpp_dim_ref("T", (int)(bpp_vars[19]), 0);
 /* BASIC: GOTO */
 goto L765;
 L1430: /* Line 1430 */
 bpp_vars[10] = floor(((9 * ((double)(rand() % (int)(0)))) + 1));
 /* Line 1440 */
 bpp_vars[17] = floor((((((*bpp_dim_ref("X", (int)(bpp_vars[19]), 0) - (*bpp_dim_ref("Y", (int)(bpp_vars[19]), 0) * bpp_vars[15])) + 25) * ((double)(rand() % (int)(1)))) - 15) / bpp_vars[10]));
 /* Line 1460 */
 bpp_vars[15] = (bpp_vars[15] - (*bpp_dim_ref("W", (int)(bpp_vars[19]), 0) * bpp_vars[17]));
 /* Line 1480 */
  printf("\n");
 printf("%s", "RUNBACK TEAM");
 { double _v = bpp_vars[19]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 { double _v = bpp_vars[17]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "YARDS");
 printf("\n");
 /* Line 1485 */
 bpp_vars[6] = ((double)(rand() % (int)(1)));
 /* BASIC: IF statement */
 if ((bpp_vars[6] < 0.025000000000000001)) { /* BASIC: GOTO */
goto L1080;
 }
 /* Line 1490 */
 /* BASIC: IF statement */
 if (((*bpp_dim_ref("Y", (int)(bpp_vars[19]), 0) * bpp_vars[15]) >= *bpp_dim_ref("X", (int)(bpp_vars[19]), 0))) { /* BASIC: GOTO */
goto L1320;
 }
 /* Line 1500 */
 /* BASIC: IF statement */
 if (((*bpp_dim_ref("W", (int)(bpp_vars[19]), 0) * bpp_vars[15]) >= *bpp_dim_ref("Z", (int)(bpp_vars[19]), 0))) { /* BASIC: GOTO */
goto L1230;
 }
 /* Line 1510 */
 /* BASIC: GOTO */
 goto L880;
 L1640: /* Line 1640 */
  printf("\n");
 printf("%s", "TEAM");
 { double _v = bpp_vars[19]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "WILL ATTEMPT A FIELD GOAL");
 printf("\n");
 /* Line 1645 */
 bpp_vars[6] = ((double)(rand() % (int)(1)));
 /* BASIC: IF statement */
 if ((bpp_vars[6] < 0.025000000000000001)) { /* BASIC: GOTO */
goto L1080;
 }
 /* Line 1650 */
 bpp_vars[5] = floor(((35 * ((double)(rand() % (int)(1)))) + 20));
 /* Line 1660 */
  printf("\n");
 printf("%s", "KICK IS");
 { double _v = bpp_vars[5]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "YARDS LONG");
 printf("\n");
 /* Line 1680 */
 bpp_vars[15] = (bpp_vars[15] - (*bpp_dim_ref("W", (int)(bpp_vars[19]), 0) * bpp_vars[5]));
 bpp_vars[6] = ((double)(rand() % (int)(1)));
 /* Line 1690 */
 /* BASIC: IF statement */
 if ((bpp_vars[6] < 0.34999999999999998)) { /* BASIC: GOTO */
goto L1735;
 }
 /* Line 1700 */
 /* BASIC: IF statement */
 if (((*bpp_dim_ref("Y", (int)(bpp_vars[19]), 0) * bpp_vars[15]) < *bpp_dim_ref("X", (int)(bpp_vars[19]), 0))) { /* BASIC: GOTO */
goto L1740;
 }
 /* Line 1710 */
 printf("%s", "FIELD GOAL GOOD FOR TEAM");
 { double _v = bpp_vars[19]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "*********************YEA");
 printf("\n");
 /* Line 1720 */
 bpp_vars[16] = 3;
 /* BASIC: GOTO */
 goto L1390;
 L1735: /* Line 1735 */
 printf("%s", "BALL WENT WIDE");
 printf("\n");
 L1740: /* Line 1740 */
 printf("%s", "FIELD GOAL UNSUCCESFUL TEAM");
 { double _v = bpp_vars[19]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "-----------------TOO BAD");
 printf("\n");
 /* Line 1742 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 9; goto L1850;
 bpp_ret_9:;
 /* BASIC: IF statement */
 if (((*bpp_dim_ref("Y", (int)(bpp_vars[19]), 0) * bpp_vars[15]) < (*bpp_dim_ref("X", (int)(bpp_vars[19]), 0) + 10))) { /* BASIC: GOTO */
goto L1745;
 }
 /* Line 1744 */
 bpp_vars[19] = *bpp_dim_ref("T", (int)(bpp_vars[19]), 0);
 /* BASIC: GOTO */
 goto L794;
 L1745: /* Line 1745 */
  printf("\n");
 printf("%s", "BALL NOW ON");
 { double _v = bpp_vars[15]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("\n");
 /* Line 1750 */
 bpp_vars[19] = *bpp_dim_ref("T", (int)(bpp_vars[19]), 0);
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 10; goto L1900;
 bpp_ret_10:;
 /* BASIC: GOTO */
 goto L830;
 /* Line 1770 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 1780 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 1790 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 1792 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 1794 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 1796 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 1798 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 L1800: /* Line 1800 */
 /* BASIC: IF statement */
 if ((bpp_vars[26] != 99)) { /* BASIC: GOTO */
goto L936;
 }
 L1810: /* Line 1810 */
  printf("\n");
 printf("%s", "TEAM 1 SCORE IS");
 { double _v = *bpp_dim_ref("H", (int)(1), 0); if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("\n");
 /* Line 1820 */
 printf("%s", "TEAM 2 SCORE IS");
 { double _v = *bpp_dim_ref("H", (int)(2), 0); if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("\n");
  printf("\n");
 /* Line 1825 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("H", (int)(bpp_vars[19]), 0) < bpp_vars[4])) { /* BASIC: GOTO */
goto L1830;
 }
 /* Line 1827 */
 printf("%s", "TEAM");
 { double _v = bpp_vars[19]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "WINS*******************");
 printf("\n");
 /* BASIC: GOTO */
 goto L2000;
 L1830: /* Line 1830 */
 /* BASIC: IF statement */
 if ((bpp_vars[26] == 99)) { /* BASIC: GOTO */
goto L940;
 }
 /* Line 1835 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 default: goto bpp_end;
 } }
 L1850: /* Line 1850 */
  printf("\n");
 L1860: /* Line 1860 */
 /* BASIC: FOR loop initialization */
 bpp_vars[23] = 1;
 bpp_for_6:;
 printf("%s", "+");
 /* BASIC: NEXT loop step */
 bpp_vars[23] += 1;
 if (bpp_vars[23] <= 72) goto bpp_for_6;
  printf("\n");
 /* Line 1870 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 default: goto bpp_end;
 } }
 L1900: /* Line 1900 */
 printf("%s", bpp_tab((int)(((*bpp_dim_ref("D", (int)(bpp_vars[19]), 0) + 5) + (bpp_vars[15] / 2)))));
 printf("%s", bpp_strdim_ref("M", (int)(bpp_vars[19]), 0));
 printf("\n");
 L1910: /* Line 1910 */
 printf("%s", "TEAM 1 [0   10   20   30   40   50   60   70   80   90");
 /* Line 1915 */
 printf("%s", "   100] TEAM 2");
 printf("\n");
 /* Line 1920 */
  printf("\n");
 /* Line 1930 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 default: goto bpp_end;
 } }
 L2000: /* Line 2000 */
 goto bpp_end;
 bpp_end:
 return 0;
}
