#ifdef _MSC_VER
#ifndef _CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
#endif
#pragma warning(disable: 4996)
#pragma warning(disable: 4101)
#pragma warning(disable: 4244)
#pragma warning(disable: 4102)
#pragma warning(disable: 4311)
#pragma warning(disable: 4312)
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wstringop-truncation"
#pragma GCC diagnostic ignored "-Wrestrict"
#pragma GCC diagnostic ignored "-Wdouble-promotion"
#pragma GCC diagnostic ignored "-Wpointer-to-int-cast"
#pragma GCC diagnostic ignored "-Wint-to-pointer-cast"
#endif

/* Generated by BASIC++ Compiler for target: windows */
#define BPP_TARGET_WINDOWS
#define BPP_SUPPORT_MULTITASKING 1
#define BPP_SUPPORT_GRAPHICS 1
#define BPP_SUPPORT_FILESYSTEM 1

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* Windows specific platform headers */
#include <windows.h>

/* === Runtime Variables === */
static double bpp_vars[1024]; /* A-Z and named */
static char bpp_strvars[1024][256]; /* A$-Z$ and named */
static double bpp_at_array[4096]; /* @() legacy array */
static int bpp_print_width = 14;

/* === GOSUB Stack === */
#define BPP_MAX_STACK 256
static int bpp_gosub_stack[BPP_MAX_STACK];
static int bpp_gosub_sp = 0;

/* === DIM Arrays === */
#define BPP_MAX_DIM 64
#define BPP_MAX_ELEM 4194304
static double bpp_dim_pool[BPP_MAX_ELEM];
static int bpp_dim_used = 0;
typedef struct { char name[32]; int d1,d2,off; } BppDim;
static BppDim bpp_dims[BPP_MAX_DIM];
static int bpp_dim_count = 0;

static void bpp_dim_alloc(const char *nm, int d1, int d2) {
 int sz = (d1+1) * (d2>0 ? d2+1 : 1);
 BppDim *d = &bpp_dims[bpp_dim_count++];
 strncpy(d->name, nm, 31); d->name[31]='\0';
 d->d1=d1; d->d2=d2; d->off=bpp_dim_used;
 memset(&bpp_dim_pool[bpp_dim_used], 0, sizeof(double)*(size_t)sz);
 bpp_dim_used += sz;
}

static double *bpp_dim_ref(const char *nm, int i1, int i2) {
 int k;
 for (k=0; k<bpp_dim_count; k++) {
 if (strcmp(bpp_dims[k].name, nm)==0) {
 int idx = (bpp_dims[k].d2>0)
 ? i1*(bpp_dims[k].d2+1)+i2 : i1;
 return &bpp_dim_pool[bpp_dims[k].off + idx];
 }
 }
 fprintf(stderr, "Array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === String DIM arrays === */
#define BPP_MAX_STRDIM 26
#define BPP_MAX_STRDIM_SIZE 256
static struct { char nm[16]; int d1; int d2;
 char data[BPP_MAX_STRDIM_SIZE][256]; } bpp_strdims[BPP_MAX_STRDIM];
static int bpp_strdim_count = 0;

static char *bpp_strdim_ref(const char *nm, int i1, int i2) {
 int k;
 (void)i2;
 for (k = 0; k < bpp_strdim_count; k++) {
 if (strcmp(bpp_strdims[k].nm, nm) == 0) {
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[k].data[i1];
 }
 }
 /* Auto-create */
 if (bpp_strdim_count < BPP_MAX_STRDIM) {
 int j;
 strncpy(bpp_strdims[bpp_strdim_count].nm, nm, 15);
 bpp_strdims[bpp_strdim_count].nm[15] = '\0';
 for (j = 0; j < BPP_MAX_STRDIM_SIZE; j++)
 bpp_strdims[bpp_strdim_count].data[j][0] = '\0';
 bpp_strdim_count++;
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[bpp_strdim_count-1].data[i1];
 }
 fprintf(stderr, "String array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === DATA/READ support === */
#define BPP_MAX_DATA 4096
static const char *bpp_data_pool[BPP_MAX_DATA];
static int bpp_data_count = 0;
static int bpp_data_ptr = 0;

static double bpp_read_num(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return atof(bpp_data_pool[bpp_data_ptr++]);
}

static const char *bpp_read_str(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return bpp_data_pool[bpp_data_ptr++];
}

/* === String helpers === */
static char bpp_strtmp[8][256];
static int bpp_strtmp_idx = 0;

static char *bpp_tmp(void) {
 char *p = bpp_strtmp[bpp_strtmp_idx];
 bpp_strtmp_idx = (bpp_strtmp_idx+1) & 7;
 return p;
}

static const char *bpp_concat(const char *a, const char *b) {
 char *t = bpp_tmp();
 t[0]='\0';
 strncat(t, a, 254);
 strncat(t, b, 254-(int)strlen(t));
 return t;
}

static const char *bpp_left(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_right(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s+len-n, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_mid(const char *s, int st, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (st<0) st=0;
 if (st>len) st=len;
 if (n<0) n=0;
 if (st+n>len) n=len-st;
 memcpy(t, s+st, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_chr(int n) {
 char *t = bpp_tmp();
 t[0]=(char)n; t[1]='\0';
 return t;
}

static const char *bpp_str(double n) {
 char *t = bpp_tmp();
 sprintf(t, "%g", n);
 return t;
}

/* === TAB helper === */
static const char *bpp_tab(int col) {
 static char buf[256];
 int i;
 if (col < 0) col = 0;
 if (col > 255) col = 255;
 for (i = 0; i < col; i++) buf[i] = ' ';
 buf[col] = '\0';
 return buf;
}

/* === DEF FN support === */
#define BPP_MAX_FN 26
typedef double (*BppFnPtr)(double);
static double bpp_fn_param;

int main(void) {
  bpp_data_count = 0;

 /* Line 1 */
 printf("%s", bpp_tab((int)(28)));
 printf("%s", "GAME OF EVEN WINS");
 printf("\n");
 /* Line 2 */
 printf("%s", bpp_tab((int)(15)));
 printf("%s", "CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY");
 printf("\n");
 /* Line 3 */
  printf("\n");
  printf("\n");
 /* Line 4 */
 printf("%s", "DO YOU WANT INSTRUCTIONS (YES OR NO)");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[0], _buf, 255); }
  printf("\n");
 /* Line 5 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[0], "NO") == 0))) { /* BASIC: GOTO */
goto L20;
 }
 /* Line 6 */
 printf("%s", "THE GAME IS PLAYED AS FOLLOWS:");
 printf("\n");
  printf("\n");
 /* Line 7 */
 printf("%s", "AT THE BEGINNING OF THE GAME, A RANDOM NUMBER OF CHIPS ARE");
 printf("\n");
 /* Line 8 */
 printf("%s", "PLACED ON THE BOARD.  THE NUMBER OF CHIPS ALWAYS STARTS");
 printf("\n");
 /* Line 9 */
 printf("%s", "AS AN ODD NUMBER.  ON EACH TURN, A PLAYER MUST TAKE ONE,");
 printf("\n");
 /* Line 10 */
 printf("%s", "TWO, THREE, OR FOUR CHIPS.  THE WINNER IS THE PLAYER WHO");
 printf("\n");
 /* Line 11 */
 printf("%s", "FINISHES WITH A TOTAL NUMBER OF CHIPS THAT IS EVEN.");
 printf("\n");
 /* Line 12 */
 printf("%s", "THE COMPUTER STARTS OUT KNOWING ONLY THE RULES OF THE");
 printf("\n");
 /* Line 13 */
 printf("%s", "GAME.  IT GRADUALLY LEARNS TO PLAY WELL.  IT SHOULD BE");
 printf("\n");
 /* Line 14 */
 printf("%s", "DIFFICULT TO BEAT THE COMPUTER AFTER TWENTY GAMES IN A ROW.");
 printf("\n");
 /* Line 15 */
 printf("%s", "TRY IT!!!!");
 printf("\n");
  printf("\n");
 /* Line 16 */
 printf("%s", "TO QUIT AT ANY TIME, TYPE A '0' AS YOUR MOVE.");
 printf("\n");
  printf("\n");
 L20: /* Line 20 */
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("R", (int)(1), (int)(5));
 /* Line 25 */
 bpp_vars[11] = 0;
 bpp_vars[1] = 0;
 /* Line 30 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 0;
 bpp_for_0:;
 /* Line 40 */
 *bpp_dim_ref("R", (int)(1), (int)(bpp_vars[8])) = 4;
 /* Line 50 */
 *bpp_dim_ref("R", (int)(0), (int)(bpp_vars[8])) = 4;
 /* Line 60 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= 5) goto bpp_for_0;
 L70: /* Line 70 */
 bpp_vars[0] = 0;
 bpp_vars[1] = 0;
 /* Line 90 */
 bpp_vars[15] = ((floor((((13 * ((double)(rand() % (int)(1)))) + 9) / 2)) * 2) + 1);
 L100: /* Line 100 */
 /* BASIC: IF statement */
 if ((bpp_vars[15] == 1)) { /* BASIC: GOTO */
goto L530;
 }
 /* Line 110 */
 printf("%s", "THERE ARE");
 { double _v = bpp_vars[15]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "CHIPS ON THE BOARD.");
 printf("\n");
 L120: /* Line 120 */
 bpp_vars[26] = bpp_vars[4];
 /* Line 130 */
 bpp_vars[27] = bpp_vars[11];
 /* Line 140 */
 bpp_vars[4] = (((bpp_vars[0] / 2) - floor((bpp_vars[0] / 2))) * 2);
 /* Line 150 */
 bpp_vars[11] = floor(((((bpp_vars[15] / 6) - floor((bpp_vars[15] / 6))) * 6) + 0.5));
 /* Line 160 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("R", (int)(bpp_vars[4]), (int)(bpp_vars[11])) >= bpp_vars[15])) { /* BASIC: GOTO */
goto L320;
 }
 /* Line 170 */
 bpp_vars[12] = *bpp_dim_ref("R", (int)(bpp_vars[4]), (int)(bpp_vars[11]));
 /* Line 180 */
 /* BASIC: IF statement */
 if ((bpp_vars[12] <= 0)) { /* BASIC: GOTO */
goto L370;
 }
 /* Line 190 */
 bpp_vars[15] = (bpp_vars[15] - bpp_vars[12]);
 /* Line 200 */
 /* BASIC: IF statement */
 if ((bpp_vars[12] == 1)) { /* BASIC: GOTO */
goto L510;
 }
 /* Line 210 */
 printf("%s", "COMPUTER TAKES");
 { double _v = bpp_vars[12]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "CHIPS LEAVING");
 { double _v = bpp_vars[15]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "... YOUR MOVE");
 L220: /* Line 220 */
 bpp_vars[1] = (bpp_vars[1] + bpp_vars[12]);
 L230: /* Line 230 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[12] = _v; }
 /* Line 240 */
 bpp_vars[12] = floor(bpp_vars[12]);
 /* Line 250 */
 /* BASIC: IF statement */
 if ((bpp_vars[12] < 1)) { /* BASIC: GOTO */
goto L450;
 }
 /* Line 260 */
 /* BASIC: IF statement */
 if ((bpp_vars[12] > 4)) { /* BASIC: GOTO */
goto L460;
 }
 /* Line 270 */
 /* BASIC: IF statement */
 if ((bpp_vars[12] > bpp_vars[15])) { /* BASIC: GOTO */
goto L460;
 }
 /* Line 280 */
 /* BASIC: IF statement */
 if ((bpp_vars[12] == bpp_vars[15])) { /* BASIC: GOTO */
goto L360;
 }
 /* Line 290 */
 bpp_vars[15] = (bpp_vars[15] - bpp_vars[12]);
 /* Line 300 */
 bpp_vars[0] = (bpp_vars[0] + bpp_vars[12]);
 /* Line 310 */
 /* BASIC: GOTO */
 goto L100;
 L320: /* Line 320 */
 /* BASIC: IF statement */
 if ((bpp_vars[15] == 1)) { /* BASIC: GOTO */
goto L550;
 }
 /* Line 330 */
 printf("%s", "COMPUTER TAKES");
 { double _v = bpp_vars[15]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "CHIPS.");
 printf("\n");
 L340: /* Line 340 */
 *bpp_dim_ref("R", (int)(bpp_vars[4]), (int)(bpp_vars[11])) = bpp_vars[15];
 /* Line 350 */
 bpp_vars[1] = (bpp_vars[1] + bpp_vars[15]);
 L360: /* Line 360 */
 /* BASIC: IF statement */
 if (((bpp_vars[1] / 2) == floor((bpp_vars[1] / 2)))) { /* BASIC: GOTO */
goto L420;
 }
 L370: /* Line 370 */
 printf("%s", "GAME OVER ... YOU WIN!!!");
 printf("\n");
  printf("\n");
 /* Line 390 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("R", (int)(bpp_vars[4]), (int)(bpp_vars[11])) == 1)) { /* BASIC: GOTO */
goto L480;
 }
 /* Line 400 */
 *bpp_dim_ref("R", (int)(bpp_vars[4]), (int)(bpp_vars[11])) = (*bpp_dim_ref("R", (int)(bpp_vars[4]), (int)(bpp_vars[11])) - 1);
 /* Line 410 */
 /* BASIC: GOTO */
 goto L70;
 L420: /* Line 420 */
 printf("%s", "GAME OVER ... I WIN!!!");
 printf("\n");
  printf("\n");
 /* Line 430 */
 /* BASIC: GOTO */
 goto L70;
 L450: /* Line 450 */
 /* BASIC: IF statement */
 if ((bpp_vars[12] == 0)) { /* BASIC: GOTO */
goto L570;
 }
 L460: /* Line 460 */
 { double _v = bpp_vars[12]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "IS AN ILLEGAL MOVE ... YOUR MOVE");
 /* Line 470 */
 /* BASIC: GOTO */
 goto L230;
 L480: /* Line 480 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("R", (int)(bpp_vars[26]), (int)(bpp_vars[27])) == 1)) { /* BASIC: GOTO */
goto L70;
 }
 /* Line 490 */
 *bpp_dim_ref("R", (int)(bpp_vars[26]), (int)(bpp_vars[27])) = (*bpp_dim_ref("R", (int)(bpp_vars[26]), (int)(bpp_vars[27])) - 1);
 /* Line 500 */
 /* BASIC: GOTO */
 goto L70;
 L510: /* Line 510 */
 printf("%s", "COMPUTER TAKES 1 CHIP LEAVING");
 { double _v = bpp_vars[15]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "... YOUR MOVE");
 /* Line 520 */
 /* BASIC: GOTO */
 goto L220;
 L530: /* Line 530 */
 printf("%s", "THERE IS 1 CHIP ON THE BOARD.");
 printf("\n");
 /* Line 540 */
 /* BASIC: GOTO */
 goto L120;
 L550: /* Line 550 */
 printf("%s", "COMPUTER TAKES 1 CHIP.");
 printf("\n");
 /* Line 560 */
 /* BASIC: GOTO */
 goto L340;
 L570: /* Line 570 */
 goto bpp_end;
 bpp_end:
 return 0;
}
