#ifdef _MSC_VER
#ifndef _CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
#endif
#pragma warning(disable: 4996)
#pragma warning(disable: 4101)
#pragma warning(disable: 4244)
#pragma warning(disable: 4102)
#pragma warning(disable: 4311)
#pragma warning(disable: 4312)
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wstringop-truncation"
#pragma GCC diagnostic ignored "-Wrestrict"
#pragma GCC diagnostic ignored "-Wdouble-promotion"
#pragma GCC diagnostic ignored "-Wpointer-to-int-cast"
#pragma GCC diagnostic ignored "-Wint-to-pointer-cast"
#endif

/* Generated by BASIC++ Compiler for target: windows */
#define BPP_TARGET_WINDOWS
#define BPP_SUPPORT_MULTITASKING 1
#define BPP_SUPPORT_GRAPHICS 1
#define BPP_SUPPORT_FILESYSTEM 1

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* Windows specific platform headers */
#include <windows.h>

/* === Runtime Variables === */
static double bpp_vars[1024]; /* A-Z and named */
static char bpp_strvars[1024][256]; /* A$-Z$ and named */
static double bpp_at_array[4096]; /* @() legacy array */
static int bpp_print_width = 14;

/* === GOSUB Stack === */
#define BPP_MAX_STACK 256
static int bpp_gosub_stack[BPP_MAX_STACK];
static int bpp_gosub_sp = 0;

/* === DIM Arrays === */
#define BPP_MAX_DIM 64
#define BPP_MAX_ELEM 4194304
static double bpp_dim_pool[BPP_MAX_ELEM];
static int bpp_dim_used = 0;
typedef struct { char name[32]; int d1,d2,off; } BppDim;
static BppDim bpp_dims[BPP_MAX_DIM];
static int bpp_dim_count = 0;

static void bpp_dim_alloc(const char *nm, int d1, int d2) {
 int sz = (d1+1) * (d2>0 ? d2+1 : 1);
 BppDim *d = &bpp_dims[bpp_dim_count++];
 strncpy(d->name, nm, 31); d->name[31]='\0';
 d->d1=d1; d->d2=d2; d->off=bpp_dim_used;
 memset(&bpp_dim_pool[bpp_dim_used], 0, sizeof(double)*(size_t)sz);
 bpp_dim_used += sz;
}

static double *bpp_dim_ref(const char *nm, int i1, int i2) {
 int k;
 for (k=0; k<bpp_dim_count; k++) {
 if (strcmp(bpp_dims[k].name, nm)==0) {
 int idx = (bpp_dims[k].d2>0)
 ? i1*(bpp_dims[k].d2+1)+i2 : i1;
 return &bpp_dim_pool[bpp_dims[k].off + idx];
 }
 }
 fprintf(stderr, "Array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === String DIM arrays === */
#define BPP_MAX_STRDIM 26
#define BPP_MAX_STRDIM_SIZE 256
static struct { char nm[16]; int d1; int d2;
 char data[BPP_MAX_STRDIM_SIZE][256]; } bpp_strdims[BPP_MAX_STRDIM];
static int bpp_strdim_count = 0;

static char *bpp_strdim_ref(const char *nm, int i1, int i2) {
 int k;
 (void)i2;
 for (k = 0; k < bpp_strdim_count; k++) {
 if (strcmp(bpp_strdims[k].nm, nm) == 0) {
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[k].data[i1];
 }
 }
 /* Auto-create */
 if (bpp_strdim_count < BPP_MAX_STRDIM) {
 int j;
 strncpy(bpp_strdims[bpp_strdim_count].nm, nm, 15);
 bpp_strdims[bpp_strdim_count].nm[15] = '\0';
 for (j = 0; j < BPP_MAX_STRDIM_SIZE; j++)
 bpp_strdims[bpp_strdim_count].data[j][0] = '\0';
 bpp_strdim_count++;
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[bpp_strdim_count-1].data[i1];
 }
 fprintf(stderr, "String array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === DATA/READ support === */
#define BPP_MAX_DATA 4096
static const char *bpp_data_pool[BPP_MAX_DATA];
static int bpp_data_count = 0;
static int bpp_data_ptr = 0;

static double bpp_read_num(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return atof(bpp_data_pool[bpp_data_ptr++]);
}

static const char *bpp_read_str(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return bpp_data_pool[bpp_data_ptr++];
}

/* === String helpers === */
static char bpp_strtmp[8][256];
static int bpp_strtmp_idx = 0;

static char *bpp_tmp(void) {
 char *p = bpp_strtmp[bpp_strtmp_idx];
 bpp_strtmp_idx = (bpp_strtmp_idx+1) & 7;
 return p;
}

static const char *bpp_concat(const char *a, const char *b) {
 char *t = bpp_tmp();
 t[0]='\0';
 strncat(t, a, 254);
 strncat(t, b, 254-(int)strlen(t));
 return t;
}

static const char *bpp_left(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_right(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s+len-n, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_mid(const char *s, int st, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (st<0) st=0;
 if (st>len) st=len;
 if (n<0) n=0;
 if (st+n>len) n=len-st;
 memcpy(t, s+st, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_chr(int n) {
 char *t = bpp_tmp();
 t[0]=(char)n; t[1]='\0';
 return t;
}

static const char *bpp_str(double n) {
 char *t = bpp_tmp();
 sprintf(t, "%g", n);
 return t;
}

/* === TAB helper === */
static const char *bpp_tab(int col) {
 static char buf[256];
 int i;
 if (col < 0) col = 0;
 if (col > 255) col = 255;
 for (i = 0; i < col; i++) buf[i] = ' ';
 buf[col] = '\0';
 return buf;
}

/* === DEF FN support === */
#define BPP_MAX_FN 26
typedef double (*BppFnPtr)(double);
static double bpp_fn_param;

int main(void) {
  bpp_data_count = 0;

 /* Line 10 */
 printf("%s", bpp_tab((int)(32)));
 printf("%s", "HAMURABI");
 printf("\n");
 /* Line 20 */
 printf("%s", bpp_tab((int)(15)));
 printf("%s", "CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY");
 printf("\n");
 /* Line 30 */
  printf("\n");
  printf("\n");
  printf("\n");
 /* Line 80 */
 printf("%s", "TRY YOUR HAND AT GOVERNING ANCIENT SUMERIA");
 printf("\n");
 /* Line 90 */
 printf("%s", "FOR A TEN-YEAR TERM OF OFFICE.");
 printf("\n");
  printf("\n");
 /* Line 95 */
 bpp_vars[26] = 0;
 bpp_vars[27] = 0;
 /* Line 100 */
 bpp_vars[25] = 0;
 bpp_vars[15] = 95;
 bpp_vars[18] = 2800;
 bpp_vars[7] = 3000;
 bpp_vars[4] = (bpp_vars[7] - bpp_vars[18]);
 /* Line 110 */
 bpp_vars[24] = 3;
 bpp_vars[0] = (bpp_vars[7] / bpp_vars[24]);
 bpp_vars[8] = 5;
 bpp_vars[16] = 1;
 L210: /* Line 210 */
 bpp_vars[3] = 0;
 L215: /* Line 215 */
  printf("\n");
  printf("\n");
 printf("%s", "HAMURABI:  I BEG TO REPORT TO YOU,");
 printf("\n");
 bpp_vars[25] = (bpp_vars[25] + 1);
 /* Line 217 */
 printf("%s", "IN YEAR");
 { double _v = bpp_vars[25]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", ",");
 { double _v = bpp_vars[3]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "PEOPLE STARVED,");
 { double _v = bpp_vars[8]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "CAME TO THE CITY,");
 printf("\n");
 /* Line 218 */
 bpp_vars[15] = (bpp_vars[15] + bpp_vars[8]);
 /* Line 227 */
 /* BASIC: IF statement */
 if ((bpp_vars[16] > 0)) { /* BASIC: GOTO */
goto L230;
 }
 /* Line 228 */
 bpp_vars[15] = floor((bpp_vars[15] / 2));
 /* Line 229 */
 printf("%s", "A HORRIBLE PLAGUE STRUCK!  HALF THE PEOPLE DIED.");
 printf("\n");
 L230: /* Line 230 */
 printf("%s", "POPULATION IS NOW");
 { double _v = bpp_vars[15]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("\n");
 /* Line 232 */
 printf("%s", "THE CITY NOW OWNS ");
 { double _v = bpp_vars[0]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "ACRES.");
 printf("\n");
 /* Line 235 */
 printf("%s", "YOU HARVESTED");
 { double _v = bpp_vars[24]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "BUSHELS PER ACRE.");
 printf("\n");
 /* Line 250 */
 printf("%s", "THE RATS ATE");
 { double _v = bpp_vars[4]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "BUSHELS.");
 printf("\n");
 /* Line 260 */
 printf("%s", "YOU NOW HAVE ");
 { double _v = bpp_vars[18]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "BUSHELS IN STORE.");
 printf("\n");
  printf("\n");
 /* Line 270 */
 /* BASIC: IF statement */
 if ((bpp_vars[25] == 11)) { /* BASIC: GOTO */
goto L860;
 }
 /* Line 310 */
 bpp_vars[2] = floor((10 * ((double)(rand() % (int)(1)))));
 bpp_vars[24] = (bpp_vars[2] + 17);
 /* Line 312 */
 printf("%s", "LAND IS TRADING AT");
 { double _v = bpp_vars[24]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "BUSHELS PER ACRE.");
 printf("\n");
 L320: /* Line 320 */
 printf("%s", "HOW MANY ACRES DO YOU WISH TO BUY");
 /* Line 321 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[16] = _v; }
 /* BASIC: IF statement */
 if ((bpp_vars[16] < 0)) { /* BASIC: GOTO */
goto L850;
 }
 /* Line 322 */
 /* BASIC: IF statement */
 if (((bpp_vars[24] * bpp_vars[16]) <= bpp_vars[18])) { /* BASIC: GOTO */
goto L330;
 }
 /* Line 323 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 0; goto L710;
 bpp_ret_0:;
 /* Line 324 */
 /* BASIC: GOTO */
 goto L320;
 L330: /* Line 330 */
 /* BASIC: IF statement */
 if ((bpp_vars[16] == 0)) { /* BASIC: GOTO */
goto L340;
 }
 /* Line 331 */
 bpp_vars[0] = (bpp_vars[0] + bpp_vars[16]);
 bpp_vars[18] = (bpp_vars[18] - (bpp_vars[24] * bpp_vars[16]));
 bpp_vars[2] = 0;
 /* Line 334 */
 /* BASIC: GOTO */
 goto L400;
 L340: /* Line 340 */
 printf("%s", "HOW MANY ACRES DO YOU WISH TO SELL");
 /* Line 341 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[16] = _v; }
 /* BASIC: IF statement */
 if ((bpp_vars[16] < 0)) { /* BASIC: GOTO */
goto L850;
 }
 /* Line 342 */
 /* BASIC: IF statement */
 if ((bpp_vars[16] < bpp_vars[0])) { /* BASIC: GOTO */
goto L350;
 }
 /* Line 343 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 1; goto L720;
 bpp_ret_1:;
 /* Line 344 */
 /* BASIC: GOTO */
 goto L340;
 L350: /* Line 350 */
 bpp_vars[0] = (bpp_vars[0] - bpp_vars[16]);
 bpp_vars[18] = (bpp_vars[18] + (bpp_vars[24] * bpp_vars[16]));
 bpp_vars[2] = 0;
 L400: /* Line 400 */
  printf("\n");
 L410: /* Line 410 */
 printf("%s", "HOW MANY BUSHELS DO YOU WISH TO FEED YOUR PEOPLE");
 /* Line 411 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[16] = _v; }
 /* Line 412 */
 /* BASIC: IF statement */
 if ((bpp_vars[16] < 0)) { /* BASIC: GOTO */
goto L850;
 }
 /* Line 418 */
 /* REM  TRYING TO USE MORE GRAIN THAN IS IN SILOS? */
 /* Line 420 */
 /* BASIC: IF statement */
 if ((bpp_vars[16] <= bpp_vars[18])) { /* BASIC: GOTO */
goto L430;
 }
 /* Line 421 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 2; goto L710;
 bpp_ret_2:;
 /* Line 422 */
 /* BASIC: GOTO */
 goto L410;
 L430: /* Line 430 */
 bpp_vars[18] = (bpp_vars[18] - bpp_vars[16]);
 bpp_vars[2] = 1;
  printf("\n");
 L440: /* Line 440 */
 printf("%s", "HOW MANY ACRES DO YOU WISH TO PLANT WITH SEED");
 /* Line 441 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[3] = _v; }
 /* BASIC: IF statement */
 if ((bpp_vars[3] == 0)) { /* BASIC: GOTO */
goto L511;
 }
 /* Line 442 */
 /* BASIC: IF statement */
 if ((bpp_vars[3] < 0)) { /* BASIC: GOTO */
goto L850;
 }
 /* Line 444 */
 /* REM  TRYING TO PLANT MORE ACRES THAN YOU OWN? */
 /* Line 445 */
 /* BASIC: IF statement */
 if ((bpp_vars[3] <= bpp_vars[0])) { /* BASIC: GOTO */
goto L450;
 }
 /* Line 446 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 3; goto L720;
 bpp_ret_3:;
 /* Line 447 */
 /* BASIC: GOTO */
 goto L440;
 /* Line 449 */
 /* REM  ENOUGH GRAIN FOR SEED? */
 L450: /* Line 450 */
 /* BASIC: IF statement */
 if ((floor((bpp_vars[3] / 2)) <= bpp_vars[18])) { /* BASIC: GOTO */
goto L455;
 }
 /* Line 452 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 4; goto L710;
 bpp_ret_4:;
 /* Line 453 */
 /* BASIC: GOTO */
 goto L440;
 /* Line 454 */
 /* REM  ENOUGH PEOPLE TO TEND THE CROPS? */
 L455: /* Line 455 */
 /* BASIC: IF statement */
 if ((bpp_vars[3] < (10 * bpp_vars[15]))) { /* BASIC: GOTO */
goto L510;
 }
 /* Line 460 */
 printf("%s", "BUT YOU HAVE ONLY");
 { double _v = bpp_vars[15]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "PEOPLE TO TEND THE FIELDS!  NOW THEN,");
 printf("\n");
 /* Line 470 */
 /* BASIC: GOTO */
 goto L440;
 L510: /* Line 510 */
 bpp_vars[18] = (bpp_vars[18] - floor((bpp_vars[3] / 2)));
 L511: /* Line 511 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 5; goto L800;
 bpp_ret_5:;
 /* Line 512 */
 /* REM  A BOUNTIFUL HARVEST! */
 /* Line 515 */
 bpp_vars[24] = bpp_vars[2];
 bpp_vars[7] = (bpp_vars[3] * bpp_vars[24]);
 bpp_vars[4] = 0;
 /* Line 521 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 6; goto L800;
 bpp_ret_6:;
 /* Line 522 */
 /* BASIC: IF statement */
 if ((floor((bpp_vars[2] / 2)) != (bpp_vars[2] / 2))) { /* BASIC: GOTO */
goto L530;
 }
 /* Line 523 */
 /* REM  RATS ARE RUNNING WILD!! */
 /* Line 525 */
 bpp_vars[4] = floor((bpp_vars[18] / bpp_vars[2]));
 L530: /* Line 530 */
 bpp_vars[18] = ((bpp_vars[18] - bpp_vars[4]) + bpp_vars[7]);
 /* Line 531 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 7; goto L800;
 bpp_ret_7:;
 /* Line 532 */
 /* REM  LET'S HAVE SOME BABIES */
 /* Line 533 */
 bpp_vars[8] = floor(((((bpp_vars[2] * ((20 * bpp_vars[0]) + bpp_vars[18])) / bpp_vars[15]) / 100) + 1));
 /* Line 539 */
 /* REM  HOW MANY PEOPLE HAD FULL TUMMIES? */
 /* Line 540 */
 bpp_vars[2] = floor((bpp_vars[16] / 20));
 /* Line 541 */
 /* REM  HORROS, A 15% CHANCE OF PLAGUE */
 /* Line 542 */
 bpp_vars[16] = floor((10 * ((2 * ((double)(rand() % (int)(1)))) - 0.29999999999999999)));
 /* Line 550 */
 /* BASIC: IF statement */
 if ((bpp_vars[15] < bpp_vars[2])) { /* BASIC: GOTO */
goto L210;
 }
 /* Line 551 */
 /* REM  STARVE ENOUGH FOR IMPEACHMENT? */
 /* Line 552 */
 bpp_vars[3] = (bpp_vars[15] - bpp_vars[2]);
 /* BASIC: IF statement */
 if ((bpp_vars[3] > (0.45000000000000001 * bpp_vars[15]))) { /* BASIC: GOTO */
goto L560;
 }
 /* Line 553 */
 bpp_vars[27] = ((((bpp_vars[25] - 1) * bpp_vars[27]) + ((bpp_vars[3] * 100) / bpp_vars[15])) / bpp_vars[25]);
 /* Line 555 */
 bpp_vars[15] = bpp_vars[2];
 bpp_vars[26] = (bpp_vars[26] + bpp_vars[3]);
 /* BASIC: GOTO */
 goto L215;
 L560: /* Line 560 */
  printf("\n");
 printf("%s", "YOU STARVED");
 { double _v = bpp_vars[3]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "PEOPLE IN ONE YEAR!!!");
 printf("\n");
 L565: /* Line 565 */
 printf("%s", "DUE TO THIS EXTREME MISMANAGEMENT YOU HAVE NOT ONLY");
 printf("\n");
 /* Line 566 */
 printf("%s", "BEEN IMPEACHED AND THROWN OUT OF OFFICE BUT YOU HAVE");
 printf("\n");
 /* Line 567 */
 printf("%s", "ALSO BEEN DECLARED NATIONAL FINK!!!!");
 printf("\n");
 /* BASIC: GOTO */
 goto L990;
 L710: /* Line 710 */
 printf("%s", "HAMURABI:  THINK AGAIN.  YOU HAVE ONLY");
 printf("\n");
 /* Line 711 */
 { double _v = bpp_vars[18]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "BUSHELS OF GRAIN.  NOW THEN,");
 printf("\n");
 /* Line 712 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 default: goto bpp_end;
 } }
 L720: /* Line 720 */
 printf("%s", "HAMURABI:  THINK AGAIN.  YOU OWN ONLY");
 { double _v = bpp_vars[0]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "ACRES.  NOW THEN,");
 printf("\n");
 /* Line 730 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 default: goto bpp_end;
 } }
 L800: /* Line 800 */
 bpp_vars[2] = (floor((((double)(rand() % (int)(1))) * 5)) + 1);
 /* Line 801 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 default: goto bpp_end;
 } }
 L850: /* Line 850 */
  printf("\n");
 printf("%s", "HAMURABI:  I CANNOT DO WHAT YOU WISH.");
 printf("\n");
 /* Line 855 */
 printf("%s", "GET YOURSELF ANOTHER STEWARD!!!!!");
 printf("\n");
 /* Line 857 */
 /* BASIC: GOTO */
 goto L990;
 L860: /* Line 860 */
 printf("%s", "IN YOUR 10-YEAR TERM OF OFFICE,");
 { double _v = bpp_vars[27]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "PERCENT OF THE");
 printf("\n");
 /* Line 862 */
 printf("%s", "POPULATION STARVED PER YEAR ON THE AVERAGE, I.E. A TOTAL OF");
 printf("\n");
 /* Line 865 */
 { double _v = bpp_vars[26]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "PEOPLE DIED!!");
 printf("\n");
 bpp_vars[11] = (bpp_vars[0] / bpp_vars[15]);
 /* Line 870 */
 printf("%s", "YOU STARTED WITH 10 ACRES PER PERSON AND ENDED WITH");
 printf("\n");
 /* Line 875 */
 { double _v = bpp_vars[11]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "ACRES PER PERSON.");
 printf("\n");
  printf("\n");
 /* Line 880 */
 /* BASIC: IF statement */
 if ((bpp_vars[27] > 33)) { /* BASIC: GOTO */
goto L565;
 }
 /* Line 885 */
 /* BASIC: IF statement */
 if ((bpp_vars[11] < 7)) { /* BASIC: GOTO */
goto L565;
 }
 /* Line 890 */
 /* BASIC: IF statement */
 if ((bpp_vars[27] > 10)) { /* BASIC: GOTO */
goto L940;
 }
 /* Line 892 */
 /* BASIC: IF statement */
 if ((bpp_vars[11] < 9)) { /* BASIC: GOTO */
goto L940;
 }
 /* Line 895 */
 /* BASIC: IF statement */
 if ((bpp_vars[27] > 3)) { /* BASIC: GOTO */
goto L960;
 }
 /* Line 896 */
 /* BASIC: IF statement */
 if ((bpp_vars[11] < 10)) { /* BASIC: GOTO */
goto L960;
 }
 /* Line 900 */
 printf("%s", "A FANTASTIC PERFORMANCE!!!  CHARLEMANGE, DISRAELI, AND");
 printf("\n");
 /* Line 905 */
 printf("%s", "JEFFERSON COMBINED COULD NOT HAVE DONE BETTER!");
 printf("\n");
 /* BASIC: GOTO */
 goto L990;
 L940: /* Line 940 */
 printf("%s", "YOUR HEAVY-HANDED PERFORMANCE SMACKS OF NERO AND IVAN IV.");
 printf("\n");
 /* Line 945 */
 printf("%s", "THE PEOPLE (REMIANING) FIND YOU AN UNPLEASANT RULER, AND,");
 printf("\n");
 /* Line 950 */
 printf("%s", "FRANKLY, HATE YOUR GUTS!!");
 printf("\n");
 /* BASIC: GOTO */
 goto L990;
 L960: /* Line 960 */
 printf("%s", "YOUR PERFORMANCE COULD HAVE BEEN SOMEWHAT BETTER, BUT");
 printf("\n");
 /* Line 965 */
 printf("%s", "REALLY WASN'T TOO BAD AT ALL. ");
 { double _v = floor(((bpp_vars[15] * 0.80000000000000004) * ((double)(rand() % (int)(1))))); if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "PEOPLE");
 printf("\n");
 /* Line 970 */
 printf("%s", "WOULD DEARLY LIKE TO SEE YOU ASSASSINATED BUT WE ALL HAVE OUR");
 printf("\n");
 /* Line 975 */
 printf("%s", "TRIVIAL PROBLEMS.");
 printf("\n");
 L990: /* Line 990 */
  printf("\n");
 /* BASIC: FOR loop initialization */
 bpp_vars[13] = 1;
 bpp_for_0:;
 printf("%s", bpp_chr((int)(7)));
 /* BASIC: NEXT loop step */
 bpp_vars[13] += 1;
 if (bpp_vars[13] <= 10) goto bpp_for_0;
 /* Line 995 */
 printf("%s", "SO LONG FOR NOW.");
 printf("\n");
  printf("\n");
 /* Line 999 */
 goto bpp_end;
 bpp_end:
 return 0;
}
