#ifdef _MSC_VER
#ifndef _CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
#endif
#pragma warning(disable: 4996)
#pragma warning(disable: 4101)
#pragma warning(disable: 4244)
#pragma warning(disable: 4102)
#pragma warning(disable: 4311)
#pragma warning(disable: 4312)
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wstringop-truncation"
#pragma GCC diagnostic ignored "-Wrestrict"
#pragma GCC diagnostic ignored "-Wdouble-promotion"
#pragma GCC diagnostic ignored "-Wpointer-to-int-cast"
#pragma GCC diagnostic ignored "-Wint-to-pointer-cast"
#endif

/* Generated by BASIC++ Compiler for target: windows */
#define BPP_TARGET_WINDOWS
#define BPP_SUPPORT_MULTITASKING 1
#define BPP_SUPPORT_GRAPHICS 1
#define BPP_SUPPORT_FILESYSTEM 1

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* Windows specific platform headers */
#include <windows.h>

/* === Runtime Variables === */
static double bpp_vars[1024]; /* A-Z and named */
static char bpp_strvars[1024][256]; /* A$-Z$ and named */
static double bpp_at_array[4096]; /* @() legacy array */
static int bpp_print_width = 14;

/* === GOSUB Stack === */
#define BPP_MAX_STACK 256
static int bpp_gosub_stack[BPP_MAX_STACK];
static int bpp_gosub_sp = 0;

/* === DIM Arrays === */
#define BPP_MAX_DIM 64
#define BPP_MAX_ELEM 4194304
static double bpp_dim_pool[BPP_MAX_ELEM];
static int bpp_dim_used = 0;
typedef struct { char name[32]; int d1,d2,off; } BppDim;
static BppDim bpp_dims[BPP_MAX_DIM];
static int bpp_dim_count = 0;

static void bpp_dim_alloc(const char *nm, int d1, int d2) {
 int sz = (d1+1) * (d2>0 ? d2+1 : 1);
 BppDim *d = &bpp_dims[bpp_dim_count++];
 strncpy(d->name, nm, 31); d->name[31]='\0';
 d->d1=d1; d->d2=d2; d->off=bpp_dim_used;
 memset(&bpp_dim_pool[bpp_dim_used], 0, sizeof(double)*(size_t)sz);
 bpp_dim_used += sz;
}

static double *bpp_dim_ref(const char *nm, int i1, int i2) {
 int k;
 for (k=0; k<bpp_dim_count; k++) {
 if (strcmp(bpp_dims[k].name, nm)==0) {
 int idx = (bpp_dims[k].d2>0)
 ? i1*(bpp_dims[k].d2+1)+i2 : i1;
 return &bpp_dim_pool[bpp_dims[k].off + idx];
 }
 }
 fprintf(stderr, "Array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === String DIM arrays === */
#define BPP_MAX_STRDIM 26
#define BPP_MAX_STRDIM_SIZE 256
static struct { char nm[16]; int d1; int d2;
 char data[BPP_MAX_STRDIM_SIZE][256]; } bpp_strdims[BPP_MAX_STRDIM];
static int bpp_strdim_count = 0;

static char *bpp_strdim_ref(const char *nm, int i1, int i2) {
 int k;
 (void)i2;
 for (k = 0; k < bpp_strdim_count; k++) {
 if (strcmp(bpp_strdims[k].nm, nm) == 0) {
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[k].data[i1];
 }
 }
 /* Auto-create */
 if (bpp_strdim_count < BPP_MAX_STRDIM) {
 int j;
 strncpy(bpp_strdims[bpp_strdim_count].nm, nm, 15);
 bpp_strdims[bpp_strdim_count].nm[15] = '\0';
 for (j = 0; j < BPP_MAX_STRDIM_SIZE; j++)
 bpp_strdims[bpp_strdim_count].data[j][0] = '\0';
 bpp_strdim_count++;
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[bpp_strdim_count-1].data[i1];
 }
 fprintf(stderr, "String array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === DATA/READ support === */
#define BPP_MAX_DATA 4096
static const char *bpp_data_pool[BPP_MAX_DATA];
static int bpp_data_count = 0;
static int bpp_data_ptr = 0;

static double bpp_read_num(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return atof(bpp_data_pool[bpp_data_ptr++]);
}

static const char *bpp_read_str(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return bpp_data_pool[bpp_data_ptr++];
}

/* === String helpers === */
static char bpp_strtmp[8][256];
static int bpp_strtmp_idx = 0;

static char *bpp_tmp(void) {
 char *p = bpp_strtmp[bpp_strtmp_idx];
 bpp_strtmp_idx = (bpp_strtmp_idx+1) & 7;
 return p;
}

static const char *bpp_concat(const char *a, const char *b) {
 char *t = bpp_tmp();
 t[0]='\0';
 strncat(t, a, 254);
 strncat(t, b, 254-(int)strlen(t));
 return t;
}

static const char *bpp_left(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_right(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s+len-n, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_mid(const char *s, int st, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (st<0) st=0;
 if (st>len) st=len;
 if (n<0) n=0;
 if (st+n>len) n=len-st;
 memcpy(t, s+st, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_chr(int n) {
 char *t = bpp_tmp();
 t[0]=(char)n; t[1]='\0';
 return t;
}

static const char *bpp_str(double n) {
 char *t = bpp_tmp();
 sprintf(t, "%g", n);
 return t;
}

/* === TAB helper === */
static const char *bpp_tab(int col) {
 static char buf[256];
 int i;
 if (col < 0) col = 0;
 if (col > 255) col = 255;
 for (i = 0; i < col; i++) buf[i] = ' ';
 buf[col] = '\0';
 return buf;
}

/* === DEF FN support === */
#define BPP_MAX_FN 26
typedef double (*BppFnPtr)(double);
static double bpp_fn_param;

int main(void) {
  bpp_data_count = 0;

 /* Line 10 */
 printf("%s", bpp_tab((int)(34)));
 printf("%s", "HI LO");
 printf("\n");
 /* Line 20 */
 printf("%s", bpp_tab((int)(15)));
 printf("%s", "CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY");
 printf("\n");
 /* Line 30 */
  printf("\n");
  printf("\n");
  printf("\n");
 /* Line 100 */
 printf("%s", "THIS IS THE GAME OF HI LO.");
 printf("\n");
  printf("\n");
 /* Line 110 */
 printf("%s", "YOU WILL HAVE 6 TRIES TO GUESS THE AMOUNT OF MONEY IN THE");
 printf("\n");
 /* Line 120 */
 printf("%s", "HI LO JACKPOT, WHICH IS BETWEEN 1 AND 100 DOLLARS.  IF YOU");
 printf("\n");
 /* Line 130 */
 printf("%s", "GUESS THE AMOUNT, YOU WIN ALL THE MONEY IN THE JACKPOT!");
 printf("\n");
 /* Line 140 */
 printf("%s", "THEN YOU GET ANOTHER CHANCE TO WIN MORE MONEY.  HOWEVER,");
 printf("\n");
 /* Line 150 */
 printf("%s", "IF YOU DO NOT GUESS THE AMOUNT, THE GAME ENDS.");
 printf("\n");
  printf("\n");
 /* Line 160 */
 bpp_vars[17] = 0;
 L170: /* Line 170 */
 bpp_vars[1] = 0;
  printf("\n");
 /* Line 180 */
 bpp_vars[24] = floor((100 * ((double)(rand() % (int)(1)))));
 L200: /* Line 200 */
 printf("%s", "YOUR GUESS");
 /* Line 210 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[0] = _v; }
 /* Line 220 */
 bpp_vars[1] = (bpp_vars[1] + 1);
 /* Line 230 */
 /* BASIC: IF statement */
 if ((bpp_vars[0] == bpp_vars[24])) { /* BASIC: GOTO */
goto L300;
 }
 /* Line 240 */
 /* BASIC: IF statement */
 if ((bpp_vars[0] > bpp_vars[24])) { /* BASIC: GOTO */
goto L270;
 }
 /* Line 250 */
 printf("%s", "YOUR GUESS IS TOO LOW.");
 printf("\n");
 /* BASIC: GOTO */
 goto L280;
 L270: /* Line 270 */
 printf("%s", "YOUR GUESS IS TOO HIGH.");
 printf("\n");
 L280: /* Line 280 */
  printf("\n");
 /* BASIC: IF statement */
 if ((bpp_vars[1] < 6)) { /* BASIC: GOTO */
goto L200;
 }
 /* Line 290 */
 printf("%s", "YOU BLEW IT...TOO BAD...THE NUMBER WAS");
 { double _v = bpp_vars[24]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("\n");
 /* Line 295 */
 bpp_vars[17] = 0;
 /* BASIC: GOTO */
 goto L350;
 L300: /* Line 300 */
 printf("%s", "GOT IT!!!!!!!!!!   YOU WIN");
 { double _v = bpp_vars[24]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "DOLLARS.");
 printf("\n");
 /* Line 310 */
 bpp_vars[17] = (bpp_vars[17] + bpp_vars[24]);
 /* Line 320 */
 printf("%s", "YOUR TOTAL WINNINGS ARE NOW");
 { double _v = bpp_vars[17]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "DOLLARS.");
 printf("\n");
 L350: /* Line 350 */
  printf("\n");
 printf("%s", "PLAY AGAIN (YES OR NO)");
 /* Line 360 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[0], _buf, 255); }
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[0], "YES") == 0))) { /* BASIC: GOTO */
goto L170;
 }
 /* Line 380 */
  printf("\n");
 printf("%s", "SO LONG.  HOPE YOU ENJOYED YOURSELF!!!");
 printf("\n");
 /* Line 390 */
 goto bpp_end;
 bpp_end:
 return 0;
}
