#ifdef _MSC_VER
#ifndef _CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
#endif
#pragma warning(disable: 4996)
#pragma warning(disable: 4101)
#pragma warning(disable: 4244)
#pragma warning(disable: 4102)
#pragma warning(disable: 4311)
#pragma warning(disable: 4312)
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wstringop-truncation"
#pragma GCC diagnostic ignored "-Wrestrict"
#pragma GCC diagnostic ignored "-Wdouble-promotion"
#pragma GCC diagnostic ignored "-Wpointer-to-int-cast"
#pragma GCC diagnostic ignored "-Wint-to-pointer-cast"
#endif

/* Generated by BASIC++ Compiler for target: windows */
#define BPP_TARGET_WINDOWS
#define BPP_SUPPORT_MULTITASKING 1
#define BPP_SUPPORT_GRAPHICS 1
#define BPP_SUPPORT_FILESYSTEM 1

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* Windows specific platform headers */
#include <windows.h>

/* === Runtime Variables === */
static double bpp_vars[1024]; /* A-Z and named */
static char bpp_strvars[1024][256]; /* A$-Z$ and named */
static double bpp_at_array[4096]; /* @() legacy array */
static int bpp_print_width = 14;

/* === GOSUB Stack === */
#define BPP_MAX_STACK 256
static int bpp_gosub_stack[BPP_MAX_STACK];
static int bpp_gosub_sp = 0;

/* === DIM Arrays === */
#define BPP_MAX_DIM 64
#define BPP_MAX_ELEM 4194304
static double bpp_dim_pool[BPP_MAX_ELEM];
static int bpp_dim_used = 0;
typedef struct { char name[32]; int d1,d2,off; } BppDim;
static BppDim bpp_dims[BPP_MAX_DIM];
static int bpp_dim_count = 0;

static void bpp_dim_alloc(const char *nm, int d1, int d2) {
 int sz = (d1+1) * (d2>0 ? d2+1 : 1);
 BppDim *d = &bpp_dims[bpp_dim_count++];
 strncpy(d->name, nm, 31); d->name[31]='\0';
 d->d1=d1; d->d2=d2; d->off=bpp_dim_used;
 memset(&bpp_dim_pool[bpp_dim_used], 0, sizeof(double)*(size_t)sz);
 bpp_dim_used += sz;
}

static double *bpp_dim_ref(const char *nm, int i1, int i2) {
 int k;
 for (k=0; k<bpp_dim_count; k++) {
 if (strcmp(bpp_dims[k].name, nm)==0) {
 int idx = (bpp_dims[k].d2>0)
 ? i1*(bpp_dims[k].d2+1)+i2 : i1;
 return &bpp_dim_pool[bpp_dims[k].off + idx];
 }
 }
 fprintf(stderr, "Array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === String DIM arrays === */
#define BPP_MAX_STRDIM 26
#define BPP_MAX_STRDIM_SIZE 256
static struct { char nm[16]; int d1; int d2;
 char data[BPP_MAX_STRDIM_SIZE][256]; } bpp_strdims[BPP_MAX_STRDIM];
static int bpp_strdim_count = 0;

static char *bpp_strdim_ref(const char *nm, int i1, int i2) {
 int k;
 (void)i2;
 for (k = 0; k < bpp_strdim_count; k++) {
 if (strcmp(bpp_strdims[k].nm, nm) == 0) {
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[k].data[i1];
 }
 }
 /* Auto-create */
 if (bpp_strdim_count < BPP_MAX_STRDIM) {
 int j;
 strncpy(bpp_strdims[bpp_strdim_count].nm, nm, 15);
 bpp_strdims[bpp_strdim_count].nm[15] = '\0';
 for (j = 0; j < BPP_MAX_STRDIM_SIZE; j++)
 bpp_strdims[bpp_strdim_count].data[j][0] = '\0';
 bpp_strdim_count++;
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[bpp_strdim_count-1].data[i1];
 }
 fprintf(stderr, "String array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === DATA/READ support === */
#define BPP_MAX_DATA 4096
static const char *bpp_data_pool[BPP_MAX_DATA];
static int bpp_data_count = 0;
static int bpp_data_ptr = 0;

static double bpp_read_num(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return atof(bpp_data_pool[bpp_data_ptr++]);
}

static const char *bpp_read_str(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return bpp_data_pool[bpp_data_ptr++];
}

/* === String helpers === */
static char bpp_strtmp[8][256];
static int bpp_strtmp_idx = 0;

static char *bpp_tmp(void) {
 char *p = bpp_strtmp[bpp_strtmp_idx];
 bpp_strtmp_idx = (bpp_strtmp_idx+1) & 7;
 return p;
}

static const char *bpp_concat(const char *a, const char *b) {
 char *t = bpp_tmp();
 t[0]='\0';
 strncat(t, a, 254);
 strncat(t, b, 254-(int)strlen(t));
 return t;
}

static const char *bpp_left(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_right(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s+len-n, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_mid(const char *s, int st, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (st<0) st=0;
 if (st>len) st=len;
 if (n<0) n=0;
 if (st+n>len) n=len-st;
 memcpy(t, s+st, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_chr(int n) {
 char *t = bpp_tmp();
 t[0]=(char)n; t[1]='\0';
 return t;
}

static const char *bpp_str(double n) {
 char *t = bpp_tmp();
 sprintf(t, "%g", n);
 return t;
}

/* === TAB helper === */
static const char *bpp_tab(int col) {
 static char buf[256];
 int i;
 if (col < 0) col = 0;
 if (col > 255) col = 255;
 for (i = 0; i < col; i++) buf[i] = ' ';
 buf[col] = '\0';
 return buf;
}

/* === DEF FN support === */
#define BPP_MAX_FN 26
typedef double (*BppFnPtr)(double);
static double bpp_fn_param;

int main(void) {
  bpp_data_pool[0] = "3";
  bpp_data_pool[1] = "102";
  bpp_data_pool[2] = "103";
  bpp_data_pool[3] = "120";
  bpp_data_pool[4] = "130";
  bpp_data_pool[5] = "121";
  bpp_data_pool[6] = "112";
  bpp_data_pool[7] = "111";
  bpp_data_pool[8] = "12";
  bpp_data_pool[9] = "21";
  bpp_data_pool[10] = "30";
  bpp_data_pool[11] = "1020";
  bpp_data_pool[12] = "1030";
  bpp_data_pool[13] = "1011";
  bpp_data_pool[14] = "1021";
  bpp_data_pool[15] = "1003";
  bpp_data_pool[16] = "1002";
  bpp_data_pool[17] = "1012";
  bpp_data_pool[18] = "-1";
  bpp_data_pool[19] = "0";
  bpp_data_pool[20] = "1";
  bpp_data_pool[21] = "0";
  bpp_data_pool[22] = "0";
  bpp_data_pool[23] = "-1";
  bpp_data_pool[24] = "0";
  bpp_data_pool[25] = "1";
  bpp_data_pool[26] = "-1";
  bpp_data_pool[27] = "-1";
  bpp_data_pool[28] = "1";
  bpp_data_pool[29] = "-1";
  bpp_data_pool[30] = "-1";
  bpp_data_pool[31] = "1";
  bpp_data_pool[32] = "1";
  bpp_data_pool[33] = "1";
  bpp_data_count = 34;

 /* Line 2 */
 printf("%s", bpp_tab((int)(33)));
 printf("%s", "LIFE2");
 printf("\n");
 /* Line 4 */
 printf("%s", bpp_tab((int)(15)));
 printf("%s", "CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY");
 printf("\n");
 /* Line 6 */
  printf("\n");
  printf("\n");
  printf("\n");
 /* Line 7 */
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("N", (int)(6), (int)(6));
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("K", (int)(18), 0);
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("A", (int)(16), 0);
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("X", (int)(2), 0);
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("Y", (int)(2), 0);
 /* Line 8 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 9 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 10 */
 /* BASIC: FOR loop initialization */
 bpp_vars[12] = 1;
 bpp_for_0:;
 /* BASIC: READ statement */
 *bpp_dim_ref("K", (int)(bpp_vars[12]), 0) = bpp_read_num();
 /* BASIC: NEXT loop step */
 bpp_vars[12] += 1;
 if (bpp_vars[12] <= 18) goto bpp_for_0;
 /* Line 13 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 14 */
 /* BASIC: FOR loop initialization */
 bpp_vars[26] = 1;
 bpp_for_1:;
 /* BASIC: READ statement */
 *bpp_dim_ref("A", (int)(bpp_vars[26]), 0) = bpp_read_num();
 /* BASIC: NEXT loop step */
 bpp_vars[26] += 1;
 if (bpp_vars[26] <= 16) goto bpp_for_1;
 /* Line 20 */
 /* BASIC: GOTO */
 goto L500;
 L50: /* Line 50 */
 /* BASIC: FOR loop initialization */
 bpp_vars[9] = 1;
 bpp_for_2:;
 /* Line 51 */
 /* BASIC: FOR loop initialization */
 bpp_vars[10] = 1;
 bpp_for_3:;
 /* Line 55 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("N", (int)(bpp_vars[9]), (int)(bpp_vars[10])) > 99)) { bpp_gosub_stack[bpp_gosub_sp++] = 0; goto L200; }
 bpp_ret_0:;
 /* Line 60 */
 /* BASIC: NEXT loop step */
 bpp_vars[10] += 1;
 if (bpp_vars[10] <= 5) goto bpp_for_3;
 /* Line 65 */
 /* BASIC: NEXT loop step */
 bpp_vars[9] += 1;
 if (bpp_vars[9] <= 5) goto bpp_for_2;
 L90: /* Line 90 */
 bpp_vars[10] = 0;
 bpp_vars[27] = 0;
 bpp_vars[28] = 0;
 /* Line 99 */
 /* BASIC: FOR loop initialization */
 bpp_vars[9] = 0;
 bpp_for_4:;
  printf("\n");
 /* Line 100 */
 /* BASIC: FOR loop initialization */
 bpp_vars[10] = 0;
 bpp_for_5:;
 /* Line 101 */
 /* BASIC: IF statement */
 if ((bpp_vars[9] != 0)) { /* BASIC: IF statement */
if ((bpp_vars[9] != 6)) { /* BASIC: GOTO */
goto L105;
 }
 }
 /* Line 102 */
 /* BASIC: IF statement */
 if ((bpp_vars[10] == 6)) { { double _v = 0; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 }
 /* Line 103 */
 { double _v = bpp_vars[10]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 /* BASIC: GOTO */
 goto L120;
 /* Line 105 */
 /* BASIC: IF statement */
 if ((bpp_vars[10] != 0)) { /* BASIC: IF statement */
if ((bpp_vars[10] != 6)) { /* BASIC: GOTO */
goto L110;
 }
 }
 /* Line 106 */
 /* BASIC: IF statement */
 if ((bpp_vars[9] == 6)) { { double _v = 0; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
printf("\n");
 }
 /* Line 107 */
 { double _v = bpp_vars[9]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 /* BASIC: GOTO */
 goto L120;
 /* Line 110 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 1; goto L300;
 bpp_ret_1:;
 L120: /* Line 120 */
 /* BASIC: NEXT loop step */
 bpp_vars[10] += 1;
 if (bpp_vars[10] <= 6) goto bpp_for_5;
 /* Line 125 */
 /* BASIC: NEXT loop step */
 bpp_vars[9] += 1;
 if (bpp_vars[9] <= 6) goto bpp_for_4;
 /* Line 126 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 default: goto bpp_end;
 } }
 L200: /* Line 200 */
 bpp_vars[1] = 1;
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("N", (int)(bpp_vars[9]), (int)(bpp_vars[10])) > 999)) { bpp_vars[1] = 10;
 }
 /* Line 220 */
 /* BASIC: FOR loop initialization */
 bpp_vars[26] = 1;
 bpp_for_6:;
 /* Line 230 */
 *bpp_dim_ref("N", (int)((bpp_vars[9] + *bpp_dim_ref("A", (int)(bpp_vars[26]), 0))), (int)((bpp_vars[10] + *bpp_dim_ref("A", (int)((bpp_vars[26] + 1)), 0)))) = (*bpp_dim_ref("N", (int)((bpp_vars[9] + *bpp_dim_ref("A", (int)(bpp_vars[26]), 0))), (int)((bpp_vars[10] + *bpp_dim_ref("A", (int)((bpp_vars[26] + 1)), 0)))) + bpp_vars[1]);
 /* Line 231 */
 /* BASIC: NEXT loop step */
 bpp_vars[26] += 2;
 if ((2 > 0 && bpp_vars[26] <= 15) || (2 < 0 && bpp_vars[26] >= 15)) goto bpp_for_6;
 /* Line 239 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 default: goto bpp_end;
 } }
 L300: /* Line 300 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("N", (int)(bpp_vars[9]), (int)(bpp_vars[10])) < 3)) { /* BASIC: GOTO */
goto L399;
 }
 /* Line 305 */
 /* BASIC: FOR loop initialization */
 bpp_vars[26] = 1;
 bpp_for_7:;
 /* Line 310 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("N", (int)(bpp_vars[9]), (int)(bpp_vars[10])) == *bpp_dim_ref("K", (int)(bpp_vars[26]), 0))) { /* BASIC: GOTO */
goto L350;
 }
 /* Line 315 */
 /* BASIC: NEXT loop step */
 bpp_vars[26] += 1;
 if (bpp_vars[26] <= 18) goto bpp_for_7;
 /* Line 320 */
 /* BASIC: GOTO */
 goto L399;
 L350: /* Line 350 */
 /* BASIC: IF statement */
 if ((bpp_vars[26] > 9)) { /* BASIC: GOTO */
goto L360;
 }
 /* Line 351 */
 *bpp_dim_ref("N", (int)(bpp_vars[9]), (int)(bpp_vars[10])) = 100;
 bpp_vars[27] = (bpp_vars[27] + 1);
 printf("%s", " * ");
 /* Line 355 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 default: goto bpp_end;
 } }
 L360: /* Line 360 */
 *bpp_dim_ref("N", (int)(bpp_vars[9]), (int)(bpp_vars[10])) = 1000;
 bpp_vars[28] = (bpp_vars[28] + 1);
 printf("%s", " # ");
 /* Line 365 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 default: goto bpp_end;
 } }
 L399: /* Line 399 */
 *bpp_dim_ref("N", (int)(bpp_vars[9]), (int)(bpp_vars[10])) = 0;
 printf("%s", "   ");
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 default: goto bpp_end;
 } }
 L500: /* Line 500 */
 printf("%s", bpp_tab((int)(10)));
 printf("%s", "U.B. LIFE GAME");
 printf("\n");
 /* Line 505 */
 bpp_vars[27] = 0;
 bpp_vars[28] = 0;
 /* Line 510 */
 /* BASIC: FOR loop initialization */
 bpp_vars[9] = 1;
 bpp_for_8:;
 /* Line 511 */
 /* BASIC: FOR loop initialization */
 bpp_vars[10] = 1;
 bpp_for_9:;
 /* Line 515 */
 *bpp_dim_ref("N", (int)(bpp_vars[9]), (int)(bpp_vars[10])) = 0;
 /* Line 516 */
 /* BASIC: NEXT loop step */
 bpp_vars[10] += 1;
 if (bpp_vars[10] <= 5) goto bpp_for_9;
 /* Line 517 */
 /* BASIC: NEXT loop step */
 bpp_vars[9] += 1;
 if (bpp_vars[9] <= 5) goto bpp_for_8;
 /* Line 519 */
 /* BASIC: FOR loop initialization */
 bpp_vars[1] = 1;
 bpp_for_10:;
 bpp_vars[29] = 3;
 /* BASIC: IF statement */
 if ((bpp_vars[1] == 2)) { bpp_vars[29] = 30;
 }
 /* Line 520 */
  printf("\n");
 printf("%s", "PLAYER");
 { double _v = bpp_vars[1]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", " - 3 LIVE PIECES.");
 printf("\n");
 /* Line 535 */
 /* BASIC: FOR loop initialization */
 bpp_vars[30] = 1;
 bpp_for_11:;
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 2; goto L700;
 bpp_ret_2:;
 /* Line 540 */
 *bpp_dim_ref("N", (int)(*bpp_dim_ref("X", (int)(bpp_vars[1]), 0)), (int)(*bpp_dim_ref("Y", (int)(bpp_vars[1]), 0))) = bpp_vars[29];
 /* BASIC: NEXT loop step */
 bpp_vars[30] += 1;
 if (bpp_vars[30] <= 3) goto bpp_for_11;
 /* Line 542 */
 /* BASIC: NEXT loop step */
 bpp_vars[1] += 1;
 if (bpp_vars[1] <= 2) goto bpp_for_10;
 /* Line 559 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 3; goto L90;
 bpp_ret_3:;
 L560: /* Line 560 */
  printf("\n");
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 4; goto L50;
 bpp_ret_4:;
 /* Line 570 */
 /* BASIC: IF statement */
 if ((bpp_vars[27] == 0)) { /* BASIC: IF statement */
if ((bpp_vars[28] == 0)) { /* BASIC: GOTO */
goto L574;
 }
 }
 /* Line 571 */
 /* BASIC: IF statement */
 if ((bpp_vars[28] == 0)) { bpp_vars[1] = 1;
 }
 /* Line 572 */
 /* BASIC: IF statement */
 if ((bpp_vars[27] == 0)) { bpp_vars[1] = 2;
 }
 /* Line 573 */
 /* BASIC: GOTO */
 goto L580;
 /* Line 574 */
  printf("\n");
 printf("%s", "A DRAW");
 printf("\n");
 /* BASIC: GOTO */
 goto L800;
 /* Line 575 */
  printf("\n");
 printf("%s", "PLAYER");
 { double _v = bpp_vars[1]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "IS THE WINNER");
 printf("\n");
 /* BASIC: GOTO */
 goto L800;
 L580: /* Line 580 */
 /* BASIC: FOR loop initialization */
 bpp_vars[1] = 1;
 bpp_for_12:;
  printf("\n");
  printf("\n");
 printf("%s", "PLAYER");
 { double _v = bpp_vars[1]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 5; goto L700;
 bpp_ret_5:;
 /* Line 581 */
 /* BASIC: IF statement */
 if ((bpp_vars[1] == 99)) { /* BASIC: GOTO */
goto L560;
 }
 /* Line 582 */
 /* BASIC: NEXT loop step */
 bpp_vars[1] += 1;
 if (bpp_vars[1] <= 2) goto bpp_for_12;
 /* Line 586 */
 *bpp_dim_ref("N", (int)(*bpp_dim_ref("X", (int)(1), 0)), (int)(*bpp_dim_ref("Y", (int)(1), 0))) = 100;
 *bpp_dim_ref("N", (int)(*bpp_dim_ref("X", (int)(2), 0)), (int)(*bpp_dim_ref("Y", (int)(2), 0))) = 1000;
 /* Line 596 */
 /* BASIC: GOTO */
 goto L560;
 L700: /* Line 700 */
 printf("%s", "X,Y");
 printf("\n");
 printf("%s", "XXXXXX");
 printf("%s", bpp_chr((int)(13)));
 printf("%s", "$$$$$$");
 printf("%s", bpp_chr((int)(13)));
 printf("%s", "&&&&&&");
 /* Line 701 */
 printf("%s", bpp_chr((int)(13)));
 printf("? ");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   *bpp_dim_ref("Y", (int)(bpp_vars[1]), 0) = _v; }
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   *bpp_dim_ref("X", (int)(bpp_vars[1]), 0) = _v; }
 /* Line 705 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("X", (int)(bpp_vars[1]), 0) <= 5)) { /* BASIC: IF statement */
if ((*bpp_dim_ref("X", (int)(bpp_vars[1]), 0) > 0)) { /* BASIC: GOTO */
goto L708;
 }
 }
 /* Line 706 */
 /* BASIC: GOTO */
 goto L750;
 /* Line 708 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("Y", (int)(bpp_vars[1]), 0) <= 5)) { /* BASIC: IF statement */
if ((*bpp_dim_ref("Y", (int)(bpp_vars[1]), 0) > 0)) { /* BASIC: GOTO */
goto L715;
 }
 }
 /* Line 710 */
 /* BASIC: GOTO */
 goto L750;
 /* Line 715 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("N", (int)(*bpp_dim_ref("X", (int)(bpp_vars[1]), 0)), (int)(*bpp_dim_ref("Y", (int)(bpp_vars[1]), 0))) != 0)) { /* BASIC: GOTO */
goto L750;
 }
 /* Line 720 */
 /* BASIC: IF statement */
 if ((bpp_vars[1] == 1)) { /* BASIC: RETURN */
{ int _ra = bpp_gosub_stack[--bpp_gosub_sp]; switch(_ra) {
 default: goto bpp_end;
 } }
 }
 /* Line 725 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("X", (int)(1), 0) == *bpp_dim_ref("X", (int)(2), 0))) { /* BASIC: IF statement */
if ((*bpp_dim_ref("Y", (int)(1), 0) == *bpp_dim_ref("Y", (int)(2), 0))) { /* BASIC: GOTO */
goto L740;
 }
 }
 /* Line 730 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 default: goto bpp_end;
 } }
 /* Line 740 */
 printf("%s", "SAME COORD.  SET TO 0");
 printf("\n");
 /* Line 741 */
 *bpp_dim_ref("N", (int)((*bpp_dim_ref("X", (int)(bpp_vars[1]), 0) + 1)), (int)((*bpp_dim_ref("Y", (int)(bpp_vars[1]), 0) + 1))) = 0;
 bpp_vars[1] = 99;
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 default: goto bpp_end;
 } }
 L750: /* Line 750 */
 printf("%s", "ILLEGAL COORDS. RETYPE");
 printf("\n");
 /* BASIC: GOTO */
 goto L700;
 /* Line 999 */
 goto bpp_end;
 bpp_end:
 return 0;
}
