#ifdef _MSC_VER
#ifndef _CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
#endif
#pragma warning(disable: 4996)
#pragma warning(disable: 4101)
#pragma warning(disable: 4244)
#pragma warning(disable: 4102)
#pragma warning(disable: 4311)
#pragma warning(disable: 4312)
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wstringop-truncation"
#pragma GCC diagnostic ignored "-Wrestrict"
#pragma GCC diagnostic ignored "-Wdouble-promotion"
#pragma GCC diagnostic ignored "-Wpointer-to-int-cast"
#pragma GCC diagnostic ignored "-Wint-to-pointer-cast"
#endif

/* Generated by BASIC++ Compiler for target: windows */
#define BPP_TARGET_WINDOWS
#define BPP_SUPPORT_MULTITASKING 1
#define BPP_SUPPORT_GRAPHICS 1
#define BPP_SUPPORT_FILESYSTEM 1

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* Windows specific platform headers */
#include <windows.h>

/* === Runtime Variables === */
static double bpp_vars[1024]; /* A-Z and named */
static char bpp_strvars[1024][256]; /* A$-Z$ and named */
static double bpp_at_array[4096]; /* @() legacy array */
static int bpp_print_width = 14;

/* === GOSUB Stack === */
#define BPP_MAX_STACK 256
static int bpp_gosub_stack[BPP_MAX_STACK];
static int bpp_gosub_sp = 0;

/* === DIM Arrays === */
#define BPP_MAX_DIM 64
#define BPP_MAX_ELEM 4194304
static double bpp_dim_pool[BPP_MAX_ELEM];
static int bpp_dim_used = 0;
typedef struct { char name[32]; int d1,d2,off; } BppDim;
static BppDim bpp_dims[BPP_MAX_DIM];
static int bpp_dim_count = 0;

static void bpp_dim_alloc(const char *nm, int d1, int d2) {
 int sz = (d1+1) * (d2>0 ? d2+1 : 1);
 BppDim *d = &bpp_dims[bpp_dim_count++];
 strncpy(d->name, nm, 31); d->name[31]='\0';
 d->d1=d1; d->d2=d2; d->off=bpp_dim_used;
 memset(&bpp_dim_pool[bpp_dim_used], 0, sizeof(double)*(size_t)sz);
 bpp_dim_used += sz;
}

static double *bpp_dim_ref(const char *nm, int i1, int i2) {
 int k;
 for (k=0; k<bpp_dim_count; k++) {
 if (strcmp(bpp_dims[k].name, nm)==0) {
 int idx = (bpp_dims[k].d2>0)
 ? i1*(bpp_dims[k].d2+1)+i2 : i1;
 return &bpp_dim_pool[bpp_dims[k].off + idx];
 }
 }
 fprintf(stderr, "Array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === String DIM arrays === */
#define BPP_MAX_STRDIM 26
#define BPP_MAX_STRDIM_SIZE 256
static struct { char nm[16]; int d1; int d2;
 char data[BPP_MAX_STRDIM_SIZE][256]; } bpp_strdims[BPP_MAX_STRDIM];
static int bpp_strdim_count = 0;

static char *bpp_strdim_ref(const char *nm, int i1, int i2) {
 int k;
 (void)i2;
 for (k = 0; k < bpp_strdim_count; k++) {
 if (strcmp(bpp_strdims[k].nm, nm) == 0) {
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[k].data[i1];
 }
 }
 /* Auto-create */
 if (bpp_strdim_count < BPP_MAX_STRDIM) {
 int j;
 strncpy(bpp_strdims[bpp_strdim_count].nm, nm, 15);
 bpp_strdims[bpp_strdim_count].nm[15] = '\0';
 for (j = 0; j < BPP_MAX_STRDIM_SIZE; j++)
 bpp_strdims[bpp_strdim_count].data[j][0] = '\0';
 bpp_strdim_count++;
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[bpp_strdim_count-1].data[i1];
 }
 fprintf(stderr, "String array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === DATA/READ support === */
#define BPP_MAX_DATA 4096
static const char *bpp_data_pool[BPP_MAX_DATA];
static int bpp_data_count = 0;
static int bpp_data_ptr = 0;

static double bpp_read_num(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return atof(bpp_data_pool[bpp_data_ptr++]);
}

static const char *bpp_read_str(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return bpp_data_pool[bpp_data_ptr++];
}

/* === String helpers === */
static char bpp_strtmp[8][256];
static int bpp_strtmp_idx = 0;

static char *bpp_tmp(void) {
 char *p = bpp_strtmp[bpp_strtmp_idx];
 bpp_strtmp_idx = (bpp_strtmp_idx+1) & 7;
 return p;
}

static const char *bpp_concat(const char *a, const char *b) {
 char *t = bpp_tmp();
 t[0]='\0';
 strncat(t, a, 254);
 strncat(t, b, 254-(int)strlen(t));
 return t;
}

static const char *bpp_left(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_right(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s+len-n, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_mid(const char *s, int st, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (st<0) st=0;
 if (st>len) st=len;
 if (n<0) n=0;
 if (st+n>len) n=len-st;
 memcpy(t, s+st, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_chr(int n) {
 char *t = bpp_tmp();
 t[0]=(char)n; t[1]='\0';
 return t;
}

static const char *bpp_str(double n) {
 char *t = bpp_tmp();
 sprintf(t, "%g", n);
 return t;
}

/* === TAB helper === */
static const char *bpp_tab(int col) {
 static char buf[256];
 int i;
 if (col < 0) col = 0;
 if (col > 255) col = 255;
 for (i = 0; i < col; i++) buf[i] = ' ';
 buf[col] = '\0';
 return buf;
}

/* === DEF FN support === */
#define BPP_MAX_FN 26
typedef double (*BppFnPtr)(double);
static double bpp_fn_param;

int main(void) {
  bpp_data_count = 0;

 /* Line 100 */
 printf("%s", bpp_tab((int)(33)));
 printf("%s", "NIM");
 printf("\n");
 /* Line 110 */
 printf("%s", bpp_tab((int)(15)));
 printf("%s", "CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY");
 printf("\n");
 /* Line 120 */
  printf("\n");
  printf("\n");
  printf("\n");
 /* Line 210 */
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("A", (int)(100), 0);
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("B", (int)(100), (int)(10));
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("D", (int)(2), 0);
 /* Line 220 */
 printf("%s", "THIS IS THE GAME OF NIM.");
 printf("\n");
 /* Line 230 */
 printf("%s", "DO YOU WANT INSTRUCTIONS");
 L240: /* Line 240 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[25], _buf, 255); }
 /* Line 250 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[25], "NO") == 0))) { /* BASIC: GOTO */
goto L440;
 }
 /* Line 260 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[25], "no") == 0))) { /* BASIC: GOTO */
goto L440;
 }
 /* Line 270 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[25], "YES") == 0))) { /* BASIC: GOTO */
goto L310;
 }
 /* Line 280 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[25], "yes") == 0))) { /* BASIC: GOTO */
goto L310;
 }
 /* Line 290 */
 printf("%s", "PLEASE ANSWER YES OR NO");
 printf("\n");
 /* Line 300 */
 /* BASIC: GOTO */
 goto L240;
 L310: /* Line 310 */
 printf("%s", "THE GAME IS PLAYED WITH A NUMBER OF PILES OF OBJECTS.");
 printf("\n");
 /* Line 320 */
 printf("%s", "ANY NUMBER OF OBJECTS ARE REMOVED FROM ONE PILE BY YOU AND");
 printf("\n");
 /* Line 330 */
 printf("%s", "THE MACHINE ALTERNATELY.  ON YOUR TURN, YOU MAY TAKE");
 printf("\n");
 /* Line 340 */
 printf("%s", "ALL THE OBJECTS THAT REMAIN IN ANY PILE, BUT YOU MUST");
 printf("\n");
 /* Line 350 */
 printf("%s", "TAKE AT LEAST ONE OBJECT, AND YOU MAY TAKE OBJECTS FROM");
 printf("\n");
 /* Line 360 */
 printf("%s", "ONLY ONE PILE ON A SINGLE TURN.  YOU MUST SPECIFY WHETHER");
 printf("\n");
 /* Line 370 */
 printf("%s", "WINNING IS DEFINED AS TAKING OR NOT TAKING THE LAST OBJECT,");
 printf("\n");
 /* Line 380 */
 printf("%s", "THE NUMBER OF PILES IN THE GAME, AND HOW MANY OBJECTS ARE");
 printf("\n");
 /* Line 390 */
 printf("%s", "ORIGINALLY IN EACH PILE.  EACH PILE MAY CONTAIN A");
 printf("\n");
 /* Line 400 */
 printf("%s", "DIFFERENT NUMBER OF OBJECTS.");
 printf("\n");
 /* Line 410 */
 printf("%s", "THE MACHINE WILL SHOW ITS MOVE BY LISTING EACH PILE AND THE");
 printf("\n");
 /* Line 420 */
 printf("%s", "NUMBER OF OBJECTS REMAINING IN THE PILES AFTER  EACH OF ITS");
 printf("\n");
 /* Line 430 */
 printf("%s", "MOVES.");
 printf("\n");
 L440: /* Line 440 */
  printf("\n");
 L450: /* Line 450 */
 printf("%s", "ENTER WIN OPTION - 1 TO TAKE LAST, 2 TO AVOID LAST");
 /* Line 460 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[22] = _v; }
 /* Line 470 */
 /* BASIC: IF statement */
 if ((bpp_vars[22] == 1)) { /* BASIC: GOTO */
goto L490;
 }
 /* Line 480 */
 /* BASIC: IF statement */
 if ((bpp_vars[22] != 2)) { /* BASIC: GOTO */
goto L450;
 }
 L490: /* Line 490 */
 printf("%s", "ENTER NUMBER OF PILES");
 /* Line 500 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[13] = _v; }
 /* Line 510 */
 /* BASIC: IF statement */
 if ((bpp_vars[13] > 100)) { /* BASIC: GOTO */
goto L490;
 }
 /* Line 520 */
 /* BASIC: IF statement */
 if ((bpp_vars[13] < 1)) { /* BASIC: GOTO */
goto L490;
 }
 /* Line 530 */
 /* BASIC: IF statement */
 if ((bpp_vars[13] != floor(bpp_vars[13]))) { /* BASIC: GOTO */
goto L490;
 }
 /* Line 540 */
 printf("%s", "ENTER PILE SIZES");
 printf("\n");
 /* Line 550 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_0:;
 L560: /* Line 560 */
 { double _v = bpp_vars[8]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 /* Line 570 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   *bpp_dim_ref("A", (int)(bpp_vars[8]), 0) = _v; }
 /* Line 580 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("A", (int)(bpp_vars[8]), 0) > 2000)) { /* BASIC: GOTO */
goto L560;
 }
 /* Line 590 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("A", (int)(bpp_vars[8]), 0) < 1)) { /* BASIC: GOTO */
goto L560;
 }
 /* Line 600 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("A", (int)(bpp_vars[8]), 0) != floor(*bpp_dim_ref("A", (int)(bpp_vars[8]), 0)))) { /* BASIC: GOTO */
goto L560;
 }
 /* Line 610 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= bpp_vars[13]) goto bpp_for_0;
 /* Line 620 */
 printf("%s", "DO YOU WANT TO MOVE FIRST");
 L630: /* Line 630 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[26], _buf, 255); }
 /* Line 640 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[26], "YES") == 0))) { /* BASIC: GOTO */
goto L1450;
 }
 /* Line 650 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[26], "yes") == 0))) { /* BASIC: GOTO */
goto L1450;
 }
 /* Line 660 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[26], "NO") == 0))) { /* BASIC: GOTO */
goto L700;
 }
 /* Line 670 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[26], "no") == 0))) { /* BASIC: GOTO */
goto L700;
 }
 /* Line 680 */
 printf("%s", "PLEASE ANSWER YES OR NO.");
 printf("\n");
 /* Line 690 */
 /* BASIC: GOTO */
 goto L630;
 L700: /* Line 700 */
 /* BASIC: IF statement */
 if ((bpp_vars[22] == 1)) { /* BASIC: GOTO */
goto L940;
 }
 /* Line 710 */
 bpp_vars[2] = 0;
 /* Line 720 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_1:;
 /* Line 730 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("A", (int)(bpp_vars[8]), 0) == 0)) { /* BASIC: GOTO */
goto L770;
 }
 /* Line 740 */
 bpp_vars[2] = (bpp_vars[2] + 1);
 /* Line 750 */
 /* BASIC: IF statement */
 if ((bpp_vars[2] == 3)) { /* BASIC: GOTO */
goto L840;
 }
 /* Line 760 */
 *bpp_dim_ref("D", (int)(bpp_vars[2]), 0) = bpp_vars[8];
 L770: /* Line 770 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= bpp_vars[13]) goto bpp_for_1;
 /* Line 780 */
 /* BASIC: IF statement */
 if ((bpp_vars[2] == 2)) { /* BASIC: GOTO */
goto L920;
 }
 /* Line 790 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("A", (int)(*bpp_dim_ref("D", (int)(1), 0)), 0) > 1)) { /* BASIC: GOTO */
goto L820;
 }
 L800: /* Line 800 */
 printf("%s", "MACHINE LOSES");
 printf("\n");
 /* Line 810 */
 /* BASIC: GOTO */
 goto L1640;
 L820: /* Line 820 */
 printf("%s", "MACHINE WINS");
 printf("\n");
 /* Line 830 */
 /* BASIC: GOTO */
 goto L1640;
 L840: /* Line 840 */
 bpp_vars[2] = 0;
 /* Line 850 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_2:;
 /* Line 860 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("A", (int)(bpp_vars[8]), 0) > 1)) { /* BASIC: GOTO */
goto L940;
 }
 /* Line 870 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("A", (int)(bpp_vars[8]), 0) == 0)) { /* BASIC: GOTO */
goto L890;
 }
 /* Line 880 */
 bpp_vars[2] = (bpp_vars[2] + 1);
 L890: /* Line 890 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= bpp_vars[13]) goto bpp_for_2;
 /* Line 900 */
 /* BASIC: IF statement */
 if (((bpp_vars[2] / 2) != floor((bpp_vars[2] / 2)))) { /* BASIC: GOTO */
goto L800;
 }
 /* Line 910 */
 /* BASIC: GOTO */
 goto L940;
 L920: /* Line 920 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("A", (int)(*bpp_dim_ref("D", (int)(1), 0)), 0) == 1)) { /* BASIC: GOTO */
goto L820;
 }
 /* Line 930 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("A", (int)(*bpp_dim_ref("D", (int)(2), 0)), 0) == 1)) { /* BASIC: GOTO */
goto L820;
 }
 L940: /* Line 940 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_3:;
 /* Line 950 */
 bpp_vars[4] = *bpp_dim_ref("A", (int)(bpp_vars[8]), 0);
 /* Line 960 */
 /* BASIC: FOR loop initialization */
 bpp_vars[9] = 0;
 bpp_for_4:;
 /* Line 970 */
 bpp_vars[5] = (bpp_vars[4] / 2);
 /* Line 980 */
 *bpp_dim_ref("B", (int)(bpp_vars[8]), (int)(bpp_vars[9])) = (2 * (bpp_vars[5] - floor(bpp_vars[5])));
 /* Line 990 */
 bpp_vars[4] = floor(bpp_vars[5]);
 /* Line 1000 */
 /* BASIC: NEXT loop step */
 bpp_vars[9] += 1;
 if (bpp_vars[9] <= 10) goto bpp_for_4;
 /* Line 1010 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= bpp_vars[13]) goto bpp_for_3;
 /* Line 1020 */
 /* BASIC: FOR loop initialization */
 bpp_vars[9] = 10;
 bpp_for_5:;
 /* Line 1030 */
 bpp_vars[2] = 0;
 /* Line 1040 */
 bpp_vars[7] = 0;
 /* Line 1050 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_6:;
 /* Line 1060 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("B", (int)(bpp_vars[8]), (int)(bpp_vars[9])) == 0)) { /* BASIC: GOTO */
goto L1110;
 }
 /* Line 1070 */
 bpp_vars[2] = (bpp_vars[2] + 1);
 /* Line 1080 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("A", (int)(bpp_vars[8]), 0) <= bpp_vars[7])) { /* BASIC: GOTO */
goto L1110;
 }
 /* Line 1090 */
 bpp_vars[7] = *bpp_dim_ref("A", (int)(bpp_vars[8]), 0);
 /* Line 1100 */
 bpp_vars[6] = bpp_vars[8];
 L1110: /* Line 1110 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= bpp_vars[13]) goto bpp_for_6;
 /* Line 1120 */
 /* BASIC: IF statement */
 if (((bpp_vars[2] / 2) != floor((bpp_vars[2] / 2)))) { /* BASIC: GOTO */
goto L1190;
 }
 /* Line 1130 */
 /* BASIC: NEXT loop step */
 bpp_vars[9] += (-(1));
 if (((-(1)) > 0 && bpp_vars[9] <= 0) || ((-(1)) < 0 && bpp_vars[9] >= 0)) goto bpp_for_5;
 L1140: /* Line 1140 */
 bpp_vars[4] = floor(((bpp_vars[13] * ((double)(rand() % (int)(1)))) + 1));
 /* Line 1150 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("A", (int)(bpp_vars[4]), 0) == 0)) { /* BASIC: GOTO */
goto L1140;
 }
 /* Line 1160 */
 bpp_vars[5] = floor(((*bpp_dim_ref("A", (int)(bpp_vars[4]), 0) * ((double)(rand() % (int)(1)))) + 1));
 /* Line 1170 */
 *bpp_dim_ref("A", (int)(bpp_vars[4]), 0) = (*bpp_dim_ref("A", (int)(bpp_vars[4]), 0) - bpp_vars[5]);
 /* Line 1180 */
 /* BASIC: GOTO */
 goto L1380;
 L1190: /* Line 1190 */
 *bpp_dim_ref("A", (int)(bpp_vars[6]), 0) = 0;
 /* Line 1200 */
 /* BASIC: FOR loop initialization */
 bpp_vars[9] = 0;
 bpp_for_7:;
 /* Line 1210 */
 *bpp_dim_ref("B", (int)(bpp_vars[6]), (int)(bpp_vars[9])) = 0;
 /* Line 1220 */
 bpp_vars[2] = 0;
 /* Line 1230 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_8:;
 /* Line 1240 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("B", (int)(bpp_vars[8]), (int)(bpp_vars[9])) == 0)) { /* BASIC: GOTO */
goto L1260;
 }
 /* Line 1250 */
 bpp_vars[2] = (bpp_vars[2] + 1);
 L1260: /* Line 1260 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= bpp_vars[13]) goto bpp_for_8;
 /* Line 1270 */
 *bpp_dim_ref("A", (int)(bpp_vars[6]), 0) = (*bpp_dim_ref("A", (int)(bpp_vars[6]), 0) + ((2 * ((bpp_vars[2] / 2) - floor((bpp_vars[2] / 2)))) * (pow(2, bpp_vars[9]))));
 /* Line 1280 */
 /* BASIC: NEXT loop step */
 bpp_vars[9] += 1;
 if (bpp_vars[9] <= 10) goto bpp_for_7;
 /* Line 1290 */
 /* BASIC: IF statement */
 if ((bpp_vars[22] == 1)) { /* BASIC: GOTO */
goto L1380;
 }
 /* Line 1300 */
 bpp_vars[2] = 0;
 /* Line 1310 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_9:;
 /* Line 1320 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("A", (int)(bpp_vars[8]), 0) > 1)) { /* BASIC: GOTO */
goto L1380;
 }
 /* Line 1330 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("A", (int)(bpp_vars[8]), 0) == 0)) { /* BASIC: GOTO */
goto L1350;
 }
 /* Line 1340 */
 bpp_vars[2] = (bpp_vars[2] + 1);
 L1350: /* Line 1350 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= bpp_vars[13]) goto bpp_for_9;
 /* Line 1360 */
 /* BASIC: IF statement */
 if (((bpp_vars[2] / 2) != floor((bpp_vars[2] / 2)))) { /* BASIC: GOTO */
goto L1380;
 }
 /* Line 1370 */
 *bpp_dim_ref("A", (int)(bpp_vars[6]), 0) = (1 - *bpp_dim_ref("A", (int)(bpp_vars[6]), 0));
 L1380: /* Line 1380 */
 printf("%s", "PILE  SIZE");
 printf("\n");
 /* Line 1390 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_10:;
 /* Line 1400 */
 { double _v = bpp_vars[8]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 { double _v = *bpp_dim_ref("A", (int)(bpp_vars[8]), 0); if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("\n");
 /* Line 1410 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= bpp_vars[13]) goto bpp_for_10;
 /* Line 1420 */
 /* BASIC: IF statement */
 if ((bpp_vars[22] == 2)) { /* BASIC: GOTO */
goto L1450;
 }
 /* Line 1430 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 0; goto L1570;
 bpp_ret_0:;
 /* Line 1440 */
 /* BASIC: IF statement */
 if ((bpp_vars[25] == 1)) { /* BASIC: GOTO */
goto L820;
 }
 L1450: /* Line 1450 */
 printf("%s", "YOUR MOVE - PILE, NUMBER TO BE REMOVED");
 /* Line 1460 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[23] = _v; }
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[24] = _v; }
 /* Line 1470 */
 /* BASIC: IF statement */
 if ((bpp_vars[23] > bpp_vars[13])) { /* BASIC: GOTO */
goto L1450;
 }
 /* Line 1480 */
 /* BASIC: IF statement */
 if ((bpp_vars[23] < 1)) { /* BASIC: GOTO */
goto L1450;
 }
 /* Line 1490 */
 /* BASIC: IF statement */
 if ((bpp_vars[23] != floor(bpp_vars[23]))) { /* BASIC: GOTO */
goto L1450;
 }
 /* Line 1500 */
 /* BASIC: IF statement */
 if ((bpp_vars[24] > *bpp_dim_ref("A", (int)(bpp_vars[23]), 0))) { /* BASIC: GOTO */
goto L1450;
 }
 /* Line 1510 */
 /* BASIC: IF statement */
 if ((bpp_vars[24] < 1)) { /* BASIC: GOTO */
goto L1450;
 }
 /* Line 1520 */
 /* BASIC: IF statement */
 if ((bpp_vars[24] != floor(bpp_vars[24]))) { /* BASIC: GOTO */
goto L1450;
 }
 /* Line 1530 */
 *bpp_dim_ref("A", (int)(bpp_vars[23]), 0) = (*bpp_dim_ref("A", (int)(bpp_vars[23]), 0) - bpp_vars[24]);
 /* Line 1540 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 1; goto L1570;
 bpp_ret_1:;
 /* Line 1550 */
 /* BASIC: IF statement */
 if ((bpp_vars[25] == 1)) { /* BASIC: GOTO */
goto L800;
 }
 /* Line 1560 */
 /* BASIC: GOTO */
 goto L700;
 L1570: /* Line 1570 */
 bpp_vars[25] = 0;
 /* Line 1580 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_11:;
 /* Line 1590 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("A", (int)(bpp_vars[8]), 0) == 0)) { /* BASIC: GOTO */
goto L1610;
 }
 /* Line 1600 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 default: goto bpp_end;
 } }
 L1610: /* Line 1610 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= bpp_vars[13]) goto bpp_for_11;
 /* Line 1620 */
 bpp_vars[25] = 1;
 /* Line 1630 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 default: goto bpp_end;
 } }
 L1640: /* Line 1640 */
 printf("%s", "do you want to play another game");
 L1650: /* Line 1650 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[26], _buf, 255); }
 /* Line 1660 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[26], "YES") == 0))) { /* BASIC: GOTO */
goto L1720;
 }
 /* Line 1670 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[26], "yes") == 0))) { /* BASIC: GOTO */
goto L1720;
 }
 /* Line 1680 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[26], "NO") == 0))) { /* BASIC: GOTO */
goto L1730;
 }
 /* Line 1690 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[26], "no") == 0))) { /* BASIC: GOTO */
goto L1730;
 }
 /* Line 1700 */
 printf("%s", "PLEASE.  YES OR NO.");
 printf("\n");
 /* Line 1710 */
 /* BASIC: GOTO */
 goto L1650;
 L1720: /* Line 1720 */
 /* BASIC: GOTO */
 goto L440;
 L1730: /* Line 1730 */
 goto bpp_end;
 bpp_end:
 return 0;
}
