#ifdef _MSC_VER
#ifndef _CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
#endif
#pragma warning(disable: 4996)
#pragma warning(disable: 4101)
#pragma warning(disable: 4244)
#pragma warning(disable: 4102)
#pragma warning(disable: 4311)
#pragma warning(disable: 4312)
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wstringop-truncation"
#pragma GCC diagnostic ignored "-Wrestrict"
#pragma GCC diagnostic ignored "-Wdouble-promotion"
#pragma GCC diagnostic ignored "-Wpointer-to-int-cast"
#pragma GCC diagnostic ignored "-Wint-to-pointer-cast"
#endif

/* Generated by BASIC++ Compiler for target: windows */
#define BPP_TARGET_WINDOWS
#define BPP_SUPPORT_MULTITASKING 1
#define BPP_SUPPORT_GRAPHICS 1
#define BPP_SUPPORT_FILESYSTEM 1

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* Windows specific platform headers */
#include <windows.h>

/* === Runtime Variables === */
static double bpp_vars[1024]; /* A-Z and named */
static char bpp_strvars[1024][256]; /* A$-Z$ and named */
static double bpp_at_array[4096]; /* @() legacy array */
static int bpp_print_width = 14;

/* === GOSUB Stack === */
#define BPP_MAX_STACK 256
static int bpp_gosub_stack[BPP_MAX_STACK];
static int bpp_gosub_sp = 0;

/* === DIM Arrays === */
#define BPP_MAX_DIM 64
#define BPP_MAX_ELEM 4194304
static double bpp_dim_pool[BPP_MAX_ELEM];
static int bpp_dim_used = 0;
typedef struct { char name[32]; int d1,d2,off; } BppDim;
static BppDim bpp_dims[BPP_MAX_DIM];
static int bpp_dim_count = 0;

static void bpp_dim_alloc(const char *nm, int d1, int d2) {
 int sz = (d1+1) * (d2>0 ? d2+1 : 1);
 BppDim *d = &bpp_dims[bpp_dim_count++];
 strncpy(d->name, nm, 31); d->name[31]='\0';
 d->d1=d1; d->d2=d2; d->off=bpp_dim_used;
 memset(&bpp_dim_pool[bpp_dim_used], 0, sizeof(double)*(size_t)sz);
 bpp_dim_used += sz;
}

static double *bpp_dim_ref(const char *nm, int i1, int i2) {
 int k;
 for (k=0; k<bpp_dim_count; k++) {
 if (strcmp(bpp_dims[k].name, nm)==0) {
 int idx = (bpp_dims[k].d2>0)
 ? i1*(bpp_dims[k].d2+1)+i2 : i1;
 return &bpp_dim_pool[bpp_dims[k].off + idx];
 }
 }
 fprintf(stderr, "Array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === String DIM arrays === */
#define BPP_MAX_STRDIM 26
#define BPP_MAX_STRDIM_SIZE 256
static struct { char nm[16]; int d1; int d2;
 char data[BPP_MAX_STRDIM_SIZE][256]; } bpp_strdims[BPP_MAX_STRDIM];
static int bpp_strdim_count = 0;

static char *bpp_strdim_ref(const char *nm, int i1, int i2) {
 int k;
 (void)i2;
 for (k = 0; k < bpp_strdim_count; k++) {
 if (strcmp(bpp_strdims[k].nm, nm) == 0) {
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[k].data[i1];
 }
 }
 /* Auto-create */
 if (bpp_strdim_count < BPP_MAX_STRDIM) {
 int j;
 strncpy(bpp_strdims[bpp_strdim_count].nm, nm, 15);
 bpp_strdims[bpp_strdim_count].nm[15] = '\0';
 for (j = 0; j < BPP_MAX_STRDIM_SIZE; j++)
 bpp_strdims[bpp_strdim_count].data[j][0] = '\0';
 bpp_strdim_count++;
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[bpp_strdim_count-1].data[i1];
 }
 fprintf(stderr, "String array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === DATA/READ support === */
#define BPP_MAX_DATA 4096
static const char *bpp_data_pool[BPP_MAX_DATA];
static int bpp_data_count = 0;
static int bpp_data_ptr = 0;

static double bpp_read_num(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return atof(bpp_data_pool[bpp_data_ptr++]);
}

static const char *bpp_read_str(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return bpp_data_pool[bpp_data_ptr++];
}

/* === String helpers === */
static char bpp_strtmp[8][256];
static int bpp_strtmp_idx = 0;

static char *bpp_tmp(void) {
 char *p = bpp_strtmp[bpp_strtmp_idx];
 bpp_strtmp_idx = (bpp_strtmp_idx+1) & 7;
 return p;
}

static const char *bpp_concat(const char *a, const char *b) {
 char *t = bpp_tmp();
 t[0]='\0';
 strncat(t, a, 254);
 strncat(t, b, 254-(int)strlen(t));
 return t;
}

static const char *bpp_left(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_right(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s+len-n, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_mid(const char *s, int st, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (st<0) st=0;
 if (st>len) st=len;
 if (n<0) n=0;
 if (st+n>len) n=len-st;
 memcpy(t, s+st, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_chr(int n) {
 char *t = bpp_tmp();
 t[0]=(char)n; t[1]='\0';
 return t;
}

static const char *bpp_str(double n) {
 char *t = bpp_tmp();
 sprintf(t, "%g", n);
 return t;
}

/* === TAB helper === */
static const char *bpp_tab(int col) {
 static char buf[256];
 int i;
 if (col < 0) col = 0;
 if (col > 255) col = 255;
 for (i = 0; i < col; i++) buf[i] = ' ';
 buf[col] = '\0';
 return buf;
}

/* === DEF FN support === */
#define BPP_MAX_FN 26
typedef double (*BppFnPtr)(double);
static double bpp_fn_param;

int main(void) {
  bpp_data_pool[0] = "A";
  bpp_data_pool[1] = "B";
  bpp_data_pool[2] = "C";
  bpp_data_pool[3] = "D";
  bpp_data_pool[4] = "E";
  bpp_data_pool[5] = "F";
  bpp_data_pool[6] = "G";
  bpp_data_pool[7] = "H";
  bpp_data_pool[8] = "I";
  bpp_data_pool[9] = "J";
  bpp_data_pool[10] = "K";
  bpp_data_pool[11] = "L";
  bpp_data_pool[12] = "M";
  bpp_data_pool[13] = "N";
  bpp_data_pool[14] = "O";
  bpp_data_pool[15] = "P";
  bpp_data_pool[16] = "1";
  bpp_data_pool[17] = "2";
  bpp_data_pool[18] = "3";
  bpp_data_pool[19] = "4";
  bpp_data_count = 20;

 /* Line 5 */
 printf("%s", bpp_tab((int)(33)));
 printf("%s", "PIZZA");
 printf("\n");
 /* Line 10 */
 printf("%s", bpp_tab((int)(15)));
 printf("%s", "CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY");
 printf("\n");
 /* Line 15 */
  printf("\n");
  printf("\n");
  printf("\n");
 /* Line 20 */
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("S$", (int)(16), 0);
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("M$", (int)(4), 0);
 /* Line 30 */
 printf("%s", "PIZZA DELIVERY GAME");
 printf("\n");
  printf("\n");
 /* Line 50 */
 printf("%s", "WHAT IS YOUR FIRST NAME");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[13], _buf, 255); }
  printf("\n");
 /* Line 80 */
 printf("%s", "HI, ");
 printf("%s", bpp_strvars[13]);
 printf("%s", ".  IN THIS GAME YOU ARE TO TAKE ORDERS");
 printf("\n");
 /* Line 90 */
 printf("%s", "FOR PIZZAS.  THEN YOU ARE TO TELL A DELIVERY BOY");
 printf("\n");
 /* Line 100 */
 printf("%s", "WHERE TO DELIVER THE ORDERED PIZZAS.");
 printf("\n");
  printf("\n");
  printf("\n");
 /* Line 140 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_0:;
 /* Line 150 */
 /* BASIC: READ statement */
 strncpy(bpp_strvars[18], bpp_read_str(), 255);
 /* Line 160 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= 16) goto bpp_for_0;
 /* Line 170 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_1:;
 /* Line 180 */
 /* BASIC: READ statement */
 strncpy(bpp_strvars[12], bpp_read_str(), 255);
 /* Line 190 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= 4) goto bpp_for_1;
 /* Line 200 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 210 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 230 */
 printf("%s", "MAP OF THE CITY OF HYATTSVILLE");
 printf("\n");
  printf("\n");
 /* Line 250 */
 printf("%s", " -----1-----2-----3-----4-----");
 printf("\n");
 /* Line 260 */
 bpp_vars[10] = 4;
 /* Line 270 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_2:;
 /* Line 280 */
 printf("%s", "-");
 printf("\n");
 printf("%s", "-");
 printf("\n");
 printf("%s", "-");
 printf("\n");
 printf("%s", "-");
 printf("\n");
 /* Line 320 */
 printf("%s", bpp_strdim_ref("M", (int)(bpp_vars[10]), 0));
 /* Line 330 */
 bpp_vars[26] = ((16 - (4 * bpp_vars[8])) + 1);
 /* Line 340 */
 printf("%s", "     ");
 printf("%s", bpp_strdim_ref("S", (int)(bpp_vars[26]), 0));
 printf("%s", "     ");
 printf("%s", bpp_strdim_ref("S", (int)((bpp_vars[26] + 1)), 0));
 printf("%s", "     ");
 printf("%s", bpp_strdim_ref("S", (int)((bpp_vars[26] + 2)), 0));
 printf("%s", "     ");
 /* Line 350 */
 printf("%s", bpp_strdim_ref("S", (int)((bpp_vars[26] + 3)), 0));
 printf("%s", "     ");
 printf("%s", bpp_strdim_ref("M", (int)(bpp_vars[10]), 0));
 printf("\n");
 /* Line 380 */
 bpp_vars[10] = (bpp_vars[10] - 1);
 /* Line 390 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= 4) goto bpp_for_2;
 /* Line 400 */
 printf("%s", "-");
 printf("\n");
 printf("%s", "-");
 printf("\n");
 printf("%s", "-");
 printf("\n");
 printf("%s", "-");
 printf("\n");
 /* Line 440 */
 printf("%s", " -----1-----2-----3-----4-----");
 printf("\n");
  printf("\n");
 /* Line 460 */
 printf("%s", "THE OUTPUT IS A MAP OF THE HOMES WHERE");
 printf("\n");
 /* Line 470 */
 printf("%s", "YOU ARE TO SEND PIZZAS.");
 printf("\n");
  printf("\n");
 /* Line 490 */
 printf("%s", "YOUR JOB IS TO GIVE A TRUCK DRIVER");
 printf("\n");
 /* Line 500 */
 printf("%s", "THE LOCATION OR COORDINATES OF THE");
 printf("\n");
 /* Line 510 */
 printf("%s", "HOME ORDERING THE PIZZA.");
 printf("\n");
  printf("\n");
 L520: /* Line 520 */
 printf("%s", "DO YOU NEED MORE DIRECTIONS");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[0], _buf, 255); }
 /* Line 530 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[0], "YES") == 0))) { /* BASIC: GOTO */
goto L590;
 }
 /* Line 540 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[0], "NO") == 0))) { /* BASIC: GOTO */
goto L750;
 }
 /* Line 550 */
 printf("%s", "'YES' OR 'NO' PLEASE, NOW THEN,");
 printf("\n");
 /* BASIC: GOTO */
 goto L520;
 L590: /* Line 590 */
  printf("\n");
 printf("%s", "SOMEBODY WILL ASK FOR A PIZZA TO BE");
 printf("\n");
 /* Line 600 */
 printf("%s", "DELIVERED.  THEN A DELIVERY BOY WILL");
 printf("\n");
 /* Line 610 */
 printf("%s", "ASK YOU FOR THE LOCATION.");
 printf("\n");
 printf("%s", "     EXAMPLE:");
 printf("\n");
 /* Line 620 */
 printf("%s", "THIS IS J.  PLEASE SEND A PIZZA.");
 printf("\n");
 /* Line 640 */
 printf("%s", "DRIVER TO ");
 printf("%s", bpp_strvars[13]);
 printf("%s", ".  WHERE DOES J LIVE?");
 printf("\n");
 /* Line 650 */
 printf("%s", "YOUR ANSWER WOULD BE 2,3");
 printf("\n");
  printf("\n");
 /* Line 660 */
 printf("%s", "UNDERSTAND");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[0], _buf, 255); }
 /* Line 670 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[0], "YES") == 0))) { /* BASIC: GOTO */
goto L690;
 }
 /* Line 680 */
 printf("%s", "THIS JOB IS DEFINITELY TOO DIFFICULT FOR YOU. THANKS ANYWAY");
 printf("\n");
 /* Line 685 */
 /* BASIC: GOTO */
 goto L999;
 L690: /* Line 690 */
 printf("%s", "GOOD.  YOU ARE NOW READY TO START TAKING ORDERS.");
 printf("\n");
  printf("\n");
 /* Line 700 */
 printf("%s", "GOOD LUCK!!");
 printf("\n");
  printf("\n");
 L750: /* Line 750 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_3:;
 /* Line 760 */
 bpp_vars[18] = floor(((((double)(rand() % (int)(1))) * 16) + 1));
  printf("\n");
 /* Line 770 */
 printf("%s", "HELLO ");
 printf("%s", bpp_strvars[13]);
 printf("%s", "'S PIZZA.  THIS IS ");
 printf("%s", bpp_strdim_ref("S", (int)(bpp_vars[18]), 0));
 printf("%s", ".");
 /* Line 775 */
 printf("%s", "  PLEASE SEND A PIZZA.");
 printf("\n");
 L780: /* Line 780 */
 printf("%s", "  DRIVER TO ");
 printf("%s", bpp_strvars[13]);
 printf("%s", ":  WHERE DOES ");
 printf("%s", bpp_strdim_ref("S", (int)(bpp_vars[18]), 0));
 printf("%s", " LIVE");
 /* Line 790 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   *bpp_dim_ref("A", (int)(1), 0) = _v; }
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   *bpp_dim_ref("A", (int)(2), 0) = _v; }
 /* Line 870 */
 bpp_vars[19] = (*bpp_dim_ref("A", (int)(1), 0) + ((*bpp_dim_ref("A", (int)(2), 0) - 1) * 4));
 /* Line 880 */
 /* BASIC: IF statement */
 if ((bpp_vars[19] == bpp_vars[18])) { /* BASIC: GOTO */
goto L920;
 }
 /* Line 890 */
 printf("%s", "THIS IS ");
 printf("%s", bpp_strdim_ref("S", (int)(bpp_vars[19]), 0));
 printf("%s", ".  I DID NOT ORDER A PIZZA.");
 printf("\n");
 /* Line 900 */
 printf("%s", "I LIVE AT ");
 { double _v = *bpp_dim_ref("A", (int)(1), 0); if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", ",");
 { double _v = *bpp_dim_ref("A", (int)(2), 0); if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("\n");
 /* Line 910 */
 /* BASIC: GOTO */
 goto L780;
 L920: /* Line 920 */
 printf("%s", "HELLO ");
 printf("\n");
 /* Line 930 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= 5) goto bpp_for_3;
 /* Line 940 */
  printf("\n");
 printf("%s", "DO YOU WANT TO DELIVER MORE PIZZAS");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[0], _buf, 255); }
 /* Line 960 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[0], "YES") == 0))) { /* BASIC: GOTO */
goto L750;
 }
 /* Line 970 */
  printf("\n");
 printf("%s", "O.K. ");
 printf("%s", bpp_strvars[13]);
 printf("%s", ", SEE YOU LATER!");
 printf("\n");
  printf("\n");
 L999: /* Line 999 */
 goto bpp_end;
 bpp_end:
 return 0;
}
