#ifdef _MSC_VER
#ifndef _CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
#endif
#pragma warning(disable: 4996)
#pragma warning(disable: 4101)
#pragma warning(disable: 4244)
#pragma warning(disable: 4102)
#pragma warning(disable: 4311)
#pragma warning(disable: 4312)
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wstringop-truncation"
#pragma GCC diagnostic ignored "-Wrestrict"
#pragma GCC diagnostic ignored "-Wdouble-promotion"
#pragma GCC diagnostic ignored "-Wpointer-to-int-cast"
#pragma GCC diagnostic ignored "-Wint-to-pointer-cast"
#endif

/* Generated by BASIC++ Compiler for target: windows */
#define BPP_TARGET_WINDOWS
#define BPP_SUPPORT_MULTITASKING 1
#define BPP_SUPPORT_GRAPHICS 1
#define BPP_SUPPORT_FILESYSTEM 1

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* Windows specific platform headers */
#include <windows.h>

/* === Runtime Variables === */
static double bpp_vars[1024]; /* A-Z and named */
static char bpp_strvars[1024][256]; /* A$-Z$ and named */
static double bpp_at_array[4096]; /* @() legacy array */
static int bpp_print_width = 14;

/* === GOSUB Stack === */
#define BPP_MAX_STACK 256
static int bpp_gosub_stack[BPP_MAX_STACK];
static int bpp_gosub_sp = 0;

/* === DIM Arrays === */
#define BPP_MAX_DIM 64
#define BPP_MAX_ELEM 4194304
static double bpp_dim_pool[BPP_MAX_ELEM];
static int bpp_dim_used = 0;
typedef struct { char name[32]; int d1,d2,off; } BppDim;
static BppDim bpp_dims[BPP_MAX_DIM];
static int bpp_dim_count = 0;

static void bpp_dim_alloc(const char *nm, int d1, int d2) {
 int sz = (d1+1) * (d2>0 ? d2+1 : 1);
 BppDim *d = &bpp_dims[bpp_dim_count++];
 strncpy(d->name, nm, 31); d->name[31]='\0';
 d->d1=d1; d->d2=d2; d->off=bpp_dim_used;
 memset(&bpp_dim_pool[bpp_dim_used], 0, sizeof(double)*(size_t)sz);
 bpp_dim_used += sz;
}

static double *bpp_dim_ref(const char *nm, int i1, int i2) {
 int k;
 for (k=0; k<bpp_dim_count; k++) {
 if (strcmp(bpp_dims[k].name, nm)==0) {
 int idx = (bpp_dims[k].d2>0)
 ? i1*(bpp_dims[k].d2+1)+i2 : i1;
 return &bpp_dim_pool[bpp_dims[k].off + idx];
 }
 }
 fprintf(stderr, "Array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === String DIM arrays === */
#define BPP_MAX_STRDIM 26
#define BPP_MAX_STRDIM_SIZE 256
static struct { char nm[16]; int d1; int d2;
 char data[BPP_MAX_STRDIM_SIZE][256]; } bpp_strdims[BPP_MAX_STRDIM];
static int bpp_strdim_count = 0;

static char *bpp_strdim_ref(const char *nm, int i1, int i2) {
 int k;
 (void)i2;
 for (k = 0; k < bpp_strdim_count; k++) {
 if (strcmp(bpp_strdims[k].nm, nm) == 0) {
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[k].data[i1];
 }
 }
 /* Auto-create */
 if (bpp_strdim_count < BPP_MAX_STRDIM) {
 int j;
 strncpy(bpp_strdims[bpp_strdim_count].nm, nm, 15);
 bpp_strdims[bpp_strdim_count].nm[15] = '\0';
 for (j = 0; j < BPP_MAX_STRDIM_SIZE; j++)
 bpp_strdims[bpp_strdim_count].data[j][0] = '\0';
 bpp_strdim_count++;
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[bpp_strdim_count-1].data[i1];
 }
 fprintf(stderr, "String array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === DATA/READ support === */
#define BPP_MAX_DATA 4096
static const char *bpp_data_pool[BPP_MAX_DATA];
static int bpp_data_count = 0;
static int bpp_data_ptr = 0;

static double bpp_read_num(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return atof(bpp_data_pool[bpp_data_ptr++]);
}

static const char *bpp_read_str(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return bpp_data_pool[bpp_data_ptr++];
}

/* === String helpers === */
static char bpp_strtmp[8][256];
static int bpp_strtmp_idx = 0;

static char *bpp_tmp(void) {
 char *p = bpp_strtmp[bpp_strtmp_idx];
 bpp_strtmp_idx = (bpp_strtmp_idx+1) & 7;
 return p;
}

static const char *bpp_concat(const char *a, const char *b) {
 char *t = bpp_tmp();
 t[0]='\0';
 strncat(t, a, 254);
 strncat(t, b, 254-(int)strlen(t));
 return t;
}

static const char *bpp_left(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_right(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s+len-n, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_mid(const char *s, int st, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (st<0) st=0;
 if (st>len) st=len;
 if (n<0) n=0;
 if (st+n>len) n=len-st;
 memcpy(t, s+st, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_chr(int n) {
 char *t = bpp_tmp();
 t[0]=(char)n; t[1]='\0';
 return t;
}

static const char *bpp_str(double n) {
 char *t = bpp_tmp();
 sprintf(t, "%g", n);
 return t;
}

/* === TAB helper === */
static const char *bpp_tab(int col) {
 static char buf[256];
 int i;
 if (col < 0) col = 0;
 if (col > 255) col = 255;
 for (i = 0; i < col; i++) buf[i] = ' ';
 buf[col] = '\0';
 return buf;
}

/* === DEF FN support === */
#define BPP_MAX_FN 26
typedef double (*BppFnPtr)(double);
static double bpp_fn_param;

static double bpp_fn_A(double X) {
 return floor((10 * ((double)(rand() % (int)(1)))));
}

static double bpp_fn_B(double X) {
 return (bpp_vars[23] - (100 * floor((bpp_vars[23] / 100))));
}

int main(void) {
  bpp_data_count = 0;

 /* Line 2 */
 printf("%s", bpp_tab((int)(33)));
 printf("%s", "POKER");
 printf("\n");
 /* Line 4 */
 printf("%s", bpp_tab((int)(15)));
 printf("%s", "CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY");
 printf("\n");
 /* Line 6 */
  printf("\n");
  printf("\n");
  printf("\n");
 /* Line 10 */
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("A", (int)(50), 0);
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("B", (int)(15), 0);
 /* Line 20 */
 /* DEF FNA - defined as inline */
 /* Line 30 */
 /* DEF FNB - defined as inline */
 /* Line 40 */
 printf("%s", "WELCOME TO THE CASINO.  WE EACH HAVE $200.");
 printf("\n");
 /* Line 50 */
 printf("%s", "I WILL OPEN THE BETTING BEFORE THE DRAW; YOU OPEN AFTER.");
 printf("\n");
 /* Line 60 */
 printf("%s", "TO FOLD BET 0; TO CHECK BET .5.");
 printf("\n");
 /* Line 70 */
 printf("%s", "ENOUGH TALK -- LET'S GET DOWN TO BUSINESS.");
 printf("\n");
 /* Line 80 */
  printf("\n");
 /* Line 90 */
 bpp_vars[14] = 1;
 /* Line 100 */
 bpp_vars[2] = 200;
 /* Line 110 */
 bpp_vars[18] = 200;
 L120: /* Line 120 */
 bpp_vars[15] = 0;
 /* Line 130 */
 /* REM  */
 L140: /* Line 140 */
  printf("\n");
 /* Line 150 */
 /* BASIC: IF statement */
 if ((bpp_vars[2] <= 5)) { /* BASIC: GOTO */
goto L3670;
 }
 /* Line 160 */
 printf("%s", "THE ANTE IS $5.  I WILL DEAL:");
 printf("\n");
 /* Line 170 */
  printf("\n");
 /* Line 180 */
 /* BASIC: IF statement */
 if ((bpp_vars[18] > 5)) { /* BASIC: GOTO */
goto L200;
 }
 /* Line 190 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 0; goto L3830;
 bpp_ret_0:;
 L200: /* Line 200 */
 bpp_vars[15] = (bpp_vars[15] + 10);
 /* Line 210 */
 bpp_vars[18] = (bpp_vars[18] - 5);
 /* Line 220 */
 bpp_vars[2] = (bpp_vars[2] - 5);
 /* Line 230 */
 /* BASIC: FOR loop initialization */
 bpp_vars[25] = 1;
 bpp_for_0:;
 /* Line 240 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 1; goto L1740;
 bpp_ret_1:;
 /* Line 250 */
 /* BASIC: NEXT loop step */
 bpp_vars[25] += 1;
 if (bpp_vars[25] <= 10) goto bpp_for_0;
 /* Line 260 */
 printf("%s", "YOUR HAND:");
 printf("\n");
 /* Line 270 */
 bpp_vars[13] = 1;
 /* Line 280 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 2; goto L1850;
 bpp_ret_2:;
 /* Line 290 */
 bpp_vars[13] = 6;
 /* Line 300 */
 bpp_vars[8] = 2;
 /* Line 310 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 3; goto L2170;
 bpp_ret_3:;
 /* Line 320 */
  printf("\n");
 /* Line 330 */
 /* BASIC: IF statement */
 if ((bpp_vars[8] != 6)) { /* BASIC: GOTO */
goto L470;
 }
 /* Line 340 */
 /* REM IF FNA(0)<=7 THEN 370 */
 /* Line 350 */
 bpp_vars[23] = 11100;
 /* Line 360 */
 /* BASIC: GOTO */
 goto L420;
 /* Line 370 */
 /* REM IF FNA(0)<=7 THEN 400 */
 /* Line 380 */
 bpp_vars[23] = 11110;
 /* Line 390 */
 /* BASIC: GOTO */
 goto L420;
 /* Line 400 */
 /* REM IF FNA(0)>=1 THEN 450 */
 /* Line 410 */
 bpp_vars[23] = 11111;
 L420: /* Line 420 */
 bpp_vars[8] = 7;
 /* Line 430 */
 bpp_vars[25] = 23;
 /* Line 440 */
 /* BASIC: GOTO */
 goto L580;
 /* Line 450 */
 bpp_vars[25] = 1;
 /* Line 460 */
 /* BASIC: GOTO */
 goto L510;
 L470: /* Line 470 */
 /* BASIC: IF statement */
 if ((bpp_vars[20] >= 13)) { /* BASIC: GOTO */
goto L540;
 }
 /* Line 480 */
 /* REM IF FNA(0)>=2 THEN 500 */
 /* Line 490 */
 /* BASIC: GOTO */
 goto L420;
 /* Line 500 */
 bpp_vars[25] = 0;
 L510: /* Line 510 */
 bpp_vars[10] = 0;
 /* Line 520 */
 printf("%s", "I CHECK.");
 printf("\n");
 /* Line 530 */
 /* BASIC: GOTO */
 goto L620;
 L540: /* Line 540 */
 /* BASIC: IF statement */
 if ((bpp_vars[20] <= 16)) { /* BASIC: GOTO */
goto L570;
 }
 /* Line 550 */
 bpp_vars[25] = 2;
 /* Line 560 */
 /* REM IF FNA(0)>=1 THEN 580 */
 L570: /* Line 570 */
 bpp_vars[25] = 35;
 L580: /* Line 580 */
 /* REM V=Z+FNA(0) */
 /* Line 590 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 4; goto L3480;
 bpp_ret_4:;
 /* Line 600 */
 printf("%s", "I'LL OPEN WITH $");
 printf("\n");
 /* Line 610 */
 bpp_vars[10] = bpp_vars[21];
 L620: /* Line 620 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 5; goto L3050;
 bpp_ret_5:;
 /* Line 630 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 6; goto L650;
 bpp_ret_6:;
 /* Line 640 */
 /* BASIC: GOTO */
 goto L820;
 L650: /* Line 650 */
 /* BASIC: IF statement */
 if ((bpp_vars[8] != 3)) { /* BASIC: GOTO */
goto L760;
 }
 /* Line 660 */
  printf("\n");
 L670: /* Line 670 */
 printf("%s", "I WIN.");
 printf("\n");
 /* Line 680 */
 bpp_vars[2] = (bpp_vars[2] + bpp_vars[15]);
 L690: /* Line 690 */
 printf("%s", "NOW I HAVE $");
 printf("\n");
 L700: /* Line 700 */
 printf("%s", "DO YOU WISH TO CONTINUE");
 /* Line 710 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[7], _buf, 255); }
 /* Line 720 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[7], "YES") == 0))) { /* BASIC: GOTO */
goto L120;
 }
 /* Line 730 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[7], "NO") == 0))) { /* BASIC: GOTO */
goto L4100;
 }
 /* Line 740 */
 printf("%s", "ANSWER YES OR NO, PLEASE.");
 printf("\n");
 /* Line 750 */
 /* BASIC: GOTO */
 goto L700;
 L760: /* Line 760 */
 /* BASIC: IF statement */
 if ((bpp_vars[8] != 4)) { /* BASIC: GOTO */
goto L810;
 }
 /* Line 770 */
  printf("\n");
 L780: /* Line 780 */
 printf("%s", "YOU WIN.");
 printf("\n");
 /* Line 790 */
 bpp_vars[18] = (bpp_vars[18] + bpp_vars[15]);
 /* Line 800 */
 /* BASIC: GOTO */
 goto L690;
 L810: /* Line 810 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L820: /* Line 820 */
  printf("\n");
 /* Line 830 */
 printf("%s", "NOW WE DRAW -- HOW MANY CARDS DO YOU WANT");
 L840: /* Line 840 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[19] = _v; }
 /* Line 850 */
 /* BASIC: IF statement */
 if ((bpp_vars[19] == 0)) { /* BASIC: GOTO */
goto L980;
 }
 /* Line 860 */
 bpp_vars[25] = 10;
 /* Line 870 */
 /* BASIC: IF statement */
 if ((bpp_vars[19] < 4)) { /* BASIC: GOTO */
goto L900;
 }
 /* Line 880 */
 printf("%s", "YOU CAN'T DRAW MORE THAN THREE CARDS.");
 printf("\n");
 /* Line 890 */
 /* BASIC: GOTO */
 goto L840;
 L900: /* Line 900 */
 printf("%s", "WHAT ARE THEIR NUMBERS:");
 printf("\n");
 /* Line 910 */
 /* BASIC: FOR loop initialization */
 bpp_vars[16] = 1;
 bpp_for_1:;
 /* Line 920 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[20] = _v; }
 /* Line 930 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 7; goto L1730;
 bpp_ret_7:;
 /* Line 940 */
 /* BASIC: NEXT loop step */
 bpp_vars[16] += 1;
 if (bpp_vars[16] <= bpp_vars[19]) goto bpp_for_1;
 /* Line 950 */
 printf("%s", "YOUR NEW HAND:");
 printf("\n");
 /* Line 960 */
 bpp_vars[13] = 1;
 /* Line 970 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 8; goto L1850;
 bpp_ret_8:;
 L980: /* Line 980 */
 bpp_vars[25] = (10 + bpp_vars[19]);
 /* Line 990 */
 /* BASIC: FOR loop initialization */
 bpp_vars[20] = 6;
 bpp_for_2:;
 /* Line 1000 */
 /* BASIC: IF statement */
 if ((floor((bpp_vars[23] / (pow(10, (bpp_vars[20] - 6))))) != (10 * floor((bpp_vars[23] / (pow(10, (bpp_vars[20] - 5)))))))) { /* BASIC: GOTO */
goto L1020;
 }
 /* Line 1010 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 9; goto L1730;
 bpp_ret_9:;
 L1020: /* Line 1020 */
 /* BASIC: NEXT loop step */
 bpp_vars[20] += 1;
 if (bpp_vars[20] <= 10) goto bpp_for_2;
 /* Line 1030 */
  printf("\n");
 /* Line 1040 */
 printf("%s", "I AM TAKING");
 printf("\n");
 /* Line 1050 */
 /* BASIC: IF statement */
 if ((bpp_vars[25] == (11 + bpp_vars[19]))) { /* BASIC: GOTO */
goto L1090;
 }
 /* Line 1060 */
 printf("%s", "S");
 printf("\n");
 /* Line 1070 */
  printf("\n");
 /* Line 1080 */
 /* BASIC: GOTO */
 goto L1100;
 L1090: /* Line 1090 */
  printf("\n");
 L1100: /* Line 1100 */
 bpp_vars[13] = 6;
 /* Line 1110 */
 bpp_vars[21] = bpp_vars[8];
 /* Line 1120 */
 bpp_vars[8] = 1;
 /* Line 1130 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 10; goto L2170;
 bpp_ret_10:;
 /* Line 1140 */
 bpp_vars[1] = bpp_vars[20];
 /* Line 1150 */
 bpp_vars[12] = bpp_vars[3];
 /* Line 1160 */
 /* BASIC: IF statement */
 if ((bpp_vars[21] != 7)) { /* BASIC: GOTO */
goto L1190;
 }
 /* Line 1170 */
 bpp_vars[25] = 28;
 /* Line 1180 */
 /* BASIC: GOTO */
 goto L1330;
 L1190: /* Line 1190 */
 /* BASIC: IF statement */
 if ((bpp_vars[8] != 6)) { /* BASIC: GOTO */
goto L1220;
 }
 /* Line 1200 */
 bpp_vars[25] = 1;
 /* Line 1210 */
 /* BASIC: GOTO */
 goto L1330;
 L1220: /* Line 1220 */
 /* BASIC: IF statement */
 if ((bpp_vars[20] >= 13)) { /* BASIC: GOTO */
goto L1270;
 }
 /* Line 1230 */
 bpp_vars[25] = 2;
 /* Line 1240 */
 /* REM IF FNA(0)<>6 THEN 1260 */
 /* Line 1250 */
 bpp_vars[25] = 19;
 /* Line 1260 */
 /* BASIC: GOTO */
 goto L1330;
 L1270: /* Line 1270 */
 /* BASIC: IF statement */
 if ((bpp_vars[20] >= 16)) { /* BASIC: GOTO */
goto L1320;
 }
 /* Line 1280 */
 bpp_vars[25] = 19;
 /* Line 1290 */
 /* REM IF FNA(0)<>8 THEN 1310 */
 /* Line 1300 */
 bpp_vars[25] = 11;
 /* Line 1310 */
 /* BASIC: GOTO */
 goto L1330;
 L1320: /* Line 1320 */
 bpp_vars[25] = 2;
 L1330: /* Line 1330 */
 bpp_vars[10] = 0;
 /* Line 1340 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 11; goto L3050;
 bpp_ret_11:;
 /* Line 1350 */
 /* BASIC: IF statement */
 if ((bpp_vars[19] != 0.5)) { /* BASIC: GOTO */
goto L1450;
 }
 /* Line 1360 */
 /* BASIC: IF statement */
 if ((bpp_vars[21] == 7)) { /* BASIC: GOTO */
goto L1400;
 }
 /* Line 1370 */
 /* BASIC: IF statement */
 if ((bpp_vars[8] != 6)) { /* BASIC: GOTO */
goto L1400;
 }
 /* Line 1380 */
 printf("%s", "I'LL CHECK");
 printf("\n");
 /* Line 1390 */
 /* BASIC: GOTO */
 goto L1460;
 L1400: /* Line 1400 */
 /* REM V=Z+FNA(0) */
 /* Line 1410 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 12; goto L3480;
 bpp_ret_12:;
 /* Line 1420 */
 printf("%s", "I'LL BET $");
 printf("\n");
 /* Line 1430 */
 bpp_vars[10] = bpp_vars[21];
 /* Line 1440 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 13; goto L3060;
 bpp_ret_13:;
 L1450: /* Line 1450 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 14; goto L650;
 bpp_ret_14:;
 L1460: /* Line 1460 */
  printf("\n");
 /* Line 1470 */
 printf("%s", "NOW WE COMPARE HANDS:");
 printf("\n");
 /* Line 1480 */
 strncpy(bpp_strvars[9], bpp_strvars[7], 255); bpp_strvars[9][255]='\0';
 /* Line 1490 */
 strncpy(bpp_strvars[10], bpp_strvars[8], 255); bpp_strvars[10][255]='\0';
 /* Line 1500 */
 printf("%s", "MY HAND:");
 printf("\n");
 /* Line 1510 */
 bpp_vars[13] = 6;
 /* Line 1520 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 15; goto L1850;
 bpp_ret_15:;
 /* Line 1530 */
 bpp_vars[13] = 1;
 /* Line 1540 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 16; goto L2170;
 bpp_ret_16:;
 /* Line 1550 */
  printf("\n");
 /* Line 1560 */
 printf("%s", "YOU HAVE ");
 /* Line 1570 */
 bpp_vars[10] = bpp_vars[3];
 /* Line 1580 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 17; goto L3690;
 bpp_ret_17:;
 /* Line 1590 */
 strncpy(bpp_strvars[7], bpp_strvars[9], 255); bpp_strvars[7][255]='\0';
 /* Line 1600 */
 strncpy(bpp_strvars[8], bpp_strvars[10], 255); bpp_strvars[8][255]='\0';
 /* Line 1610 */
 bpp_vars[10] = bpp_vars[12];
 /* Line 1620 */
 printf("%s", "AND I HAVE ");
 /* Line 1630 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 18; goto L3690;
 bpp_ret_18:;
 /* Line 1640 */
 /* BASIC: IF statement */
 if ((bpp_vars[1] > bpp_vars[20])) { /* BASIC: GOTO */
goto L670;
 }
 /* Line 1650 */
 /* BASIC: IF statement */
 if ((bpp_vars[20] > bpp_vars[1])) { /* BASIC: GOTO */
goto L780;
 }
 /* Line 1660 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[7], "A FLUS") == 0))) { /* BASIC: GOTO */
goto L1700;
 }
 /* Line 1662 */
 /* REM IF FNB(M)<FNB(D) THEN 780 */
 /* Line 1664 */
 /* REM IF FNB(M)>FNB(D) THEN 670 */
 L1670: /* Line 1670 */
 printf("%s", "THE HAND IS DRAWN.");
 printf("\n");
 /* Line 1680 */
 printf("%s", "ALL $");
 printf("\n");
 /* Line 1690 */
 /* BASIC: GOTO */
 goto L140;
 L1700: /* Line 1700 */
 /* REM IF FNB(M)>FNB(D) THEN 670 */
 /* Line 1710 */
 /* REM IF FNB(D)>FNB(M) THEN 780 */
 /* Line 1720 */
 /* BASIC: GOTO */
 goto L1670;
 L1730: /* Line 1730 */
 bpp_vars[25] = (bpp_vars[25] + 1);
 L1740: /* Line 1740 */
 *bpp_dim_ref("A", (int)(bpp_vars[25]), 0) = ((100 * floor((4 * ((double)(rand() % (int)(1)))))) + floor((100 * ((double)(rand() % (int)(1))))));
 /* Line 1750 */
 /* BASIC: IF statement */
 if ((floor((*bpp_dim_ref("A", (int)(bpp_vars[25]), 0) / 100)) > 3)) { /* BASIC: GOTO */
goto L1740;
 }
 /* Line 1760 */
 /* BASIC: IF statement */
 if (((*bpp_dim_ref("A", (int)(bpp_vars[25]), 0) - (100 * floor((*bpp_dim_ref("A", (int)(bpp_vars[25]), 0) / 100)))) > 12)) { /* BASIC: GOTO */
goto L1740;
 }
 /* Line 1765 */
 /* BASIC: IF statement */
 if ((bpp_vars[25] == 1)) { /* BASIC: GOTO */
goto L1840;
 }
 /* Line 1770 */
 /* BASIC: FOR loop initialization */
 bpp_vars[10] = 1;
 bpp_for_3:;
 /* Line 1780 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("A", (int)(bpp_vars[25]), 0) == *bpp_dim_ref("A", (int)(bpp_vars[10]), 0))) { /* BASIC: GOTO */
goto L1740;
 }
 /* Line 1790 */
 /* BASIC: NEXT loop step */
 bpp_vars[10] += 1;
 if (bpp_vars[10] <= (bpp_vars[25] - 1)) goto bpp_for_3;
 /* Line 1800 */
 /* BASIC: IF statement */
 if ((bpp_vars[25] <= 10)) { /* BASIC: GOTO */
goto L1840;
 }
 /* Line 1810 */
 bpp_vars[13] = *bpp_dim_ref("A", (int)(bpp_vars[20]), 0);
 /* Line 1820 */
 *bpp_dim_ref("A", (int)(bpp_vars[20]), 0) = *bpp_dim_ref("A", (int)(bpp_vars[25]), 0);
 /* Line 1830 */
 *bpp_dim_ref("A", (int)(bpp_vars[25]), 0) = bpp_vars[13];
 L1840: /* Line 1840 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L1850: /* Line 1850 */
 /* BASIC: FOR loop initialization */
 bpp_vars[25] = bpp_vars[13];
 bpp_for_4:;
 /* Line 1860 */
 { double _v = bpp_vars[25]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("\n");
 /* Line 1870 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 19; goto L1950;
 bpp_ret_19:;
 /* Line 1880 */
 printf("%s", " OF");
 /* Line 1890 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 20; goto L2070;
 bpp_ret_20:;
 /* Line 1900 */
 /* BASIC: IF statement */
 if (((bpp_vars[25] / 2) != floor((bpp_vars[25] / 2)))) { /* BASIC: GOTO */
goto L1920;
 }
 /* Line 1910 */
  printf("\n");
 L1920: /* Line 1920 */
 /* BASIC: NEXT loop step */
 bpp_vars[25] += 1;
 if (bpp_vars[25] <= (bpp_vars[13] + 4)) goto bpp_for_4;
 /* Line 1930 */
  printf("\n");
 /* Line 1940 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L1950: /* Line 1950 */
 /* REM K=FNB(A(Z)) */
 L1960: /* Line 1960 */
 /* BASIC: IF statement */
 if ((bpp_vars[10] != 9)) { /* BASIC: GOTO */
goto L1980;
 }
 /* Line 1970 */
 printf("%s", "JACK");
 L1980: /* Line 1980 */
 /* BASIC: IF statement */
 if ((bpp_vars[10] != 10)) { /* BASIC: GOTO */
goto L2000;
 }
 /* Line 1990 */
 printf("%s", "QUEEN");
 L2000: /* Line 2000 */
 /* BASIC: IF statement */
 if ((bpp_vars[10] != 11)) { /* BASIC: GOTO */
goto L2020;
 }
 /* Line 2010 */
 printf("%s", "KING");
 L2020: /* Line 2020 */
 /* BASIC: IF statement */
 if ((bpp_vars[10] != 12)) { /* BASIC: GOTO */
goto L2040;
 }
 /* Line 2030 */
 printf("%s", "ACE");
 L2040: /* Line 2040 */
 /* BASIC: IF statement */
 if ((bpp_vars[10] >= 9)) { /* BASIC: GOTO */
goto L2060;
 }
 /* Line 2050 */
 { double _v = (bpp_vars[10] + 2); if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 L2060: /* Line 2060 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L2070: /* Line 2070 */
 bpp_vars[10] = floor((*bpp_dim_ref("A", (int)(bpp_vars[25]), 0) / 100));
 L2080: /* Line 2080 */
 /* BASIC: IF statement */
 if ((bpp_vars[10] != 0)) { /* BASIC: GOTO */
goto L2100;
 }
 /* Line 2090 */
 printf("%s", " CLUBS");
 L2100: /* Line 2100 */
 /* BASIC: IF statement */
 if ((bpp_vars[10] != 1)) { /* BASIC: GOTO */
goto L2120;
 }
 /* Line 2110 */
 printf("%s", " DIAMONDS");
 L2120: /* Line 2120 */
 /* BASIC: IF statement */
 if ((bpp_vars[10] != 2)) { /* BASIC: GOTO */
goto L2140;
 }
 /* Line 2130 */
 printf("%s", " HEARTS");
 L2140: /* Line 2140 */
 /* BASIC: IF statement */
 if ((bpp_vars[10] != 3)) { /* BASIC: GOTO */
goto L2160;
 }
 /* Line 2150 */
 printf("%s", " SPADES");
 L2160: /* Line 2160 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L2170: /* Line 2170 */
 bpp_vars[20] = 0;
 /* Line 2180 */
 /* BASIC: FOR loop initialization */
 bpp_vars[25] = bpp_vars[13];
 bpp_for_5:;
 /* Line 2190 */
 /* REM B(Z)=FNB(A(Z)) */
 /* Line 2200 */
 /* BASIC: IF statement */
 if ((bpp_vars[25] == (bpp_vars[13] + 4))) { /* BASIC: GOTO */
goto L2230;
 }
 /* Line 2210 */
 /* BASIC: IF statement */
 if ((floor((*bpp_dim_ref("A", (int)(bpp_vars[25]), 0) / 100)) != floor((*bpp_dim_ref("A", (int)((bpp_vars[25] + 1)), 0) / 100)))) { /* BASIC: GOTO */
goto L2230;
 }
 /* Line 2220 */
 bpp_vars[20] = (bpp_vars[20] + 1);
 L2230: /* Line 2230 */
 /* BASIC: NEXT loop step */
 bpp_vars[25] += 1;
 if (bpp_vars[25] <= (bpp_vars[13] + 4)) goto bpp_for_5;
 /* Line 2240 */
 /* BASIC: IF statement */
 if ((bpp_vars[20] != 4)) { /* BASIC: GOTO */
goto L2310;
 }
 /* Line 2250 */
 bpp_vars[23] = 11111;
 /* Line 2260 */
 bpp_vars[3] = *bpp_dim_ref("A", (int)(bpp_vars[13]), 0);
 /* Line 2270 */
 strncpy(bpp_strvars[7], "A FLUS", 255); bpp_strvars[7][255]='\0';
 /* Line 2280 */
 strncpy(bpp_strvars[8], "H IN", 255); bpp_strvars[8][255]='\0';
 /* Line 2290 */
 bpp_vars[20] = 15;
 /* Line 2300 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L2310: /* Line 2310 */
 /* BASIC: FOR loop initialization */
 bpp_vars[25] = bpp_vars[13];
 bpp_for_6:;
 /* Line 2320 */
 /* BASIC: FOR loop initialization */
 bpp_vars[10] = (bpp_vars[25] + 1);
 bpp_for_7:;
 /* Line 2330 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("B", (int)(bpp_vars[25]), 0) <= *bpp_dim_ref("B", (int)(bpp_vars[10]), 0))) { /* BASIC: GOTO */
goto L2390;
 }
 /* Line 2340 */
 bpp_vars[23] = *bpp_dim_ref("A", (int)(bpp_vars[25]), 0);
 /* Line 2350 */
 *bpp_dim_ref("A", (int)(bpp_vars[25]), 0) = *bpp_dim_ref("A", (int)(bpp_vars[10]), 0);
 /* Line 2360 */
 *bpp_dim_ref("B", (int)(bpp_vars[25]), 0) = *bpp_dim_ref("B", (int)(bpp_vars[10]), 0);
 /* Line 2370 */
 *bpp_dim_ref("A", (int)(bpp_vars[10]), 0) = bpp_vars[23];
 /* Line 2380 */
 *bpp_dim_ref("B", (int)(bpp_vars[10]), 0) = (*bpp_dim_ref("A", (int)(bpp_vars[10]), 0) - (100 * floor((*bpp_dim_ref("A", (int)(bpp_vars[10]), 0) / 100))));
 L2390: /* Line 2390 */
 /* BASIC: NEXT loop step */
 bpp_vars[10] += 1;
 if (bpp_vars[10] <= (bpp_vars[13] + 4)) goto bpp_for_7;
 /* Line 2400 */
 /* BASIC: NEXT loop step */
 bpp_vars[25] += 1;
 if (bpp_vars[25] <= (bpp_vars[13] + 3)) goto bpp_for_6;
 /* Line 2410 */
 bpp_vars[23] = 0;
 /* Line 2420 */
 /* BASIC: FOR loop initialization */
 bpp_vars[25] = bpp_vars[13];
 bpp_for_8:;
 /* Line 2430 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("B", (int)(bpp_vars[25]), 0) != *bpp_dim_ref("B", (int)((bpp_vars[25] + 1)), 0))) { /* BASIC: GOTO */
goto L2470;
 }
 /* Line 2440 */
 bpp_vars[23] = (bpp_vars[23] + (11 * (pow(10, (bpp_vars[25] - bpp_vars[13])))));
 /* Line 2450 */
 bpp_vars[3] = *bpp_dim_ref("A", (int)(bpp_vars[25]), 0);
 /* Line 2460 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 21; goto L2760;
 bpp_ret_21:;
 L2470: /* Line 2470 */
 /* BASIC: NEXT loop step */
 bpp_vars[25] += 1;
 if (bpp_vars[25] <= (bpp_vars[13] + 3)) goto bpp_for_8;
 /* Line 2480 */
 /* BASIC: IF statement */
 if ((bpp_vars[23] != 0)) { /* BASIC: GOTO */
goto L2620;
 }
 /* Line 2490 */
 /* BASIC: IF statement */
 if (((*bpp_dim_ref("B", (int)(bpp_vars[13]), 0) + 3) != *bpp_dim_ref("B", (int)((bpp_vars[13] + 3)), 0))) { /* BASIC: GOTO */
goto L2520;
 }
 /* Line 2500 */
 bpp_vars[23] = 1111;
 /* Line 2510 */
 bpp_vars[20] = 10;
 L2520: /* Line 2520 */
 /* BASIC: IF statement */
 if (((*bpp_dim_ref("B", (int)((bpp_vars[13] + 1)), 0) + 3) != *bpp_dim_ref("B", (int)((bpp_vars[13] + 4)), 0))) { /* BASIC: GOTO */
goto L2620;
 }
 /* Line 2530 */
 /* BASIC: IF statement */
 if ((bpp_vars[20] != 10)) { /* BASIC: GOTO */
goto L2600;
 }
 /* Line 2540 */
 bpp_vars[20] = 14;
 /* Line 2550 */
 strncpy(bpp_strvars[7], "STRAIG", 255); bpp_strvars[7][255]='\0';
 /* Line 2560 */
 strncpy(bpp_strvars[8], "HT", 255); bpp_strvars[8][255]='\0';
 /* Line 2570 */
 bpp_vars[23] = 11111;
 /* Line 2580 */
 bpp_vars[3] = *bpp_dim_ref("A", (int)((bpp_vars[13] + 4)), 0);
 /* Line 2590 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L2600: /* Line 2600 */
 bpp_vars[20] = 10;
 /* Line 2610 */
 bpp_vars[23] = 11110;
 L2620: /* Line 2620 */
 /* BASIC: IF statement */
 if ((bpp_vars[20] >= 10)) { /* BASIC: GOTO */
goto L2690;
 }
 /* Line 2630 */
 bpp_vars[3] = *bpp_dim_ref("A", (int)((bpp_vars[13] + 4)), 0);
 /* Line 2640 */
 strncpy(bpp_strvars[7], "SCHMAL", 255); bpp_strvars[7][255]='\0';
 /* Line 2650 */
 strncpy(bpp_strvars[8], "TZ, ", 255); bpp_strvars[8][255]='\0';
 /* Line 2660 */
 bpp_vars[20] = 9;
 /* Line 2670 */
 bpp_vars[23] = 11000;
 /* Line 2680 */
 /* BASIC: GOTO */
 goto L2740;
 L2690: /* Line 2690 */
 /* BASIC: IF statement */
 if ((bpp_vars[20] != 10)) { /* BASIC: GOTO */
goto L2720;
 }
 /* Line 2700 */
 /* BASIC: IF statement */
 if ((bpp_vars[8] == 1)) { /* BASIC: GOTO */
goto L2740;
 }
 /* Line 2710 */
 /* BASIC: GOTO */
 goto L2750;
 L2720: /* Line 2720 */
 /* BASIC: IF statement */
 if ((bpp_vars[20] > 12)) { /* BASIC: GOTO */
goto L2750;
 }
 /* Line 2730 */
 /* REM IF FNB(D)>6 THEN 2750 */
 L2740: /* Line 2740 */
 bpp_vars[8] = 6;
 L2750: /* Line 2750 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L2760: /* Line 2760 */
 /* BASIC: IF statement */
 if ((bpp_vars[20] >= 11)) { /* BASIC: GOTO */
goto L2810;
 }
 /* Line 2770 */
 bpp_vars[20] = 11;
 /* Line 2780 */
 strncpy(bpp_strvars[7], "A PAIR", 255); bpp_strvars[7][255]='\0';
 /* Line 2790 */
 strncpy(bpp_strvars[8], " OF ", 255); bpp_strvars[8][255]='\0';
 /* Line 2800 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L2810: /* Line 2810 */
 /* BASIC: IF statement */
 if ((bpp_vars[20] != 11)) { /* BASIC: GOTO */
goto L2910;
 }
 /* Line 2820 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("B", (int)(bpp_vars[25]), 0) != *bpp_dim_ref("B", (int)((bpp_vars[25] - 1)), 0))) { /* BASIC: GOTO */
goto L2870;
 }
 /* Line 2830 */
 strncpy(bpp_strvars[7], "THREE", 255); bpp_strvars[7][255]='\0';
 /* Line 2840 */
 strncpy(bpp_strvars[8], " ", 255); bpp_strvars[8][255]='\0';
 /* Line 2850 */
 bpp_vars[20] = 13;
 /* Line 2860 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L2870: /* Line 2870 */
 strncpy(bpp_strvars[7], "TWO P", 255); bpp_strvars[7][255]='\0';
 /* Line 2880 */
 strncpy(bpp_strvars[8], "AIR, ", 255); bpp_strvars[8][255]='\0';
 /* Line 2890 */
 bpp_vars[20] = 12;
 /* Line 2900 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L2910: /* Line 2910 */
 /* BASIC: IF statement */
 if ((bpp_vars[20] > 12)) { /* BASIC: GOTO */
goto L2960;
 }
 /* Line 2920 */
 bpp_vars[20] = 16;
 /* Line 2930 */
 strncpy(bpp_strvars[7], "FULL H", 255); bpp_strvars[7][255]='\0';
 /* Line 2940 */
 strncpy(bpp_strvars[8], "OUSE, ", 255); bpp_strvars[8][255]='\0';
 /* Line 2950 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L2960: /* Line 2960 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("B", (int)(bpp_vars[25]), 0) != *bpp_dim_ref("B", (int)((bpp_vars[25] - 1)), 0))) { /* BASIC: GOTO */
goto L3010;
 }
 /* Line 2970 */
 bpp_vars[20] = 17;
 /* Line 2980 */
 strncpy(bpp_strvars[7], "FOUR", 255); bpp_strvars[7][255]='\0';
 /* Line 2990 */
 strncpy(bpp_strvars[8], " ", 255); bpp_strvars[8][255]='\0';
 /* Line 3000 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L3010: /* Line 3010 */
 bpp_vars[20] = 16;
 /* Line 3020 */
 strncpy(bpp_strvars[7], "FULL H", 255); bpp_strvars[7][255]='\0';
 /* Line 3030 */
 strncpy(bpp_strvars[8], "OUSE, ", 255); bpp_strvars[8][255]='\0';
 /* Line 3040 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L3050: /* Line 3050 */
 bpp_vars[6] = 0;
 L3060: /* Line 3060 */
  printf("\n");
 printf("%s", "WHAT IS YOUR BET");
 /* Line 3070 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[19] = _v; }
 /* Line 3080 */
 /* BASIC: IF statement */
 if (((bpp_vars[19] - floor(bpp_vars[19])) == 0)) { /* BASIC: GOTO */
goto L3140;
 }
 /* Line 3090 */
 /* BASIC: IF statement */
 if ((bpp_vars[10] != 0)) { /* BASIC: GOTO */
goto L3120;
 }
 /* Line 3100 */
 /* BASIC: IF statement */
 if ((bpp_vars[6] != 0)) { /* BASIC: GOTO */
goto L3120;
 }
 /* Line 3110 */
 /* BASIC: IF statement */
 if ((bpp_vars[19] == 0.5)) { /* BASIC: GOTO */
goto L3410;
 }
 L3120: /* Line 3120 */
 printf("%s", "NO SMALL CHANGE, PLEASE.");
 printf("\n");
 /* Line 3130 */
 /* BASIC: GOTO */
 goto L3060;
 L3140: /* Line 3140 */
 /* BASIC: IF statement */
 if ((((bpp_vars[18] - bpp_vars[6]) - bpp_vars[19]) >= 0)) { /* BASIC: GOTO */
goto L3170;
 }
 /* Line 3150 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 22; goto L3830;
 bpp_ret_22:;
 /* Line 3160 */
 /* BASIC: GOTO */
 goto L3060;
 L3170: /* Line 3170 */
 /* BASIC: IF statement */
 if ((bpp_vars[19] != 0)) { /* BASIC: GOTO */
goto L3200;
 }
 /* Line 3180 */
 bpp_vars[8] = 3;
 /* Line 3190 */
 /* BASIC: GOTO */
 goto L3380;
 L3200: /* Line 3200 */
 /* BASIC: IF statement */
 if (((bpp_vars[6] + bpp_vars[19]) >= bpp_vars[10])) { /* BASIC: GOTO */
goto L3230;
 }
 /* Line 3210 */
 printf("%s", "IF YOU CAN'T SEE MY BET, THEN FOLD.");
 printf("\n");
 /* Line 3220 */
 /* BASIC: GOTO */
 goto L3060;
 L3230: /* Line 3230 */
 bpp_vars[6] = (bpp_vars[6] + bpp_vars[19]);
 /* Line 3240 */
 /* BASIC: IF statement */
 if ((bpp_vars[6] == bpp_vars[10])) { /* BASIC: GOTO */
goto L3380;
 }
 /* Line 3250 */
 /* BASIC: IF statement */
 if ((bpp_vars[25] != 1)) { /* BASIC: GOTO */
goto L3420;
 }
 /* Line 3260 */
 /* BASIC: IF statement */
 if ((bpp_vars[6] > 5)) { /* BASIC: GOTO */
goto L3300;
 }
 /* Line 3270 */
 /* BASIC: IF statement */
 if ((bpp_vars[25] >= 2)) { /* BASIC: GOTO */
goto L3350;
 }
 /* Line 3280 */
 bpp_vars[21] = 5;
 /* Line 3290 */
 /* BASIC: GOTO */
 goto L3420;
 L3300: /* Line 3300 */
 /* BASIC: IF statement */
 if ((bpp_vars[25] == 1)) { /* BASIC: GOTO */
goto L3320;
 }
 /* Line 3310 */
 /* BASIC: IF statement */
 if ((bpp_vars[19] <= 25)) { /* BASIC: GOTO */
goto L3350;
 }
 L3320: /* Line 3320 */
 bpp_vars[8] = 4;
 /* Line 3330 */
 printf("%s", "I FOLD.");
 printf("\n");
 /* Line 3340 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L3350: /* Line 3350 */
 /* BASIC: IF statement */
 if ((bpp_vars[25] == 2)) { /* BASIC: GOTO */
goto L3430;
 }
 L3360: /* Line 3360 */
 printf("%s", "I'LL SEE YOU.");
 printf("\n");
 /* Line 3370 */
 bpp_vars[10] = bpp_vars[6];
 L3380: /* Line 3380 */
 bpp_vars[18] = (bpp_vars[18] - bpp_vars[6]);
 /* Line 3390 */
 bpp_vars[2] = (bpp_vars[2] - bpp_vars[10]);
 /* Line 3400 */
 bpp_vars[15] = ((bpp_vars[15] + bpp_vars[6]) + bpp_vars[10]);
 L3410: /* Line 3410 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L3420: /* Line 3420 */
 /* BASIC: IF statement */
 if ((bpp_vars[6] > (3 * bpp_vars[25]))) { /* BASIC: GOTO */
goto L3350;
 }
 L3430: /* Line 3430 */
 /* REM V=G-K+FNA(0) */
 /* Line 3440 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 23; goto L3480;
 bpp_ret_23:;
 /* Line 3450 */
 printf("%s", "I'LL SEE YOU, AND RAISE YOU");
 printf("\n");
 /* Line 3460 */
 bpp_vars[10] = (bpp_vars[6] + bpp_vars[21]);
 /* Line 3470 */
 /* BASIC: GOTO */
 goto L3060;
 L3480: /* Line 3480 */
 /* BASIC: IF statement */
 if ((((bpp_vars[2] - bpp_vars[6]) - bpp_vars[21]) >= 0)) { /* BASIC: GOTO */
goto L3660;
 }
 /* Line 3490 */
 /* BASIC: IF statement */
 if ((bpp_vars[6] != 0)) { /* BASIC: GOTO */
goto L3520;
 }
 /* Line 3500 */
 bpp_vars[21] = bpp_vars[2];
 /* Line 3510 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L3520: /* Line 3520 */
 /* BASIC: IF statement */
 if (((bpp_vars[2] - bpp_vars[6]) >= 0)) { /* BASIC: GOTO */
goto L3360;
 }
 /* Line 3530 */
 /* BASIC: IF statement */
 if (((bpp_vars[14] / 2) != floor((bpp_vars[14] / 2)))) { /* BASIC: GOTO */
goto L3600;
 }
 /* Line 3540 */
 printf("%s", "WOULD YOU LIKE TO BUY BACK YOUR WATCH FOR $50");
 /* Line 3550 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[9], _buf, 255); }
 /* Line 3560 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_left(bpp_strvars[9], (int)(1)), "N") == 0))) { /* BASIC: GOTO */
goto L3600;
 }
 /* Line 3570 */
 bpp_vars[2] = (bpp_vars[2] + 50);
 /* Line 3580 */
 bpp_vars[14] = (bpp_vars[14] / 2);
 /* Line 3590 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L3600: /* Line 3600 */
 /* BASIC: IF statement */
 if (((bpp_vars[14] / 3) != floor((bpp_vars[14] / 3)))) { /* BASIC: GOTO */
goto L3670;
 }
 /* Line 3610 */
 printf("%s", "WOULD YOU LIKE TO BUY BACK YOUR TIE TACK FOR $50");
 /* Line 3620 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[9], _buf, 255); }
 /* Line 3630 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_left(bpp_strvars[9], (int)(1)), "N") == 0))) { /* BASIC: GOTO */
goto L3670;
 }
 /* Line 3640 */
 bpp_vars[2] = (bpp_vars[2] + 50);
 /* Line 3650 */
 bpp_vars[14] = (bpp_vars[14] / 3);
 L3660: /* Line 3660 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L3670: /* Line 3670 */
 printf("%s", "I'M BUSTED.  CONGRATULATIONS!");
 printf("\n");
 /* Line 3680 */
 printf("STOPPED\n"); goto bpp_end;
 L3690: /* Line 3690 */
 printf("%s", bpp_strvars[7]);
 printf("%s", bpp_strvars[8]);
 /* Line 3700 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[7], "A FLUS") != 0))) { /* BASIC: GOTO */
goto L3750;
 }
 /* Line 3710 */
 bpp_vars[10] = floor((bpp_vars[10] / 100));
 /* Line 3720 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 24; goto L2080;
 bpp_ret_24:;
 /* Line 3730 */
  printf("\n");
 /* Line 3740 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L3750: /* Line 3750 */
 /* REM K=FNB(K) */
 /* Line 3760 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 25; goto L1960;
 bpp_ret_25:;
 /* Line 3770 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[7], "SCHMAL") == 0))) { /* BASIC: GOTO */
goto L3790;
 }
 /* Line 3780 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[7], "STRAIG") != 0))) { /* BASIC: GOTO */
goto L3810;
 }
 L3790: /* Line 3790 */
 printf("%s", " HIGH");
 printf("\n");
 /* Line 3800 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L3810: /* Line 3810 */
 printf("%s", "'S");
 printf("\n");
 /* Line 3820 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L3830: /* Line 3830 */
  printf("\n");
 /* Line 3840 */
 printf("%s", "YOU CAN'T BET WITH WHAT YOU HAVEN'T GOT.");
 printf("\n");
 /* Line 3850 */
 /* BASIC: IF statement */
 if (((bpp_vars[14] / 2) == floor((bpp_vars[14] / 2)))) { /* BASIC: GOTO */
goto L3970;
 }
 /* Line 3860 */
 printf("%s", "WOULD YOU LIKE TO SELL YOUR WATCH");
 /* Line 3870 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[9], _buf, 255); }
 /* Line 3880 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_left(bpp_strvars[9], (int)(1)), "N") == 0))) { /* BASIC: GOTO */
goto L3970;
 }
 /* Line 3890 */
 /* REM IF FNA(0)>=7 THEN 3930 */
 /* Line 3900 */
 printf("%s", "I'LL GIVE YOU $75 FOR IT.");
 printf("\n");
 /* Line 3910 */
 bpp_vars[18] = (bpp_vars[18] + 75);
 /* Line 3920 */
 /* BASIC: GOTO */
 goto L3950;
 /* Line 3930 */
 printf("%s", "THAT'S A PRETTY CRUMMY WATCH - I'LL GIVE YOU $25.");
 printf("\n");
 /* Line 3940 */
 bpp_vars[18] = (bpp_vars[18] + 25);
 L3950: /* Line 3950 */
 bpp_vars[14] = (bpp_vars[14] * 2);
 /* Line 3960 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L3970: /* Line 3970 */
 /* BASIC: IF statement */
 if (((bpp_vars[14] / 3) != floor((bpp_vars[14] / 3)))) { /* BASIC: GOTO */
goto L4090;
 }
 /* Line 3980 */
 printf("%s", "WILL YOU PART WITH THAT DIAMOND TIE TACK");
 printf("\n");
 /* Line 3990 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[9], _buf, 255); }
 /* Line 4000 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_left(bpp_strvars[9], (int)(1)), "N") == 0))) { /* BASIC: GOTO */
goto L4080;
 }
 /* Line 4010 */
 /* REM IF FNA(0)>=6 THEN 4050 */
 /* Line 4020 */
 printf("%s", "YOU ARE NOW $100 RICHER.");
 printf("\n");
 /* Line 4030 */
 bpp_vars[18] = (bpp_vars[18] + 100);
 /* Line 4040 */
 /* BASIC: GOTO */
 goto L4070;
 /* Line 4050 */
 printf("%s", "IT'S PASTE.  $25.");
 printf("\n");
 /* Line 4060 */
 bpp_vars[18] = (bpp_vars[18] + 25);
 L4070: /* Line 4070 */
 bpp_vars[14] = (bpp_vars[14] * 3);
 L4080: /* Line 4080 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 case 15: goto bpp_ret_15;
 case 16: goto bpp_ret_16;
 case 17: goto bpp_ret_17;
 case 18: goto bpp_ret_18;
 case 19: goto bpp_ret_19;
 case 20: goto bpp_ret_20;
 case 21: goto bpp_ret_21;
 case 22: goto bpp_ret_22;
 case 23: goto bpp_ret_23;
 case 24: goto bpp_ret_24;
 case 25: goto bpp_ret_25;
 default: goto bpp_end;
 } }
 L4090: /* Line 4090 */
 printf("%s", "YOUR WAD IS SHOT.  SO LONG, SUCKER!");
 printf("\n");
 L4100: /* Line 4100 */
 goto bpp_end;
 bpp_end:
 return 0;
}
