#ifdef _MSC_VER
#ifndef _CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
#endif
#pragma warning(disable: 4996)
#pragma warning(disable: 4101)
#pragma warning(disable: 4244)
#pragma warning(disable: 4102)
#pragma warning(disable: 4311)
#pragma warning(disable: 4312)
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wstringop-truncation"
#pragma GCC diagnostic ignored "-Wrestrict"
#pragma GCC diagnostic ignored "-Wdouble-promotion"
#pragma GCC diagnostic ignored "-Wpointer-to-int-cast"
#pragma GCC diagnostic ignored "-Wint-to-pointer-cast"
#endif

/* Generated by BASIC++ Compiler for target: windows */
#define BPP_TARGET_WINDOWS
#define BPP_SUPPORT_MULTITASKING 1
#define BPP_SUPPORT_GRAPHICS 1
#define BPP_SUPPORT_FILESYSTEM 1

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* Windows specific platform headers */
#include <windows.h>

/* === Runtime Variables === */
static double bpp_vars[1024]; /* A-Z and named */
static char bpp_strvars[1024][256]; /* A$-Z$ and named */
static double bpp_at_array[4096]; /* @() legacy array */
static int bpp_print_width = 14;

/* === GOSUB Stack === */
#define BPP_MAX_STACK 256
static int bpp_gosub_stack[BPP_MAX_STACK];
static int bpp_gosub_sp = 0;

/* === DIM Arrays === */
#define BPP_MAX_DIM 64
#define BPP_MAX_ELEM 4194304
static double bpp_dim_pool[BPP_MAX_ELEM];
static int bpp_dim_used = 0;
typedef struct { char name[32]; int d1,d2,off; } BppDim;
static BppDim bpp_dims[BPP_MAX_DIM];
static int bpp_dim_count = 0;

static void bpp_dim_alloc(const char *nm, int d1, int d2) {
 int sz = (d1+1) * (d2>0 ? d2+1 : 1);
 BppDim *d = &bpp_dims[bpp_dim_count++];
 strncpy(d->name, nm, 31); d->name[31]='\0';
 d->d1=d1; d->d2=d2; d->off=bpp_dim_used;
 memset(&bpp_dim_pool[bpp_dim_used], 0, sizeof(double)*(size_t)sz);
 bpp_dim_used += sz;
}

static double *bpp_dim_ref(const char *nm, int i1, int i2) {
 int k;
 for (k=0; k<bpp_dim_count; k++) {
 if (strcmp(bpp_dims[k].name, nm)==0) {
 int idx = (bpp_dims[k].d2>0)
 ? i1*(bpp_dims[k].d2+1)+i2 : i1;
 return &bpp_dim_pool[bpp_dims[k].off + idx];
 }
 }
 fprintf(stderr, "Array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === String DIM arrays === */
#define BPP_MAX_STRDIM 26
#define BPP_MAX_STRDIM_SIZE 256
static struct { char nm[16]; int d1; int d2;
 char data[BPP_MAX_STRDIM_SIZE][256]; } bpp_strdims[BPP_MAX_STRDIM];
static int bpp_strdim_count = 0;

static char *bpp_strdim_ref(const char *nm, int i1, int i2) {
 int k;
 (void)i2;
 for (k = 0; k < bpp_strdim_count; k++) {
 if (strcmp(bpp_strdims[k].nm, nm) == 0) {
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[k].data[i1];
 }
 }
 /* Auto-create */
 if (bpp_strdim_count < BPP_MAX_STRDIM) {
 int j;
 strncpy(bpp_strdims[bpp_strdim_count].nm, nm, 15);
 bpp_strdims[bpp_strdim_count].nm[15] = '\0';
 for (j = 0; j < BPP_MAX_STRDIM_SIZE; j++)
 bpp_strdims[bpp_strdim_count].data[j][0] = '\0';
 bpp_strdim_count++;
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[bpp_strdim_count-1].data[i1];
 }
 fprintf(stderr, "String array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === DATA/READ support === */
#define BPP_MAX_DATA 4096
static const char *bpp_data_pool[BPP_MAX_DATA];
static int bpp_data_count = 0;
static int bpp_data_ptr = 0;

static double bpp_read_num(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return atof(bpp_data_pool[bpp_data_ptr++]);
}

static const char *bpp_read_str(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return bpp_data_pool[bpp_data_ptr++];
}

/* === String helpers === */
static char bpp_strtmp[8][256];
static int bpp_strtmp_idx = 0;

static char *bpp_tmp(void) {
 char *p = bpp_strtmp[bpp_strtmp_idx];
 bpp_strtmp_idx = (bpp_strtmp_idx+1) & 7;
 return p;
}

static const char *bpp_concat(const char *a, const char *b) {
 char *t = bpp_tmp();
 t[0]='\0';
 strncat(t, a, 254);
 strncat(t, b, 254-(int)strlen(t));
 return t;
}

static const char *bpp_left(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_right(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s+len-n, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_mid(const char *s, int st, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (st<0) st=0;
 if (st>len) st=len;
 if (n<0) n=0;
 if (st+n>len) n=len-st;
 memcpy(t, s+st, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_chr(int n) {
 char *t = bpp_tmp();
 t[0]=(char)n; t[1]='\0';
 return t;
}

static const char *bpp_str(double n) {
 char *t = bpp_tmp();
 sprintf(t, "%g", n);
 return t;
}

/* === TAB helper === */
static const char *bpp_tab(int col) {
 static char buf[256];
 int i;
 if (col < 0) col = 0;
 if (col > 255) col = 255;
 for (i = 0; i < col; i++) buf[i] = ' ';
 buf[col] = '\0';
 return buf;
}

/* === DEF FN support === */
#define BPP_MAX_FN 26
typedef double (*BppFnPtr)(double);
static double bpp_fn_param;

int main(void) {
  bpp_data_count = 0;

 /* Line 10 */
 printf("%s", bpp_tab((int)(30)));
 printf("%s", "ROCKET");
 printf("\n");
 /* Line 20 */
 printf("%s", bpp_tab((int)(15)));
 printf("%s", "CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY");
 printf("\n");
 /* Line 30 */
  printf("\n");
  printf("\n");
  printf("\n");
 /* Line 70 */
 printf("%s", "LUNAR LANDING SIMULATION");
 printf("\n");
 /* Line 80 */
 printf("%s", "----- ------- ----------");
 printf("\n");
  printf("\n");
 /* Line 100 */
 printf("%s", "DO YOU WANT INSTRUCTIONS (YES OR NO)");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[0], _buf, 255); }
 /* Line 110 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[0], "NO") == 0))) { /* BASIC: GOTO */
goto L390;
 }
 /* Line 160 */
  printf("\n");
 /* Line 200 */
 printf("%s", "YOU ARE LANDING ON THE MOON AND AND HAVE TAKEN OVER MANUAL");
 printf("\n");
 /* Line 210 */
 printf("%s", "CONTROL 1000 FEET ABOVE A GOOD LANDING SPOT. YOU HAVE A DOWN-");
 printf("\n");
 /* Line 220 */
 printf("%s", "WARD VELOCITY OF 50 FEET/SEC. 150 UNITS OF FUEL REMAIN.");
 printf("\n");
 /* Line 225 */
  printf("\n");
 /* Line 230 */
 printf("%s", "HERE ARE THE RULES THAT GOVERN YOUR APOLLO SPACE-CRAFT:");
 printf("\n");
  printf("\n");
 /* Line 240 */
 printf("%s", "(1) AFTER EACH SECOND THE HEIGHT, VELOCITY, AND REMAINING FUEL");
 printf("\n");
 /* Line 250 */
 printf("%s", "    WILL BE REPORTED VIA DIGBY YOUR ON-BOARD COMPUTER.");
 printf("\n");
 /* Line 260 */
 printf("%s", "(2) AFTER THE REPORT A '?' WILL APPEAR. ENTER THE NUMBER");
 printf("\n");
 /* Line 270 */
 printf("%s", "    OF UNITS OF FUEL YOU WISH TO BURN DURING THE NEXT");
 printf("\n");
 /* Line 280 */
 printf("%s", "    SECOND. EACH UNIT OF FUEL WILL SLOW YOUR DESCENT BY");
 printf("\n");
 /* Line 290 */
 printf("%s", "    1 FOOT/SEC.");
 printf("\n");
 /* Line 310 */
 printf("%s", "(3) THE MAXIMUM THRUST OF YOUR ENGINE IS 30 FEET/SEC/SEC");
 printf("\n");
 /* Line 320 */
 printf("%s", "    OR 30 UNITS OF FUEL PER SECOND.");
 printf("\n");
 /* Line 330 */
 printf("%s", "(4) WHEN YOU CONTACT THE LUNAR SURFACE. YOUR DESCENT ENGINE");
 printf("\n");
 /* Line 340 */
 printf("%s", "    WILL AUTOMATICALLY SHUT DOWN AND YOU WILL BE GIVEN A");
 printf("\n");
 /* Line 350 */
 printf("%s", "    REPORT OF YOUR LANDING SPEED AND REMAINING FUEL.");
 printf("\n");
 /* Line 360 */
 printf("%s", "(5) IF YOU RUN OUT OF FUEL THE '?' WILL NO LONGER APPEAR");
 printf("\n");
 /* Line 370 */
 printf("%s", "    BUT YOUR SECOND BY SECOND REPORT WILL CONTINUE UNTIL");
 printf("\n");
 /* Line 380 */
 printf("%s", "    YOU CONTACT THE LUNAR SURFACE.");
 printf("\n");
  printf("\n");
 L390: /* Line 390 */
 printf("%s", "BEGINNING LANDING PROCEDURE..........");
 printf("\n");
  printf("\n");
 /* Line 400 */
 printf("%s", "G O O D  L U C K ! ! !");
 printf("\n");
 /* Line 420 */
  printf("\n");
  printf("\n");
 /* Line 430 */
 printf("%s", "SEC  FEET      SPEED     FUEL     PLOT OF DISTANCE");
 printf("\n");
 /* Line 450 */
  printf("\n");
 /* Line 455 */
 bpp_vars[19] = 0;
 bpp_vars[7] = 1000;
 bpp_vars[21] = 50;
 bpp_vars[5] = 150;
 L490: /* Line 490 */
 { double _v = bpp_vars[19]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", bpp_tab((int)(6)));
 { double _v = bpp_vars[7]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", bpp_tab((int)(16)));
 { double _v = bpp_vars[21]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", bpp_tab((int)(26)));
 { double _v = bpp_vars[5]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", bpp_tab((int)(35)));
 printf("%s", "I");
 printf("%s", bpp_tab((int)((bpp_vars[7] / 15))));
 printf("%s", "*");
 printf("\n");
 /* Line 500 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[1] = _v; }
 /* Line 510 */
 /* BASIC: IF statement */
 if ((bpp_vars[1] < 0)) { /* BASIC: GOTO */
goto L650;
 }
 /* Line 520 */
 /* BASIC: IF statement */
 if ((bpp_vars[1] > 30)) { bpp_vars[1] = 30;
 }
 /* Line 530 */
 /* BASIC: IF statement */
 if ((bpp_vars[1] > bpp_vars[5])) { bpp_vars[1] = bpp_vars[5];
 }
 L540: /* Line 540 */
 bpp_vars[26] = ((bpp_vars[21] - bpp_vars[1]) + 5);
 /* Line 560 */
 bpp_vars[5] = (bpp_vars[5] - bpp_vars[1]);
 /* Line 570 */
 bpp_vars[7] = (bpp_vars[7] - (0.5 * (bpp_vars[21] + bpp_vars[26])));
 /* Line 580 */
 /* BASIC: IF statement */
 if ((bpp_vars[7] <= 0)) { /* BASIC: GOTO */
goto L670;
 }
 /* Line 590 */
 bpp_vars[19] = (bpp_vars[19] + 1);
 /* Line 600 */
 bpp_vars[21] = bpp_vars[26];
 /* Line 610 */
 /* BASIC: IF statement */
 if ((bpp_vars[5] > 0)) { /* BASIC: GOTO */
goto L490;
 }
 /* Line 615 */
 /* BASIC: IF statement */
 if ((bpp_vars[1] == 0)) { /* BASIC: GOTO */
goto L640;
 }
 /* Line 620 */
 printf("%s", "**** OUT OF FUEL ****");
 printf("\n");
 L640: /* Line 640 */
 { double _v = bpp_vars[19]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", bpp_tab((int)(4)));
 { double _v = bpp_vars[7]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", bpp_tab((int)(12)));
 { double _v = bpp_vars[21]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", bpp_tab((int)(20)));
 { double _v = bpp_vars[5]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", bpp_tab((int)(29)));
 printf("%s", "I");
 printf("%s", bpp_tab((int)(((bpp_vars[7] / 12) + 29))));
 printf("%s", "*");
 printf("\n");
 L650: /* Line 650 */
 bpp_vars[1] = 0;
 /* Line 660 */
 /* BASIC: GOTO */
 goto L540;
 L670: /* Line 670 */
 printf("%s", "***** CONTACT *****");
 printf("\n");
 /* Line 680 */
 bpp_vars[7] = (bpp_vars[7] + (0.5 * (bpp_vars[26] + bpp_vars[21])));
 /* Line 690 */
 /* BASIC: IF statement */
 if ((bpp_vars[1] == 5)) { /* BASIC: GOTO */
goto L720;
 }
 /* Line 700 */
 bpp_vars[3] = (((-(bpp_vars[21])) + sqrt(((bpp_vars[21] * bpp_vars[21]) + (bpp_vars[7] * (10 - (2 * bpp_vars[1])))))) / (5 - bpp_vars[1]));
 /* Line 710 */
 /* BASIC: GOTO */
 goto L730;
 L720: /* Line 720 */
 bpp_vars[3] = (bpp_vars[7] / bpp_vars[21]);
 L730: /* Line 730 */
 bpp_vars[26] = (bpp_vars[21] + ((5 - bpp_vars[1]) * bpp_vars[3]));
 /* Line 760 */
 printf("%s", "TOUCHDOWN AT");
 { double _v = (bpp_vars[19] + bpp_vars[3]); if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "SECONDS.");
 printf("\n");
 /* Line 770 */
 printf("%s", "LANDING VELOCITY=");
 { double _v = bpp_vars[26]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "FEET/SEC.");
 printf("\n");
 /* Line 780 */
 { double _v = bpp_vars[5]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "UNITS OF FUEL REMAINING.");
 printf("\n");
 /* Line 790 */
 /* BASIC: IF statement */
 if ((bpp_vars[26] != 0)) { /* BASIC: GOTO */
goto L810;
 }
 /* Line 800 */
 printf("%s", "CONGRATULATIONS! A PERFECT LANDING!!");
 printf("\n");
 /* Line 805 */
 printf("%s", "YOUR LICENSE WILL BE RENEWED.......LATER.");
 printf("\n");
 L810: /* Line 810 */
 /* BASIC: IF statement */
 if ((fabs(bpp_vars[26]) < 2)) { /* BASIC: GOTO */
goto L840;
 }
 /* Line 820 */
 printf("%s", "***** SORRY, BUT YOU BLEW IT!!!!");
 printf("\n");
 /* Line 830 */
 printf("%s", "APPROPRIATE CONDOLENCES WILL BE SENT TO YOUR NEXT OF KIN.");
 printf("\n");
 L840: /* Line 840 */
  printf("\n");
  printf("\n");
  printf("\n");
 /* Line 850 */
 printf("%s", "ANOTHER MISSION");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[0], _buf, 255); }
 /* Line 860 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[0], "YES") == 0))) { /* BASIC: GOTO */
goto L390;
 }
 /* Line 870 */
  printf("\n");
 printf("%s", "CONTROL OUT.");
 printf("\n");
  printf("\n");
 /* Line 999 */
 goto bpp_end;
 bpp_end:
 return 0;
}
