#ifdef _MSC_VER
#ifndef _CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
#endif
#pragma warning(disable: 4996)
#pragma warning(disable: 4101)
#pragma warning(disable: 4244)
#pragma warning(disable: 4102)
#pragma warning(disable: 4311)
#pragma warning(disable: 4312)
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wstringop-truncation"
#pragma GCC diagnostic ignored "-Wrestrict"
#pragma GCC diagnostic ignored "-Wdouble-promotion"
#pragma GCC diagnostic ignored "-Wpointer-to-int-cast"
#pragma GCC diagnostic ignored "-Wint-to-pointer-cast"
#endif

/* Generated by BASIC++ Compiler for target: windows */
#define BPP_TARGET_WINDOWS
#define BPP_SUPPORT_MULTITASKING 1
#define BPP_SUPPORT_GRAPHICS 1
#define BPP_SUPPORT_FILESYSTEM 1

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* Windows specific platform headers */
#include <windows.h>

/* === Runtime Variables === */
static double bpp_vars[1024]; /* A-Z and named */
static char bpp_strvars[1024][256]; /* A$-Z$ and named */
static double bpp_at_array[4096]; /* @() legacy array */
static int bpp_print_width = 14;

/* === GOSUB Stack === */
#define BPP_MAX_STACK 256
static int bpp_gosub_stack[BPP_MAX_STACK];
static int bpp_gosub_sp = 0;

/* === DIM Arrays === */
#define BPP_MAX_DIM 64
#define BPP_MAX_ELEM 4194304
static double bpp_dim_pool[BPP_MAX_ELEM];
static int bpp_dim_used = 0;
typedef struct { char name[32]; int d1,d2,off; } BppDim;
static BppDim bpp_dims[BPP_MAX_DIM];
static int bpp_dim_count = 0;

static void bpp_dim_alloc(const char *nm, int d1, int d2) {
 int sz = (d1+1) * (d2>0 ? d2+1 : 1);
 BppDim *d = &bpp_dims[bpp_dim_count++];
 strncpy(d->name, nm, 31); d->name[31]='\0';
 d->d1=d1; d->d2=d2; d->off=bpp_dim_used;
 memset(&bpp_dim_pool[bpp_dim_used], 0, sizeof(double)*(size_t)sz);
 bpp_dim_used += sz;
}

static double *bpp_dim_ref(const char *nm, int i1, int i2) {
 int k;
 for (k=0; k<bpp_dim_count; k++) {
 if (strcmp(bpp_dims[k].name, nm)==0) {
 int idx = (bpp_dims[k].d2>0)
 ? i1*(bpp_dims[k].d2+1)+i2 : i1;
 return &bpp_dim_pool[bpp_dims[k].off + idx];
 }
 }
 fprintf(stderr, "Array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === String DIM arrays === */
#define BPP_MAX_STRDIM 26
#define BPP_MAX_STRDIM_SIZE 256
static struct { char nm[16]; int d1; int d2;
 char data[BPP_MAX_STRDIM_SIZE][256]; } bpp_strdims[BPP_MAX_STRDIM];
static int bpp_strdim_count = 0;

static char *bpp_strdim_ref(const char *nm, int i1, int i2) {
 int k;
 (void)i2;
 for (k = 0; k < bpp_strdim_count; k++) {
 if (strcmp(bpp_strdims[k].nm, nm) == 0) {
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[k].data[i1];
 }
 }
 /* Auto-create */
 if (bpp_strdim_count < BPP_MAX_STRDIM) {
 int j;
 strncpy(bpp_strdims[bpp_strdim_count].nm, nm, 15);
 bpp_strdims[bpp_strdim_count].nm[15] = '\0';
 for (j = 0; j < BPP_MAX_STRDIM_SIZE; j++)
 bpp_strdims[bpp_strdim_count].data[j][0] = '\0';
 bpp_strdim_count++;
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[bpp_strdim_count-1].data[i1];
 }
 fprintf(stderr, "String array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === DATA/READ support === */
#define BPP_MAX_DATA 4096
static const char *bpp_data_pool[BPP_MAX_DATA];
static int bpp_data_count = 0;
static int bpp_data_ptr = 0;

static double bpp_read_num(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return atof(bpp_data_pool[bpp_data_ptr++]);
}

static const char *bpp_read_str(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return bpp_data_pool[bpp_data_ptr++];
}

/* === String helpers === */
static char bpp_strtmp[8][256];
static int bpp_strtmp_idx = 0;

static char *bpp_tmp(void) {
 char *p = bpp_strtmp[bpp_strtmp_idx];
 bpp_strtmp_idx = (bpp_strtmp_idx+1) & 7;
 return p;
}

static const char *bpp_concat(const char *a, const char *b) {
 char *t = bpp_tmp();
 t[0]='\0';
 strncat(t, a, 254);
 strncat(t, b, 254-(int)strlen(t));
 return t;
}

static const char *bpp_left(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_right(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s+len-n, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_mid(const char *s, int st, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (st<0) st=0;
 if (st>len) st=len;
 if (n<0) n=0;
 if (st+n>len) n=len-st;
 memcpy(t, s+st, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_chr(int n) {
 char *t = bpp_tmp();
 t[0]=(char)n; t[1]='\0';
 return t;
}

static const char *bpp_str(double n) {
 char *t = bpp_tmp();
 sprintf(t, "%g", n);
 return t;
}

/* === TAB helper === */
static const char *bpp_tab(int col) {
 static char buf[256];
 int i;
 if (col < 0) col = 0;
 if (col > 255) col = 255;
 for (i = 0; i < col; i++) buf[i] = ' ';
 buf[col] = '\0';
 return buf;
}

/* === DEF FN support === */
#define BPP_MAX_FN 26
typedef double (*BppFnPtr)(double);
static double bpp_fn_param;

int main(void) {
  bpp_data_count = 0;

 /* Line 10 */
 printf("%s", bpp_tab((int)(30)));
 printf("%s", "SLOTS");
 printf("\n");
 /* Line 20 */
 printf("%s", bpp_tab((int)(15)));
 printf("%s", "CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY");
 printf("\n");
 /* Line 30 */
  printf("\n");
  printf("\n");
  printf("\n");
 /* Line 100 */
 /* REM  MIRABELLE AND BOB HARPER ON JAN 29, 1973 */
 /* Line 110 */
 /* REM  SLOT MACHINE. */
 /* Line 120 */
 printf("%s", "YOU ARE IN THE H&M CASINO,IN FRONT OF ONE OF OUR");
 printf("\n");
 /* Line 130 */
 printf("%s", "ONE-ARM BANDITS. BET FROM $1 TO $100.");
 printf("\n");
 /* Line 140 */
 printf("%s", "TO PULL THE ARM, PUNCH THE RETURN KEY AFTER MAKING YOUR BET.");
 printf("\n");
 /* Line 150 */
 bpp_vars[15] = 0;
 L160: /* Line 160 */
  printf("\n");
 printf("%s", "YOUR BET");
 /* Line 170 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[12] = _v; }
 /* Line 180 */
 /* BASIC: IF statement */
 if ((bpp_vars[12] > 100)) { /* BASIC: GOTO */
goto L860;
 }
 /* Line 190 */
 /* BASIC: IF statement */
 if ((bpp_vars[12] < 1)) { /* BASIC: GOTO */
goto L880;
 }
 /* Line 200 */
 bpp_vars[12] = floor(bpp_vars[12]);
 /* Line 210 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 0; goto L1270;
 bpp_ret_0:;
 L220: /* Line 220 */
  printf("\n");
 /* Line 230 */
 bpp_vars[23] = floor(((6 * ((double)(rand() % (int)(1)))) + 1));
 /* Line 240 */
 bpp_vars[24] = floor(((6 * ((double)(rand() % (int)(1)))) + 1));
 /* Line 250 */
 bpp_vars[25] = floor(((6 * ((double)(rand() % (int)(1)))) + 1));
 /* Line 260 */
  printf("\n");
 /* Line 270 */
 /* BASIC: IF statement */
 if ((bpp_vars[23] == 1)) { /* BASIC: GOTO */
goto L910;
 }
 /* Line 280 */
 /* BASIC: IF statement */
 if ((bpp_vars[23] == 2)) { /* BASIC: GOTO */
goto L930;
 }
 /* Line 290 */
 /* BASIC: IF statement */
 if ((bpp_vars[23] == 3)) { /* BASIC: GOTO */
goto L950;
 }
 /* Line 300 */
 /* BASIC: IF statement */
 if ((bpp_vars[23] == 4)) { /* BASIC: GOTO */
goto L970;
 }
 /* Line 310 */
 /* BASIC: IF statement */
 if ((bpp_vars[23] == 5)) { /* BASIC: GOTO */
goto L990;
 }
 /* Line 320 */
 /* BASIC: IF statement */
 if ((bpp_vars[23] == 6)) { /* BASIC: GOTO */
goto L1010;
 }
 L330: /* Line 330 */
 /* BASIC: IF statement */
 if ((bpp_vars[24] == 1)) { /* BASIC: GOTO */
goto L1030;
 }
 /* Line 340 */
 /* BASIC: IF statement */
 if ((bpp_vars[24] == 2)) { /* BASIC: GOTO */
goto L1050;
 }
 /* Line 350 */
 /* BASIC: IF statement */
 if ((bpp_vars[24] == 3)) { /* BASIC: GOTO */
goto L1070;
 }
 /* Line 360 */
 /* BASIC: IF statement */
 if ((bpp_vars[24] == 4)) { /* BASIC: GOTO */
goto L1090;
 }
 /* Line 370 */
 /* BASIC: IF statement */
 if ((bpp_vars[24] == 5)) { /* BASIC: GOTO */
goto L1110;
 }
 /* Line 380 */
 /* BASIC: IF statement */
 if ((bpp_vars[24] == 6)) { /* BASIC: GOTO */
goto L1130;
 }
 L390: /* Line 390 */
 /* BASIC: IF statement */
 if ((bpp_vars[25] == 1)) { /* BASIC: GOTO */
goto L1150;
 }
 /* Line 400 */
 /* BASIC: IF statement */
 if ((bpp_vars[25] == 2)) { /* BASIC: GOTO */
goto L1170;
 }
 /* Line 410 */
 /* BASIC: IF statement */
 if ((bpp_vars[25] == 3)) { /* BASIC: GOTO */
goto L1190;
 }
 /* Line 420 */
 /* BASIC: IF statement */
 if ((bpp_vars[25] == 4)) { /* BASIC: GOTO */
goto L1210;
 }
 /* Line 430 */
 /* BASIC: IF statement */
 if ((bpp_vars[25] == 5)) { /* BASIC: GOTO */
goto L1230;
 }
 /* Line 440 */
 /* BASIC: IF statement */
 if ((bpp_vars[25] == 6)) { /* BASIC: GOTO */
goto L1250;
 }
 L450: /* Line 450 */
 /* BASIC: IF statement */
 if ((bpp_vars[23] == bpp_vars[24])) { /* BASIC: GOTO */
goto L600;
 }
 /* Line 460 */
 /* BASIC: IF statement */
 if ((bpp_vars[23] == bpp_vars[25])) { /* BASIC: GOTO */
goto L630;
 }
 L470: /* Line 470 */
 /* BASIC: IF statement */
 if ((bpp_vars[24] == bpp_vars[25])) { /* BASIC: GOTO */
goto L650;
 }
 /* Line 480 */
  printf("\n");
 /* Line 490 */
 printf("%s", "YOU LOST.");
 printf("\n");
 /* Line 500 */
 bpp_vars[15] = (bpp_vars[15] - bpp_vars[12]);
 L510: /* Line 510 */
 printf("%s", "YOUR STANDINGS ARE $");
 printf("\n");
 /* Line 520 */
 printf("%s", "AGAIN");
 /* Line 530 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[0], _buf, 255); }
 /* Line 540 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[0], "Y") == 0))) { /* BASIC: GOTO */
goto L160;
 }
 /* Line 550 */
  printf("\n");
 /* Line 560 */
 /* BASIC: IF statement */
 if ((bpp_vars[15] < 0)) { /* BASIC: GOTO */
goto L670;
 }
 /* Line 570 */
 /* BASIC: IF statement */
 if ((bpp_vars[15] == 0)) { /* BASIC: GOTO */
goto L690;
 }
 /* Line 580 */
 /* BASIC: IF statement */
 if ((bpp_vars[15] > 0)) { /* BASIC: GOTO */
goto L710;
 }
 /* Line 590 */
 /* BASIC: GOTO */
 goto L1350;
 L600: /* Line 600 */
 /* BASIC: IF statement */
 if ((bpp_vars[24] == bpp_vars[25])) { /* BASIC: GOTO */
goto L730;
 }
 /* Line 610 */
 /* BASIC: IF statement */
 if ((bpp_vars[24] == 1)) { /* BASIC: GOTO */
goto L820;
 }
 /* Line 620 */
 /* BASIC: GOTO */
 goto L1341;
 L630: /* Line 630 */
 /* BASIC: IF statement */
 if ((bpp_vars[25] == 1)) { /* BASIC: GOTO */
goto L820;
 }
 /* Line 640 */
 /* BASIC: GOTO */
 goto L470;
 L650: /* Line 650 */
 /* BASIC: IF statement */
 if ((bpp_vars[25] == 1)) { /* BASIC: GOTO */
goto L820;
 }
 /* Line 660 */
 /* BASIC: GOTO */
 goto L1341;
 L670: /* Line 670 */
 printf("%s", "PAY UP!  PLEASE LEAVE YOUR MONEY ON THE TERMINAL.");
 printf("\n");
 /* Line 680 */
 /* BASIC: GOTO */
 goto L1350;
 L690: /* Line 690 */
 printf("%s", "HEY, YOU BROKE EVEN.");
 printf("\n");
 /* Line 700 */
 /* BASIC: GOTO */
 goto L1350;
 L710: /* Line 710 */
 printf("%s", "COLLECT YOUR WINNINGS FROM THE H&M CASHIER.");
 printf("\n");
 /* Line 720 */
 /* BASIC: GOTO */
 goto L1350;
 L730: /* Line 730 */
 /* BASIC: IF statement */
 if ((bpp_vars[25] == 1)) { /* BASIC: GOTO */
goto L780;
 }
 /* Line 740 */
  printf("\n");
 printf("%s", "**TOP DOLLAR**");
 printf("\n");
 /* Line 750 */
 printf("%s", "YOU WON!");
 printf("\n");
 /* Line 760 */
 bpp_vars[15] = (((10 * bpp_vars[12]) + bpp_vars[12]) + bpp_vars[15]);
 /* Line 770 */
 /* BASIC: GOTO */
 goto L510;
 L780: /* Line 780 */
  printf("\n");
 printf("%s", "***JACKPOT***");
 printf("\n");
 /* Line 790 */
 printf("%s", "YOU WON!");
 printf("\n");
 /* Line 800 */
 bpp_vars[15] = (((100 * bpp_vars[12]) + bpp_vars[12]) + bpp_vars[15]);
 /* Line 810 */
 /* BASIC: GOTO */
 goto L510;
 L820: /* Line 820 */
  printf("\n");
 printf("%s", "*DOUBLE BAR*");
 printf("\n");
 /* Line 830 */
 printf("%s", "YOU WON!");
 printf("\n");
 /* Line 840 */
 bpp_vars[15] = (((5 * bpp_vars[12]) + bpp_vars[12]) + bpp_vars[15]);
 /* Line 850 */
 /* BASIC: GOTO */
 goto L510;
 L860: /* Line 860 */
 printf("%s", "HOUSE LIMITS ARE $100");
 printf("\n");
 /* Line 870 */
 /* BASIC: GOTO */
 goto L160;
 L880: /* Line 880 */
 printf("%s", "MINIMUM BET IS $1");
 printf("\n");
 /* Line 890 */
 /* BASIC: GOTO */
 goto L160;
 /* Line 900 */
 /* BASIC: GOTO */
 goto L220;
 L910: /* Line 910 */
 printf("%s", "BAR");
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 1; goto L1310;
 bpp_ret_1:;
 /* Line 920 */
 /* BASIC: GOTO */
 goto L330;
 L930: /* Line 930 */
 printf("%s", "BELL");
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 2; goto L1310;
 bpp_ret_2:;
 /* Line 940 */
 /* BASIC: GOTO */
 goto L330;
 L950: /* Line 950 */
 printf("%s", "ORANGE");
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 3; goto L1310;
 bpp_ret_3:;
 /* Line 960 */
 /* BASIC: GOTO */
 goto L330;
 L970: /* Line 970 */
 printf("%s", "LEMON");
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 4; goto L1310;
 bpp_ret_4:;
 /* Line 980 */
 /* BASIC: GOTO */
 goto L330;
 L990: /* Line 990 */
 printf("%s", "PLUM");
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 5; goto L1310;
 bpp_ret_5:;
 /* Line 1000 */
 /* BASIC: GOTO */
 goto L330;
 L1010: /* Line 1010 */
 printf("%s", "CHERRY");
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 6; goto L1310;
 bpp_ret_6:;
 /* Line 1020 */
 /* BASIC: GOTO */
 goto L330;
 L1030: /* Line 1030 */
 printf("%s", " BAR");
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 7; goto L1310;
 bpp_ret_7:;
 /* Line 1040 */
 /* BASIC: GOTO */
 goto L390;
 L1050: /* Line 1050 */
 printf("%s", " BELL");
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 8; goto L1310;
 bpp_ret_8:;
 /* Line 1060 */
 /* BASIC: GOTO */
 goto L390;
 L1070: /* Line 1070 */
 printf("%s", " ORANGE");
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 9; goto L1310;
 bpp_ret_9:;
 /* Line 1080 */
 /* BASIC: GOTO */
 goto L390;
 L1090: /* Line 1090 */
 printf("%s", " LEMON");
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 10; goto L1310;
 bpp_ret_10:;
 /* Line 1100 */
 /* BASIC: GOTO */
 goto L390;
 L1110: /* Line 1110 */
 printf("%s", " PLUM");
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 11; goto L1310;
 bpp_ret_11:;
 /* Line 1120 */
 /* BASIC: GOTO */
 goto L390;
 L1130: /* Line 1130 */
 printf("%s", " CHERRY");
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 12; goto L1310;
 bpp_ret_12:;
 /* Line 1140 */
 /* BASIC: GOTO */
 goto L390;
 L1150: /* Line 1150 */
 printf("%s", " BAR");
 printf("\n");
 /* Line 1160 */
 /* BASIC: GOTO */
 goto L450;
 L1170: /* Line 1170 */
 printf("%s", " BELL");
 printf("\n");
 /* Line 1180 */
 /* BASIC: GOTO */
 goto L450;
 L1190: /* Line 1190 */
 printf("%s", " ORANGE");
 printf("\n");
 /* Line 1200 */
 /* BASIC: GOTO */
 goto L450;
 L1210: /* Line 1210 */
 printf("%s", " LEMON");
 printf("\n");
 /* Line 1220 */
 /* BASIC: GOTO */
 goto L450;
 L1230: /* Line 1230 */
 printf("%s", " PLUM");
 printf("\n");
 /* Line 1240 */
 /* BASIC: GOTO */
 goto L450;
 L1250: /* Line 1250 */
 printf("%s", " CHERRY");
 printf("\n");
 /* Line 1260 */
 /* BASIC: GOTO */
 goto L450;
 L1270: /* Line 1270 */
 /* BASIC: FOR loop initialization */
 bpp_vars[26] = 1;
 bpp_for_0:;
 /* Line 1280 */
 printf("%s", bpp_chr((int)(7)));
 /* Line 1290 */
 /* BASIC: NEXT loop step */
 bpp_vars[26] += 1;
 if (bpp_vars[26] <= 10) goto bpp_for_0;
 /* Line 1300 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 default: goto bpp_end;
 } }
 L1310: /* Line 1310 */
 /* BASIC: FOR loop initialization */
 bpp_vars[27] = 1;
 bpp_for_1:;
 /* Line 1320 */
 printf("%s", bpp_chr((int)(7)));
 /* Line 1330 */
 /* BASIC: NEXT loop step */
 bpp_vars[27] += 1;
 if (bpp_vars[27] <= 5) goto bpp_for_1;
 /* Line 1340 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 default: goto bpp_end;
 } }
 L1341: /* Line 1341 */
  printf("\n");
 printf("%s", "DOUBLE!!");
 printf("\n");
 /* Line 1342 */
 printf("%s", "YOU WON!");
 printf("\n");
 /* Line 1343 */
 bpp_vars[15] = (((2 * bpp_vars[12]) + bpp_vars[12]) + bpp_vars[15]);
 /* Line 1344 */
 /* BASIC: GOTO */
 goto L510;
 L1350: /* Line 1350 */
 printf("STOPPED\n"); goto bpp_end;
 /* Line 9999 */
 goto bpp_end;
 bpp_end:
 return 0;
}
