#ifdef _MSC_VER
#ifndef _CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
#endif
#pragma warning(disable: 4996)
#pragma warning(disable: 4101)
#pragma warning(disable: 4244)
#pragma warning(disable: 4102)
#pragma warning(disable: 4311)
#pragma warning(disable: 4312)
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wstringop-truncation"
#pragma GCC diagnostic ignored "-Wrestrict"
#pragma GCC diagnostic ignored "-Wdouble-promotion"
#pragma GCC diagnostic ignored "-Wpointer-to-int-cast"
#pragma GCC diagnostic ignored "-Wint-to-pointer-cast"
#endif

/* Generated by BASIC++ Compiler for target: windows */
#define BPP_TARGET_WINDOWS
#define BPP_SUPPORT_MULTITASKING 1
#define BPP_SUPPORT_GRAPHICS 1
#define BPP_SUPPORT_FILESYSTEM 1

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* Windows specific platform headers */
#include <windows.h>

/* === Runtime Variables === */
static double bpp_vars[1024]; /* A-Z and named */
static char bpp_strvars[1024][256]; /* A$-Z$ and named */
static double bpp_at_array[4096]; /* @() legacy array */
static int bpp_print_width = 14;

/* === GOSUB Stack === */
#define BPP_MAX_STACK 256
static int bpp_gosub_stack[BPP_MAX_STACK];
static int bpp_gosub_sp = 0;

/* === DIM Arrays === */
#define BPP_MAX_DIM 64
#define BPP_MAX_ELEM 4194304
static double bpp_dim_pool[BPP_MAX_ELEM];
static int bpp_dim_used = 0;
typedef struct { char name[32]; int d1,d2,off; } BppDim;
static BppDim bpp_dims[BPP_MAX_DIM];
static int bpp_dim_count = 0;

static void bpp_dim_alloc(const char *nm, int d1, int d2) {
 int sz = (d1+1) * (d2>0 ? d2+1 : 1);
 BppDim *d = &bpp_dims[bpp_dim_count++];
 strncpy(d->name, nm, 31); d->name[31]='\0';
 d->d1=d1; d->d2=d2; d->off=bpp_dim_used;
 memset(&bpp_dim_pool[bpp_dim_used], 0, sizeof(double)*(size_t)sz);
 bpp_dim_used += sz;
}

static double *bpp_dim_ref(const char *nm, int i1, int i2) {
 int k;
 for (k=0; k<bpp_dim_count; k++) {
 if (strcmp(bpp_dims[k].name, nm)==0) {
 int idx = (bpp_dims[k].d2>0)
 ? i1*(bpp_dims[k].d2+1)+i2 : i1;
 return &bpp_dim_pool[bpp_dims[k].off + idx];
 }
 }
 fprintf(stderr, "Array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === String DIM arrays === */
#define BPP_MAX_STRDIM 26
#define BPP_MAX_STRDIM_SIZE 256
static struct { char nm[16]; int d1; int d2;
 char data[BPP_MAX_STRDIM_SIZE][256]; } bpp_strdims[BPP_MAX_STRDIM];
static int bpp_strdim_count = 0;

static char *bpp_strdim_ref(const char *nm, int i1, int i2) {
 int k;
 (void)i2;
 for (k = 0; k < bpp_strdim_count; k++) {
 if (strcmp(bpp_strdims[k].nm, nm) == 0) {
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[k].data[i1];
 }
 }
 /* Auto-create */
 if (bpp_strdim_count < BPP_MAX_STRDIM) {
 int j;
 strncpy(bpp_strdims[bpp_strdim_count].nm, nm, 15);
 bpp_strdims[bpp_strdim_count].nm[15] = '\0';
 for (j = 0; j < BPP_MAX_STRDIM_SIZE; j++)
 bpp_strdims[bpp_strdim_count].data[j][0] = '\0';
 bpp_strdim_count++;
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[bpp_strdim_count-1].data[i1];
 }
 fprintf(stderr, "String array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === DATA/READ support === */
#define BPP_MAX_DATA 4096
static const char *bpp_data_pool[BPP_MAX_DATA];
static int bpp_data_count = 0;
static int bpp_data_ptr = 0;

static double bpp_read_num(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return atof(bpp_data_pool[bpp_data_ptr++]);
}

static const char *bpp_read_str(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return bpp_data_pool[bpp_data_ptr++];
}

/* === String helpers === */
static char bpp_strtmp[8][256];
static int bpp_strtmp_idx = 0;

static char *bpp_tmp(void) {
 char *p = bpp_strtmp[bpp_strtmp_idx];
 bpp_strtmp_idx = (bpp_strtmp_idx+1) & 7;
 return p;
}

static const char *bpp_concat(const char *a, const char *b) {
 char *t = bpp_tmp();
 t[0]='\0';
 strncat(t, a, 254);
 strncat(t, b, 254-(int)strlen(t));
 return t;
}

static const char *bpp_left(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_right(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s+len-n, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_mid(const char *s, int st, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (st<0) st=0;
 if (st>len) st=len;
 if (n<0) n=0;
 if (st+n>len) n=len-st;
 memcpy(t, s+st, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_chr(int n) {
 char *t = bpp_tmp();
 t[0]=(char)n; t[1]='\0';
 return t;
}

static const char *bpp_str(double n) {
 char *t = bpp_tmp();
 sprintf(t, "%g", n);
 return t;
}

/* === TAB helper === */
static const char *bpp_tab(int col) {
 static char buf[256];
 int i;
 if (col < 0) col = 0;
 if (col > 255) col = 255;
 for (i = 0; i < col; i++) buf[i] = ' ';
 buf[col] = '\0';
 return buf;
}

/* === DEF FN support === */
#define BPP_MAX_FN 26
typedef double (*BppFnPtr)(double);
static double bpp_fn_param;

int main(void) {
  bpp_data_pool[0] = "1";
  bpp_data_pool[1] = "49";
  bpp_data_pool[2] = "52";
  bpp_data_pool[3] = "4";
  bpp_data_pool[4] = "13";
  bpp_data_pool[5] = "61";
  bpp_data_pool[6] = "64";
  bpp_data_pool[7] = "16";
  bpp_data_pool[8] = "22";
  bpp_data_pool[9] = "39";
  bpp_data_pool[10] = "23";
  bpp_data_pool[11] = "38";
  bpp_data_pool[12] = "26";
  bpp_data_pool[13] = "42";
  bpp_data_pool[14] = "27";
  bpp_data_pool[15] = "43";
  bpp_data_pool[16] = "1";
  bpp_data_pool[17] = "2";
  bpp_data_pool[18] = "3";
  bpp_data_pool[19] = "4";
  bpp_data_pool[20] = "5";
  bpp_data_pool[21] = "6";
  bpp_data_pool[22] = "7";
  bpp_data_pool[23] = "8";
  bpp_data_pool[24] = "9";
  bpp_data_pool[25] = "10";
  bpp_data_pool[26] = "11";
  bpp_data_pool[27] = "12";
  bpp_data_pool[28] = "13";
  bpp_data_pool[29] = "14";
  bpp_data_pool[30] = "15";
  bpp_data_pool[31] = "16";
  bpp_data_pool[32] = "17";
  bpp_data_pool[33] = "18";
  bpp_data_pool[34] = "19";
  bpp_data_pool[35] = "20";
  bpp_data_pool[36] = "21";
  bpp_data_pool[37] = "22";
  bpp_data_pool[38] = "23";
  bpp_data_pool[39] = "24";
  bpp_data_pool[40] = "25";
  bpp_data_pool[41] = "26";
  bpp_data_pool[42] = "27";
  bpp_data_pool[43] = "28";
  bpp_data_pool[44] = "29";
  bpp_data_pool[45] = "30";
  bpp_data_pool[46] = "31";
  bpp_data_pool[47] = "32";
  bpp_data_pool[48] = "33";
  bpp_data_pool[49] = "34";
  bpp_data_pool[50] = "35";
  bpp_data_pool[51] = "36";
  bpp_data_pool[52] = "37";
  bpp_data_pool[53] = "38";
  bpp_data_pool[54] = "39";
  bpp_data_pool[55] = "40";
  bpp_data_pool[56] = "41";
  bpp_data_pool[57] = "42";
  bpp_data_pool[58] = "43";
  bpp_data_pool[59] = "44";
  bpp_data_pool[60] = "45";
  bpp_data_pool[61] = "46";
  bpp_data_pool[62] = "47";
  bpp_data_pool[63] = "48";
  bpp_data_pool[64] = "49";
  bpp_data_pool[65] = "50";
  bpp_data_pool[66] = "51";
  bpp_data_pool[67] = "52";
  bpp_data_pool[68] = "53";
  bpp_data_pool[69] = "54";
  bpp_data_pool[70] = "55";
  bpp_data_pool[71] = "56";
  bpp_data_pool[72] = "57";
  bpp_data_pool[73] = "58";
  bpp_data_pool[74] = "59";
  bpp_data_pool[75] = "60";
  bpp_data_pool[76] = "61";
  bpp_data_pool[77] = "62";
  bpp_data_pool[78] = "63";
  bpp_data_pool[79] = "64";
  bpp_data_pool[80] = "1";
  bpp_data_pool[81] = "17";
  bpp_data_pool[82] = "33";
  bpp_data_pool[83] = "49";
  bpp_data_pool[84] = "5";
  bpp_data_pool[85] = "21";
  bpp_data_pool[86] = "37";
  bpp_data_pool[87] = "53";
  bpp_data_pool[88] = "9";
  bpp_data_pool[89] = "25";
  bpp_data_pool[90] = "41";
  bpp_data_pool[91] = "57";
  bpp_data_pool[92] = "13";
  bpp_data_pool[93] = "29";
  bpp_data_pool[94] = "45";
  bpp_data_pool[95] = "61";
  bpp_data_pool[96] = "2";
  bpp_data_pool[97] = "18";
  bpp_data_pool[98] = "34";
  bpp_data_pool[99] = "50";
  bpp_data_pool[100] = "6";
  bpp_data_pool[101] = "22";
  bpp_data_pool[102] = "38";
  bpp_data_pool[103] = "54";
  bpp_data_pool[104] = "10";
  bpp_data_pool[105] = "26";
  bpp_data_pool[106] = "42";
  bpp_data_pool[107] = "58";
  bpp_data_pool[108] = "14";
  bpp_data_pool[109] = "30";
  bpp_data_pool[110] = "46";
  bpp_data_pool[111] = "62";
  bpp_data_pool[112] = "3";
  bpp_data_pool[113] = "19";
  bpp_data_pool[114] = "35";
  bpp_data_pool[115] = "51";
  bpp_data_pool[116] = "7";
  bpp_data_pool[117] = "23";
  bpp_data_pool[118] = "39";
  bpp_data_pool[119] = "55";
  bpp_data_pool[120] = "11";
  bpp_data_pool[121] = "27";
  bpp_data_pool[122] = "43";
  bpp_data_pool[123] = "59";
  bpp_data_pool[124] = "15";
  bpp_data_pool[125] = "31";
  bpp_data_pool[126] = "47";
  bpp_data_pool[127] = "63";
  bpp_data_pool[128] = "4";
  bpp_data_pool[129] = "20";
  bpp_data_pool[130] = "36";
  bpp_data_pool[131] = "52";
  bpp_data_pool[132] = "8";
  bpp_data_pool[133] = "24";
  bpp_data_pool[134] = "40";
  bpp_data_pool[135] = "56";
  bpp_data_pool[136] = "12";
  bpp_data_pool[137] = "28";
  bpp_data_pool[138] = "44";
  bpp_data_pool[139] = "60";
  bpp_data_pool[140] = "16";
  bpp_data_pool[141] = "32";
  bpp_data_pool[142] = "48";
  bpp_data_pool[143] = "64";
  bpp_data_pool[144] = "1";
  bpp_data_pool[145] = "5";
  bpp_data_pool[146] = "9";
  bpp_data_pool[147] = "13";
  bpp_data_pool[148] = "17";
  bpp_data_pool[149] = "21";
  bpp_data_pool[150] = "25";
  bpp_data_pool[151] = "29";
  bpp_data_pool[152] = "33";
  bpp_data_pool[153] = "37";
  bpp_data_pool[154] = "41";
  bpp_data_pool[155] = "45";
  bpp_data_pool[156] = "49";
  bpp_data_pool[157] = "53";
  bpp_data_pool[158] = "57";
  bpp_data_pool[159] = "61";
  bpp_data_pool[160] = "2";
  bpp_data_pool[161] = "6";
  bpp_data_pool[162] = "10";
  bpp_data_pool[163] = "14";
  bpp_data_pool[164] = "18";
  bpp_data_pool[165] = "22";
  bpp_data_pool[166] = "26";
  bpp_data_pool[167] = "30";
  bpp_data_pool[168] = "34";
  bpp_data_pool[169] = "38";
  bpp_data_pool[170] = "42";
  bpp_data_pool[171] = "46";
  bpp_data_pool[172] = "50";
  bpp_data_pool[173] = "54";
  bpp_data_pool[174] = "58";
  bpp_data_pool[175] = "62";
  bpp_data_pool[176] = "3";
  bpp_data_pool[177] = "7";
  bpp_data_pool[178] = "11";
  bpp_data_pool[179] = "15";
  bpp_data_pool[180] = "19";
  bpp_data_pool[181] = "23";
  bpp_data_pool[182] = "27";
  bpp_data_pool[183] = "31";
  bpp_data_pool[184] = "35";
  bpp_data_pool[185] = "39";
  bpp_data_pool[186] = "43";
  bpp_data_pool[187] = "47";
  bpp_data_pool[188] = "51";
  bpp_data_pool[189] = "55";
  bpp_data_pool[190] = "59";
  bpp_data_pool[191] = "63";
  bpp_data_pool[192] = "4";
  bpp_data_pool[193] = "8";
  bpp_data_pool[194] = "12";
  bpp_data_pool[195] = "16";
  bpp_data_pool[196] = "20";
  bpp_data_pool[197] = "24";
  bpp_data_pool[198] = "28";
  bpp_data_pool[199] = "32";
  bpp_data_pool[200] = "36";
  bpp_data_pool[201] = "40";
  bpp_data_pool[202] = "44";
  bpp_data_pool[203] = "48";
  bpp_data_pool[204] = "52";
  bpp_data_pool[205] = "56";
  bpp_data_pool[206] = "60";
  bpp_data_pool[207] = "64";
  bpp_data_pool[208] = "1";
  bpp_data_pool[209] = "6";
  bpp_data_pool[210] = "11";
  bpp_data_pool[211] = "16";
  bpp_data_pool[212] = "17";
  bpp_data_pool[213] = "22";
  bpp_data_pool[214] = "27";
  bpp_data_pool[215] = "32";
  bpp_data_pool[216] = "33";
  bpp_data_pool[217] = "38";
  bpp_data_pool[218] = "43";
  bpp_data_pool[219] = "48";
  bpp_data_pool[220] = "49";
  bpp_data_pool[221] = "54";
  bpp_data_pool[222] = "59";
  bpp_data_pool[223] = "64";
  bpp_data_pool[224] = "13";
  bpp_data_pool[225] = "10";
  bpp_data_pool[226] = "7";
  bpp_data_pool[227] = "4";
  bpp_data_pool[228] = "29";
  bpp_data_pool[229] = "26";
  bpp_data_pool[230] = "23";
  bpp_data_pool[231] = "20";
  bpp_data_pool[232] = "45";
  bpp_data_pool[233] = "42";
  bpp_data_pool[234] = "39";
  bpp_data_pool[235] = "36";
  bpp_data_pool[236] = "61";
  bpp_data_pool[237] = "58";
  bpp_data_pool[238] = "55";
  bpp_data_pool[239] = "52";
  bpp_data_pool[240] = "1";
  bpp_data_pool[241] = "21";
  bpp_data_pool[242] = "41";
  bpp_data_pool[243] = "61";
  bpp_data_pool[244] = "2";
  bpp_data_pool[245] = "22";
  bpp_data_pool[246] = "42";
  bpp_data_pool[247] = "62";
  bpp_data_pool[248] = "3";
  bpp_data_pool[249] = "23";
  bpp_data_pool[250] = "43";
  bpp_data_pool[251] = "63";
  bpp_data_pool[252] = "4";
  bpp_data_pool[253] = "24";
  bpp_data_pool[254] = "44";
  bpp_data_pool[255] = "64";
  bpp_data_pool[256] = "49";
  bpp_data_pool[257] = "37";
  bpp_data_pool[258] = "25";
  bpp_data_pool[259] = "13";
  bpp_data_pool[260] = "50";
  bpp_data_pool[261] = "38";
  bpp_data_pool[262] = "26";
  bpp_data_pool[263] = "14";
  bpp_data_pool[264] = "51";
  bpp_data_pool[265] = "39";
  bpp_data_pool[266] = "27";
  bpp_data_pool[267] = "15";
  bpp_data_pool[268] = "52";
  bpp_data_pool[269] = "40";
  bpp_data_pool[270] = "28";
  bpp_data_pool[271] = "16";
  bpp_data_pool[272] = "1";
  bpp_data_pool[273] = "18";
  bpp_data_pool[274] = "35";
  bpp_data_pool[275] = "52";
  bpp_data_pool[276] = "5";
  bpp_data_pool[277] = "22";
  bpp_data_pool[278] = "39";
  bpp_data_pool[279] = "56";
  bpp_data_pool[280] = "9";
  bpp_data_pool[281] = "26";
  bpp_data_pool[282] = "43";
  bpp_data_pool[283] = "60";
  bpp_data_pool[284] = "13";
  bpp_data_pool[285] = "30";
  bpp_data_pool[286] = "47";
  bpp_data_pool[287] = "64";
  bpp_data_pool[288] = "49";
  bpp_data_pool[289] = "34";
  bpp_data_pool[290] = "19";
  bpp_data_pool[291] = "4";
  bpp_data_pool[292] = "53";
  bpp_data_pool[293] = "38";
  bpp_data_pool[294] = "23";
  bpp_data_pool[295] = "8";
  bpp_data_pool[296] = "57";
  bpp_data_pool[297] = "42";
  bpp_data_pool[298] = "27";
  bpp_data_pool[299] = "12";
  bpp_data_pool[300] = "61";
  bpp_data_pool[301] = "46";
  bpp_data_pool[302] = "31";
  bpp_data_pool[303] = "16";
  bpp_data_pool[304] = "1";
  bpp_data_pool[305] = "22";
  bpp_data_pool[306] = "43";
  bpp_data_pool[307] = "64";
  bpp_data_pool[308] = "16";
  bpp_data_pool[309] = "27";
  bpp_data_pool[310] = "38";
  bpp_data_pool[311] = "49";
  bpp_data_pool[312] = "4";
  bpp_data_pool[313] = "23";
  bpp_data_pool[314] = "42";
  bpp_data_pool[315] = "61";
  bpp_data_pool[316] = "13";
  bpp_data_pool[317] = "26";
  bpp_data_pool[318] = "39";
  bpp_data_pool[319] = "52";
  bpp_data_count = 320;

 /* Line 100 */
 printf("%s", bpp_tab((int)(33)));
 printf("%s", "QUBIC");
 printf("\n");
  printf("\n");
 /* Line 110 */
 printf("%s", bpp_tab((int)(15)));
 printf("%s", "CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY");
 printf("\n");
 /* Line 120 */
  printf("\n");
  printf("\n");
  printf("\n");
 /* Line 210 */
 printf("%s", "DO YOU WANT INSTRUCTIONS");
 L220: /* Line 220 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[2], _buf, 255); }
 /* Line 230 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_left(bpp_strvars[2], (int)(1)), "N") == 0))) { /* BASIC: GOTO */
goto L315;
 }
 /* Line 240 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_left(bpp_strvars[2], (int)(1)), "Y") == 0))) { /* BASIC: GOTO */
goto L265;
 }
 /* Line 250 */
 printf("%s", "INCORRECT ANSWER.  PLEASE TYPE 'YES' OR 'NO'");
 /* Line 260 */
 /* BASIC: GOTO */
 goto L220;
 L265: /* Line 265 */
  printf("\n");
 /* Line 270 */
 printf("%s", "THE GAME IS TIC-TAC-TOE IN A 4 X 4 X 4 CUBE.");
 printf("\n");
 /* Line 280 */
 printf("%s", "EACH MOVE IS INDICATED BY A 3 DIGIT NUMBER, WITH EACH");
 printf("\n");
 /* Line 290 */
 printf("%s", "DIGIT BETWEEN 1 AND 4 INCLUSIVE.  THE DIGITS INDICATE THE");
 printf("\n");
 /* Line 300 */
 printf("%s", "LEVEL, ROW, AND COLUMN, RESPECTIVELY, OF THE OCCUPIED");
 printf("\n");
 /* Line 305 */
 printf("%s", "PLACE.  ");
 printf("\n");
 /* Line 306 */
  printf("\n");
 /* Line 307 */
 printf("%s", "TO PRINT THE PLAYING BOARD, TYPE 0 (ZERO) AS YOUR MOVE.");
 printf("\n");
 /* Line 308 */
 printf("%s", "THE PROGRAM WILL PRINT THE BOARD WITH YOUR MOVES INDI-");
 printf("\n");
 /* Line 309 */
 printf("%s", "CATED WITH A (Y), THE MACHINE'S MOVES WITH AN (M), AND");
 printf("\n");
 /* Line 310 */
 printf("%s", "UNUSED SQUARES WITH A ( ).  OUTPUT IS ON PAPER.");
 printf("\n");
 /* Line 311 */
  printf("\n");
 /* Line 312 */
 printf("%s", "TO STOP THE PROGRAM RUN, TYPE 1 AS YOUR MOVE.");
 printf("\n");
 /* Line 313 */
  printf("\n");
  printf("\n");
 L315: /* Line 315 */
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("X", (int)(64), 0);
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("L", (int)(76), 0);
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("M", (int)(76), (int)(4));
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("Y", (int)(16), 0);
 /* Line 320 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_0:;
 /* Line 330 */
 /* BASIC: READ statement */
 *bpp_dim_ref("Y", (int)(bpp_vars[8]), 0) = bpp_read_num();
 /* Line 340 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= 16) goto bpp_for_0;
 /* Line 350 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_1:;
 /* Line 360 */
 /* BASIC: FOR loop initialization */
 bpp_vars[9] = 1;
 bpp_for_2:;
 /* Line 370 */
 /* BASIC: READ statement */
 *bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9])) = bpp_read_num();
 /* Line 380 */
 /* BASIC: NEXT loop step */
 bpp_vars[9] += 1;
 if (bpp_vars[9] <= 4) goto bpp_for_2;
 /* Line 390 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= 76) goto bpp_for_1;
 L400: /* Line 400 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_3:;
 /* Line 410 */
 *bpp_dim_ref("X", (int)(bpp_vars[8]), 0) = 0;
 /* Line 420 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= 64) goto bpp_for_3;
 /* Line 430 */
 bpp_vars[25] = 1;
 /* Line 440 */
 printf("%s", "DO YOU WANT TO MOVE FIRST");
 L450: /* Line 450 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[18], _buf, 255); }
 /* Line 460 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_left(bpp_strvars[18], (int)(1)), "N") == 0))) { /* BASIC: GOTO */
goto L630;
 }
 /* Line 470 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_left(bpp_strvars[18], (int)(1)), "Y") == 0))) { /* BASIC: GOTO */
goto L500;
 }
 /* Line 480 */
 printf("%s", "INCORRECT ANSWER.  PLEASE TYPE 'YES' OR 'NO'.");
 /* Line 490 */
 /* BASIC: GOTO */
 goto L450;
 L500: /* Line 500 */
 printf("%s", " ");
 printf("\n");
 /* Line 510 */
 printf("%s", "YOUR MOVE");
 L520: /* Line 520 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[26] = _v; }
 /* Line 521 */
 /* BASIC: IF statement */
 if ((bpp_vars[26] == 1)) { /* BASIC: GOTO */
goto L2770;
 }
 /* Line 522 */
 /* BASIC: IF statement */
 if ((bpp_vars[26] != 0)) { /* BASIC: GOTO */
goto L525;
 }
 /* Line 523 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 0; goto L2550;
 bpp_ret_0:;
 /* Line 524 */
 /* BASIC: GOTO */
 goto L500;
 L525: /* Line 525 */
 /* BASIC: IF statement */
 if ((bpp_vars[26] < 111)) { /* BASIC: GOTO */
goto L2750;
 }
 /* Line 526 */
 /* BASIC: IF statement */
 if ((bpp_vars[26] > 444)) { /* BASIC: GOTO */
goto L2750;
 }
 /* Line 530 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 1; goto L2500;
 bpp_ret_1:;
 /* Line 540 */
 bpp_vars[27] = floor((bpp_vars[26] / 100));
 /* Line 550 */
 bpp_vars[28] = (bpp_vars[26] - (bpp_vars[27] * 100));
 /* Line 560 */
 bpp_vars[29] = floor((bpp_vars[28] / 10));
 /* Line 570 */
 bpp_vars[30] = ((bpp_vars[26] - (bpp_vars[27] * 100)) - (bpp_vars[29] * 10));
 /* Line 580 */
 bpp_vars[12] = ((((16 * bpp_vars[27]) + (4 * bpp_vars[29])) + bpp_vars[30]) - 20);
 /* Line 590 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("X", (int)(bpp_vars[12]), 0) == 0)) { /* BASIC: GOTO */
goto L620;
 }
 /* Line 600 */
 printf("%s", "THAT SQUARE IS USED, TRY AGAIN.");
 printf("\n");
 /* Line 610 */
 /* BASIC: GOTO */
 goto L500;
 L620: /* Line 620 */
 *bpp_dim_ref("X", (int)(bpp_vars[12]), 0) = 1;
 L630: /* Line 630 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 2; goto L1640;
 bpp_ret_2:;
 /* Line 640 */
 bpp_vars[9] = 1;
 L650: /* Line 650 */
 bpp_vars[8] = 1;
 L660: /* Line 660 */
 /* BASIC: IF statement */
 if ((bpp_vars[9] == 1)) { /* BASIC: GOTO */
goto L720;
 }
 /* Line 670 */
 /* BASIC: IF statement */
 if ((bpp_vars[9] == 2)) { /* BASIC: GOTO */
goto L790;
 }
 /* Line 680 */
 /* BASIC: IF statement */
 if ((bpp_vars[9] == 3)) { /* BASIC: GOTO */
goto L930;
 }
 L690: /* Line 690 */
 bpp_vars[8] = (bpp_vars[8] + 1);
 /* BASIC: IF statement */
 if ((bpp_vars[8] <= 76)) { /* BASIC: GOTO */
goto L660;
 }
 /* Line 700 */
 bpp_vars[9] = (bpp_vars[9] + 1);
 /* BASIC: IF statement */
 if ((bpp_vars[9] <= 3)) { /* BASIC: GOTO */
goto L650;
 }
 /* Line 710 */
 /* BASIC: GOTO */
 goto L1300;
 L720: /* Line 720 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("L", (int)(bpp_vars[8]), 0) != 4)) { /* BASIC: GOTO */
goto L690;
 }
 /* Line 730 */
 printf("%s", "YOU WIN AS FOLLOWS");
 /* Line 740 */
 /* BASIC: FOR loop initialization */
 bpp_vars[9] = 1;
 bpp_for_4:;
 /* Line 750 */
 bpp_vars[12] = *bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]));
 /* Line 760 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 3; goto L1570;
 bpp_ret_3:;
 /* Line 770 */
 /* BASIC: NEXT loop step */
 bpp_vars[9] += 1;
 if (bpp_vars[9] <= 4) goto bpp_for_4;
 /* Line 780 */
 /* BASIC: GOTO */
 goto L1490;
 L790: /* Line 790 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("L", (int)(bpp_vars[8]), 0) != 15)) { /* BASIC: GOTO */
goto L690;
 }
 /* Line 800 */
 /* BASIC: FOR loop initialization */
 bpp_vars[9] = 1;
 bpp_for_5:;
 /* Line 810 */
 bpp_vars[12] = *bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]));
 /* Line 820 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("X", (int)(bpp_vars[12]), 0) != 0)) { /* BASIC: GOTO */
goto L860;
 }
 /* Line 830 */
 *bpp_dim_ref("X", (int)(bpp_vars[12]), 0) = 5;
 /* Line 840 */
 printf("%s", "MACHINE MOVES TO");
 /* Line 850 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 4; goto L1570;
 bpp_ret_4:;
 L860: /* Line 860 */
 /* BASIC: NEXT loop step */
 bpp_vars[9] += 1;
 if (bpp_vars[9] <= 4) goto bpp_for_5;
 /* Line 870 */
 printf("%s", ", AND WINS AS FOLLOWS");
 printf("\n");
 /* Line 880 */
 /* BASIC: FOR loop initialization */
 bpp_vars[9] = 1;
 bpp_for_6:;
 /* Line 890 */
 bpp_vars[12] = *bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]));
 /* Line 900 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 5; goto L1570;
 bpp_ret_5:;
 /* Line 910 */
 /* BASIC: NEXT loop step */
 bpp_vars[9] += 1;
 if (bpp_vars[9] <= 4) goto bpp_for_6;
 /* Line 920 */
 /* BASIC: GOTO */
 goto L1490;
 L930: /* Line 930 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("L", (int)(bpp_vars[8]), 0) != 3)) { /* BASIC: GOTO */
goto L690;
 }
 /* Line 940 */
 printf("%s", "NICE TRY. MACHINE MOVES TO");
 /* Line 950 */
 /* BASIC: FOR loop initialization */
 bpp_vars[9] = 1;
 bpp_for_7:;
 /* Line 960 */
 bpp_vars[12] = *bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]));
 /* Line 970 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("X", (int)(bpp_vars[12]), 0) != 0)) { /* BASIC: GOTO */
goto L1010;
 }
 /* Line 980 */
 *bpp_dim_ref("X", (int)(bpp_vars[12]), 0) = 5;
 /* Line 990 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 6; goto L1570;
 bpp_ret_6:;
 /* Line 1000 */
 /* BASIC: GOTO */
 goto L500;
 L1010: /* Line 1010 */
 /* BASIC: NEXT loop step */
 bpp_vars[9] += 1;
 if (bpp_vars[9] <= 4) goto bpp_for_7;
 /* Line 1020 */
 /* BASIC: GOTO */
 goto L1300;
 L1030: /* Line 1030 */
 bpp_vars[8] = 1;
 L1040: /* Line 1040 */
 *bpp_dim_ref("L", (int)(bpp_vars[8]), 0) = (((*bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(1))), 0) + *bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(2))), 0)) + *bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(3))), 0)) + *bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(4))), 0));
 /* Line 1050 */
 bpp_vars[11] = *bpp_dim_ref("L", (int)(bpp_vars[8]), 0);
 /* Line 1060 */
 /* BASIC: IF statement */
 if ((bpp_vars[11] < 2)) { /* BASIC: GOTO */
goto L1130;
 }
 /* Line 1070 */
 /* BASIC: IF statement */
 if ((bpp_vars[11] >= 3)) { /* BASIC: GOTO */
goto L1130;
 }
 /* Line 1080 */
 /* BASIC: IF statement */
 if ((bpp_vars[11] > 2)) { /* BASIC: GOTO */
goto L2230;
 }
 /* Line 1090 */
 /* BASIC: FOR loop initialization */
 bpp_vars[9] = 1;
 bpp_for_8:;
 /* Line 1100 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]))), 0) != 0)) { /* BASIC: GOTO */
goto L1120;
 }
 /* Line 1110 */
 *bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]))), 0) = (1 / 8);
 L1120: /* Line 1120 */
 /* BASIC: NEXT loop step */
 bpp_vars[9] += 1;
 if (bpp_vars[9] <= 4) goto bpp_for_8;
 L1130: /* Line 1130 */
 bpp_vars[8] = (bpp_vars[8] + 1);
 /* BASIC: IF statement */
 if ((bpp_vars[8] <= 76)) { /* BASIC: GOTO */
goto L1040;
 }
 /* Line 1140 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 7; goto L1640;
 bpp_ret_7:;
 /* Line 1150 */
 bpp_vars[8] = 1;
 L1160: /* Line 1160 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("L", (int)(bpp_vars[8]), 0) == (1 / 2))) { /* BASIC: GOTO */
goto L2360;
 }
 /* Line 1170 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("L", (int)(bpp_vars[8]), 0) == (1 + (3 / 8)))) { /* BASIC: GOTO */
goto L2360;
 }
 /* Line 1180 */
 bpp_vars[8] = (bpp_vars[8] + 1);
 /* BASIC: IF statement */
 if ((bpp_vars[8] <= 76)) { /* BASIC: GOTO */
goto L1160;
 }
 /* Line 1190 */
 /* BASIC: GOTO */
 goto L1830;
 L1200: /* Line 1200 */
 bpp_vars[25] = 1;
 L1210: /* Line 1210 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("X", (int)(*bpp_dim_ref("Y", (int)(bpp_vars[25]), 0)), 0) == 0)) { /* BASIC: GOTO */
goto L1250;
 }
 /* Line 1220 */
 bpp_vars[25] = (bpp_vars[25] + 1);
 /* Line 1230 */
 /* BASIC: IF statement */
 if ((bpp_vars[25] != 17)) { /* BASIC: GOTO */
goto L1210;
 }
 /* Line 1240 */
 /* BASIC: GOTO */
 goto L1720;
 L1250: /* Line 1250 */
 bpp_vars[12] = *bpp_dim_ref("Y", (int)(bpp_vars[25]), 0);
 /* Line 1260 */
 *bpp_dim_ref("X", (int)(bpp_vars[12]), 0) = 5;
 /* Line 1270 */
 printf("%s", "MACHINE MOVES TO");
 /* Line 1280 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 8; goto L1570;
 bpp_ret_8:;
 /* Line 1290 */
 /* BASIC: GOTO */
 goto L500;
 L1300: /* Line 1300 */
 bpp_vars[23] = bpp_vars[23];
 /* Line 1310 */
 bpp_vars[8] = 1;
 L1320: /* Line 1320 */
 *bpp_dim_ref("L", (int)(bpp_vars[8]), 0) = (((*bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(1))), 0) + *bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(2))), 0)) + *bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(3))), 0)) + *bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(4))), 0));
 /* Line 1330 */
 bpp_vars[11] = *bpp_dim_ref("L", (int)(bpp_vars[8]), 0);
 /* Line 1340 */
 /* BASIC: IF statement */
 if ((bpp_vars[11] < 10)) { /* BASIC: GOTO */
goto L1410;
 }
 /* Line 1350 */
 /* BASIC: IF statement */
 if ((bpp_vars[11] >= 11)) { /* BASIC: GOTO */
goto L1410;
 }
 /* Line 1360 */
 /* BASIC: IF statement */
 if ((bpp_vars[11] > 10)) { /* BASIC: GOTO */
goto L2230;
 }
 /* Line 1370 */
 /* BASIC: FOR loop initialization */
 bpp_vars[9] = 1;
 bpp_for_9:;
 /* Line 1380 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]))), 0) != 0)) { /* BASIC: GOTO */
goto L1400;
 }
 /* Line 1390 */
 *bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]))), 0) = (1 / 8);
 L1400: /* Line 1400 */
 /* BASIC: NEXT loop step */
 bpp_vars[9] += 1;
 if (bpp_vars[9] <= 4) goto bpp_for_9;
 L1410: /* Line 1410 */
 bpp_vars[8] = (bpp_vars[8] + 1);
 /* BASIC: IF statement */
 if ((bpp_vars[8] <= 76)) { /* BASIC: GOTO */
goto L1320;
 }
 /* Line 1420 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 9; goto L1640;
 bpp_ret_9:;
 /* Line 1430 */
 bpp_vars[8] = 1;
 L1440: /* Line 1440 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("L", (int)(bpp_vars[8]), 0) == 0.5)) { /* BASIC: GOTO */
goto L2360;
 }
 /* Line 1450 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("L", (int)(bpp_vars[8]), 0) == (5 + (3 / 8)))) { /* BASIC: GOTO */
goto L2360;
 }
 /* Line 1460 */
 bpp_vars[8] = (bpp_vars[8] + 1);
 /* BASIC: IF statement */
 if ((bpp_vars[8] <= 76)) { /* BASIC: GOTO */
goto L1440;
 }
 /* Line 1470 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 10; goto L2500;
 bpp_ret_10:;
 /* Line 1480 */
 /* BASIC: GOTO */
 goto L1030;
 L1490: /* Line 1490 */
 printf("%s", " ");
 printf("\n");
 /* Line 1500 */
 printf("%s", "DO YOU WANT TO TRY ANOTHER GAME");
 L1510: /* Line 1510 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[23], _buf, 255); }
 /* Line 1520 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_left(bpp_strvars[23], (int)(1)), "Y") == 0))) { /* BASIC: GOTO */
goto L400;
 }
 /* Line 1530 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_left(bpp_strvars[23], (int)(1)), "N") == 0))) { /* BASIC: GOTO */
goto L1560;
 }
 /* Line 1540 */
 printf("%s", "INCORRECT ANSWER. PLEASE TYPE 'YES' OR 'NO'");
 /* Line 1550 */
 /* BASIC: GOTO */
 goto L1510;
 L1560: /* Line 1560 */
 /* REM RUN (compiled: restart) */
 printf("STOPPED\n"); goto bpp_end;
  L1570: /* Line 1570 */
 bpp_vars[27] = (floor(((bpp_vars[12] - 1) / 16)) + 1);
 /* Line 1580 */
 bpp_vars[28] = (bpp_vars[12] - (16 * (bpp_vars[27] - 1)));
 /* Line 1590 */
 bpp_vars[29] = (floor(((bpp_vars[28] - 1) / 4)) + 1);
 /* Line 1600 */
 bpp_vars[30] = ((bpp_vars[12] - ((bpp_vars[27] - 1) * 16)) - ((bpp_vars[29] - 1) * 4));
 /* Line 1610 */
 bpp_vars[12] = (((bpp_vars[27] * 100) + (bpp_vars[29] * 10)) + bpp_vars[30]);
 /* Line 1620 */
 { double _v = bpp_vars[12]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 /* Line 1630 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 default: goto bpp_end;
 } }
 L1640: /* Line 1640 */
 /* BASIC: FOR loop initialization */
 bpp_vars[18] = 1;
 bpp_for_10:;
 /* Line 1650 */
 bpp_vars[26] = *bpp_dim_ref("M", (int)(bpp_vars[18]), (int)(1));
 /* Line 1660 */
 bpp_vars[28] = *bpp_dim_ref("M", (int)(bpp_vars[18]), (int)(2));
 /* Line 1670 */
 bpp_vars[31] = *bpp_dim_ref("M", (int)(bpp_vars[18]), (int)(3));
 /* Line 1680 */
 bpp_vars[32] = *bpp_dim_ref("M", (int)(bpp_vars[18]), (int)(4));
 /* Line 1690 */
 *bpp_dim_ref("L", (int)(bpp_vars[18]), 0) = (((*bpp_dim_ref("X", (int)(bpp_vars[26]), 0) + *bpp_dim_ref("X", (int)(bpp_vars[28]), 0)) + *bpp_dim_ref("X", (int)(bpp_vars[31]), 0)) + *bpp_dim_ref("X", (int)(bpp_vars[32]), 0));
 /* Line 1700 */
 /* BASIC: NEXT loop step */
 bpp_vars[18] += 1;
 if (bpp_vars[18] <= 76) goto bpp_for_10;
 /* Line 1710 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 default: goto bpp_end;
 } }
 L1720: /* Line 1720 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_11:;
 /* Line 1730 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("X", (int)(bpp_vars[8]), 0) != 0)) { /* BASIC: GOTO */
goto L1800;
 }
 /* Line 1740 */
 *bpp_dim_ref("X", (int)(bpp_vars[8]), 0) = 5;
 /* Line 1750 */
 bpp_vars[12] = bpp_vars[8];
 /* Line 1760 */
 printf("%s", "MACHINE LIKES");
 /* Line 1770 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 11; goto L1570;
 bpp_ret_11:;
 /* Line 1780 */
 printf("%s", " ");
 printf("\n");
 /* Line 1790 */
 /* BASIC: GOTO */
 goto L500;
 L1800: /* Line 1800 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= 64) goto bpp_for_11;
 /* Line 1810 */
 printf("%s", "THE GAME IS A DRAW.");
 printf("\n");
 /* Line 1820 */
 /* BASIC: GOTO */
 goto L1490;
 L1830: /* Line 1830 */
 /* BASIC: FOR loop initialization */
 bpp_vars[10] = 1;
 bpp_for_12:;
 /* Line 1840 */
 bpp_vars[15] = 0;
 /* Line 1850 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = ((4 * bpp_vars[10]) - 3);
 bpp_for_13:;
 /* Line 1860 */
 /* BASIC: FOR loop initialization */
 bpp_vars[9] = 1;
 bpp_for_14:;
 /* Line 1870 */
 bpp_vars[15] = (bpp_vars[15] + *bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]))), 0));
 /* Line 1880 */
 /* BASIC: NEXT loop step */
 bpp_vars[9] += 1;
 if (bpp_vars[9] <= 4) goto bpp_for_14;
 /* Line 1890 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= (4 * bpp_vars[10])) goto bpp_for_13;
 /* Line 1900 */
 /* BASIC: IF statement */
 if ((bpp_vars[15] < 4)) { /* BASIC: GOTO */
goto L1940;
 }
 /* Line 1910 */
 /* BASIC: IF statement */
 if ((bpp_vars[15] < 5)) { /* BASIC: GOTO */
goto L1970;
 }
 /* Line 1920 */
 /* BASIC: IF statement */
 if ((bpp_vars[15] < 9)) { /* BASIC: GOTO */
goto L1940;
 }
 /* Line 1930 */
 /* BASIC: IF statement */
 if ((bpp_vars[15] < 10)) { /* BASIC: GOTO */
goto L1970;
 }
 L1940: /* Line 1940 */
 /* BASIC: NEXT loop step */
 bpp_vars[10] += 1;
 if (bpp_vars[10] <= 18) goto bpp_for_12;
 /* Line 1950 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 12; goto L2500;
 bpp_ret_12:;
 /* Line 1960 */
 /* BASIC: GOTO */
 goto L1200;
 L1970: /* Line 1970 */
 bpp_vars[18] = (1 / 8);
 L1980: /* Line 1980 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = ((4 * bpp_vars[10]) - 3);
 bpp_for_15:;
 /* Line 1990 */
 /* BASIC: GOTO */
 goto L2370;
 L2000: /* Line 2000 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= (4 * bpp_vars[10])) goto bpp_for_15;
 /* Line 2010 */
 bpp_vars[18] = 0;
 /* Line 2020 */
 /* BASIC: GOTO */
 goto L1980;
 /* Line 2030 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 2040 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 2050 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 2060 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 2070 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 2080 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 2090 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 2100 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 2110 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 2120 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 2130 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 2140 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 2150 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 2160 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 2170 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 2180 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 2190 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 2200 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 2210 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 /* Line 2220 */
 /* BASIC: DATA definition */
 /* DATA - see initialization */
 L2230: /* Line 2230 */
 /* BASIC: FOR loop initialization */
 bpp_vars[9] = 1;
 bpp_for_16:;
 /* Line 2240 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]))), 0) != (1 / 8))) { /* BASIC: GOTO */
goto L2330;
 }
 /* Line 2250 */
 *bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]))), 0) = 5;
 /* Line 2260 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("L", (int)(bpp_vars[8]), 0) < 5)) { /* BASIC: GOTO */
goto L2290;
 }
 /* Line 2270 */
 printf("%s", "LET'S SEE YOU GET OUT OF THIS:  MACHINE MOVES TO");
 /* Line 2280 */
 /* BASIC: GOTO */
 goto L2300;
 L2290: /* Line 2290 */
 printf("%s", "YOU FOX.  JUST IN THE NICK OF TIME, MACHINE MOVES TO");
 L2300: /* Line 2300 */
 bpp_vars[12] = *bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]));
 /* Line 2310 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 13; goto L1570;
 bpp_ret_13:;
 /* Line 2320 */
 /* BASIC: GOTO */
 goto L500;
 L2330: /* Line 2330 */
 /* BASIC: NEXT loop step */
 bpp_vars[9] += 1;
 if (bpp_vars[9] <= 4) goto bpp_for_16;
 /* Line 2340 */
 printf("%s", "MACHINE CONCEDES THIS GAME.");
 printf("\n");
 /* Line 2350 */
 /* BASIC: GOTO */
 goto L1490;
 L2360: /* Line 2360 */
 bpp_vars[18] = (1 / 8);
 L2370: /* Line 2370 */
 /* BASIC: IF statement */
 if (((bpp_vars[8] - (floor((bpp_vars[8] / 4)) * 4)) > 1)) { /* BASIC: GOTO */
goto L2400;
 }
 /* Line 2380 */
 bpp_vars[0] = 1;
 /* Line 2390 */
 /* BASIC: GOTO */
 goto L2410;
 L2400: /* Line 2400 */
 bpp_vars[0] = 2;
 L2410: /* Line 2410 */
 /* BASIC: FOR loop initialization */
 bpp_vars[9] = bpp_vars[0];
 bpp_for_17:;
 /* Line 2420 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]))), 0) == bpp_vars[18])) { /* BASIC: GOTO */
goto L2450;
 }
 /* Line 2430 */
 /* BASIC: NEXT loop step */
 bpp_vars[9] += (5 - (2 * bpp_vars[0]));
 if (((5 - (2 * bpp_vars[0])) > 0 && bpp_vars[9] <= (5 - bpp_vars[0])) || ((5 - (2 * bpp_vars[0])) < 0 && bpp_vars[9] >= (5 - bpp_vars[0]))) goto bpp_for_17;
 /* Line 2440 */
 /* BASIC: GOTO */
 goto L2000;
 L2450: /* Line 2450 */
 *bpp_dim_ref("X", (int)(*bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]))), 0) = 5;
 /* Line 2460 */
 bpp_vars[12] = *bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9]));
 /* Line 2470 */
 printf("%s", "MACHINE TAKES");
 /* Line 2480 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 14; goto L1570;
 bpp_ret_14:;
 /* Line 2490 */
 /* BASIC: GOTO */
 goto L500;
 L2500: /* Line 2500 */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_18:;
 /* Line 2510 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("X", (int)(bpp_vars[8]), 0) != (1 / 8))) { /* BASIC: GOTO */
goto L2530;
 }
 /* Line 2520 */
 *bpp_dim_ref("X", (int)(bpp_vars[8]), 0) = 0;
 L2530: /* Line 2530 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= 64) goto bpp_for_18;
 /* Line 2540 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 default: goto bpp_end;
 } }
 L2550: /* Line 2550 */
 /* BASIC: FOR loop initialization */
 bpp_vars[33] = 1;
 bpp_for_19:;
  printf("\n");
 /* BASIC: NEXT loop step */
 /* NEXT  : no matching FOR */
 /* BASIC: FOR loop initialization */
 bpp_vars[8] = 1;
 bpp_for_20:;
 /* Line 2560 */
 /* BASIC: FOR loop initialization */
 bpp_vars[9] = 1;
 bpp_for_21:;
 /* Line 2562 */
 /* BASIC: FOR loop initialization */
 bpp_vars[34] = 1;
 bpp_for_22:;
 /* Line 2564 */
 printf("%s", "   ");
 /* Line 2566 */
 /* BASIC: NEXT loop step */
 bpp_vars[34] += 1;
 if (bpp_vars[34] <= bpp_vars[9]) goto bpp_for_22;
 /* Line 2570 */
 /* BASIC: FOR loop initialization */
 bpp_vars[10] = 1;
 bpp_for_23:;
 /* Line 2600 */
 bpp_vars[16] = ((((16 * bpp_vars[8]) + (4 * bpp_vars[9])) + bpp_vars[10]) - 20);
 /* Line 2610 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("X", (int)(bpp_vars[16]), 0) != bpp_vars[14])) { /* BASIC: GOTO */
goto L2630;
 }
 /* Line 2620 */
 printf("%s", "( )      ");
 L2630: /* Line 2630 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("X", (int)(bpp_vars[16]), 0) != 5)) { /* BASIC: GOTO */
goto L2650;
 }
 /* Line 2640 */
 printf("%s", "(M)      ");
 L2650: /* Line 2650 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("X", (int)(bpp_vars[16]), 0) != 1)) { /* BASIC: GOTO */
goto L2660;
 }
 /* Line 2655 */
 printf("%s", "(Y)      ");
 L2660: /* Line 2660 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("X", (int)(bpp_vars[16]), 0) != (1 / 8))) { /* BASIC: GOTO */
goto L2670;
 }
 /* Line 2665 */
 printf("%s", "( )      ");
 L2670: /* Line 2670 */
 /* BASIC: NEXT loop step */
 bpp_vars[10] += 1;
 if (bpp_vars[10] <= 4) goto bpp_for_23;
 /* Line 2680 */
  printf("\n");
 /* Line 2690 */
  printf("\n");
 /* Line 2700 */
 /* BASIC: NEXT loop step */
 bpp_vars[9] += 1;
 if (bpp_vars[9] <= 4) goto bpp_for_21;
 /* Line 2710 */
  printf("\n");
 /* Line 2720 */
  printf("\n");
 /* Line 2730 */
 /* BASIC: NEXT loop step */
 bpp_vars[8] += 1;
 if (bpp_vars[8] <= 4) goto bpp_for_20;
 /* Line 2735 */
 /* REM 12) */
 /* Line 2740 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 case 2: goto bpp_ret_2;
 case 3: goto bpp_ret_3;
 case 4: goto bpp_ret_4;
 case 5: goto bpp_ret_5;
 case 6: goto bpp_ret_6;
 case 7: goto bpp_ret_7;
 case 8: goto bpp_ret_8;
 case 9: goto bpp_ret_9;
 case 10: goto bpp_ret_10;
 case 11: goto bpp_ret_11;
 case 12: goto bpp_ret_12;
 case 13: goto bpp_ret_13;
 case 14: goto bpp_ret_14;
 default: goto bpp_end;
 } }
 L2750: /* Line 2750 */
 printf("%s", "INCORRECT MOVE, RETYPE IT--");
 /* Line 2760 */
 /* BASIC: GOTO */
 goto L520;
 L2770: /* Line 2770 */
 goto bpp_end;
 bpp_end:
 return 0;
}
