#ifdef _MSC_VER
#ifndef _CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
#endif
#pragma warning(disable: 4996)
#pragma warning(disable: 4101)
#pragma warning(disable: 4244)
#pragma warning(disable: 4102)
#pragma warning(disable: 4311)
#pragma warning(disable: 4312)
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wstringop-truncation"
#pragma GCC diagnostic ignored "-Wrestrict"
#pragma GCC diagnostic ignored "-Wdouble-promotion"
#pragma GCC diagnostic ignored "-Wpointer-to-int-cast"
#pragma GCC diagnostic ignored "-Wint-to-pointer-cast"
#endif

/* Generated by BASIC++ Compiler for target: windows */
#define BPP_TARGET_WINDOWS
#define BPP_SUPPORT_MULTITASKING 1
#define BPP_SUPPORT_GRAPHICS 1
#define BPP_SUPPORT_FILESYSTEM 1

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* Windows specific platform headers */
#include <windows.h>

/* === Runtime Variables === */
static double bpp_vars[1024]; /* A-Z and named */
static char bpp_strvars[1024][256]; /* A$-Z$ and named */
static double bpp_at_array[4096]; /* @() legacy array */
static int bpp_print_width = 14;

/* === GOSUB Stack === */
#define BPP_MAX_STACK 256
static int bpp_gosub_stack[BPP_MAX_STACK];
static int bpp_gosub_sp = 0;

/* === DIM Arrays === */
#define BPP_MAX_DIM 64
#define BPP_MAX_ELEM 4194304
static double bpp_dim_pool[BPP_MAX_ELEM];
static int bpp_dim_used = 0;
typedef struct { char name[32]; int d1,d2,off; } BppDim;
static BppDim bpp_dims[BPP_MAX_DIM];
static int bpp_dim_count = 0;

static void bpp_dim_alloc(const char *nm, int d1, int d2) {
 int sz = (d1+1) * (d2>0 ? d2+1 : 1);
 BppDim *d = &bpp_dims[bpp_dim_count++];
 strncpy(d->name, nm, 31); d->name[31]='\0';
 d->d1=d1; d->d2=d2; d->off=bpp_dim_used;
 memset(&bpp_dim_pool[bpp_dim_used], 0, sizeof(double)*(size_t)sz);
 bpp_dim_used += sz;
}

static double *bpp_dim_ref(const char *nm, int i1, int i2) {
 int k;
 for (k=0; k<bpp_dim_count; k++) {
 if (strcmp(bpp_dims[k].name, nm)==0) {
 int idx = (bpp_dims[k].d2>0)
 ? i1*(bpp_dims[k].d2+1)+i2 : i1;
 return &bpp_dim_pool[bpp_dims[k].off + idx];
 }
 }
 fprintf(stderr, "Array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === String DIM arrays === */
#define BPP_MAX_STRDIM 26
#define BPP_MAX_STRDIM_SIZE 256
static struct { char nm[16]; int d1; int d2;
 char data[BPP_MAX_STRDIM_SIZE][256]; } bpp_strdims[BPP_MAX_STRDIM];
static int bpp_strdim_count = 0;

static char *bpp_strdim_ref(const char *nm, int i1, int i2) {
 int k;
 (void)i2;
 for (k = 0; k < bpp_strdim_count; k++) {
 if (strcmp(bpp_strdims[k].nm, nm) == 0) {
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[k].data[i1];
 }
 }
 /* Auto-create */
 if (bpp_strdim_count < BPP_MAX_STRDIM) {
 int j;
 strncpy(bpp_strdims[bpp_strdim_count].nm, nm, 15);
 bpp_strdims[bpp_strdim_count].nm[15] = '\0';
 for (j = 0; j < BPP_MAX_STRDIM_SIZE; j++)
 bpp_strdims[bpp_strdim_count].data[j][0] = '\0';
 bpp_strdim_count++;
 if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
 return bpp_strdims[bpp_strdim_count-1].data[i1];
 }
 fprintf(stderr, "String array not found: %s\n", nm);
 exit(1);
 return NULL;
}

/* === DATA/READ support === */
#define BPP_MAX_DATA 4096
static const char *bpp_data_pool[BPP_MAX_DATA];
static int bpp_data_count = 0;
static int bpp_data_ptr = 0;

static double bpp_read_num(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return atof(bpp_data_pool[bpp_data_ptr++]);
}

static const char *bpp_read_str(void) {
  if (bpp_data_ptr >= bpp_data_count) {
    fprintf(stderr, "OUT OF DATA\n"); exit(1);
  }
  return bpp_data_pool[bpp_data_ptr++];
}

/* === String helpers === */
static char bpp_strtmp[8][256];
static int bpp_strtmp_idx = 0;

static char *bpp_tmp(void) {
 char *p = bpp_strtmp[bpp_strtmp_idx];
 bpp_strtmp_idx = (bpp_strtmp_idx+1) & 7;
 return p;
}

static const char *bpp_concat(const char *a, const char *b) {
 char *t = bpp_tmp();
 t[0]='\0';
 strncat(t, a, 254);
 strncat(t, b, 254-(int)strlen(t));
 return t;
}

static const char *bpp_left(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_right(const char *s, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (n>len) n=len;
 if (n<0) n=0;
 memcpy(t, s+len-n, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_mid(const char *s, int st, int n) {
 char *t = bpp_tmp();
 int len = (int)strlen(s);
 if (st<0) st=0;
 if (st>len) st=len;
 if (n<0) n=0;
 if (st+n>len) n=len-st;
 memcpy(t, s+st, (size_t)n); t[n]='\0';
 return t;
}

static const char *bpp_chr(int n) {
 char *t = bpp_tmp();
 t[0]=(char)n; t[1]='\0';
 return t;
}

static const char *bpp_str(double n) {
 char *t = bpp_tmp();
 sprintf(t, "%g", n);
 return t;
}

/* === TAB helper === */
static const char *bpp_tab(int col) {
 static char buf[256];
 int i;
 if (col < 0) col = 0;
 if (col > 255) col = 255;
 for (i = 0; i < col; i++) buf[i] = ' ';
 buf[col] = '\0';
 return buf;
}

/* === DEF FN support === */
#define BPP_MAX_FN 26
typedef double (*BppFnPtr)(double);
static double bpp_fn_param;

int main(void) {
  bpp_data_count = 0;

 /* Line 10 */
 printf("%s", bpp_tab((int)(33)));
 printf("%s", "TOWERS");
 printf("\n");
 /* Line 20 */
 printf("%s", bpp_tab((int)(15)));
 printf("%s", "CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY");
 printf("\n");
 /* Line 30 */
  printf("\n");
  printf("\n");
  printf("\n");
 L90: /* Line 90 */
  printf("\n");
 /* Line 100 */
 /* REM  INITIALIZE */
 /* Line 110 */
 /* BASIC: DIM (Array Allocation) */
 bpp_dim_alloc("T", (int)(7), (int)(3));
 /* Line 120 */
 bpp_vars[4] = 0;
 /* Line 130 */
 /* BASIC: FOR loop initialization */
 bpp_vars[3] = 1;
 bpp_for_0:;
 /* Line 140 */
 /* BASIC: FOR loop initialization */
 bpp_vars[13] = 1;
 bpp_for_1:;
 /* Line 150 */
 *bpp_dim_ref("T", (int)(bpp_vars[3]), (int)(bpp_vars[13])) = 0;
 /* Line 160 */
 /* BASIC: NEXT loop step */
 bpp_vars[13] += 1;
 if (bpp_vars[13] <= 3) goto bpp_for_1;
 /* Line 170 */
 /* BASIC: NEXT loop step */
 bpp_vars[3] += 1;
 if (bpp_vars[3] <= 7) goto bpp_for_0;
 /* Line 180 */
 printf("%s", "TOWERS OF HANOI PUZZLE.");
 printf("\n");
  printf("\n");
 /* Line 200 */
 printf("%s", "YOU MUST TRANSFER THE DISKS FROM THE LEFT TO THE RIGHT");
 printf("\n");
 /* Line 205 */
 printf("%s", "TOWER, ONE AT A TIME, NEVER PUTTING A LARGER DISK ON A");
 printf("\n");
 /* Line 210 */
 printf("%s", "SMALLER DISK.");
 printf("\n");
  printf("\n");
 L215: /* Line 215 */
 printf("%s", "HOW MANY DISKS DO YOU WANT TO MOVE (7 IS MAX)");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[18] = _v; }
 /* Line 220 */
  printf("\n");
 /* Line 230 */
 bpp_vars[12] = 0;
 /* Line 240 */
 /* BASIC: FOR loop initialization */
 bpp_vars[16] = 1;
 bpp_for_2:;
 /* Line 250 */
 /* BASIC: IF statement */
 if ((bpp_vars[16] == bpp_vars[18])) { /* BASIC: GOTO */
goto L350;
 }
 /* Line 260 */
 /* BASIC: NEXT loop step */
 bpp_vars[16] += 1;
 if (bpp_vars[16] <= 7) goto bpp_for_2;
 /* Line 270 */
 bpp_vars[4] = (bpp_vars[4] + 1);
 /* Line 280 */
 /* BASIC: IF statement */
 if ((bpp_vars[4] > 2)) { /* BASIC: GOTO */
goto L310;
 }
 /* Line 290 */
 printf("%s", "SORRY, BUT I CAN'T DO THAT JOB FOR YOU.");
 printf("\n");
 /* BASIC: GOTO */
 goto L215;
 L310: /* Line 310 */
 printf("%s", "ALL RIGHT, WISE GUY, IF YOU CAN'T PLAY THE GAME RIGHT, I'LL");
 printf("\n");
 /* Line 320 */
 printf("%s", "JUST TAKE MY PUZZLE AND GO HOME.  SO LONG.");
 printf("\n");
 printf("STOPPED\n"); goto bpp_end;
 /* Line 340 */
 /* REM  STORE DISKS FROM SMALLEST TO LARGEST */
 L350: /* Line 350 */
 printf("%s", "IN THIS PROGRAM, WE SHALL REFER TO DISKS BY NUMERICAL CODE.");
 printf("\n");
 /* Line 355 */
 printf("%s", "3 WILL REPRESENT THE SMALLEST DISK, 5 THE NEXT SIZE,");
 printf("\n");
 /* Line 360 */
 printf("%s", "7 THE NEXT, AND SO ON, UP TO 15.  IF YOU DO THE PUZZLE WITH");
 printf("\n");
 /* Line 365 */
 printf("%s", "2 DISKS, THEIR CODE NAMES WOULD BE 13 AND 15.  WITH 3 DISKS");
 printf("\n");
 /* Line 370 */
 printf("%s", "THE CODE NAMES WOULD BE 11, 13 AND 15, ETC.  THE NEEDLES");
 printf("\n");
 /* Line 375 */
 printf("%s", "ARE NUMBERED FROM LEFT TO RIGHT, 1 TO 3.  WE WILL");
 printf("\n");
 /* Line 380 */
 printf("%s", "START WITH THE DISKS ON NEEDLE 1, AND ATTEMPT TO MOVE THEM");
 printf("\n");
 /* Line 385 */
 printf("%s", "TO NEEDLE 3.");
 printf("\n");
 /* Line 390 */
  printf("\n");
 printf("%s", "GOOD LUCK!");
 printf("\n");
  printf("\n");
 /* Line 400 */
 bpp_vars[24] = 7;
 bpp_vars[3] = 15;
 /* Line 420 */
 /* BASIC: FOR loop initialization */
 bpp_vars[23] = bpp_vars[18];
 bpp_for_3:;
 /* Line 430 */
 *bpp_dim_ref("T", (int)(bpp_vars[24]), (int)(1)) = bpp_vars[3];
 bpp_vars[3] = (bpp_vars[3] - 2);
 bpp_vars[24] = (bpp_vars[24] - 1);
 /* Line 460 */
 /* BASIC: NEXT loop step */
 bpp_vars[23] += (-(1));
 if (((-(1)) > 0 && bpp_vars[23] <= 1) || ((-(1)) < 0 && bpp_vars[23] >= 1)) goto bpp_for_3;
 /* Line 470 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 0; goto L1230;
 bpp_ret_0:;
 L480: /* Line 480 */
 printf("%s", "WHICH DISK WOULD YOU LIKE TO MOVE");
 bpp_vars[4] = 0;
 L500: /* Line 500 */
 printf("? ");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[3] = _v; }
 /* Line 510 */
 /* BASIC: IF statement */
 if (((((((((bpp_vars[3] - 3) * (bpp_vars[3] - 5)) * (bpp_vars[3] - 7)) * (bpp_vars[3] - 9)) * (bpp_vars[3] - 11)) * (bpp_vars[3] - 13)) * (bpp_vars[3] - 15)) == 0)) { /* BASIC: GOTO */
goto L580;
 }
 /* Line 520 */
 printf("%s", "ILLEGAL ENTRY... YOU MAY ONLY TYPE 3,5,7,9,11,13, OR 15.");
 printf("\n");
 /* Line 530 */
 bpp_vars[4] = (bpp_vars[4] + 1);
 /* BASIC: IF statement */
 if ((bpp_vars[4] > 1)) { /* BASIC: GOTO */
goto L560;
 }
 /* Line 550 */
 /* BASIC: GOTO */
 goto L500;
 L560: /* Line 560 */
 printf("%s", "STOP WASTING MY TIME.  GO BOTHER SOMEONE ELSE.");
 printf("\n");
 printf("STOPPED\n"); goto bpp_end;
 L580: /* Line 580 */
 /* REM  CHECK IF REQUESTED DISK IS BELOW ANOTHER */
 /* Line 590 */
 /* BASIC: FOR loop initialization */
 bpp_vars[17] = 1;
 bpp_for_4:;
 /* Line 600 */
 /* BASIC: FOR loop initialization */
 bpp_vars[2] = 1;
 bpp_for_5:;
 /* Line 610 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("T", (int)(bpp_vars[17]), (int)(bpp_vars[2])) == bpp_vars[3])) { /* BASIC: GOTO */
goto L640;
 }
 /* Line 620 */
 /* BASIC: NEXT loop step */
 bpp_vars[2] += 1;
 if (bpp_vars[2] <= 3) goto bpp_for_5;
 /* BASIC: NEXT loop step */
 bpp_vars[17] += 1;
 if (bpp_vars[17] <= 7) goto bpp_for_4;
 L640: /* Line 640 */
 /* BASIC: FOR loop initialization */
 bpp_vars[16] = bpp_vars[17];
 bpp_for_6:;
 /* Line 645 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("T", (int)(bpp_vars[16]), (int)(bpp_vars[2])) == 0)) { /* BASIC: GOTO */
goto L660;
 }
 /* Line 650 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("T", (int)(bpp_vars[16]), (int)(bpp_vars[2])) < bpp_vars[3])) { /* BASIC: GOTO */
goto L680;
 }
 L660: /* Line 660 */
 /* BASIC: NEXT loop step */
 bpp_vars[16] += (-(1));
 if (((-(1)) > 0 && bpp_vars[16] <= 1) || ((-(1)) < 0 && bpp_vars[16] >= 1)) goto bpp_for_6;
 /* Line 670 */
 /* BASIC: GOTO */
 goto L700;
 L680: /* Line 680 */
 printf("%s", "THAT DISK IS BELOW ANOTHER ONE.  MAKE ANOTHER CHOICE.");
 printf("\n");
 /* Line 690 */
 /* BASIC: GOTO */
 goto L480;
 L700: /* Line 700 */
 bpp_vars[4] = 0;
 L705: /* Line 705 */
 printf("%s", "PLACE DISK ON WHICH NEEDLE");
 fflush(stdout);
 { char _buf[256]; double _v;
   fgets(_buf, 256, stdin); _v = atof(_buf);
   bpp_vars[13] = _v; }
 /* Line 730 */
 /* BASIC: IF statement */
 if (((((bpp_vars[13] - 1) * (bpp_vars[13] - 2)) * (bpp_vars[13] - 3)) == 0)) { /* BASIC: GOTO */
goto L800;
 }
 /* Line 735 */
 bpp_vars[4] = (bpp_vars[4] + 1);
 /* Line 740 */
 /* BASIC: IF statement */
 if ((bpp_vars[4] > 1)) { /* BASIC: GOTO */
goto L780;
 }
 /* Line 750 */
 printf("%s", "I'LL ASSUME YOU HIT THE WRONG KEY THIS TIME.  BUT WATCH IT,");
 printf("\n");
 /* Line 760 */
 printf("%s", "I ONLY ALLOW ONE MISTAKE.");
 printf("\n");
 /* BASIC: GOTO */
 goto L705;
 L780: /* Line 780 */
 printf("%s", "I TRIED TO WARN YOU, BUT YOU WOULDN'T LISTEN.");
 printf("\n");
 /* Line 790 */
 printf("%s", "BYE BYE, BIG SHOT.");
 printf("\n");
 printf("STOPPED\n"); goto bpp_end;
 L800: /* Line 800 */
 /* BASIC: FOR loop initialization */
 bpp_vars[17] = 1;
 bpp_for_7:;
 /* Line 810 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("T", (int)(bpp_vars[17]), (int)(bpp_vars[13])) != 0)) { /* BASIC: GOTO */
goto L840;
 }
 /* Line 820 */
 /* BASIC: NEXT loop step */
 bpp_vars[17] += 1;
 if (bpp_vars[17] <= 7) goto bpp_for_7;
 /* Line 830 */
 /* BASIC: GOTO */
 goto L880;
 /* Line 835 */
 /* REM  CHECK IF DISK TO BE PLACED ON A LARGER ONE */
 L840: /* Line 840 */
 /* BASIC: IF statement */
 if ((bpp_vars[3] < *bpp_dim_ref("T", (int)(bpp_vars[17]), (int)(bpp_vars[13])))) { /* BASIC: GOTO */
goto L880;
 }
 /* Line 850 */
 printf("%s", "YOU CAN'T PLACE A LARGER DISK ON TOP OF A SMALLER ONE,");
 printf("\n");
 /* Line 860 */
 printf("%s", "IT MIGHT CRUSH IT!");
 printf("\n");
 printf("%s", "NOW THEN, ");
 /* BASIC: GOTO */
 goto L480;
 /* Line 875 */
 /* REM  MOVE RELOCATED DISK */
 L880: /* Line 880 */
 /* BASIC: FOR loop initialization */
 bpp_vars[21] = 1;
 bpp_for_8:;
 /* BASIC: FOR loop initialization */
 bpp_vars[22] = 1;
 bpp_for_9:;
 /* Line 900 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("T", (int)(bpp_vars[21]), (int)(bpp_vars[22])) == bpp_vars[3])) { /* BASIC: GOTO */
goto L930;
 }
 /* Line 910 */
 /* BASIC: NEXT loop step */
 bpp_vars[22] += 1;
 if (bpp_vars[22] <= 3) goto bpp_for_9;
 /* BASIC: NEXT loop step */
 bpp_vars[21] += 1;
 if (bpp_vars[21] <= 7) goto bpp_for_8;
 /* Line 925 */
 /* REM  LOCATE EMPTY SPACE ON NEEDLE N */
 L930: /* Line 930 */
 /* BASIC: FOR loop initialization */
 bpp_vars[20] = 1;
 bpp_for_10:;
 /* Line 940 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("T", (int)(bpp_vars[20]), (int)(bpp_vars[13])) != 0)) { /* BASIC: GOTO */
goto L970;
 }
 /* Line 950 */
 /* BASIC: NEXT loop step */
 bpp_vars[20] += 1;
 if (bpp_vars[20] <= 7) goto bpp_for_10;
 /* Line 960 */
 bpp_vars[20] = 7;
 /* BASIC: GOTO */
 goto L980;
 /* Line 965 */
 /* REM  MOVE DISK AND SET OLD LOCATION TO 0 */
 L970: /* Line 970 */
 bpp_vars[20] = (bpp_vars[20] - 1);
 L980: /* Line 980 */
 *bpp_dim_ref("T", (int)(bpp_vars[20]), (int)(bpp_vars[13])) = *bpp_dim_ref("T", (int)(bpp_vars[21]), (int)(bpp_vars[22]));
 *bpp_dim_ref("T", (int)(bpp_vars[21]), (int)(bpp_vars[22])) = 0;
 /* Line 995 */
 /* REM  PRINT OUT CURRENT STATUS */
 /* Line 1000 */
 /* BASIC: GOSUB */
 bpp_gosub_stack[bpp_gosub_sp++] = 1; goto L1230;
 bpp_ret_1:;
 /* Line 1018 */
 /* REM  CHECK IF DONE */
 /* Line 1020 */
 bpp_vars[12] = (bpp_vars[12] + 1);
 /* Line 1030 */
 /* BASIC: FOR loop initialization */
 bpp_vars[17] = 1;
 bpp_for_11:;
 /* BASIC: FOR loop initialization */
 bpp_vars[2] = 1;
 bpp_for_12:;
 /* Line 1050 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("T", (int)(bpp_vars[17]), (int)(bpp_vars[2])) != 0)) { /* BASIC: GOTO */
goto L1090;
 }
 /* Line 1060 */
 /* BASIC: NEXT loop step */
 bpp_vars[2] += 1;
 if (bpp_vars[2] <= 2) goto bpp_for_12;
 /* BASIC: NEXT loop step */
 bpp_vars[17] += 1;
 if (bpp_vars[17] <= 7) goto bpp_for_11;
 /* Line 1080 */
 /* BASIC: GOTO */
 goto L1120;
 L1090: /* Line 1090 */
 /* BASIC: IF statement */
 if ((bpp_vars[12] <= 128)) { /* BASIC: GOTO */
goto L480;
 }
 /* Line 1100 */
 printf("%s", "SORRY, BUT I HAVE ORDERS TO STOP IF YOU MAKE MORE THAN");
 printf("\n");
 /* Line 1110 */
 printf("%s", "128 MOVES.");
 printf("\n");
 printf("STOPPED\n"); goto bpp_end;
 L1120: /* Line 1120 */
 /* BASIC: IF statement */
 if ((bpp_vars[12] != ((pow(2, bpp_vars[18])) - 1))) { /* BASIC: GOTO */
goto L1140;
 }
 /* Line 1130 */
  printf("\n");
 printf("%s", "CONGRATULATIONS!!");
 printf("\n");
  printf("\n");
 L1140: /* Line 1140 */
 printf("%s", "YOU HAVE PERFORMED THE TASK IN");
 { double _v = bpp_vars[12]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
 printf("%s", "MOVES.");
 printf("\n");
 /* Line 1150 */
  printf("\n");
 printf("%s", "TRY AGAIN (YES OR NO)");
 printf("? ");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[0], _buf, 255); }
 L1160: /* Line 1160 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[0], "NO") == 0))) { /* BASIC: GOTO */
goto L1390;
 }
 /* Line 1170 */
 /* BASIC: IF statement */
 if (((strcmp(bpp_strvars[0], "YES") == 0))) { /* BASIC: GOTO */
goto L90;
 }
 /* Line 1180 */
  printf("\n");
 printf("%s", "'YES' OR 'NO' PLEASE");
 printf("? ");
 fflush(stdout);
 { char _buf[256]; int _len;
   fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
   while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
   strncpy(bpp_strvars[0], _buf, 255); }
 /* BASIC: GOTO */
 goto L1160;
 L1230: /* Line 1230 */
 /* REM  PRINT SUBROUTINE */
 /* Line 1240 */
 /* BASIC: FOR loop initialization */
 bpp_vars[10] = 1;
 bpp_for_13:;
 /* Line 1250 */
 bpp_vars[25] = 10;
 /* Line 1260 */
 /* BASIC: FOR loop initialization */
 bpp_vars[9] = 1;
 bpp_for_14:;
 /* Line 1270 */
 /* BASIC: IF statement */
 if ((*bpp_dim_ref("T", (int)(bpp_vars[10]), (int)(bpp_vars[9])) == 0)) { /* BASIC: GOTO */
goto L1330;
 }
 /* Line 1280 */
 printf("%s", bpp_tab((int)((bpp_vars[25] - floor((*bpp_dim_ref("T", (int)(bpp_vars[10]), (int)(bpp_vars[9])) / 2))))));
 /* Line 1290 */
 /* BASIC: FOR loop initialization */
 bpp_vars[21] = 1;
 bpp_for_15:;
 /* Line 1300 */
 printf("%s", "*");
 /* Line 1310 */
 /* BASIC: NEXT loop step */
 bpp_vars[21] += 1;
 if (bpp_vars[21] <= *bpp_dim_ref("T", (int)(bpp_vars[10]), (int)(bpp_vars[9]))) goto bpp_for_15;
 /* Line 1320 */
 /* BASIC: GOTO */
 goto L1340;
 L1330: /* Line 1330 */
 printf("%s", bpp_tab((int)(bpp_vars[25])));
 printf("%s", "*");
 L1340: /* Line 1340 */
 bpp_vars[25] = (bpp_vars[25] + 21);
 /* Line 1350 */
 /* BASIC: NEXT loop step */
 bpp_vars[9] += 1;
 if (bpp_vars[9] <= 3) goto bpp_for_14;
 /* Line 1360 */
  printf("\n");
 /* Line 1370 */
 /* BASIC: NEXT loop step */
 bpp_vars[10] += 1;
 if (bpp_vars[10] <= 7) goto bpp_for_13;
 /* Line 1380 */
 /* BASIC: RETURN */
 { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
 switch(_ra) {
 case 0: goto bpp_ret_0;
 case 1: goto bpp_ret_1;
 default: goto bpp_end;
 } }
 L1390: /* Line 1390 */
  printf("\n");
 printf("%s", "THANKS FOR THE GAME!");
 printf("\n");
  printf("\n");
 goto bpp_end;
 bpp_end:
 return 0;
}
