# Specification for Turtle Graphics Feature

DEFINE SPECIFICATION "TURTLE"
    CATEGORY "STATEMENT"
    VERSION "1.0"
    LIB "turtle.lib"
    SECURITY "STANDARD"
END SPECIFICATION

DEFINE SPECIFICATION "CUBE"
    CATEGORY "FUNCTION"
    VERSION "1.1"
    LIB "turtle.lib"
    SECURITY "STANDARD"
END SPECIFICATION
