/* Generated by BASIC++ Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* === Runtime Variables === */
static double bpp_vars[26];           /* A-Z */
static char bpp_strvars[26][256];     /* A$-Z$ */
static double bpp_at_array[4096];     /* @() legacy array */
static int bpp_print_width = 14;

/* === GOSUB Stack === */
#define BPP_MAX_STACK 256
static int bpp_gosub_stack[BPP_MAX_STACK];
static int bpp_gosub_sp = 0;

/* === DIM Arrays === */
#define BPP_MAX_DIM 64
#define BPP_MAX_ELEM 8192
static double bpp_dim_pool[BPP_MAX_ELEM];
static int bpp_dim_used = 0;
typedef struct { char name[32]; int d1,d2,off; } BppDim;
static BppDim bpp_dims[BPP_MAX_DIM];
static int bpp_dim_count = 0;

static void bpp_dim_alloc(const char *nm, int d1, int d2) {
    int sz = (d1+1) * (d2>0 ? d2+1 : 1);
    BppDim *d = &bpp_dims[bpp_dim_count++];
    strncpy(d->name, nm, 31); d->name[31]='\0';
    d->d1=d1; d->d2=d2; d->off=bpp_dim_used;
    memset(&bpp_dim_pool[bpp_dim_used], 0, sizeof(double)*(size_t)sz);
    bpp_dim_used += sz;
}

static double *bpp_dim_ref(const char *nm, int i1, int i2) {
    int k;
    for (k=0; k<bpp_dim_count; k++) {
        if (strcmp(bpp_dims[k].name, nm)==0) {
            int idx = (bpp_dims[k].d2>0)
                ? i1*(bpp_dims[k].d2+1)+i2 : i1;
            return &bpp_dim_pool[bpp_dims[k].off + idx];
        }
    }
    fprintf(stderr, "Array not found: %s\n", nm);
    exit(1);
    return NULL;
}

/* === String DIM arrays === */
#define BPP_MAX_STRDIM 26
#define BPP_MAX_STRDIM_SIZE 256
static struct { char nm[16]; int d1; int d2;
    char data[BPP_MAX_STRDIM_SIZE][256]; } bpp_strdims[BPP_MAX_STRDIM];
static int bpp_strdim_count = 0;

static char *bpp_strdim_ref(const char *nm, int i1, int i2) {
    int k;
    (void)i2;
    for (k = 0; k < bpp_strdim_count; k++) {
        if (strcmp(bpp_strdims[k].nm, nm) == 0) {
            if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
            return bpp_strdims[k].data[i1];
        }
    }
    /* Auto-create */
    if (bpp_strdim_count < BPP_MAX_STRDIM) {
        int j;
        strncpy(bpp_strdims[bpp_strdim_count].nm, nm, 15);
        bpp_strdims[bpp_strdim_count].nm[15] = '\0';
        for (j = 0; j < BPP_MAX_STRDIM_SIZE; j++)
            bpp_strdims[bpp_strdim_count].data[j][0] = '\0';
        bpp_strdim_count++;
        if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
        return bpp_strdims[bpp_strdim_count-1].data[i1];
    }
    fprintf(stderr, "String array not found: %s\n", nm);
    exit(1);
    return NULL;
}

/* === DATA/READ support === */
#define BPP_MAX_DATA 4096
static double bpp_data_pool[BPP_MAX_DATA];
static int bpp_data_count = 0;
static int bpp_data_ptr = 0;

static double bpp_read_num(void) {
    if (bpp_data_ptr >= bpp_data_count) {
        fprintf(stderr, "OUT OF DATA\n"); exit(1);
    }
    return bpp_data_pool[bpp_data_ptr++];
}

/* === String helpers === */
static char bpp_strtmp[8][256];
static int bpp_strtmp_idx = 0;

static char *bpp_tmp(void) {
    char *p = bpp_strtmp[bpp_strtmp_idx];
    bpp_strtmp_idx = (bpp_strtmp_idx+1) & 7;
    return p;
}

static const char *bpp_concat(const char *a, const char *b) {
    char *t = bpp_tmp();
    t[0]='\0';
    strncat(t, a, 254);
    strncat(t, b, 254-(int)strlen(t));
    return t;
}

static const char *bpp_left(const char *s, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if (n>len) n=len; if(n<0) n=0;
    memcpy(t, s, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_right(const char *s, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if (n>len) n=len; if(n<0) n=0;
    memcpy(t, s+len-n, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_mid(const char *s, int st, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if(st<0) st=0; if(st>len) st=len;
    if(n<0) n=0; if(st+n>len) n=len-st;
    memcpy(t, s+st, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_chr(int n) {
    char *t = bpp_tmp();
    t[0]=(char)n; t[1]='\0';
    return t;
}

static const char *bpp_str(double n) {
    char *t = bpp_tmp();
    sprintf(t, "%g", n);
    return t;
}

/* === TAB helper === */
static const char *bpp_tab(int col) {
    static char buf[256];
    int i;
    if (col < 0) col = 0;
    if (col > 255) col = 255;
    for (i = 0; i < col; i++) buf[i] = ' ';
    buf[col] = '\0';
    return buf;
}

/* === DEF FN support === */
#define BPP_MAX_FN 26
typedef double (*BppFnPtr)(double);
static double bpp_fn_param;

int main(void) {

  L5: /* Line 5 */
    printf("%s", bpp_tab((int)(33)));
    printf("%s", "BAGELS");
    printf("\n");
  L10: /* Line 10 */
    printf("%s", bpp_tab((int)(15)));
    printf("%s", "CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY");
    printf("\n");
        printf("\n");
        printf("\n");
  L15: /* Line 15 */
    /* REM  *** BAGLES NUMBER GUESSING GAME */
  L20: /* Line 20 */
    /* REM  *** ORIGINAL SOURCE UNKNOWN BUT SUSPECTED TO BE */
  L25: /* Line 25 */
    /* REM  *** LAWRENCE HALL OF SCIENCE, U.C. BERKELY */
  L30: /* Line 30 */
    bpp_dim_alloc("A1", (int)(3), 0);
    bpp_dim_alloc("A", (int)(3), 0);
    bpp_dim_alloc("B", (int)(3), 0);
  L40: /* Line 40 */
    bpp_vars[24] = 0;
    bpp_vars[19] = 255;
  L50: /* Line 50 */
        printf("\n");
        printf("\n");
        printf("\n");
  L70: /* Line 70 */
      L90: /* Line 90 */
    if (((strcmp(bpp_left(bpp_strvars[0], (int)(1)), "N") == 0))) { goto L150;
 }
  L100: /* Line 100 */
        printf("\n");
    printf("%s", "I AM THINKING OF A THREE-DIGIT NUMBER.  TRY TO GUESS");
    printf("\n");
  L110: /* Line 110 */
    printf("%s", "MY NUMBER AND I WILL GIVE YOU CLUES AS FOLLOWS:");
    printf("\n");
  L120: /* Line 120 */
    printf("%s", "   PICO   - ONE DIGIT CORRECT BUT IN THE WRONG POSITION");
    printf("\n");
  L130: /* Line 130 */
    printf("%s", "   FERMI  - ONE DIGIT CORRECT AND IN THE RIGHT POSITION");
    printf("\n");
  L140: /* Line 140 */
    printf("%s", "   BAGELS - NO DIGITS CORRECT");
    printf("\n");
  L150: /* Line 150 */
    bpp_vars[8] = 1;
  bpp_for_0:;
  L160: /* Line 160 */
    *bpp_dim_ref("A", (int)(bpp_vars[8]), 0) = floor((10 * ((double)(rand() % (int)(1)))));
  L165: /* Line 165 */
    if (((bpp_vars[8] - 1) == 0)) { goto L200;
 }
  L170: /* Line 170 */
    bpp_vars[9] = 1;
  bpp_for_1:;
  L180: /* Line 180 */
    if ((*bpp_dim_ref("A", (int)(bpp_vars[8]), 0) == *bpp_dim_ref("A", (int)(bpp_vars[9]), 0))) { goto L160;
 }
  L190: /* Line 190 */
    bpp_vars[9] += 1;
    if (bpp_vars[9] <= (bpp_vars[8] - 1)) goto bpp_for_1;
  L200: /* Line 200 */
    bpp_vars[8] += 1;
    if (bpp_vars[8] <= 3) goto bpp_for_0;
  L210: /* Line 210 */
        printf("\n");
    printf("%s", "O.K.  I HAVE A NUMBER IN MIND.");
    printf("\n");
  L220: /* Line 220 */
    bpp_vars[8] = 1;
  bpp_for_2:;
  L230: /* Line 230 */
    printf("%s", "GUESS #");
    { double _v = bpp_vars[8]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
  L240: /* Line 240 */
    printf("? ");
    fflush(stdout);
    { char _buf[256]; int _len;
      fgets(_buf, 256, stdin); _len=(int)strlen(_buf);
      while(_len>0 && (_buf[_len-1]=='\n'||_buf[_len-1]=='\r')) _buf[--_len]='\0';
      strncpy(bpp_strvars[0], _buf, 255); }
  L245: /* Line 245 */
    if (((double)strlen(bpp_strvars[0]) != 3)) { goto L630;
 }
  L250: /* Line 250 */
    bpp_vars[25] = 1;
  bpp_for_3:;
    *bpp_dim_ref("A1", (int)(bpp_vars[25]), 0) = (double)(unsigned char)(bpp_mid(bpp_strvars[0], (int)(bpp_vars[25]), (int)(1)))[0];
    bpp_vars[25] += 1;
    if (bpp_vars[25] <= 3) goto bpp_for_3;
  L260: /* Line 260 */
    bpp_vars[9] = 1;
  bpp_for_4:;
  L270: /* Line 270 */
    if ((*bpp_dim_ref("A1", (int)(bpp_vars[9]), 0) < 48)) { goto L300;
 }
  L280: /* Line 280 */
    if ((*bpp_dim_ref("A1", (int)(bpp_vars[9]), 0) > 57)) { goto L300;
 }
  L285: /* Line 285 */
    *bpp_dim_ref("B", (int)(bpp_vars[9]), 0) = (*bpp_dim_ref("A1", (int)(bpp_vars[9]), 0) - 48);
  L290: /* Line 290 */
    bpp_vars[9] += 1;
    if (bpp_vars[9] <= 3) goto bpp_for_4;
  L295: /* Line 295 */
    goto L320;
  L300: /* Line 300 */
    printf("%s", "WHAT?");
    printf("\n");
  L310: /* Line 310 */
    goto L230;
  L320: /* Line 320 */
    if ((*bpp_dim_ref("B", (int)(1), 0) == *bpp_dim_ref("B", (int)(2), 0))) { goto L650;
 }
  L330: /* Line 330 */
    if ((*bpp_dim_ref("B", (int)(2), 0) == *bpp_dim_ref("B", (int)(3), 0))) { goto L650;
 }
  L340: /* Line 340 */
    if ((*bpp_dim_ref("B", (int)(3), 0) == *bpp_dim_ref("B", (int)(1), 0))) { goto L650;
 }
  L350: /* Line 350 */
    bpp_vars[2] = 0;
    bpp_vars[3] = 0;
  L360: /* Line 360 */
    bpp_vars[9] = 1;
  bpp_for_5:;
  L370: /* Line 370 */
    if ((*bpp_dim_ref("A", (int)(bpp_vars[9]), 0) != *bpp_dim_ref("B", (int)((bpp_vars[9] + 1)), 0))) { goto L390;
 }
  L380: /* Line 380 */
    bpp_vars[2] = (bpp_vars[2] + 1);
  L390: /* Line 390 */
    if ((*bpp_dim_ref("A", (int)((bpp_vars[9] + 1)), 0) != *bpp_dim_ref("B", (int)(bpp_vars[9]), 0))) { goto L410;
 }
  L400: /* Line 400 */
    bpp_vars[2] = (bpp_vars[2] + 1);
  L410: /* Line 410 */
    bpp_vars[9] += 1;
    if (bpp_vars[9] <= 2) goto bpp_for_5;
  L420: /* Line 420 */
    if ((*bpp_dim_ref("A", (int)(1), 0) != *bpp_dim_ref("B", (int)(3), 0))) { goto L440;
 }
  L430: /* Line 430 */
    bpp_vars[2] = (bpp_vars[2] + 1);
  L440: /* Line 440 */
    if ((*bpp_dim_ref("A", (int)(3), 0) != *bpp_dim_ref("B", (int)(1), 0))) { goto L460;
 }
  L450: /* Line 450 */
    bpp_vars[2] = (bpp_vars[2] + 1);
  L460: /* Line 460 */
    bpp_vars[9] = 1;
  bpp_for_6:;
  L470: /* Line 470 */
    if ((*bpp_dim_ref("A", (int)(bpp_vars[9]), 0) != *bpp_dim_ref("B", (int)(bpp_vars[9]), 0))) { goto L490;
 }
  L480: /* Line 480 */
    bpp_vars[3] = (bpp_vars[3] + 1);
  L490: /* Line 490 */
    bpp_vars[9] += 1;
    if (bpp_vars[9] <= 3) goto bpp_for_6;
  L500: /* Line 500 */
    if ((bpp_vars[3] == 3)) { goto L680;
 }
  L505: /* Line 505 */
    if ((bpp_vars[2] == 0)) { goto L545;
 }
  L520: /* Line 520 */
    bpp_vars[9] = 1;
  bpp_for_7:;
  L530: /* Line 530 */
    printf("%s", "PICO ");
  L540: /* Line 540 */
    bpp_vars[9] += 1;
    if (bpp_vars[9] <= bpp_vars[2]) goto bpp_for_7;
  L545: /* Line 545 */
    if ((bpp_vars[3] == 0)) { goto L580;
 }
  L550: /* Line 550 */
    bpp_vars[9] = 1;
  bpp_for_8:;
  L560: /* Line 560 */
    printf("%s", "FERMI ");
  L570: /* Line 570 */
    bpp_vars[9] += 1;
    if (bpp_vars[9] <= bpp_vars[3]) goto bpp_for_8;
  L580: /* Line 580 */
    if (((bpp_vars[2] + bpp_vars[3]) != 0)) { goto L600;
 }
  L590: /* Line 590 */
    printf("%s", "BAGELS");
  L600: /* Line 600 */
        printf("\n");
  L605: /* Line 605 */
    bpp_vars[8] += 1;
    if (bpp_vars[8] <= 20) goto bpp_for_2;
  L610: /* Line 610 */
    printf("%s", "OH WELL.");
    printf("\n");
  L615: /* Line 615 */
    printf("%s", "THAT'S TWENTY GUESSES.  MY NUMBER WAS");
    { double _v = (((100 * *bpp_dim_ref("A", (int)(1), 0)) + (10 * *bpp_dim_ref("A", (int)(2), 0))) + *bpp_dim_ref("A", (int)(3), 0)); if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("\n");
  L620: /* Line 620 */
    goto L700;
  L630: /* Line 630 */
    printf("%s", "TRY GUESSING A THREE-DIGIT NUMBER.");
    printf("\n");
    goto L230;
  L650: /* Line 650 */
    printf("%s", "OH, I FORGOT TO TELL YOU THAT THE NUMBER I HAVE IN MIND");
    printf("\n");
  L660: /* Line 660 */
    printf("%s", "HAS NO TWO DIGITS THE SAME.");
    printf("\n");
    goto L230;
  L680: /* Line 680 */
    printf("%s", "YOU GOT IT!!!");
    printf("\n");
        printf("\n");
  L690: /* Line 690 */
    bpp_vars[24] = (bpp_vars[24] + 1);
  L700: /* Line 700 */
      L720: /* Line 720 */
    if (((strcmp(bpp_left(bpp_strvars[0], (int)(1)), "Y") == 0))) { goto L150;
 }
  L730: /* Line 730 */
    if ((bpp_vars[24] == 0)) { goto L750;
 }
  L740: /* Line 740 */
        printf("\n");
    printf("%s", "A");
    { double _v = bpp_vars[24]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("%s", "POINT BAGELS BUFF!!");
    printf("\n");
  L750: /* Line 750 */
    printf("%s", "HOPE YOU HAD FUN.  BYE.");
    printf("\n");
  L999: /* Line 999 */
    goto bpp_end;
  bpp_end:
    return 0;
}
