/* Generated by BASIC++ Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* === Runtime Variables === */
static double bpp_vars[26];           /* A-Z */
static char bpp_strvars[26][256];     /* A$-Z$ */
static double bpp_at_array[4096];     /* @() legacy array */
static int bpp_print_width = 14;

/* === GOSUB Stack === */
#define BPP_MAX_STACK 256
static int bpp_gosub_stack[BPP_MAX_STACK];
static int bpp_gosub_sp = 0;

/* === DIM Arrays === */
#define BPP_MAX_DIM 64
#define BPP_MAX_ELEM 8192
static double bpp_dim_pool[BPP_MAX_ELEM];
static int bpp_dim_used = 0;
typedef struct { char name[32]; int d1,d2,off; } BppDim;
static BppDim bpp_dims[BPP_MAX_DIM];
static int bpp_dim_count = 0;

static void bpp_dim_alloc(const char *nm, int d1, int d2) {
    int sz = (d1+1) * (d2>0 ? d2+1 : 1);
    BppDim *d = &bpp_dims[bpp_dim_count++];
    strncpy(d->name, nm, 31); d->name[31]='\0';
    d->d1=d1; d->d2=d2; d->off=bpp_dim_used;
    memset(&bpp_dim_pool[bpp_dim_used], 0, sizeof(double)*(size_t)sz);
    bpp_dim_used += sz;
}

static double *bpp_dim_ref(const char *nm, int i1, int i2) {
    int k;
    for (k=0; k<bpp_dim_count; k++) {
        if (strcmp(bpp_dims[k].name, nm)==0) {
            int idx = (bpp_dims[k].d2>0)
                ? i1*(bpp_dims[k].d2+1)+i2 : i1;
            return &bpp_dim_pool[bpp_dims[k].off + idx];
        }
    }
    fprintf(stderr, "Array not found: %s\n", nm);
    exit(1);
    return NULL;
}

/* === String DIM arrays === */
#define BPP_MAX_STRDIM 26
#define BPP_MAX_STRDIM_SIZE 256
static struct { char nm[16]; int d1; int d2;
    char data[BPP_MAX_STRDIM_SIZE][256]; } bpp_strdims[BPP_MAX_STRDIM];
static int bpp_strdim_count = 0;

static char *bpp_strdim_ref(const char *nm, int i1, int i2) {
    int k;
    (void)i2;
    for (k = 0; k < bpp_strdim_count; k++) {
        if (strcmp(bpp_strdims[k].nm, nm) == 0) {
            if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
            return bpp_strdims[k].data[i1];
        }
    }
    /* Auto-create */
    if (bpp_strdim_count < BPP_MAX_STRDIM) {
        int j;
        strncpy(bpp_strdims[bpp_strdim_count].nm, nm, 15);
        bpp_strdims[bpp_strdim_count].nm[15] = '\0';
        for (j = 0; j < BPP_MAX_STRDIM_SIZE; j++)
            bpp_strdims[bpp_strdim_count].data[j][0] = '\0';
        bpp_strdim_count++;
        if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
        return bpp_strdims[bpp_strdim_count-1].data[i1];
    }
    fprintf(stderr, "String array not found: %s\n", nm);
    exit(1);
    return NULL;
}

/* === DATA/READ support === */
#define BPP_MAX_DATA 4096
static double bpp_data_pool[BPP_MAX_DATA];
static int bpp_data_count = 0;
static int bpp_data_ptr = 0;

static double bpp_read_num(void) {
    if (bpp_data_ptr >= bpp_data_count) {
        fprintf(stderr, "OUT OF DATA\n"); exit(1);
    }
    return bpp_data_pool[bpp_data_ptr++];
}

/* === String helpers === */
static char bpp_strtmp[8][256];
static int bpp_strtmp_idx = 0;

static char *bpp_tmp(void) {
    char *p = bpp_strtmp[bpp_strtmp_idx];
    bpp_strtmp_idx = (bpp_strtmp_idx+1) & 7;
    return p;
}

static const char *bpp_concat(const char *a, const char *b) {
    char *t = bpp_tmp();
    t[0]='\0';
    strncat(t, a, 254);
    strncat(t, b, 254-(int)strlen(t));
    return t;
}

static const char *bpp_left(const char *s, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if (n>len) n=len; if(n<0) n=0;
    memcpy(t, s, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_right(const char *s, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if (n>len) n=len; if(n<0) n=0;
    memcpy(t, s+len-n, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_mid(const char *s, int st, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if(st<0) st=0; if(st>len) st=len;
    if(n<0) n=0; if(st+n>len) n=len-st;
    memcpy(t, s+st, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_chr(int n) {
    char *t = bpp_tmp();
    t[0]=(char)n; t[1]='\0';
    return t;
}

static const char *bpp_str(double n) {
    char *t = bpp_tmp();
    sprintf(t, "%g", n);
    return t;
}

/* === TAB helper === */
static const char *bpp_tab(int col) {
    static char buf[256];
    int i;
    if (col < 0) col = 0;
    if (col > 255) col = 255;
    for (i = 0; i < col; i++) buf[i] = ' ';
    buf[col] = '\0';
    return buf;
}

/* === DEF FN support === */
#define BPP_MAX_FN 26
typedef double (*BppFnPtr)(double);
static double bpp_fn_param;

int main(void) {
    bpp_data_pool[0] = 0;
    bpp_data_pool[1] = 1;
    bpp_data_pool[2] = 3;
    bpp_data_count = 3;

  L10: /* Line 10 */
    printf("%s", bpp_tab((int)(33)));
    printf("%s", "DIGITS");
    printf("\n");
  L20: /* Line 20 */
    printf("%s", bpp_tab((int)(15)));
    printf("%s", "CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY");
    printf("\n");
  L30: /* Line 30 */
        printf("\n");
        printf("\n");
        printf("\n");
  L210: /* Line 210 */
    printf("%s", "THIS IS A GAME OF GUESSING.");
    printf("\n");
  L220: /* Line 220 */
    printf("%s", "FOR INSTRUCTIONS, TYPE '1', ELSE TYPE '0'");
  L230: /* Line 230 */
    printf("? ");
    fflush(stdout);
    { char _buf[256]; double _v;
      fgets(_buf, 256, stdin); _v = atof(_buf);
      bpp_vars[4] = _v; }
  L240: /* Line 240 */
    if ((bpp_vars[4] == 0)) { goto L360;
 }
  L250: /* Line 250 */
        printf("\n");
  L260: /* Line 260 */
    printf("%s", "PLEASE TAKE A PIECE OF PAPER AND WRITE DOWN");
    printf("\n");
  L270: /* Line 270 */
    printf("%s", "THE DIGITS '0', '1', OR '2' THIRTY TIMES AT RANDOM.");
    printf("\n");
  L280: /* Line 280 */
    printf("%s", "ARRANGE THEM IN THREE LINES OF TEN DIGITS EACH.");
    printf("\n");
  L290: /* Line 290 */
    printf("%s", "I WILL ASK FOR THEN TEN AT A TIME.");
    printf("\n");
  L300: /* Line 300 */
    printf("%s", "I WILL ALWAYS GUESS THEM FIRST AND THEN LOOK AT YOUR");
    printf("\n");
  L310: /* Line 310 */
    printf("%s", "NEXT NUMBER TO SEE IF I WAS RIGHT. BY PURE LUCK,");
    printf("\n");
  L320: /* Line 320 */
    printf("%s", "I OUGHT TO BE RIGHT TEN TIMES. BUT I HOPE TO DO BETTER");
    printf("\n");
  L330: /* Line 330 */
    printf("%s", "THAN THAT *****");
    printf("\n");
  L340: /* Line 340 */
        printf("\n");
        printf("\n");
  L360: /* Line 360 */
    bpp_vars[0] = bpp_read_num();
    bpp_vars[1] = bpp_read_num();
    bpp_vars[2] = bpp_read_num();
  L370: /* Line 370 */
    /* DATA - see initialization */
  L380: /* Line 380 */
    bpp_dim_alloc("M", (int)(26), (int)(2));
    bpp_dim_alloc("K", (int)(2), (int)(2));
    bpp_dim_alloc("L", (int)(8), (int)(2));
  L400: /* Line 400 */
    bpp_vars[8] = 0;
  bpp_for_0:;
    bpp_vars[9] = 0;
  bpp_for_1:;
    *bpp_dim_ref("M", (int)(bpp_vars[8]), (int)(bpp_vars[9])) = 1;
    bpp_vars[9] += 1;
    if (bpp_vars[9] <= 2) goto bpp_for_1;
    bpp_vars[8] += 1;
    if (bpp_vars[8] <= 26) goto bpp_for_0;
  L410: /* Line 410 */
    bpp_vars[8] = 0;
  bpp_for_2:;
    bpp_vars[9] = 0;
  bpp_for_3:;
    *bpp_dim_ref("K", (int)(bpp_vars[8]), (int)(bpp_vars[9])) = 9;
    bpp_vars[9] += 1;
    if (bpp_vars[9] <= 2) goto bpp_for_3;
    bpp_vars[8] += 1;
    if (bpp_vars[8] <= 2) goto bpp_for_2;
  L420: /* Line 420 */
    bpp_vars[8] = 0;
  bpp_for_4:;
    bpp_vars[9] = 0;
  bpp_for_5:;
    *bpp_dim_ref("L", (int)(bpp_vars[8]), (int)(bpp_vars[9])) = 3;
    bpp_vars[9] += 1;
    if (bpp_vars[9] <= 2) goto bpp_for_5;
    bpp_vars[8] += 1;
    if (bpp_vars[8] <= 8) goto bpp_for_4;
  L450: /* Line 450 */
    *bpp_dim_ref("L", (int)(0), (int)(0)) = 2;
    *bpp_dim_ref("L", (int)(4), (int)(1)) = 2;
    *bpp_dim_ref("L", (int)(8), (int)(2)) = 2;
  L480: /* Line 480 */
    bpp_vars[25] = 26;
    bpp_vars[25] = 8;
    bpp_vars[25] = 2;
  L510: /* Line 510 */
    bpp_vars[23] = 0;
  L520: /* Line 520 */
    bpp_vars[19] = 1;
  bpp_for_6:;
  L530: /* Line 530 */
        printf("\n");
  L540: /* Line 540 */
    printf("%s", "TEN NUMBERS, PLEASE");
  L550: /* Line 550 */
    printf("? ");
    fflush(stdout);
    { char _buf[256]; double _v;
      fgets(_buf, 256, stdin); _v = atof(_buf);
      bpp_vars[13] = _v; }
  L560: /* Line 560 */
    bpp_vars[8] = 1;
  bpp_for_7:;
  L570: /* Line 570 */
    bpp_vars[22] = (*bpp_dim_ref("N", (int)(bpp_vars[8]), 0) - 1);
  L580: /* Line 580 */
    if ((bpp_vars[22] == ((bpp_vars[22])>0?1:((bpp_vars[22])<0?-1:0)))) { goto L620;
 }
  L590: /* Line 590 */
    printf("%s", "ONLY USE THE DIGITS '0', '1', OR '2'.");
    printf("\n");
  L600: /* Line 600 */
    printf("%s", "LET'S TRY AGAIN.");
    printf("\n");
    goto L530;
  L620: /* Line 620 */
    bpp_vars[8] += 1;
    if (bpp_vars[8] <= 10) goto bpp_for_7;
  L630: /* Line 630 */
        printf("\n");
    printf("%s", "MY GUESS");
    printf("%s", "YOUR NO.");
    printf("%s", "RESULT");
    printf("%s", "NO. RIGHT");
    printf("\n");
        printf("\n");
  L660: /* Line 660 */
    bpp_vars[20] = 1;
  bpp_for_8:;
  L670: /* Line 670 */
    bpp_vars[13] = *bpp_dim_ref("N", (int)(bpp_vars[20]), 0);
    bpp_vars[18] = 0;
  L690: /* Line 690 */
    bpp_vars[9] = 0;
  bpp_for_9:;
  L700: /* Line 700 */
    bpp_vars[18] = (((bpp_vars[0] * *bpp_dim_ref("K", (int)(bpp_vars[25]), (int)(bpp_vars[9]))) + (bpp_vars[1] * *bpp_dim_ref("L", (int)(bpp_vars[25]), (int)(bpp_vars[9])))) + (bpp_vars[2] * *bpp_dim_ref("M", (int)(bpp_vars[25]), (int)(bpp_vars[9]))));
  L710: /* Line 710 */
    if ((bpp_vars[18] > bpp_vars[18])) { goto L760;
 }
  L720: /* Line 720 */
    if ((bpp_vars[18] < bpp_vars[18])) { goto L740;
 }
  L730: /* Line 730 */
    if ((((double)(rand() % (int)(1))) < 0.5)) { goto L760;
 }
  L740: /* Line 740 */
    bpp_vars[18] = bpp_vars[18];
    bpp_vars[6] = bpp_vars[9];
  L760: /* Line 760 */
    bpp_vars[9] += 1;
    if (bpp_vars[9] <= 2) goto bpp_for_9;
  L770: /* Line 770 */
    printf("%s", "  ");
    { double _v = bpp_vars[6]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("%s", "   ");
    { double _v = *bpp_dim_ref("N", (int)(bpp_vars[20]), 0); if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
  L780: /* Line 780 */
    if ((bpp_vars[6] == *bpp_dim_ref("N", (int)(bpp_vars[20]), 0))) { goto L810;
 }
  L790: /* Line 790 */
    printf("%s", " WRONG");
    { double _v = bpp_vars[23]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("\n");
  L800: /* Line 800 */
    goto L880;
  L810: /* Line 810 */
    bpp_vars[23] = (bpp_vars[23] + 1);
  L820: /* Line 820 */
    printf("%s", " RIGHT");
    { double _v = bpp_vars[23]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("\n");
  L830: /* Line 830 */
    *bpp_dim_ref("M", (int)(bpp_vars[25]), (int)(bpp_vars[13])) = (*bpp_dim_ref("M", (int)(bpp_vars[25]), (int)(bpp_vars[13])) + 1);
  L840: /* Line 840 */
    *bpp_dim_ref("L", (int)(bpp_vars[25]), (int)(bpp_vars[13])) = (*bpp_dim_ref("L", (int)(bpp_vars[25]), (int)(bpp_vars[13])) + 1);
  L850: /* Line 850 */
    *bpp_dim_ref("K", (int)(bpp_vars[25]), (int)(bpp_vars[13])) = (*bpp_dim_ref("K", (int)(bpp_vars[25]), (int)(bpp_vars[13])) + 1);
  L860: /* Line 860 */
    bpp_vars[25] = (bpp_vars[25] - (floor((bpp_vars[25] / 9)) * 9));
  L870: /* Line 870 */
    bpp_vars[25] = ((3 * bpp_vars[25]) + *bpp_dim_ref("N", (int)(bpp_vars[20]), 0));
  L880: /* Line 880 */
    bpp_vars[25] = (bpp_vars[25] - (floor((bpp_vars[25] / 9)) * 9));
  L890: /* Line 890 */
    bpp_vars[25] = *bpp_dim_ref("N", (int)(bpp_vars[20]), 0);
  L900: /* Line 900 */
    bpp_vars[20] += 1;
    if (bpp_vars[20] <= 10) goto bpp_for_8;
  L910: /* Line 910 */
    bpp_vars[19] += 1;
    if (bpp_vars[19] <= 3) goto bpp_for_6;
  L920: /* Line 920 */
        printf("\n");
  L930: /* Line 930 */
    if ((bpp_vars[23] > 10)) { goto L980;
 }
  L940: /* Line 940 */
    if ((bpp_vars[23] < 10)) { goto L1010;
 }
  L950: /* Line 950 */
    printf("%s", "I GUESSED EXACTLY 1/3 OF YOUR NUMBERS.");
    printf("\n");
  L960: /* Line 960 */
    printf("%s", "IT'S A TIE GAME.");
    printf("\n");
  L970: /* Line 970 */
    goto L1030;
  L980: /* Line 980 */
    printf("%s", "I GUESSED MORE THAN 1/3 OF YOUR NUMBERS.");
    printf("\n");
  L990: /* Line 990 */
    printf("%s", "I WIN.");
    printf("\n");
    bpp_vars[16] = 1;
  bpp_for_10:;
    printf("%s", bpp_chr((int)(7)));
    bpp_vars[16] += 1;
    if (bpp_vars[16] <= 10) goto bpp_for_10;
  L1000: /* Line 1000 */
    goto L1030;
  L1010: /* Line 1010 */
    printf("%s", "I GUESSED LESS THAN 1/3 OF YOUR NUMBERS.");
    printf("\n");
  L1020: /* Line 1020 */
    printf("%s", "YOU BEAT ME.  CONGRATULATIONS *****");
    printf("\n");
  L1030: /* Line 1030 */
        printf("\n");
  L1040: /* Line 1040 */
    printf("%s", "DO YOU WANT TO TRY AGAIN (1 FOR YES, 0 FOR NO)");
  L1060: /* Line 1060 */
    printf("? ");
    fflush(stdout);
    { char _buf[256]; double _v;
      fgets(_buf, 256, stdin); _v = atof(_buf);
      bpp_vars[23] = _v; }
  L1070: /* Line 1070 */
    if ((bpp_vars[23] == 1)) { goto L400;
 }
  L1080: /* Line 1080 */
        printf("\n");
    printf("%s", "THANKS FOR THE GAME.");
    printf("\n");
  L1090: /* Line 1090 */
    goto bpp_end;
  bpp_end:
    return 0;
}
