/* Generated by BASIC++ Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* === Runtime Variables === */
static double bpp_vars[26];           /* A-Z */
static char bpp_strvars[26][256];     /* A$-Z$ */
static double bpp_at_array[4096];     /* @() legacy array */
static int bpp_print_width = 14;

/* === GOSUB Stack === */
#define BPP_MAX_STACK 256
static int bpp_gosub_stack[BPP_MAX_STACK];
static int bpp_gosub_sp = 0;

/* === DIM Arrays === */
#define BPP_MAX_DIM 64
#define BPP_MAX_ELEM 8192
static double bpp_dim_pool[BPP_MAX_ELEM];
static int bpp_dim_used = 0;
typedef struct { char name[32]; int d1,d2,off; } BppDim;
static BppDim bpp_dims[BPP_MAX_DIM];
static int bpp_dim_count = 0;

static void bpp_dim_alloc(const char *nm, int d1, int d2) {
    int sz = (d1+1) * (d2>0 ? d2+1 : 1);
    BppDim *d = &bpp_dims[bpp_dim_count++];
    strncpy(d->name, nm, 31); d->name[31]='\0';
    d->d1=d1; d->d2=d2; d->off=bpp_dim_used;
    memset(&bpp_dim_pool[bpp_dim_used], 0, sizeof(double)*(size_t)sz);
    bpp_dim_used += sz;
}

static double *bpp_dim_ref(const char *nm, int i1, int i2) {
    int k;
    for (k=0; k<bpp_dim_count; k++) {
        if (strcmp(bpp_dims[k].name, nm)==0) {
            int idx = (bpp_dims[k].d2>0)
                ? i1*(bpp_dims[k].d2+1)+i2 : i1;
            return &bpp_dim_pool[bpp_dims[k].off + idx];
        }
    }
    fprintf(stderr, "Array not found: %s\n", nm);
    exit(1);
    return NULL;
}

/* === String DIM arrays === */
#define BPP_MAX_STRDIM 26
#define BPP_MAX_STRDIM_SIZE 256
static struct { char nm[16]; int d1; int d2;
    char data[BPP_MAX_STRDIM_SIZE][256]; } bpp_strdims[BPP_MAX_STRDIM];
static int bpp_strdim_count = 0;

static char *bpp_strdim_ref(const char *nm, int i1, int i2) {
    int k;
    (void)i2;
    for (k = 0; k < bpp_strdim_count; k++) {
        if (strcmp(bpp_strdims[k].nm, nm) == 0) {
            if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
            return bpp_strdims[k].data[i1];
        }
    }
    /* Auto-create */
    if (bpp_strdim_count < BPP_MAX_STRDIM) {
        int j;
        strncpy(bpp_strdims[bpp_strdim_count].nm, nm, 15);
        bpp_strdims[bpp_strdim_count].nm[15] = '\0';
        for (j = 0; j < BPP_MAX_STRDIM_SIZE; j++)
            bpp_strdims[bpp_strdim_count].data[j][0] = '\0';
        bpp_strdim_count++;
        if (i1 < 0 || i1 >= BPP_MAX_STRDIM_SIZE) i1 = 0;
        return bpp_strdims[bpp_strdim_count-1].data[i1];
    }
    fprintf(stderr, "String array not found: %s\n", nm);
    exit(1);
    return NULL;
}

/* === DATA/READ support === */
#define BPP_MAX_DATA 4096
static double bpp_data_pool[BPP_MAX_DATA];
static int bpp_data_count = 0;
static int bpp_data_ptr = 0;

static double bpp_read_num(void) {
    if (bpp_data_ptr >= bpp_data_count) {
        fprintf(stderr, "OUT OF DATA\n"); exit(1);
    }
    return bpp_data_pool[bpp_data_ptr++];
}

/* === String helpers === */
static char bpp_strtmp[8][256];
static int bpp_strtmp_idx = 0;

static char *bpp_tmp(void) {
    char *p = bpp_strtmp[bpp_strtmp_idx];
    bpp_strtmp_idx = (bpp_strtmp_idx+1) & 7;
    return p;
}

static const char *bpp_concat(const char *a, const char *b) {
    char *t = bpp_tmp();
    t[0]='\0';
    strncat(t, a, 254);
    strncat(t, b, 254-(int)strlen(t));
    return t;
}

static const char *bpp_left(const char *s, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if (n>len) n=len; if(n<0) n=0;
    memcpy(t, s, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_right(const char *s, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if (n>len) n=len; if(n<0) n=0;
    memcpy(t, s+len-n, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_mid(const char *s, int st, int n) {
    char *t = bpp_tmp();
    int len = (int)strlen(s);
    if(st<0) st=0; if(st>len) st=len;
    if(n<0) n=0; if(st+n>len) n=len-st;
    memcpy(t, s+st, (size_t)n); t[n]='\0';
    return t;
}

static const char *bpp_chr(int n) {
    char *t = bpp_tmp();
    t[0]=(char)n; t[1]='\0';
    return t;
}

static const char *bpp_str(double n) {
    char *t = bpp_tmp();
    sprintf(t, "%g", n);
    return t;
}

/* === TAB helper === */
static const char *bpp_tab(int col) {
    static char buf[256];
    int i;
    if (col < 0) col = 0;
    if (col > 255) col = 255;
    for (i = 0; i < col; i++) buf[i] = ' ';
    buf[col] = '\0';
    return buf;
}

/* === DEF FN support === */
#define BPP_MAX_FN 26
typedef double (*BppFnPtr)(double);
static double bpp_fn_param;

int main(void) {

  L10: /* Line 10 */
    printf("%s", bpp_tab((int)(33)));
    printf("%s", "LUNAR");
    printf("\n");
  L20: /* Line 20 */
    printf("%s", bpp_tab((int)(15)));
    printf("%s", "CREATIVE COMPUTING MORRISTOWN, NEW JERSEY");
    printf("\n");
  L25: /* Line 25 */
        printf("\n");
        printf("\n");
        printf("\n");
  L30: /* Line 30 */
    printf("%s", "THIS IS A COMPUTER SIMULATION OF AN APOLLO LUNAR");
    printf("\n");
  L40: /* Line 40 */
    printf("%s", "LANDING CAPSULE.");
    printf("\n");
        printf("\n");
        printf("\n");
  L50: /* Line 50 */
    printf("%s", "THE ON-BOARD COMPUTER HAS FAILED (IT WAS MADE BY");
    printf("\n");
  L60: /* Line 60 */
    printf("%s", "XEROX) SO YOU HAVE TO LAND THE CAPSULE MANUALLY.");
    printf("\n");
  L70: /* Line 70 */
        printf("\n");
    printf("%s", "SET BURN RATE OF RETRO ROCKETS TO ANY VALUE BETWEEN");
    printf("\n");
  L80: /* Line 80 */
    printf("%s", "0 (FREE FALL) AND 200 (MAXIMUM BURN) POUNDS PER SECOND.");
    printf("\n");
  L90: /* Line 90 */
    printf("%s", "SET NEW BURN RATE EVERY 10 SECONDS.");
    printf("\n");
        printf("\n");
  L100: /* Line 100 */
    printf("%s", "CAPSULE WEIGHT 32,500 LBS; FUEL WEIGHT 16,000 LBS.");
    printf("\n");
  L110: /* Line 110 */
        printf("\n");
        printf("\n");
        printf("\n");
    printf("%s", "GOOD LUCK");
    printf("\n");
  L120: /* Line 120 */
    bpp_vars[11] = 0;
  L130: /* Line 130 */
        printf("\n");
    printf("%s", "SEC");
    printf("%s", "MI + FT");
    printf("%s", "MPH");
    printf("%s", "LB FUEL");
    printf("%s", "BURN RATE");
    printf("\n");
        printf("\n");
  L140: /* Line 140 */
    bpp_vars[0] = 120;
    bpp_vars[21] = 1;
    bpp_vars[12] = 33000;
    bpp_vars[13] = 16500;
    bpp_vars[6] = 0.001;
    bpp_vars[25] = 1.8;
  L150: /* Line 150 */
    { double _v = bpp_vars[11]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    { double _v = floor(bpp_vars[0]); if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    { double _v = floor((5280 * (bpp_vars[0] - floor(bpp_vars[0])))); if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    { double _v = (3600 * bpp_vars[21]); if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    { double _v = (bpp_vars[12] - bpp_vars[13]); if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("? ");
    fflush(stdout);
    { char _buf[256]; double _v;
      fgets(_buf, 256, stdin); _v = atof(_buf);
      bpp_vars[10] = _v; }
    bpp_vars[19] = 10;
  L160: /* Line 160 */
    if (((bpp_vars[12] - bpp_vars[13]) < 0.001)) { goto L240;
 }
  L170: /* Line 170 */
    if ((bpp_vars[19] < 0.001)) { goto L150;
 }
  L180: /* Line 180 */
    bpp_vars[18] = bpp_vars[19];
    if ((bpp_vars[12] >= (bpp_vars[13] + (bpp_vars[18] * bpp_vars[10])))) { goto L200;
 }
  L190: /* Line 190 */
    bpp_vars[18] = ((bpp_vars[12] - bpp_vars[13]) / bpp_vars[10]);
  L200: /* Line 200 */
    bpp_gosub_stack[bpp_gosub_sp++] = 0; goto L420;
  bpp_ret_0:;
    if ((bpp_vars[8] <= 0)) { goto L340;
 }
  L210: /* Line 210 */
    if ((bpp_vars[21] <= 0)) { goto L230;
 }
  L220: /* Line 220 */
    if ((bpp_vars[9] < 0)) { goto L370;
 }
  L230: /* Line 230 */
    bpp_gosub_stack[bpp_gosub_sp++] = 1; goto L330;
  bpp_ret_1:;
    goto L160;
  L240: /* Line 240 */
    printf("%s", "FUEL OUT AT");
    { double _v = bpp_vars[11]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("%s", "SECONDS");
    printf("\n");
    bpp_vars[18] = (((-(bpp_vars[21])) + sqrt(((bpp_vars[21] * bpp_vars[21]) + ((2 * bpp_vars[0]) * bpp_vars[6])))) / bpp_vars[6]);
  L250: /* Line 250 */
    bpp_vars[21] = (bpp_vars[21] + (bpp_vars[6] * bpp_vars[18]));
    bpp_vars[11] = (bpp_vars[11] + bpp_vars[18]);
  L260: /* Line 260 */
    bpp_vars[22] = (3600 * bpp_vars[21]);
    printf("%s", "ON MOON AT");
    { double _v = bpp_vars[11]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("%s", "SECONDS - IMPACT VELOCITY");
    { double _v = bpp_vars[22]; if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("%s", "MPH");
    printf("\n");
  L274: /* Line 274 */
    if ((bpp_vars[22] <= 1.2)) { printf("%s", "PERFECT LANDING!");
printf("\n");
 }
    goto L440;
  L280: /* Line 280 */
    if ((bpp_vars[22] <= 10)) { printf("%s", "GOOD LANDING (COULD BE BETTER)");
printf("\n");
 }
    goto L440;
  L282: /* Line 282 */
    if ((bpp_vars[22] > 60)) { goto L300;
 }
  L284: /* Line 284 */
    printf("%s", "CRAFT DAMAGE... YOU'RE STRANDED HERE UNTIL A RESCUE");
    printf("\n");
  L286: /* Line 286 */
    printf("%s", "PARTY ARRIVES. HOPE YOU HAVE ENOUGH OXYGEN!");
    printf("\n");
  L288: /* Line 288 */
    goto L440;
  L300: /* Line 300 */
    printf("%s", "SORRY THERE WERE NO SURVIVORS. YOU BLEW IT!");
    printf("\n");
  L310: /* Line 310 */
    printf("%s", "IN FACT, YOU BLASTED A NEW LUNAR CRATER");
    { double _v = (bpp_vars[22] * 0.22700000000000001); if (_v == (double)(long)_v) printf("%*ld", bpp_print_width, (long)_v); else printf("%g", _v); }
    printf("%s", "FEET DEEP!");
    printf("\n");
  L320: /* Line 320 */
    goto L440;
  L330: /* Line 330 */
    bpp_vars[11] = (bpp_vars[11] + bpp_vars[18]);
    bpp_vars[19] = (bpp_vars[19] - bpp_vars[18]);
    bpp_vars[12] = (bpp_vars[12] - (bpp_vars[18] * bpp_vars[10]));
    bpp_vars[0] = bpp_vars[8];
    bpp_vars[21] = bpp_vars[9];
    { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
      switch(_ra) {
        case 0: goto bpp_ret_0;
        case 1: goto bpp_ret_1;
        case 2: goto bpp_ret_2;
        case 3: goto bpp_ret_3;
        case 4: goto bpp_ret_4;
        case 5: goto bpp_ret_5;
        default: goto bpp_end;
      } }
  L340: /* Line 340 */
    if ((bpp_vars[18] < 0.0050000000000000001)) { goto L260;
 }
  L350: /* Line 350 */
    bpp_vars[3] = (bpp_vars[21] + sqrt(((bpp_vars[21] * bpp_vars[21]) + ((2 * bpp_vars[0]) * (bpp_vars[6] - ((bpp_vars[25] * bpp_vars[10]) / bpp_vars[12]))))));
    bpp_vars[18] = ((2 * bpp_vars[0]) / bpp_vars[3]);
  L360: /* Line 360 */
    bpp_gosub_stack[bpp_gosub_sp++] = 2; goto L420;
  bpp_ret_2:;
    bpp_gosub_stack[bpp_gosub_sp++] = 3; goto L330;
  bpp_ret_3:;
    goto L340;
  L370: /* Line 370 */
    bpp_vars[22] = ((1 - ((bpp_vars[12] * bpp_vars[6]) / (bpp_vars[25] * bpp_vars[10]))) / 2);
    bpp_vars[18] = (((bpp_vars[12] * bpp_vars[21]) / ((bpp_vars[25] * bpp_vars[10]) * (bpp_vars[22] + sqrt(((bpp_vars[22] * bpp_vars[22]) + (bpp_vars[21] / bpp_vars[25])))))) + 0.050000000000000003);
    bpp_gosub_stack[bpp_gosub_sp++] = 4; goto L420;
  bpp_ret_4:;
  L380: /* Line 380 */
    if ((bpp_vars[8] <= 0)) { goto L340;
 }
  L390: /* Line 390 */
    bpp_gosub_stack[bpp_gosub_sp++] = 5; goto L330;
  bpp_ret_5:;
    if ((bpp_vars[9] > 0)) { goto L160;
 }
  L400: /* Line 400 */
    if ((bpp_vars[21] > 0)) { goto L370;
 }
  L410: /* Line 410 */
    goto L160;
  L420: /* Line 420 */
    bpp_vars[16] = ((bpp_vars[18] * bpp_vars[10]) / bpp_vars[12]);
    bpp_vars[9] = ((bpp_vars[21] + (bpp_vars[6] * bpp_vars[18])) + (bpp_vars[25] * (((((-(bpp_vars[16])) - ((bpp_vars[16] * bpp_vars[16]) / 2)) - ((pow(bpp_vars[16], 3)) / 3)) - ((pow(bpp_vars[16], 4)) / 4)) - ((pow(bpp_vars[16], 5)) / 5))));
  L430: /* Line 430 */
    bpp_vars[8] = (((bpp_vars[0] - (((bpp_vars[6] * bpp_vars[18]) * bpp_vars[18]) / 2)) - (bpp_vars[21] * bpp_vars[18])) + ((bpp_vars[25] * bpp_vars[18]) * (((((bpp_vars[16] / 2) + ((pow(bpp_vars[16], 2)) / 6)) + ((pow(bpp_vars[16], 3)) / 12)) + ((pow(bpp_vars[16], 4)) / 20)) + ((pow(bpp_vars[16], 5)) / 30))));
    { int _ra = bpp_gosub_stack[--bpp_gosub_sp];
      switch(_ra) {
        case 0: goto bpp_ret_0;
        case 1: goto bpp_ret_1;
        case 2: goto bpp_ret_2;
        case 3: goto bpp_ret_3;
        case 4: goto bpp_ret_4;
        case 5: goto bpp_ret_5;
        default: goto bpp_end;
      } }
  L440: /* Line 440 */
        printf("\n");
        printf("\n");
        printf("\n");
    printf("%s", "TRY AGAIN??");
    printf("\n");
    goto L70;
  bpp_end:
    return 0;
}
