// FILENAME: common_reg_stmts.c
// LICENSE: Copyleft (c) 2026 BASIC++ Community — All Wrongs Reserved
// VERSION: 6.5.2.0
// NEEDED BY: 
// NEEDS: libboot (common_internal.h)
// Provides core logic and interface definitions for common_reg_stmts within BASIC++.
//
// ---- Includes ----

#include "bootstrap/common_internal.h"

// Statement Registration Externs
void stmt_incr_register(void);
void stmt_clr_register(void);
void stmt_void_register(void);
void stmt_arrayfill_register(void);
void stmt_share_register(void);
void stmt_public_register(void);
void stmt_global_register(void);
void stmt_var_mux_register(void);
void stmt_mid_stmt_register(void);
void stmt_array_ext_register(void);
void stmt_renum_register(void);
void stmt_merge_register(void);
void stmt_delete_register(void);
void stmt_auto_register(void);
void stmt_def_register(void);
void stmt_mat_ops_register(void);
void stmt_ask_register(void);
void stmt_window_register(void);
void stmt_view_register(void);
void stmt_pset_register(void);
void stmt_preset_register(void);
void stmt_palette_register(void);
void stmt_paint_register(void);
void stmt_draw_register(void);
void stmt_gfx_compat_register(void);
void stmt_bgi_register(void);
void stmt_lock_register(void);
void stmt_bload_register(void);
void stmt_on_com_register(void);
void stmt_randomize_register(void);
void stmt_when_register(void);
void stmt_retry_register(void);
void stmt_handler_register(void);
void stmt_external_register(void);
void stmt_declare_register(void);
void stmt_const_register(void);
void stmt_continue_register(void);
void stmt_cause_register(void);
void stmt_viewport_register(void);
void stmt_picture_register(void);
void stmt_enter_register(void);
void stmt_complex_register(void);
void stmt_class_register(void);
void stmt_record_register(void);
void stmt_find_register(void);
void stmt_map_register(void);
void stmt_session_register(void);
void stmt_category_register(void);
void stmt_goto_register(void);
void stmt_gosub_register(void);
void stmt_return_register(void);
void stmt_if_register(void);
void stmt_end_register(void);
void stmt_rem_register(void);
void stmt_stop_register(void);
void stmt_print_register(void);
void stmt_input_register(void);
void stmt_select_register(void);
void stmt_for_register(void);
void stmt_next_register(void);
void stmt_while_register(void);
void stmt_wend_register(void);
void stmt_do_register(void);
void stmt_loop_register(void);
void stmt_exit_loop_register(void);
void stmt_open_register(void);
void stmt_close_register(void);
void stmt_get_register(void);
void stmt_put_register(void);
void stmt_field_register(void);
void stmt_files_register(void);
void stmt_kill_register(void);
void stmt_mkdir_register(void);
void stmt_name_register(void);
void stmt_seek_register(void);
void stmt_screen_register(void);
void stmt_cls_register(void);
void stmt_home_register(void);
void stmt_color_register(void);
void stmt_line_register(void);
void stmt_circle_register(void);
void stmt_sound_register(void);
void stmt_play_register(void);
void stmt_beep_register(void);
void stmt_voice_register(void);
void stmt_key_register(void);
void stmt_on_key_register(void);
void stmt_on_timer_register(void);
void stmt_on_error_register(void);
void stmt_resume_register(void);
void stmt_try_register(void);
void stmt_mat_input_register(void);
void stmt_mat_print_register(void);
void stmt_mat_read_register(void);
void stmt_mat_write_register(void);
void stmt_whenever_register(void);
void stmt_scope_register(void);
void stmt_help_register(void);
void stmt_reformat_register(void);
void stmt_check_register(void);
void stmt_verify_register(void);
void stmt_test_register(void);
void stmt_debug_register(void);
void stmt_version_register(void);
void stmt_introspection_register(void);
void stmt_selftest_register(void);
void stmt_isam_register(void);
void stmt_vbdos_widgets_register(void);
void stmt_dim_register(void);
void stmt_redim_register(void);
void stmt_erase_register(void);
void stmt_let_register(void);
void stmt_swap_register(void);
void stmt_read_register(void);
void stmt_restore_register(void);
void stmt_data_register(void);
void stmt_defint_register(void);
void stmt_defsng_register(void);
void stmt_defdbl_register(void);
void stmt_defstr_register(void);
void stmt_deflng_register(void);
void stmt_common_register(void);
void stmt_lset_register(void);
void stmt_rset_register(void);
void stmt_def_seg_register(void);
void stmt_def_usr_register(void);
void stmt_shell_register(void);
void stmt_pause_register(void);
void stmt_sys_register(void);
void stmt_bsave_register(void);
void stmt_brun_register(void);
void stmt_bload_register(void);
void stmt_chdir_register(void);
void stmt_rmdir_register(void);
void stmt_lprint_register(void);
void stmt_line_input_register(void);
void stmt_plot_register(void);
void stmt_wifi_register(void);
void stmt_mqtt_register(void);
void stmt_webrepl_register(void);
void stmt_peer_register(void);
void stmt_bt_register(void);
void stmt_ble_register(void);
void stmt_nfc_register(void);
void stmt_gemini_register(void);
void stmt_gopher_register(void);
void stmt_tnfs_register(void);
void stmt_remote_register(void);
void stmt_nil_unpack_register(void);
void stmt_sock_register(void);
void stmt_port_trigger_register(void);
void stmt_sniff_register(void);
void stmt_net_config_register(void);

//
// ---- Registration Dispatcher ----

void boot_register_all_statements(void) {
    stmt_incr_register();
    stmt_clr_register();
    stmt_void_register();
    stmt_arrayfill_register();
    stmt_share_register();
    stmt_public_register();
    stmt_global_register();
    stmt_var_mux_register();
    stmt_mid_stmt_register();
    stmt_array_ext_register();
    stmt_renum_register();
    stmt_merge_register();
    stmt_delete_register();
    stmt_auto_register();
    stmt_def_register();
    stmt_mat_ops_register();
    stmt_ask_register();
    stmt_window_register();
    stmt_view_register();
    stmt_pset_register();
    stmt_preset_register();
    stmt_palette_register();
    stmt_paint_register();
    stmt_draw_register();
    stmt_gfx_compat_register();
    stmt_bgi_register();
    stmt_lock_register();
    stmt_bload_register();
    stmt_on_com_register();
    stmt_randomize_register();
    stmt_when_register();
    stmt_retry_register();
    stmt_handler_register();
    stmt_external_register();
    stmt_declare_register();
    stmt_const_register();
    stmt_continue_register();
    stmt_cause_register();
    stmt_viewport_register();
    stmt_picture_register();
    stmt_plot_register();
    stmt_enter_register();
    stmt_complex_register();
    stmt_class_register();
    stmt_record_register();
    stmt_find_register();
    stmt_map_register();
    stmt_session_register();
    stmt_category_register();
    stmt_goto_register();
    stmt_gosub_register();
    stmt_return_register();
    stmt_if_register();
    stmt_end_register();
    stmt_rem_register();
    stmt_stop_register();
    stmt_print_register();
    stmt_input_register();
    stmt_select_register();
    stmt_for_register();
    stmt_next_register();
    stmt_while_register();
    stmt_wend_register();
    stmt_do_register();
    stmt_loop_register();
    stmt_exit_loop_register();
    stmt_open_register();
    stmt_close_register();
    stmt_get_register();
    stmt_put_register();
    stmt_field_register();
    stmt_files_register();
    stmt_kill_register();
    stmt_mkdir_register();
    stmt_name_register();
    stmt_seek_register();
    stmt_screen_register();
    stmt_cls_register();
    stmt_home_register();
    stmt_color_register();
    stmt_line_register();
    stmt_circle_register();
    stmt_sound_register();
    stmt_play_register();
    stmt_beep_register();
    stmt_voice_register();
    stmt_key_register();
    stmt_on_key_register();
    stmt_on_timer_register();
    stmt_on_error_register();
    stmt_resume_register();
    stmt_try_register();
    stmt_mat_input_register();
    stmt_mat_print_register();
    stmt_mat_read_register();
    stmt_mat_write_register();
    stmt_whenever_register();
    stmt_scope_register();
    stmt_help_register();
    stmt_reformat_register();
    stmt_check_register();
    stmt_verify_register();
    stmt_test_register();
    stmt_debug_register();
    stmt_version_register();
    stmt_introspection_register();
    stmt_selftest_register();
    stmt_isam_register();
    stmt_vbdos_widgets_register();
    stmt_dim_register();
    stmt_redim_register();
    stmt_erase_register();
    stmt_let_register();
    stmt_swap_register();
    stmt_read_register();
    stmt_restore_register();
    stmt_data_register();
    stmt_defint_register();
    stmt_defsng_register();
    stmt_defdbl_register();
    stmt_defstr_register();
    stmt_deflng_register();
    stmt_common_register();
    stmt_lset_register();
    stmt_rset_register();
    stmt_def_seg_register();
    stmt_def_usr_register();
    stmt_shell_register();
    stmt_pause_register();
    stmt_sys_register();
    stmt_bsave_register();
    stmt_brun_register();
    stmt_chdir_register();
    stmt_rmdir_register();
    stmt_lprint_register();
    stmt_line_input_register();
    stmt_wifi_register();
    stmt_mqtt_register();
    stmt_webrepl_register();
    stmt_peer_register();
    stmt_bt_register();
    stmt_ble_register();
    stmt_nfc_register();
    stmt_gemini_register();
    stmt_gopher_register();
    stmt_tnfs_register();
    stmt_remote_register();
    stmt_nil_unpack_register();
    stmt_sock_register();
    stmt_port_trigger_register();
    stmt_sniff_register();
    stmt_net_config_register();
}
