// FILENAME: common_reg_funcs.c
// LICENSE: Copyleft (c) 2026 BASIC++ Community — All Wrongs Reserved
// VERSION: 6.5.2.0
// NEEDED BY: 
// NEEDS: libboot (common_internal.h)
// Provides core logic and interface definitions for common_reg_funcs within BASIC++.
//
// ---- Includes ----

#include "bootstrap/common_internal.h"

// Function Registration Externs
void func_dot_register(void);
void func_det_register(void);
void func_cross_register(void);
void func_rnd_register(void);
void func_int_register(void);
void func_abs_register(void);
void func_sqr_register(void);
void func_sin_register(void);
void func_cos_register(void);
void func_tan_register(void);
void func_atn_register(void);
void func_log_register(void);
void func_exp_register(void);
void func_acos_register(void);
void func_asin_register(void);
void func_atan2_register(void);
void func_ceil_register(void);
void func_clamp_register(void);
void func_fix_register(void);
void func_floor_register(void);
void func_lerp_register(void);
void func_pi_register(void);
void func_round_register(void);
void func_sgn_register(void);
void func_eps_register(void);
void func_inf_register(void);
void func_maxnum_register(void);
void func_degrees_register(void);
void func_radians_register(void);
void func_remainder_register(void);
void func_angle_register(void);
void func_truncate_register(void);
void func_bin_register(void);
void func_chr_register(void);
void func_hex_register(void);
void func_instr_register(void);
void func_lcase_register(void);
void func_left_register(void);
void func_len_register(void);
void func_ltrim_register(void);
void func_mid_register(void);
void func_oct_register(void);
void func_pack_register(void);
void func_right_register(void);
void func_rtrim_register(void);
void func_space_register(void);
void func_shuffle_register(void);
void func_str_register(void);
void func_string_register(void);
void func_trim_register(void);
void func_ucase_register(void);
void func_unpack_register(void);
void func_val_register(void);
void func_bitcount_register(void);
void func_readbit_register(void);
void func_resetbit_register(void);
void func_setbit_register(void);
void func_shl_register(void);
void func_shr_register(void);
void func_togglebit_register(void);
void func_and_register(void);
void func_or_register(void);
void func_xor_register(void);
void func_imp_register(void);
void func_eqv_register(void);
void func_not_register(void);
void func_min_register(void);
void func_max_register(void);
void func_hypot_register(void);
void func_mod_register(void);
void func_clock_num_register(void);
void func_clock_str_register(void);
void func_date_register(void);
void func_environ_register(void);
void func_fre_register(void);
void func_inkey_register(void);
void func_inp_register(void);
void func_peek_register(void);
void func_ticks_register(void);
void func_time_register(void);
void func_timer_register(void);
void func_seg_register(void);
void func_ert_register(void);
void func_ascii_fn_register(void);
void func_ups_register(void);
void func_index_fn_register(void);
void func_str_math_register(void);
void func_spec_fn_register(void);
void func_magtape_register(void);
void func_complex_register(void);
void func_verify_register(void);
void func_category_register(void);
void func_varptr_register(void);
void func_mbf_register(void);
void func_financial_register(void);
void func_vbdos_filebox_register(void);
void func_tab_register(void);
void func_spc_register(void);
void func_pos_register(void);
void func_csrlin_register(void);
void func_lpos_register(void);
void func_erl_register(void);
void func_err_fn_register(void);
void func_eof_fn_register(void);
void func_lof_register(void);
void func_loc_fn_register(void);
void func_freefile_register(void);
void func_point_fn_register(void);
void func_lbound_register(void);
void func_ubound_register(void);
void func_dread_register(void);
void func_aread_register(void);
void func_touch_register(void);
void func_hall_register(void);
void func_ticks_iot_register(void);
void func_mem_register(void);
void func_http_register(void);
void func_gemini_register(void);
void func_gopher_register(void);
void func_python_register(void);

void register_crypto_functions(void);
void register_string_ext_functions(void);
#ifndef BASIC_LITE_BUILD
void register_arrayext_functions(void);
#endif
void register_array_sort_functions(void);
void register_regex_functions(void);

//
// ---- Function Registration Dispatcher ----

void boot_register_all_functions(void) {
    func_dot_register();
    func_det_register();
    func_cross_register();
    func_rnd_register();
    func_int_register();
    func_abs_register();
    func_sqr_register();
    func_sin_register();
    func_cos_register();
    func_tan_register();
    func_atn_register();
    func_log_register();
    func_exp_register();
    func_acos_register();
    func_asin_register();
    func_atan2_register();
    func_ceil_register();
    func_clamp_register();
    func_fix_register();
    func_floor_register();
    func_lerp_register();
    func_pi_register();
    func_round_register();
    func_sgn_register();
    func_eps_register();
    func_inf_register();
    func_maxnum_register();
    func_degrees_register();
    func_radians_register();
    func_remainder_register();
    func_angle_register();
    func_truncate_register();
    func_bin_register();
    func_chr_register();
    func_hex_register();
    func_instr_register();
    func_lcase_register();
    func_left_register();
    func_len_register();
    func_ltrim_register();
    func_mid_register();
    func_oct_register();
    func_pack_register();
    func_right_register();
    func_rtrim_register();
    func_space_register();
    func_shuffle_register();
    func_str_register();
    func_string_register();
    func_trim_register();
    func_ucase_register();
    func_unpack_register();
    func_val_register();
    func_bitcount_register();
    func_readbit_register();
    func_resetbit_register();
    func_setbit_register();
    func_shl_register();
    func_shr_register();
    func_togglebit_register();
    func_and_register();
    func_or_register();
    func_xor_register();
    func_imp_register();
    func_eqv_register();
    func_not_register();
    func_min_register();
    func_max_register();
    func_hypot_register();
    func_mod_register();
    func_clock_num_register();
    func_clock_str_register();
    func_date_register();
    func_environ_register();
    func_fre_register();
    func_inkey_register();
    func_inp_register();
    func_peek_register();
    func_ticks_register();
    func_time_register();
    func_timer_register();
    func_seg_register();
    func_ert_register();
    func_ascii_fn_register();
    func_ups_register();
    func_index_fn_register();
    func_str_math_register();
    func_spec_fn_register();
    func_magtape_register();
    func_complex_register();
    func_verify_register();
    func_category_register();
    func_varptr_register();
    func_mbf_register();
    func_financial_register();
    func_vbdos_filebox_register();
    func_tab_register();
    func_spc_register();
    func_pos_register();
    func_csrlin_register();
    func_lpos_register();
    func_erl_register();
    func_err_fn_register();
    func_eof_fn_register();
    func_lof_register();
    func_loc_fn_register();
    func_freefile_register();
    func_point_fn_register();
    func_lbound_register();
    func_ubound_register();
    func_dread_register();
    func_aread_register();
    func_touch_register();
    func_hall_register();
    func_ticks_iot_register();
    func_mem_register();
    func_http_register();
    func_gemini_register();
    func_gopher_register();
    func_python_register();

    register_crypto_functions();
    register_string_ext_functions();
#ifndef BASIC_LITE_BUILD
    register_arrayext_functions();
#endif
    register_regex_functions();
    register_array_sort_functions();
}
