// FILENAME: common_reg_funcs.c
// LICENSE: Copyleft (c) 2026 BASIC++ Community — All Wrongs Reserved
// VERSION: 6.5.2.0
// NEEDED BY: libboot
// NEEDS: libboot (common_internal.h)
// Provides core logic and function registration dispatcher for BASIC++.

#include "bootstrap/common_internal.h"

// Function Registration Externs
void func_dot_register(void);
void func_det_register(void);
void func_cross_register(void);
void func_rnd_register(void);
void func_int_register(void);
void func_abs_register(void);
void func_sqr_register(void);
void func_sin_register(void);
void func_cos_register(void);
void func_tan_register(void);
void func_atn_register(void);
void func_log_register(void);
void func_exp_register(void);
void func_acos_register(void);
void func_asin_register(void);
void func_atan2_register(void);
void func_ceil_register(void);
void func_clamp_register(void);
void func_fix_register(void);
void func_floor_register(void);
void func_lerp_register(void);
void func_pi_register(void);
void func_round_register(void);
void func_sgn_register(void);
void func_eps_register(void);
void func_inf_register(void);
void func_maxnum_register(void);
void func_degrees_register(void);
void func_radians_register(void);
void func_grad_register(void);
void func_pol_rec_register(void);
void func_translate_register(void);
void func_record_lock_register(void);
void func_isam_fn_register(void);
void func_systems_types_register(void);
void func_remainder_register(void);
void func_angle_register(void);
void func_truncate_register(void);
void func_bin_register(void);
void func_chr_register(void);
void func_hex_register(void);
void func_instr_register(void);
void func_rinstr_register(void);
void func_lcase_register(void);
void func_left_register(void);
void func_len_register(void);
void func_week_register(void);
void func_neg_register(void);
void system_var_descriptors_register(void);
void func_ltrim_register(void);
void func_mid_register(void);
void func_oct_register(void);
void func_pack_register(void);
void func_right_register(void);
void func_rtrim_register(void);
void func_space_register(void);
void func_udx_register(void);
void func_pn_register(void);
void func_rpn_register(void);
void func_cpu86_register(void);
void func_bios_register(void);
void func_shuffle_register(void);
void func_str_register(void);
void func_string_register(void);
void func_trim_register(void);
void func_delete_str_register(void);
void func_remove_register(void);
void func_insert_register(void);
void func_overlay_register(void);
void func_replace_register(void);
void func_format_register(void);
void func_shell_register(void);
void func_exec_register(void);
void func_ucase_register(void);
void func_unpack_register(void);
void func_val_register(void);
void func_bitcount_register(void);
void func_readbit_register(void);
void func_resetbit_register(void);
void func_setbit_register(void);
void func_shl_register(void);
void func_shr_register(void);
void func_togglebit_register(void);
void func_and_register(void);
void func_or_register(void);
void func_xor_register(void);
void func_imp_register(void);
void func_eqv_register(void);
void func_not_register(void);
void func_min_register(void);
void func_max_register(void);
void func_avg_register(void);
void func_math_sum_register(void);
void func_rol_register(void);
void func_ror_register(void);
void func_bitfield_register(void);
void func_hypot_register(void);
void func_mod_register(void);
void func_clk_register(void);
void func_clock_num_register(void);
void func_clock_str_register(void);
void func_date_register(void);
void func_environ_register(void);
void func_fre_register(void);
void func_inkey_register(void);
void func_inp_register(void);
void func_peek_register(void);
void func_ticks_register(void);
void func_jiffies_register(void);
void func_ti_register(void);
void func_time_register(void);
void func_timer_register(void);
void func_seg_register(void);
void func_ert_register(void);
void func_ascii_fn_register(void);
void func_ups_register(void);
void func_index_fn_register(void);
void func_sum_register(void);
void func_dif_register(void);
void func_prod_register(void);
void func_quo_register(void);
void func_place_register(void);
void func_spec_fn_register(void);
void func_magtape_register(void);
void func_complex_register(void);
void func_verify_register(void);
void func_category_register(void);
void func_varptr_register(void);
void func_cvsmbf_register(void);
void func_cvdmbf_register(void);
void func_mksmbf_register(void);
void func_mkdmbf_register(void);
void func_pv_register(void);
void func_fv_register(void);
void func_pmt_register(void);
void func_ipmt_register(void);
void func_ppmt_register(void);
void func_nper_register(void);
void func_rate_register(void);
void func_npv_register(void);
void func_irr_register(void);
void func_dp_register(void);
void func_xp_register(void);
void func_fpt_register(void);
void func_ipt_register(void);
void func_hta_register(void);
void func_ath_register(void);
void func_fileopenbox_register(void);
void func_filesavebox_register(void);
void func_msgbox_register(void);
void func_inputbox_register(void);
void func_input_str_register(void);
void func_screen_fn_register(void);
void func_doevents_register(void);
void func_tab_register(void);
void func_spc_register(void);
void func_pos_register(void);
void func_csrlin_register(void);
void func_lpos_register(void);
void func_erl_register(void);
void func_err_fn_register(void);
void func_eof_fn_register(void);
void func_lof_register(void);
void func_loc_fn_register(void);
void func_freefile_register(void);
void func_point_fn_register(void);
void func_baud_register(void);
void func_cpuspeed_register(void);
void func_clocks_register(void);
void func_stick_register(void);
void func_strig_register(void);
void func_paddle_register(void);
void func_ptrig_register(void);
void func_attr_register(void);
void func_lbound_register(void);
void func_ubound_register(void);
void func_dread_register(void);
void func_aread_register(void);
void func_touch_register(void);
void func_hall_register(void);
void func_ticks_iot_register(void);
void func_mem_register(void);
void func_http_register(void);
void func_gemini_register(void);
void func_gopher_register(void);
void func_python_register(void);
void func_receive_register(void);
void func_dateserial_register(void);
void func_timeserial_register(void);
void func_datevalue_register(void);
void func_timevalue_register(void);
void func_day_register(void);
void func_month_register(void);
void func_year_register(void);
void func_weekday_register(void);
void func_hour_register(void);
void func_minute_register(void);
void func_second_register(void);
void func_unixtime_register(void);
void func_epochdate_register(void);
void func_utc_register(void);
void func_dir_fn_register(void);
void func_curdir_register(void);
void func_isnumeric_register(void);
void func_isarray_register(void);
void func_setmem_register(void);
void func_sseg_register(void);
void func_hebrew_register(void);
void func_exepath_register(void);
void func_scriptpath_register(void);
void func_workdir_register(void);
void func_program_register(void);
void func_tempdir_register(void);
void func_userpath_register(void);
void func_ver_register(void);
void func_vintage_vars_register(void);
void func_net_telemetry_register(void);
void func_upnp_register(void);
void func_nil_compress_register(void);
void func_devctl_register(void);
void func_fujinet_register(void);
void func_gemini_meta_register(void);
void func_nil_bead_register(void);
void func_packet_register(void);
void func_remote_register(void);
void func_sock_register(void);
void func_tnfs_register(void);
void func_crypto_register(void);
void func_arg_register(void);
void func_command_register(void);
void func_comp_register(void);
void func_cosh_register(void);
void func_cot_register(void);
void func_csc_register(void);
void func_cvt_register(void);
void func_devinfo_register(void);
void func_fid_register(void);
void func_ip_register(void);
void func_log10_register(void);
void func_log2_register(void);
void func_mag_register(void);
void func_moddir_register(void);
void func_num_register(void);
void func_pdif_register(void);
void func_pick_register(void);
void func_rad_register(void);
void func_sec_register(void);
void func_sinh_register(void);
void func_sys_register(void);
void func_tanh_register(void);
void func_tek_register(void);
void func_tim_register(void);
void func_time_fn_register(void);
void func_time_part_register(void);
void func_typ_register(void);
void func_xlate_register(void);

void register_crypto_functions(void);
void register_string_ext_functions(void);
#ifndef BASIC_LITE_BUILD
void register_arrayext_functions(void);
#endif
void register_array_sort_functions(void);
void register_regex_functions(void);

//
// ---- Function Registration Dispatcher ----
//

void boot_register_all_functions(void) {
    func_dot_register();
    func_det_register();
    func_cross_register();
    func_rnd_register();
    func_int_register();
    func_abs_register();
    func_sqr_register();
    func_sin_register();
    func_cos_register();
    func_tan_register();
    func_atn_register();
    func_log_register();
    func_exp_register();
    func_acos_register();
    func_asin_register();
    func_atan2_register();
    func_ceil_register();
    func_clamp_register();
    func_fix_register();
    func_floor_register();
    func_lerp_register();
    func_pi_register();
    func_round_register();
    func_sgn_register();
    func_eps_register();
    func_inf_register();
    func_maxnum_register();
    func_degrees_register();
    func_radians_register();
    func_grad_register();
    func_pol_rec_register();
    func_translate_register();
    func_remainder_register();
    func_angle_register();
    func_truncate_register();
    func_bin_register();
    func_chr_register();
    func_hex_register();
    func_instr_register();
    func_rinstr_register();
    func_lcase_register();
    func_left_register();
    func_len_register();
    func_ltrim_register();
    func_mid_register();
    func_oct_register();
    func_pack_register();
    func_right_register();
    func_rtrim_register();
    func_space_register();
    func_shuffle_register();
    func_str_register();
    func_string_register();
    func_trim_register();
    func_delete_str_register();
    func_remove_register();
    func_insert_register();
    func_overlay_register();
    func_replace_register();
    func_format_register();
    func_shell_register();
    func_exec_register();
    func_ucase_register();
    func_unpack_register();
    func_val_register();
    func_bitcount_register();
    func_readbit_register();
    func_resetbit_register();
    func_setbit_register();
    func_shl_register();
    func_shr_register();
    func_togglebit_register();
    func_and_register();
    func_or_register();
    func_xor_register();
    func_imp_register();
    func_eqv_register();
    func_not_register();
    func_min_register();
    func_max_register();
    func_avg_register();
    func_math_sum_register();
    func_rol_register();
    func_ror_register();
    func_bitfield_register();
    func_hypot_register();
    func_mod_register();
    func_clk_register();
    func_clock_num_register();
    func_clock_str_register();
    func_date_register();
    func_environ_register();
    func_fre_register();
    func_inkey_register();
    func_inp_register();
    func_peek_register();
    func_ticks_register();
    func_jiffies_register();
    func_ti_register();
    func_time_register();
    func_timer_register();
    func_seg_register();
    func_ert_register();
    func_ascii_fn_register();
    func_ups_register();
    func_index_fn_register();
    func_sum_register();
    func_dif_register();
    func_prod_register();
    func_quo_register();
    func_place_register();
    func_spec_fn_register();
    func_magtape_register();
    func_complex_register();
    func_verify_register();
    func_category_register();
    func_varptr_register();
    func_cvsmbf_register();
    func_cvdmbf_register();
    func_mksmbf_register();
    func_mkdmbf_register();
    func_pv_register();
    func_fv_register();
    func_pmt_register();
    func_ipmt_register();
    func_ppmt_register();
    func_nper_register();
    func_rate_register();
    func_npv_register();
    func_irr_register();
    func_dp_register();
    func_xp_register();
    func_fpt_register();
    func_ipt_register();
    func_hta_register();
    func_ath_register();
    func_fileopenbox_register();
    func_filesavebox_register();
    func_msgbox_register();
    func_inputbox_register();
    func_input_str_register();
    func_screen_fn_register();
    func_doevents_register();
    func_tab_register();
    func_spc_register();
    func_pos_register();
    func_csrlin_register();
    func_lpos_register();
    func_erl_register();
    func_err_fn_register();
    func_eof_fn_register();
    func_lof_register();
    func_loc_fn_register();
    func_freefile_register();
    func_point_fn_register();
    func_baud_register();
    func_cpuspeed_register();
    func_clocks_register();
    func_stick_register();
    func_strig_register();
    func_paddle_register();
    func_ptrig_register();
    func_attr_register();
    func_lbound_register();
    func_ubound_register();
    func_dread_register();
    func_aread_register();
    func_touch_register();
    func_hall_register();
    func_ticks_iot_register();
    func_mem_register();
    func_http_register();
    func_gemini_register();
    func_gopher_register();
    func_python_register();
    func_receive_register();
    func_dateserial_register();
    func_timeserial_register();
    func_datevalue_register();
    func_timevalue_register();
    func_day_register();
    func_month_register();
    func_year_register();
    func_weekday_register();
    func_hour_register();
    func_minute_register();
    func_second_register();
    func_unixtime_register();
    func_epochdate_register();
    func_utc_register();
    func_dir_fn_register();
    func_curdir_register();
    func_isnumeric_register();
    func_isarray_register();
    func_setmem_register();
    func_sseg_register();
    func_hebrew_register();
    func_exepath_register();
    func_scriptpath_register();
    func_workdir_register();
    func_program_register();
    func_tempdir_register();
    func_userpath_register();
    func_ver_register();
    func_week_register();
    func_neg_register();
    func_vintage_vars_register();
    func_net_telemetry_register();
    func_upnp_register();
    func_nil_compress_register();
    func_devctl_register();
    func_fujinet_register();
    func_gemini_meta_register();
    func_nil_bead_register();
    func_packet_register();
    func_remote_register();
    func_sock_register();
    func_tnfs_register();
    func_crypto_register();
    func_arg_register();
    func_command_register();
    func_comp_register();
    func_cosh_register();
    func_cot_register();
    func_csc_register();
    func_cvt_register();
    func_devinfo_register();
    func_fid_register();
    func_ip_register();
    func_log10_register();
    func_log2_register();
    func_mag_register();
    func_moddir_register();
    func_num_register();
    func_pdif_register();
    func_pick_register();
    func_rad_register();
    func_sec_register();
    func_sinh_register();
    func_sys_register();
    func_tanh_register();
    func_tek_register();
    func_tim_register();
    func_time_fn_register();
    func_time_part_register();
    func_typ_register();
    func_xlate_register();
    func_record_lock_register();
    func_isam_fn_register();
    func_systems_types_register();

    register_crypto_functions();
    register_string_ext_functions();
#ifndef BASIC_LITE_BUILD
    register_arrayext_functions();
#endif
    register_regex_functions();
    register_array_sort_functions();
    system_var_descriptors_register();
    func_udx_register();
    func_pn_register();
    func_rpn_register();
    func_cpu86_register();
    func_bios_register();
}
