// FILENAME: common_reg_stmts.c
// LICENSE: Copyleft (c) 2026 BASIC++ Community — All Wrongs Reserved
// VERSION: 6.5.2.0
// NEEDED BY: libboot
// NEEDS: libboot (common_internal.h)
// Provides core logic and statement registration dispatcher for BASIC++.

#include "bootstrap/common_internal.h"

// Statement Registration Externs
void stmt_incr_register(void);
void stmt_decr_register(void);
void stmt_clr_register(void);
void stmt_void_register(void);
void stmt_arrayfill_register(void);
void stmt_share_register(void);
void stmt_public_register(void);
void stmt_global_register(void);
void stmt_var_mux_register(void);
void stmt_mid_stmt_register(void);
void stmt_array_ext_register(void);
void stmt_renum_register(void);
void stmt_merge_register(void);
void stmt_delete_register(void);
void stmt_compile_register(void);
void stmt_jit_register(void);
void stmt_auto_register(void);
void stmt_def_register(void);
void stmt_mat_ops_register(void);
void stmt_ask_register(void);
void stmt_window_register(void);
void stmt_view_register(void);
void stmt_pset_register(void);
void stmt_preset_register(void);
void stmt_palette_register(void);
void stmt_paint_register(void);
void stmt_draw_register(void);
void stmt_gfx_compat_register(void);
void stmt_bgi_register(void);
void stmt_lock_register(void);
void stmt_bload_register(void);
void stmt_on_com_register(void);
void stmt_randomize_register(void);
void stmt_shuffle_register(void);
void stmt_when_register(void);
void stmt_retry_register(void);
void stmt_handler_register(void);
void stmt_external_register(void);
void stmt_declare_register(void);
void stmt_const_register(void);
void stmt_continue_register(void);
void stmt_cause_register(void);
void stmt_viewport_register(void);
void stmt_collate_register(void);
void stmt_angle_register(void);
void stmt_gpib_register(void);
void stmt_translate_register(void);
void stmt_readu_register(void);
void stmt_writeu_register(void);
void stmt_release_register(void);
void stmt_mutex_register(void);
void stmt_picture_register(void);
void stmt_enter_register(void);
void stmt_complex_register(void);
void stmt_class_register(void);
void stmt_record_register(void);
void stmt_find_register(void);
void stmt_udx_register(void);
void stmt_stack_register(void);
void stmt_bios_register(void);
void stmt_map_register(void);
void stmt_login_register(void);
void stmt_who_register(void);
void stmt_tty_register(void);
void stmt_priority_register(void);
void stmt_category_register(void);
void stmt_baud_register(void);
void stmt_speed_register(void);
void stmt_cpuspeed_register(void);
void stmt_goto_register(void);
void stmt_gosub_register(void);
void stmt_return_register(void);
void stmt_if_register(void);
void stmt_end_register(void);
void stmt_rem_register(void);
void stmt_stop_register(void);
void stmt_print_register(void);
void stmt_input_register(void);
void stmt_select_register(void);
void stmt_for_register(void);
void stmt_next_register(void);
void stmt_while_register(void);
void stmt_wend_register(void);
void stmt_do_register(void);
void stmt_loop_register(void);
void stmt_exit_loop_register(void);
void stmt_open_register(void);
void stmt_close_register(void);
void stmt_get_register(void);
void stmt_put_register(void);
void stmt_field_register(void);
void stmt_files_register(void);
void stmt_kill_register(void);
void stmt_mkdir_register(void);
void stmt_name_register(void);
void stmt_seek_register(void);
void stmt_screen_register(void);
void stmt_cls_register(void);
void stmt_home_register(void);
void stmt_color_register(void);
void stmt_line_register(void);
void stmt_circle_register(void);
void stmt_sound_register(void);
void stmt_play_register(void);
void stmt_beep_register(void);
void stmt_voice_register(void);
void stmt_key_register(void);
void stmt_on_key_register(void);
void stmt_on_timer_register(void);
void stmt_on_error_register(void);
void stmt_resume_register(void);
void stmt_try_register(void);
void stmt_mat_input_register(void);
void stmt_mat_print_register(void);
void stmt_mat_read_register(void);
void stmt_mat_write_register(void);
void stmt_whenever_register(void);
void stmt_alias_register(void);
void stmt_keyword_register(void);
void stmt_override_register(void);
void stmt_remove_register(void);
void stmt_scope_register(void);
void stmt_help_register(void);
void stmt_reformat_register(void);
void stmt_rename_register(void);
void stmt_check_register(void);
void stmt_verify_register(void);
void stmt_revert_register(void);
void stmt_test_register(void);
void stmt_debug_register(void);
void stmt_version_register(void);
void stmt_introspection_register(void);
void stmt_selftest_register(void);
void stmt_isam_register(void);
void stmt_button_register(void);
void stmt_menu_register(void);
void stmt_textbox_register(void);
void stmt_listbox_register(void);
void stmt_checkbox_register(void);
void stmt_optionbutton_register(void);
void stmt_label_register(void);
void stmt_frame_register(void);
void stmt_combobox_register(void);
void stmt_hscrollbar_register(void);
void stmt_vscrollbar_register(void);
void stmt_drivelistbox_register(void);
void stmt_dirlistbox_register(void);
void stmt_filelistbox_register(void);
void stmt_timercontrol_register(void);
void stmt_dim_register(void);
void stmt_redim_register(void);
void stmt_erase_register(void);
void stmt_let_register(void);
void stmt_swap_register(void);
void stmt_read_register(void);
void stmt_restore_register(void);
void stmt_data_register(void);
void stmt_defint_register(void);
void stmt_defsng_register(void);
void stmt_defdbl_register(void);
void stmt_defstr_register(void);
void stmt_deflng_register(void);
void stmt_common_register(void);
void stmt_lset_register(void);
void stmt_rset_register(void);
void stmt_def_seg_register(void);
void stmt_def_usr_register(void);
void stmt_shell_register(void);
void stmt_pause_register(void);
void stmt_sys_register(void);
void stmt_bsave_register(void);
void stmt_qsave_register(void);
void stmt_qload_register(void);
void stmt_brun_register(void);
void stmt_qrun_register(void);
void stmt_merge_register(void);
void stmt_append_register(void);
void stmt_chdir_register(void);
void stmt_rmdir_register(void);
void stmt_lprint_register(void);
void stmt_line_input_register(void);
void stmt_plot_register(void);
void stmt_wifi_register(void);
void stmt_mqtt_register(void);
void stmt_webrepl_register(void);
void stmt_peer_register(void);
void stmt_bt_register(void);
void stmt_ble_register(void);
void stmt_nfc_register(void);
void stmt_gemini_register(void);
void stmt_gopher_register(void);
void stmt_tnfs_register(void);
void stmt_remote_register(void);
void stmt_nil_unpack_register(void);
void stmt_sock_register(void);
void stmt_port_trigger_register(void);
void stmt_sniff_register(void);
void stmt_net_config_register(void);
void stmt_log_register(void);
void stmt_send_register(void);
void stmt_publish_register(void);
void stmt_subscribe_register(void);
void stmt_unsubscribe_register(void);
void stmt_unpublish_register(void);
void stmt_signal_register(void);
void stmt_pipe_register(void);
void stmt_extern_register(void);
void stmt_yield_register(void);
void stmt_assign_register(void);
void stmt_backspace_register(void);
void stmt_bios_register(void);
void stmt_call_register(void);
void stmt_chain_register(void);
void stmt_change_register(void);
void stmt_clear_register(void);
void stmt_cont_register(void);
void stmt_create_register(void);
void stmt_dac_register(void);
void stmt_deepsleep_register(void);
void stmt_delay_register(void);
void stmt_demand_register(void);
void stmt_destroy_register(void);
void stmt_devctl_register(void);
void stmt_device_register(void);
void stmt_dht_register(void);
void stmt_doevents_register(void);
void stmt_dwrite_register(void);
void stmt_echo_register(void);
void stmt_end_sub_register(void);
void stmt_endloop_register(void);
void stmt_enum_register(void);
void stmt_espnow_register(void);
void stmt_every_register(void);
void stmt_exchange_register(void);
void stmt_exitif_register(void);
void stmt_extend_register(void);
void stmt_form_register(void);
void stmt_freq_register(void);
void stmt_function_register(void);
void stmt_gemini_browse_register(void);
void stmt_goodbye_register(void);
void stmt_i2c_register(void);
void stmt_image_register(void);
void stmt_input_file_register(void);
void stmt_interrupt_register(void);
void stmt_invoke_register(void);
void stmt_joystick_register(void);
void stmt_linput_register(void);
void stmt_list_register(void);
void stmt_llist_register(void);
void stmt_load_register(void);
void stmt_margin_register(void);
void stmt_modify_register(void);
void stmt_module_register(void);
void stmt_mouse_register(void);
void stmt_msgbox_register(void);
void stmt_neopixel_register(void);
void stmt_new_register(void);
void stmt_option_register(void);
void stmt_out_register(void);
void stmt_page_register(void);
void stmt_param_register(void);
void stmt_pen_register(void);
void stmt_perform_register(void);
void stmt_pinmode_register(void);
void stmt_poke_register(void);
void stmt_prefix_register(void);
void stmt_print_file_register(void);
void stmt_procedure_register(void);
void stmt_pwm_register(void);
void stmt_python_register(void);
void stmt_reboot_register(void);
void stmt_record_type_register(void);
void stmt_reformat_engine_register(void);
void stmt_repeat_register(void);
void stmt_rewind_register(void);
void stmt_run_register(void);
void stmt_save_register(void);
void stmt_scale_register(void);
void stmt_security_register(void);
void stmt_servo_register(void);
void stmt_shared_register(void);
void stmt_sleep_register(void);
void stmt_slot_io_register(void);
void stmt_spi_register(void);
void stmt_sub_register(void);
void stmt_suspend_register(void);
void stmt_system_register(void);
void stmt_task_register(void);
void stmt_text_register(void);
void stmt_txn_register(void);
void stmt_type_register(void);
void stmt_unless_register(void);
void stmt_until_register(void);
void stmt_upnp_register(void);
void stmt_user_ipc_register(void);
void stmt_vdim_register(void);
void stmt_wait_register(void);
void stmt_with_register(void);
void stmt_write_file_register(void);
void stmt_xio_register(void);
void stmt_zone_register(void);
void stmt_defseg_register(void);
void stmt_mux_register(void);
void stmt_print_at_register(void);

//
// ---- Registration Dispatcher ----
//

void boot_register_all_statements(void) {
    stmt_incr_register();
    stmt_decr_register();
    stmt_clr_register();
    stmt_void_register();
    stmt_arrayfill_register();
    stmt_share_register();
    stmt_public_register();
    stmt_global_register();
    stmt_var_mux_register();
    stmt_mid_stmt_register();
    stmt_array_ext_register();
    stmt_renum_register();
    stmt_merge_register();
    stmt_delete_register();
    stmt_auto_register();
    stmt_def_register();
    stmt_mat_ops_register();
    stmt_ask_register();
    stmt_window_register();
    stmt_view_register();
    stmt_pset_register();
    stmt_preset_register();
    stmt_palette_register();
    stmt_paint_register();
    stmt_draw_register();
    stmt_gfx_compat_register();
    stmt_bgi_register();
    stmt_lock_register();
    stmt_bload_register();
    stmt_on_com_register();
    stmt_randomize_register();
    stmt_shuffle_register();
    stmt_when_register();
    stmt_retry_register();
    stmt_handler_register();
    stmt_external_register();
    stmt_declare_register();
    stmt_const_register();
    stmt_continue_register();
    stmt_cause_register();
    stmt_viewport_register();
    stmt_picture_register();
    stmt_plot_register();
    stmt_enter_register();
    stmt_complex_register();
    stmt_class_register();
    stmt_record_register();
    stmt_find_register();
    stmt_map_register();
    stmt_login_register();
    stmt_who_register();
    stmt_tty_register();
    stmt_priority_register();
    stmt_category_register();
    stmt_goto_register();
    stmt_gosub_register();
    stmt_return_register();
    stmt_if_register();
    stmt_end_register();
    stmt_rem_register();
    stmt_stop_register();
    stmt_print_register();
    stmt_input_register();
    stmt_select_register();
    stmt_for_register();
    stmt_next_register();
    stmt_while_register();
    stmt_wend_register();
    stmt_do_register();
    stmt_loop_register();
    stmt_exit_loop_register();
    stmt_open_register();
    stmt_close_register();
    stmt_get_register();
    stmt_put_register();
    stmt_field_register();
    stmt_files_register();
    stmt_kill_register();
    stmt_mkdir_register();
    stmt_name_register();
    stmt_seek_register();
    stmt_screen_register();
    stmt_cls_register();
    stmt_home_register();
    stmt_color_register();
    stmt_line_register();
    stmt_circle_register();
    stmt_sound_register();
    stmt_play_register();
    stmt_beep_register();
    stmt_voice_register();
    stmt_key_register();
    stmt_on_key_register();
    stmt_on_timer_register();
    stmt_on_error_register();
    stmt_resume_register();
    stmt_try_register();
    stmt_mat_input_register();
    stmt_mat_print_register();
    stmt_mat_read_register();
    stmt_mat_write_register();
    stmt_whenever_register();
    stmt_alias_register();
    stmt_keyword_register();
    stmt_override_register();
    stmt_remove_register();
    stmt_scope_register();
    stmt_help_register();
    stmt_baud_register();
    stmt_speed_register();
    stmt_cpuspeed_register();
    stmt_reformat_register();
    stmt_rename_register();
    stmt_check_register();
    stmt_verify_register();
    stmt_revert_register();
    stmt_test_register();
    stmt_debug_register();
    stmt_version_register();
    stmt_introspection_register();
    stmt_selftest_register();
    stmt_isam_register();
    stmt_button_register();
    stmt_menu_register();
    stmt_textbox_register();
    stmt_listbox_register();
    stmt_checkbox_register();
    stmt_optionbutton_register();
    stmt_label_register();
    stmt_frame_register();
    stmt_combobox_register();
    stmt_hscrollbar_register();
    stmt_vscrollbar_register();
    stmt_drivelistbox_register();
    stmt_dirlistbox_register();
    stmt_filelistbox_register();
    stmt_timercontrol_register();
    stmt_dim_register();
    stmt_redim_register();
    stmt_erase_register();
    stmt_let_register();
    stmt_swap_register();
    stmt_read_register();
    stmt_restore_register();
    stmt_data_register();
    stmt_defint_register();
    stmt_defsng_register();
    stmt_defdbl_register();
    stmt_defstr_register();
    stmt_deflng_register();
    stmt_common_register();
    stmt_lset_register();
    stmt_rset_register();
    stmt_def_seg_register();
    stmt_def_usr_register();
    stmt_shell_register();
    stmt_pause_register();
    stmt_sys_register();
    stmt_bsave_register();
    stmt_qsave_register();
    stmt_qload_register();
    stmt_brun_register();
    stmt_qrun_register();
    stmt_merge_register();
    stmt_append_register();
    stmt_chdir_register();
    stmt_rmdir_register();
    stmt_lprint_register();
    stmt_line_input_register();
    stmt_wifi_register();
    stmt_mqtt_register();
    stmt_webrepl_register();
    stmt_peer_register();
    stmt_bt_register();
    stmt_ble_register();
    stmt_nfc_register();
    stmt_gemini_register();
    stmt_gopher_register();
    stmt_tnfs_register();
    stmt_remote_register();
    stmt_nil_unpack_register();
    stmt_sock_register();
    stmt_port_trigger_register();
    stmt_sniff_register();
    stmt_net_config_register();
    stmt_log_register();
    stmt_send_register();
    stmt_publish_register();
    stmt_subscribe_register();
    stmt_unsubscribe_register();
    stmt_unpublish_register();
    stmt_signal_register();
    stmt_pipe_register();
    stmt_extern_register();
    stmt_yield_register();
    stmt_collate_register();
    stmt_angle_register();
    stmt_gpib_register();
    stmt_translate_register();
    stmt_readu_register();
    stmt_writeu_register();
    stmt_release_register();
    stmt_mutex_register();
    stmt_assign_register();
    stmt_backspace_register();
    stmt_bios_register();
    stmt_call_register();
    stmt_chain_register();
    stmt_change_register();
    stmt_clear_register();
    stmt_cont_register();
    stmt_create_register();
    stmt_dac_register();
    stmt_deepsleep_register();
    stmt_delay_register();
    stmt_demand_register();
    stmt_destroy_register();
    stmt_devctl_register();
    stmt_device_register();
    stmt_dht_register();
    stmt_doevents_register();
    stmt_dwrite_register();
    stmt_echo_register();
    stmt_end_sub_register();
    stmt_endloop_register();
    stmt_enum_register();
    stmt_espnow_register();
    stmt_every_register();
    stmt_exchange_register();
    stmt_exitif_register();
    stmt_extend_register();
    stmt_form_register();
    stmt_freq_register();
    stmt_function_register();
    stmt_gemini_browse_register();
    stmt_goodbye_register();
    stmt_i2c_register();
    stmt_image_register();
    stmt_input_file_register();
    stmt_interrupt_register();
    stmt_invoke_register();
    stmt_joystick_register();
    stmt_linput_register();
    stmt_list_register();
    stmt_llist_register();
    stmt_load_register();
    stmt_margin_register();
    stmt_modify_register();
    stmt_module_register();
    stmt_mouse_register();
    stmt_msgbox_register();
    stmt_neopixel_register();
    stmt_new_register();
    stmt_option_register();
    stmt_out_register();
    stmt_page_register();
    stmt_param_register();
    stmt_pen_register();
    stmt_perform_register();
    stmt_pinmode_register();
    stmt_poke_register();
    stmt_prefix_register();
    stmt_print_file_register();
    stmt_procedure_register();
    stmt_pwm_register();
    stmt_python_register();
    stmt_reboot_register();
    stmt_record_type_register();
    stmt_reformat_engine_register();
    stmt_repeat_register();
    stmt_rewind_register();
    stmt_run_register();
    stmt_save_register();
    stmt_scale_register();
    stmt_security_register();
    stmt_servo_register();
    stmt_shared_register();
    stmt_sleep_register();
    stmt_slot_io_register();
    stmt_spi_register();
    stmt_sub_register();
    stmt_suspend_register();
    stmt_system_register();
    stmt_task_register();
    stmt_text_register();
    stmt_txn_register();
    stmt_type_register();
    stmt_unless_register();
    stmt_until_register();
    stmt_upnp_register();
    stmt_user_ipc_register();
    stmt_vdim_register();
    stmt_wait_register();
    stmt_with_register();
    stmt_write_file_register();
    stmt_xio_register();
    stmt_zone_register();
    stmt_defseg_register();
    stmt_mux_register();
    stmt_compile_register();
    stmt_jit_register();
    stmt_print_at_register();
    stmt_udx_register();
    stmt_stack_register();
    stmt_bios_register();
}
