// FILENAME: trans_pascal.c
// LICENSE: Copyleft (c) 2026 BASIC++ Community — All Wrongs Reserved
// VERSION: 6.5.2.0
// NEEDED BY: libcore (trans.c, bppc_transpile.c)
// NEEDS: libcore (trans_pascal.h, bppc_internal.h), libplatform
// Implements the Object Pascal (Free Pascal) transpiler backend for BASIC++.
//
// ---- Includes ----

#include "compiler/trans_pascal.h"
#include "tools/bppc_internal.h"
#include "platform/platform.h"
#include "runtime/format/snprintf.h"
#include "runtime/string/strops.h"
#include "runtime/string/memops.h"
#include "runtime/ctype/ctype.h"

#define pas_printf(f, ...) platform_file_printf((void *)(f), __VA_ARGS__)

static char *g_pascal_strtok_save = NULL;
#define strtok(str, delim) runtime_strtok_r(str, delim, &g_pascal_strtok_save)

static void emit_pascal_preamble(void *out) {
    pas_printf(out, "(******************************************************************************)\n");
    pas_printf(out, "(* Generated by BASIC++ Native Object Pascal Transpiler (trans --pascal)       *)\n");
    pas_printf(out, "(* Target: Free Pascal Compiler (FPC) with Bare-Metal / UEFI Compatibility     *)\n");
    pas_printf(out, "(******************************************************************************)\n\n");
    pas_printf(out, "program GeneratedBppProgram;\n\n");
    pas_printf(out, "{$IFDEF FPC}\n");
    pas_printf(out, "  {$mode objfpc}{$H+}\n");
    pas_printf(out, "{$ENDIF}\n\n");
    pas_printf(out, "uses\n");
    pas_printf(out, "  SysUtils;\n\n");

    pas_printf(out, "// --- Sized Ordinal Primitive Types & Pointer Aliases ---\n");
    pas_printf(out, "type\n");
    pas_printf(out, "  U8 = Byte;\n");
    pas_printf(out, "  I8 = ShortInt;\n");
    pas_printf(out, "  U16 = Word;\n");
    pas_printf(out, "  I16 = SmallInt;\n");
    pas_printf(out, "  U32 = LongWord;\n");
    pas_printf(out, "  I32 = LongInt;\n");
    pas_printf(out, "  U64 = QWord;\n");
    pas_printf(out, "  I64 = Int64;\n");
    pas_printf(out, "  USIZE = PtrUInt;\n");
    pas_printf(out, "  ISIZE = PtrInt;\n\n");
}

static void emit_pascal_statement(void *out, const char *stmt) {
    const char *s = bppc_trim((char *)stmt);
    if (!s || *s == '\0') return;

    if (runtime_strncasecmp(s, "PRINT", 5) == 0) {
        const char *args = bppc_trim((char *)s + 5);
        if (*args == '\0') {
            pas_printf(out, "  WriteLn;\n");
        } else if (args[0] == '"') {
            char txt[512] = {0};
            size_t len = runtime_strlen(args);
            if (len >= 2 && args[len - 1] == '"') {
                runtime_memcpy(txt, args + 1, len - 2);
                txt[len - 2] = '\0';
            } else {
                runtime_strcpy(txt, args + 1);
            }
            pas_printf(out, "  WriteLn('%s');\n", txt);
        } else {
            pas_printf(out, "  WriteLn(%s);\n", args);
        }
    } else if (runtime_strncasecmp(s, "MEM[", 4) == 0) {
        const char *rb = runtime_strchr(s, ']');
        if (rb) {
            char addr[256] = {0};
            runtime_memcpy(addr, s + 4, rb - (s + 4));
            const char *eq = runtime_strchr(rb, '=');
            if (eq) {
                const char *val = bppc_trim((char *)eq + 1);
                pas_printf(out, "  PByte(PtrUInt(%s))^ := %s;\n", bppc_trim(addr), val);
            }
        }
    } else if (runtime_strncasecmp(s, "MEMW[", 5) == 0) {
        const char *rb = runtime_strchr(s, ']');
        if (rb) {
            char addr[256] = {0};
            runtime_memcpy(addr, s + 5, rb - (s + 5));
            const char *eq = runtime_strchr(rb, '=');
            if (eq) {
                const char *val = bppc_trim((char *)eq + 1);
                pas_printf(out, "  PWord(PtrUInt(%s))^ := %s;\n", bppc_trim(addr), val);
            }
        }
    } else if (runtime_strncasecmp(s, "MEML[", 5) == 0) {
        const char *rb = runtime_strchr(s, ']');
        if (rb) {
            char addr[256] = {0};
            runtime_memcpy(addr, s + 5, rb - (s + 5));
            const char *eq = runtime_strchr(rb, '=');
            if (eq) {
                const char *val = bppc_trim((char *)eq + 1);
                pas_printf(out, "  PDWord(PtrUInt(%s))^ := %s;\n", bppc_trim(addr), val);
            }
        }
    } else if (runtime_strncasecmp(s, "POKE ", 5) == 0) {
        char *comma = runtime_strchr((char *)s + 5, ',');
        if (comma) {
            *comma = '\0';
            const char *addr = bppc_trim((char *)s + 5);
            const char *val = bppc_trim(comma + 1);
            pas_printf(out, "  PByte(PtrUInt(%s))^ := %s;\n", addr, val);
        }
    } else if (runtime_strchr(s, '=') != NULL) {
        char *eq = runtime_strchr((char *)s, '=');
        char var[64] = {0};
        size_t nlen = eq - s;
        if (nlen < sizeof(var)) {
            runtime_memcpy(var, s, nlen);
            var[nlen] = '\0';
        }
        const char *rhs = bppc_trim(eq + 1);
        pas_printf(out, "  var_%s := %s;\n", bppc_trim(var), rhs);
    } else {
        pas_printf(out, "  // %s;\n", s);
    }
}

bool trans_emit_pascal(void *out, const char *source, bool optimize, bool debug) {
    (void)optimize;
    (void)debug;
    if (!out || !source) return false;

    emit_pascal_preamble(out);

    pas_printf(out, "var\n");
    pas_printf(out, "  var_A, var_B, var_C, var_D, var_X, var_Y, var_Z: Double;\n");
    pas_printf(out, "  var_I, var_J, var_K: Int32;\n\n");

    pas_printf(out, "begin\n");

    char *copy = bppc_strdup(source);
    if (copy) {
        char *line = strtok(copy, "\r\n");
        while (line) {
            char *p = bppc_trim(line);
            int line_no = 0;
            const char *stmt = NULL;
            if (bppc_parse_line_number(p, &line_no, &stmt)) p = (char *)stmt;
            p = bppc_trim(p);
            if (*p && runtime_strncmp(p, "REM", 3) != 0 && *p != '\'') {
                emit_pascal_statement(out, p);
            }
            line = strtok(NULL, "\r\n");
        }
        runtime_free(copy);
    }

    pas_printf(out, "end.\n");
    return true;
}
